### ISSUE TITLE
Unable to connect to the server: net/http: TLS handshake timeout in SouthEastAsia Kubernetes

### ISSUE THREAD

**Issue by richieteh94** [Azure/AKS#1013]
**What happened**:
I'm facing an issue of Unable to connect to the server: net/http: TLS handshake timeout
I use kubectl command sometimes i will get an error of 
`Unable to connect to the server: net/http: TLS handshake timeout`
and when i use kubectl cp command I get an error of
```
tar: netcore_GatewaySimulator: Cannot open: File exists
tar: Exiting with failure status due to previous errors
command terminated with exit code 2
```

Currently my Cluster is in SouthEastAsia

**What you expected to happen**:
no error

**How to reproduce it (as minimally and precisely as possible)**:
I used these 2 command that get error
kubectl create -f <yaml_file_name>.yaml
kubectl cp <file_location> <pod_name>:<file_location>

**Anything else we need to know?**:
-
**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

Size of Cluster - 1 Node

General workload in the cluster - running .NET core application

**Comment by richieteh94** [comment]
After few hours I tried the service again. Now AKS is stable. 
May I know what is the cause of the the error?

**Comment by jnoller** [comment]
First, thank you for reaching out to the AKS team. 

AKS Github issues must be generally re-creatable (e.g here is the YAML/settings/packages/etc installed, can recreate the issue on existing clusters as well as newly created clusters). Unfortunately, this issue is cluster-specific.

For cluster specific issues (those that will require support and on-call staff to access you Subscription and clusters) we ask that you file an Azure Technical Support ticket with the identified issue, rec-creation steps if available, and link to this github thread.

**We can not ask** for the access, logs and other sensitive information on github, or ask you to email/slack/etc this information to us. Our portal ticketing system will protect the information including Subscription ids and credentials. If we discover as part of the root cause that this is an AKS or upstream bug, we will mark this issue as a known issue and ensure it is on the Product backlog as a repair item.

This will allow us to root-cause the issue and ensure it’s not specific to the environment or other configuration level issue - such as NSGs, custom network devices, etc.

Jesse

**Comment by levilugato** [comment]
Hello, second time that this happens to me ? i couldn't recreate de hole cluster, I want a solution

[]s
