### ISSUE TITLE
AKS creation error from cli after update

### ISSUE THREAD

**Issue by akin-ozer** [Azure/AKS#1017]
**What happened**: AKS creation from azure cli taking too long(Haven't see the completion).

**What you expected to happen**: Creation should be completed in 5-15 mins.

**How to reproduce it (as minimally and precisely as possible)**: With this command : 

az aks create \
--resource-group $GROUP_NAME \
--name $CLUSTER_NAME \
--node-count 3 \
--node-vm-size $NODE_TYPE \
--generate-ssh-keys

**Anything else we need to know?**: I tried several times with different node types and used default kubernetes version and tried with 1.14.0. Location is "westeurope". Never waited over 1 hour. It was working 2 weeks ago.

**Environment**:
- Kubernetes version (use `kubectl version`): default and 
- Size of cluster (how many worker nodes are in the cluster?): 3

**Comment by jnoller** [comment]
First, thank you for reaching out to the AKS team. 

AKS Github issues must be generally re-creatable (e.g here is the YAML/settings/packages/etc installed, can recreate the issue on existing clusters as well as newly created clusters). Unfortunately, this issue is cluster-specific.

For cluster specific issues (those that will require support and on-call staff to access you Subscription and clusters) we ask that you file an Azure Technical Support ticket with the identified issue, rec-creation steps if available, and link to this github thread.

**We can not ask** for the access, logs and other sensitive information on github, or ask you to email/slack/etc this information to us. Our portal ticketing system will protect the information including Subscription ids and credentials. If we discover as part of the root cause that this is an AKS or upstream bug, we will mark this issue as a known issue and ensure it is on the Product backlog as a repair item.

This will allow us to root-cause the issue and ensure it’s not specific to the environment or other configuration level issue - such as NSGs, custom network devices, etc.

Jesse
