### ISSUE TITLE
AKS 1.13.5 having DNS issue

### ISSUE THREAD

**Issue by maxiwu** [Azure/AKS#1032]
**What happened**: Trying to connect to CosmosDB from a pod

**What you expected to happen**: connect to CosmosDB using MongoDB API

**How to reproduce it (as minimally and precisely as possible)**: AKS cluster 1.12.8 upgrade to 1.13.5

**Anything else we need to know?**: The cluster 1 has an "kubernetes-internal (Load Balancer)" which is absent in other clusters. 

**Environment**:
- 1.12.8 upgrade to 1.13.5
- Size of cluster 2 nodes
- Java App which use MongoDB-driver to connect to CosmosDB

Update:
I run $kubectl get deploy --all-namespaces and see that coredns is not ready. I am not sure if this is caused by upgrading from 1.12.8 to 1.13.5. 

result: 
kube-system coredns 0/2

**Comment by jnoller** [comment]
First, thank you for reaching out to the AKS team. 

AKS Github issues must be generally re-creatable (e.g here is the YAML/settings/packages/etc installed, can recreate the issue on existing clusters as well as newly created clusters). Unfortunately, this issue is cluster-specific.

For cluster specific issues (those that will require support and on-call staff to access you Subscription and clusters) we ask that you file an Azure Technical Support ticket with the identified issue, rec-creation steps if available, and link to this github thread.

**We can not ask** for the access, logs and other sensitive information on github, or ask you to email/slack/etc this information to us. Our portal ticketing system will protect the information including Subscription ids and credentials. If we discover as part of the root cause that this is an AKS or upstream bug, we will mark this issue as a known issue and ensure it is on the Product backlog as a repair item.

This will allow us to root-cause the issue and ensure it’s not specific to the environment or other configuration level issue - such as NSGs, custom network devices, etc.

Jesse
