### ISSUE TITLE
AZ ML failed to call AKS with error "Replica closed connection before replying"

### ISSUE THREAD

**Issue by guangw** [Azure/AKS#1033]
**What happened**: Azure Machine Learning service failed to call Azure Kubernetes Service(AKS) with the error "Replica closed connection before replying". Here is the deployment configuration, 2VCPU & 14GMem, and AKS has 3 nodes, 4 Cores and 16GB Mem each. It works well if I pass in a dataset of a few rows for scoring, but it fails the size is over 30, which is not a lot. I was able to run the same model in local Jupyter notebook for 100K rows.

**What you expected to happen**: I do expect AKS should be able to handle such small load.

**How to reproduce it (as minimally and precisely as possible)**:
I can share my subscription and AKS instances if needed for troubleshooting.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12.8
- Size of cluster (how many worker nodes are in the cluster?) 3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) Python runtime, 
- Others:

**Comment by jnoller** [comment]
First, thank you for reaching out to the AKS team. 

AKS Github issues must be generally re-creatable (e.g here is the YAML/settings/packages/etc installed, can recreate the issue on existing clusters as well as newly created clusters). Unfortunately, this issue is cluster-specific.

For cluster specific issues (those that will require support and on-call staff to access you Subscription and clusters) we ask that you file an Azure Technical Support ticket with the identified issue, rec-creation steps if available, and link to this github thread.

**We can not ask** for the access, logs and other sensitive information on github, or ask you to email/slack/etc this information to us. Our portal ticketing system will protect the information including Subscription ids and credentials. If we discover as part of the root cause that this is an AKS or upstream bug, we will mark this issue as a known issue and ensure it is on the Product backlog as a repair item.

This will allow us to root-cause the issue and ensure it’s not specific to the environment or other configuration level issue - such as NSGs, custom network devices, etc.

Jesse
