### ISSUE TITLE
Azure CNI and a default route seems to break k8s networking

### ISSUE THREAD

**Issue by t0mmyt** [Azure/AKS#1046]
I am trying to bring up a cluster in a pre-existing VNet peered with another VNet containing an Azure Firewall.  The VNet for AKS is empty.

Adding a default route to the route table on the cluster subnet appears to prevent pods from being able to talk to any service endpoints (including the k8s api), removing the entry (i.e. leaving an empty route table) lets everything work again (but obviously bypasses the firewall for egress).

Am I missing a step in being able to use a default route (in another VNet in this case)?

**Steps to create**:
VNet 1 with an Azure firewall for egress
VNet 2 with a single subnet for cluster
Peer the two VNets
Create a Route Table in the cluster subnet with a route to 0.0.0.0/0 via the firewall in VNet 1
Create an AKS cluster with "advanced networking" using the cluster subnet and an unrelated CIDR for the service subnet

**Environment**:
- Kubernetes version: 1.13.5 & 1.14.0
- Size of cluster: 3
- General description of workloads in the cluster: empty

**Comment by Senai-T** [comment]
this is an interesting issue, my default assumption is that something might be getting NAT'd out somewhere in the mix or the firewall is conducting some sort of source/destination check and dropping packets when they fail to match. I hope this might be of [assistance](https://docs.microsoft.com/en-us/azure/aks/egress) but i'll keep looking into it.

**Comment by jnoller** [comment]
First, thank you for reaching out to the AKS team. 

AKS Github issues must be generally re-creatable (e.g here is the YAML/settings/packages/etc installed, can recreate the issue on existing clusters as well as newly created clusters). Unfortunately, this issue is cluster-specific.

For cluster specific issues (those that will require support and on-call staff to access you Subscription and clusters) we ask that you file an Azure Technical Support ticket with the identified issue, rec-creation steps if available, and link to this github thread.

**We can not ask** for the access, logs and other sensitive information on github, or ask you to email/slack/etc this information to us. Our portal ticketing system will protect the information including Subscription ids and credentials. If we discover as part of the root cause that this is an AKS or upstream bug, we will mark this issue as a known issue and ensure it is on the Product backlog as a repair item.

This will allow us to root-cause the issue and ensure it’s not specific to the environment or other configuration level issue - such as NSGs, custom network devices, etc.

Jesse

**Comment by t0mmyt** [comment]
Following the steps I posted should be able to re-create it.  This is AKS using Advanced Networking with a default route via an Azure Firewall.  Either I'm doing something wrong or Azure CNI doesn't work with Azure Firewall.

**Comment by t0mmyt** [comment]
@jnoller - can you re-open this?  This is 100% re-creatable following the above steps and is not cluster specific.

**Comment by neumanndaniel** [comment]
Can you follow this blog post?
https://medium.com/@denniszielke/setting-up-azure-firewall-for-analysing-outgoing-traffic-in-aks-55759d188039

**Comment by patpicos** [comment]
@t0mmyt did you end up opening an issue w/ support on this. I am experiencing the same. I will try w/o CNI this morning to isolate
