### ISSUE TITLE
Unable to get pod logs on clusters created after mid-June 2019

### ISSUE THREAD

**Issue by amandadebler** [Azure/AKS#1073]
**What happened**: kubectl logs fails with this error:

Error from server: Get https://aks-nodepool1-20679802-1:10250/containerLogs/kube-system/tunnelfront-df74775c4-nnqsp/tunnel-front: dial tcp 10.115.71.35:10250: i/o timeout

**What you expected to happen**: kubectl logs pulls the logs from the pod requested

**How to reproduce it (as minimally and precisely as possible)**:
Create new cluster in a custom VNet that has a routing table, then
kubectl get pods --namespace kube-system
Copy the tunnelfront pod's full name
kubectl logs --namespace kube-system (tunnelfront pod's full name) --verbose=10 (to see that the call is going into the management API just fine)

**Anything else we need to know?**: all clusters created after a point in time sometime between June 2 and June 14; all clusters created on or before June 2 are fine, all clusters created on or after June 14 are affected. I initially thought this had something to do with [the 2019-06-18 release](https://github.com/Azure/AKS/blob/master/CHANGELOG.md#release-2019-06-18), but we are using the Azure CNI plugin for all of our clusters, not Kubenet.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12.8, 1.13.5, 1.14.0
- Size of cluster (how many worker nodes are in the cluster?) 1-3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) Miscellaneous
- Others: We are using a custom VNet that has a routing table connected to each subnet; each cluster is using Azure networking and is in its own subnet.

**Comment by jnoller** [comment]
First, thank you for reaching out to the AKS team. 

AKS Github issues must be generally re-creatable (e.g here is the YAML/settings/packages/etc installed, can recreate the issue on existing clusters as well as newly created clusters). Unfortunately, this issue is cluster-specific due to the custom VNet/UDR configuration, the error you shared is a generic error when trying to route traffic to the API server.

For cluster specific issues (those that will require support and on-call staff to access you Subscription and clusters) we ask that you file an Azure Technical Support ticket with the identified issue, rec-creation steps if available, and link to this github thread.

**We can not ask** for the access, logs and other sensitive information on github, or ask you to email/slack/etc this information to us. Our portal ticketing system will protect the information including Subscription ids and credentials. If we discover as part of the root cause that this is an AKS or upstream bug, we will mark this issue as a known issue and ensure it is on the Product backlog as a repair item.

This will allow us to root-cause the issue and ensure it’s not specific to the environment or other configuration level issue - such as NSGs, custom network devices, etc.

Jesse

**Comment by patrickmslatteryvt** [comment]
We encountered this as well.
The root cause is that TCP port 22 is being swapped out for TCP port 9000 without being properly communicated to users.
See: https://github.com/MicrosoftDocs/azure-docs/commit/543f1bc8e365d7dfbc6b7b845d93e4ddbb28b079#diff-b6f22987cfa00b6b3e2fc647db3b75f7

**Comment by ferantivero** [comment]
@jnoller same here. This is what I've done to workaround this https://github.com/Azure/AKS/issues/642#issuecomment-424245323

**Comment by patrickmslatteryvt** [comment]
The AKS support engineer that we worked with looked at tunnelfront very early on but ultimately rejected that as being the issue, in our case we had an egress firewall (as any sane network has) and while it had been told about port 22 it was never told about port port 9000 (since it wasn't documented for non-preview usages)
