### ISSUE TITLE
"Changing property 'platformFaultDomainCount' is not allowed" on upgrade

### ISSUE THREAD

**Issue by joaocc** [Azure/AKS#1112]
**What happened**:
While trying to upgrade a cluster from 0.11.8 to 0.11.10, we got the following error:
```
Changing property 'platformFaultDomainCount' is not allowed
```
Not only that, but the underlying VMs disappeared (but the OS disks and NICs are still there).
We tried to do the upgrade via the portal.

**What you expected to happen**:
A normal upgrade.

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Anything else we need to know?**:
A ticket was already created in Azure Support (********5***364).

**Environment**:
- kubernetes 0.11.8, upgrading to 0.11.10
- at this moment, no nodes.
- ingress, web, JVMs

**Comment by mboersma** [comment]
Both of the issues mentioned above were specific to the `aks-engine scale` command, and aren't relevant to the fix that was deployed for AKS.

**Comment by joaocc** [comment]
Thx @mboersma. I'll remove the links to prevent confusion.

**Comment by jnoller** [comment]
This should now be patched / resolved. Please reopen if not

**Comment by joaocc** [comment]
Hi. Unfortunately nothing changed on our side. The issue with Azure is still open (escalated to product group it seems). I just checked and both clusters are still in a failed states (no VMs since 16th July - yes, 10 days ago).

**Comment by jnoller** [comment]
@joacc Can you post the support ticket ID number so I can look?

**Comment by joaocc** [comment]
@jnoller Yes, just sent via email. Thanks

**Comment by jnoller** [comment]
@joacc I found the issue in our support system - PG provided a response. We found a bug that you triggered. Specifically, the first agent node was shut down / deleted and then a scale up command was executed. The mitigation provided to support was the following:

1. If the agent nodes is turned off, turn on them and do upgrade/scale - in this case, it's deleted so please see:

2. If the agent nodes are already deleted, please delete the availability set resource: nodepool1-availabilitySet-18080329, and then do scale/upgrade.

The bug has been fixed in the service, however your cluster will need the above to restore the cluster state.

**Comment by joaocc** [comment]
@jnoller Thanks for the prompt response. The workaround (delete nodepool1-availabilitySet) worked. 
Unfortunately this means we were left w/o any kind of service for 10 days, with appalling response from support. And this is not the first time (even if I only consider GA). 
We had to move the services to another non-AKS instance in a rush, which is clearly undesirable and very disappointing from the point of view of trusting AKS in the future.
And it's sad, as AKS is very interesting and has a huge potential...
