### ISSUE TITLE
AKS support of Azure NAT Gateway as outboundType option

### ISSUE THREAD

**Issue by sagivle** [Azure/AKS#1122]
**What happened**: i have kubernetes in aws , and they have nat service(gw).
all pod outbound traffic uses the nat gw ip.
in azure aks the outbound uses the nlb ip

**What you expected to happen**:
allow a feature like aws nat gw so my pods will be using the nat gw ip address for outboud traffic

**How to reproduce it (as minimally and precisely as possible)**:
create a simple pod and use curl ifconfig.me ,you will see its a randoom nat address

**Anything else we need to know?**:
this feature is highly needed since we want the option to white list outgoing ips

**Comment by alanjcastonguay** [comment]
See issue #1116

**Comment by cgreenza** [comment]
When adding support for NAT Gateway as outboundType, please also consider adding a cluster level option to prevent AKS from assigning a public IP to the Azure load balancer that it creates i.e. ensure that the AKS deployed load balancer is always an internal-only load balancer. The purpose of this is to prevent any incoming connections from the internet (even if a Kubernetes LoadBalancer service is deployed without the `service.beta.kubernetes.io/azure-load-balancer-internal: "true"` annotation).

**Comment by palma21** [comment]
@cgreenza thanks for the feedback we're looking at that option. The biggest hurdle is that assuming you have nothing (no NAT GW, not outbound public IP on LB, etc.) and you create an ILB you will loose all external connectivity and you cluster will be broken since you need at least (https://aka.ms/aks/egress).

That's the reason why by default there is a an outbound PIP on the SLB. For reference, this IP can be used for outbound only, it's only attached to an outbound pool, it does not provide any inbound.

We are working on solutions that might require changes to k8s cloud provider upstream for this. In essence with Standard ILB you will have to have some form of explicitly defined egress.

**Comment by kinkist** [comment]
Hi.

We use kubernetes on AWS.

And when We operating AKS on Azure, We faced SNAT port exhaustion.
When we check that who using SNAT port.  All outbound of public IP except Azure DNS and Blob.
even Azure Paas Service (Azure SQL/Postgresql/Mysql/MariaDB) used SNAT port.

We plan to attaching NAT Gateway to Subnet of AKS node.

Can you check that which is better that LB attached NAT Gateway vs Subnet of AKS node attached NAT Gateway?

**Comment by palma21** [comment]
Hi, as per my comment above, today neither of those options are supported on AKS.

The way to solve that is to add more Outbound IPs to the Load Balancer and Add/configure the outbound ports as required:
https://docs.microsoft.com/en-us/azure/aks/load-balancer-standard#configure-the-public-standard-load-balancer

We're still evaluating the managed NAT solution as we found it doesn't solve the SNAT problem for large clusters, since it still requires you to add more outbound IPs, so we will add scaling capabilities for the SLB in the meantime to conservatively automate the above steps.

**Comment by tomasr** [comment]
Are there any updates on this?

I am also kinda confused by this comment from @palma21 :


> The way to solve that is to add more Outbound IPs to the Load Balancer and Add/configure the outbound ports as required:
https://docs.microsoft.com/en-us/azure/aks/load-balancer-standard#configure-the-public-standard-load-balancer
> We're still evaluating the managed NAT solution as we found it doesn't solve the SNAT problem for large clusters, since it still requires you to add more outbound IPs, so we will add scaling capabilities for the SLB in the meantime to conservatively automate the above steps.

Wouldn't using the SLB still require you to add more public IPs for outbound traffic as the cluster needs grow? How is that any different from the NAT case? I guess auto-scaling the outbound IPs fixes that as long as you don't need consistent outbound IPs, which seems... like the most common reason to even be looking at this to me.

**Comment by miwithro** [comment]
We are looking into this as this is becoming a common request.  Will provide an update here in the next few weeks.

**Comment by PixelRobots** [comment]
Any update one this?

**Comment by rlees85** [comment]
I tried to achieve this today as it seemed it would be possible just by making a subnet, attaching a NAT gateway to it and then dropping in an AKS cluster with user defined networking.

WRONG.

AKS forces a route table to be present, with route `0.0.0.0/0` going to either a known private IP address or a VPN gateway.

NAT gateways do not provide a known private IP. Might be possible by spinning up a VM and grabbing the default gateway but I never bothered to try since if it can't be done in Terraform I'm not interested.

I don't understand why Microsoft insist to use arbitrary restrictions and write code to actively reduce the power of their own platform. **If making NAT gateway an outbound option is a big job why not just drop some of the restrictions on using user defined networking?**

Also the argument about needing to scale public IPs anyway so offers no/little value is flawed because NAT gateways can balance all available ports rather than having to assign a static amount of ports per node which makes a huge difference in how many public IPs you will actually need in some use cases.

**Comment by webczat** [comment]
> I tried to achieve this today as it seemed it would be possible just by making a subnet, attaching a NAT gateway to it and then dropping in an AKS cluster with user defined networking.
> 
> WRONG.
> 
> AKS forces a route table to be present, with route `0.0.0.0/0` going to either a known private IP address or a VPN gateway.
What happens if you added an explicit 0.0.0.0/0 route with next hop type set to internet? there are some suggestions in documentation it would work. I also managed to set up nat gateway outbound, except I have done this for a separate node pool in separate subnet and it forced me to use azure networking instead of kubenet.
> 
> NAT gateways do not provide a known private IP. Might be possible by spinning up a VM and grabbing the default gateway but I never bothered to try since if it can't be done in Terraform I'm not interested.
> 
> I don't understand why Microsoft insist to use arbitrary restrictions and write code to actively reduce the power of their own platform. **If making NAT gateway an outbound option is a big job why not just drop some of the restrictions on using user defined networking?**
> 
> Also the argument about needing to scale public IPs anyway so offers no/little value is flawed because NAT gateways can balance all available ports rather than having to assign a static amount of ports per node which makes a huge difference in how many public IPs you will actually need in some use cases.

**Comment by anavinahar** [comment]
https://azure.microsoft.com/en-us/updates/public-preview-nat-gateway-integration-with-aks-2/

**Comment by RehanSaeed** [comment]
What is the recommended approach for a productionized cluster once this feature hits GA?

**Comment by eosfor** [comment]
Any examples of using/creating it via Bicep?
Can we update the existing cluster somehow, to let it through the NAT GW?

**Comment by samaea** [comment]
Am I right in saying this capability has now gone to GA based on these doc changes[1]? Thanks.

[1] https://github.com/MicrosoftDocs/azure-docs/commit/72b1a91311eb52056314466c6d6bc9b411b176fc

**Comment by PixelRobots** [comment]
Yes it's now GA. It was announced at Microsoft Build.

**Comment by BojanOro** [comment]
Can I use NAT GW along with UDR?

**Comment by PixelRobots** [comment]
> Any update on how to use AKS with Natgateway? I need to know the outgoing IP from AKS to whitelisted.

You can check out the Microsoft docs at https://docs.microsoft.com/en-us/azure/aks/nat-gateway

**Comment by poochwashere** [comment]
Is it possible to migrate an existing AKS cluster to use a NAT gateway? The documentation above is for creating a cluster using a NAT gateway.

**Comment by jn-github** [comment]
> Is it possible to migrate an existing AKS cluster to use a NAT gateway? The documentation above is for creating a cluster using a NAT gateway.

I am also looking for the same information. any documentation on Migrating an existing AKS cluster to use NAT gateway ?

**Comment by PixelRobots** [comment]
As far as I know this is not an option yet. But maybe @phealy might be able to say more.

**Comment by dan-leanix** [comment]
@phealy Any news on that? We would like to avoid the redeployment of our Kubernetes clusters. Hence, adding a user-defined NAT gateway to a subnet which is used by an AKS cluster changes the outbound flow already to the NAT gateway without breaking anything. So, for user-defined NAT gateways this should be allowed to change the `outboundType` of an existing AKS cluster.

**Comment by PixelRobots** [comment]
> @phealy Also blocked on how to handle existing clusters. Appreciate any guidance there.

There is no way to change the outbound type on existing clusters. 

What you can do is create a NAT gateway and assign it to your node subnet. This will change the routing to use the NAT gateway rather than the load balancer.

**Comment by mjyeaney** [comment]
@PixelRobots We tried the above, and it caused instability in routing. For example, given an API pod with 2 instances, only one of them would route correctly. The other pod (on a different node) would not. 

Note we are using the Kubenet plugin, AKS version 1.22.6

**Comment by mjyeaney** [comment]
North central US, and we do _not_ have konnectivity pods on any of our clusters (ongoing issue - and yes, there are no changes to these clusters, they are vanilla AKS deployments).

Perhaps I missed the docs, but is konnectivity a requirement?

**Comment by PixelRobots** [comment]
> North central US, and we do _not_ have konnectivity pods on any of our clusters (ongoing issue - and yes, there are no changes to these clusters, they are vanilla AKS deployments).
> 
> Perhaps I missed the docs, but is konnectivity a requirement?

I have just deployed a new test cluster using kubenet for the CNI. It uses konnectivity.

Looking at the last release notes. The konnectivity rollout should be finished by the end of this week.

So I would say once Konnectivity is running on your clusters you should be fine.

**Comment by mjyeaney** [comment]
@PixelRobots That may explain some of the oddities then - but I don't see anything in the UDR that would prevent 0.0.0.0/0.  I am wondering if there is an issue with the public balancer having and outbound rule programmed while we attached the NAT gateway (I was hoping NAT gateway would override). May have to test again and remove the LB outbound rule.

**Comment by PixelRobots** [comment]
@mjyeaney if I remember right. UDR will take precedence over the subnet. So if you have a load balancer, NAT will trump it. Then UDR will trump NAT. 

Hope that makes sense.

**Comment by MartinForReal** [comment]
Maybe you can try out userAssignedNATGateway option?
