### ISSUE TITLE
az aks upgrade | all nodes upgraded except one

### ISSUE THREAD

**Issue by kim0** [Azure/AKS#1167]
**What happened**:
az aks upgrade -k 1.14.6

**What you expected to happen**:
Actually I expected it to only upgrade the control plain, it did that and also upgraded the nodepool. That caught me by surprise, but that's Ok! The real problem is that all nodes except one were upgraded!

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.5 => 1.14.6
- Size of cluster (how many worker nodes are in the cluster?) 5

```
$ kubectl get node
NAME                                STATUS   ROLES   AGE   VERSION
aks-agentpool-33463928-vmss000005   Ready    agent   9d    v1.14.5
aks-agentpool-33463928-vmss00000h   Ready    agent   43h   v1.14.6
aks-agentpool-33463928-vmss00000i   Ready    agent   43h   v1.14.6
aks-agentpool-33463928-vmss00000j   Ready    agent   43h   v1.14.6
aks-agentpool-33463928-vmss00000k   Ready    agent   43h   v1.14.6
```

**Comment by jluk** [comment]
@kim0 if you have a single nodepool, the az aks upgrade command will upgrade both control plane and pool just FYI. when you have multiple pools that is when az aks upgrade is CP only since if only one exists the assumption is keeping both in-sync.

could you check the clusterstate of this cluster / is the upgrade operation succeeded? this might even be a known issue being addressed with in-place upgrade but uncertain - @xizhamsft thoughts?

**Comment by kim0** [comment]
Yes .. the state for both the cluster and the nodepool is succeeded
```bash
az aks list -g weu1 -o jsonc | grep -i state
        "provisioningState": "Succeeded",
    "provisioningState": "Succeeded",
```

**Comment by jluk** [comment]
Thanks @kim0 for the report, would you please open a support ticket for this? We have planned work to improve the reconciliation path for an agentpool that may not be synced to goal state. A support ticket enables us to take a look at the cluster itself to see if there is a specific bug causing the single node loss of upgrade. Closing here as a result of needing on-call inspection.
