### ISSUE TITLE
az aks create tries to use deleted service principal

### ISSUE THREAD

**Issue by aleksen** [Azure/AKS#117]
When deploying an AKS cluster it seems like the az command is reading service principal information from the file ~/.azure/acsServicePrincipal.json . In my case this service principal does not exist anymore and the deployment fails. Output:

`Operation failed with status: 'Bad Request'. Details: Service principal clientID: <clientId> not found in Active Directory tenant <tenantId>, Please see https://aka.ms/acs-sp-help for more details.`

Desired outcome is that the command should create a new service principal.

**Comment by mboersma** [comment]
@aleksen this is expected behavior, although you have to read fine print of `az aks create -h` to find out. If you don't supply an explicit `--service-principal` and `--client-secret`, the `az` CLI creates one for you and caches it for reuse by subsequent commands.

If you `rm ~/.azure/acsServicePrincipal.json` and try again, you'll get a new service principal.

**Comment by aleksen** [comment]
Thanks, @mboersma !

**Comment by TallOrderDev** [comment]
Correction, `rm ~/.azure/aksServicePrincipal.json` above uses acs, not sure if they updated or it always was, but the file is now "askSer..." 

The error message should be better here as this is not an unreasonable event to have happen.
