### ISSUE TITLE
Question: if azure aks kubenet networks are internal, why shouldn't they overlap?

### ISSUE THREAD

**Issue by mb345345** [Azure/AKS#1175]
Hi folks, after checking out [https://docs.microsoft.com/en-us/azure/aks/configure-kubenet](url), and following the advice there, it appears that for the services, pods and docker cidr's shouldn't overlap with any other addresses used (presumably within the same vnet), eg.

> The --service-cidr is used to assign internal services in the AKS cluster an IP address. This IP address range should be an address space that isn't in use elsewhere in your network environment.

I'm just not sure why this should be. Are these ip's actually accessible on the vnet? I was under the impression that these cidrs were only within aks, and only a cni cluster would allow direct access. Can anyone elucidate on this matter?

And I suppose the next question would be, what happens if they do overlap?

**Comment by seanmck** [comment]
If they overlap, then any applications running in the cluster will not be able to reach the endpoints outside the cluster because traffic will always be directed to endpoints backing the Kubernetes service IP. This guidance is defensive on the assumption that such interactions may be required. If you don't need anything running in the cluster to reach the endpoints in the overlapping network range, it should be fine.

**Comment by mb345345** [comment]
Thanks for clarifying this Sean :)
