### ISSUE TITLE
After AKS ARM template deployment, subnet originally associated with routetable gets dissociated

### ISSUE THREAD

**Issue by vic4926** [Azure/AKS#1242]
**What happened**:
After an ARM template deployment, it appeared to have a DNS issue across the cluster which led to consistent pod failures. Turned out the subnet associated with the route table of the cluster nodes was no longer associated. 

**What you expected to happen**: 
The associated subnet should still be associated after the ARM template deployment.

**How to reproduce it (as minimally and precisely as possible)**:
Make an ARM template deployment to an existing cluster(or a new deployment of the cluster with a same name) which the nodes have a route table associating with a subnet. Observe the subnet gets dissociated after the deployment. (Happens most of the time).

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13.10
- Size of cluster (how many worker nodes are in the cluster?): 3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): python apps, ingress controller, redis
- Others:

**Comment by jluk** [comment]
@vic4926 can you please open a support ticket so our engineers can take a look? This is not expected behavior and we will fix it if discovered it's a bug. Having a ticket open allows us to take a look and get some better details as opposed to bouncing back and forth on github.

Closing but please do keep the cluster and ref it in the ticket.
