### ISSUE TITLE
single instance of Tunnelfront pod not enough , AKS cluster is not completely HA

### ISSUE THREAD

**Issue by abidahmeds** [Azure/AKS#1300]
whenever the Tunnelfront pod has a issue or upgrade happens or restarts once in a while, even if it is for few minutes - cluster access to logs, helm /tiller execution , container attach etc fails. When a cluster is in production environment with 24/7 testing or production payload, logs pulled or charts created , even if for few mins tunnelfront pod is down or being replaced with a new image or restarts , all jobs fail.  
The question is why Tunnelfront pod is single instance in AKS cluster ?? why it is not HA configuration if it is so important for logs, tunnel functionality using port 10250.

**Comment by palma21** [comment]
We've added additional resilience and recovery to the tunnel prod and there's a new implementation for it being rolled out now called aks-link that will open the possibility for HA. You can already receive this on AKS Uptime SLA clusters, and free clusters are receiving it gradually.

On the current implementation technical constraints did not allow that. 

Since we already have a feature to track that I'll close this for now since it has some time as well, but feel free to reply if you feel otherwise.
