### ISSUE TITLE
Problems with unresponsive nodes

### ISSUE THREAD

**Issue by seniorquico** [Azure/AKS#131]
We've experienced some issues today with our managed Azure Container Service (K8s) cluster. This is the second time we've weathered a scenario just like this, and we're still trying to sort through whether this is an AKS-related issue or an "us" issue.

One of the nodes' CPU spiked to 100%, and we could no longer SSH to pods, query for logs (get erros that the pods don't exist), or reach the dashboard (which was coincidentally running on this node). The node appeared in a "NotReady" state when querying via kubectl. After waiting for a couple of hours to see if the problem would resolve itself, we rebooted the node.

Almost immediately, a second node's CPU spiked to 100%. After some time, I noticed that all of the pods on this second node were "stuck" in a "Terminating" status. We still couldn't reach the dashboard-- which coincidentally or not-- appears to have moved to this node. After waiting for a couple of hours, we rebooted the node.

Things now appear to be running just fine. Poking around for a bit, I can't really find anything that indicates what happened. I did notice that the two nodes that failed and we rebooted (1 and 2) have different kernel versions that the other two that haven't been manually rebooted (0 and 3):

```sh
$ kubectl get nodes -o=wide
NAME                        STATUS    ROLES     AGE       VERSION   EXTERNAL-IP   OS-IMAGE                      KERNEL-VERSION      CONTAINER-RUNTIME
aks-agentpool1-xxx-0   Ready     agent     62d       v1.8.2    <none>        Debian GNU/Linux 8 (jessie)   4.11.0-1014-azure   docker://1.12.6
aks-agentpool1-xxx-1   Ready     agent     62d       v1.8.2    <none>        Debian GNU/Linux 8 (jessie)   4.13.0-1005-azure   docker://1.12.6
aks-agentpool1-xxx-2   Ready     agent     62d       v1.8.2    <none>        Debian GNU/Linux 8 (jessie)   4.13.0-1005-azure   docker://1.12.6
aks-agentpool1-xxx-3   Ready     agent     62d       v1.8.2    <none>        Debian GNU/Linux 8 (jessie)   4.11.0-1014-azure   docker://1.12.6
```

I have some questions, and I'm hoping anyone in the community might have some experience to share.

- Have you experienced anything similar to this?
- How do you monitor your managed Azure Container Service nodes for problems?
- Will managed Azure Container Service automatically restart failed nodes?
- Is there a schedule/policy/algorithm posted that describes the OS patching procedure on Azure Container Service nodes?

**Comment by alexanderzimmer** [comment]
We do also see this behavior in our cluster. We are using kubernetes version 1.8.6. The node reaches ~90-95% CPU usage. Pods on this node can't terminate and are slow or don't respond. Even ssh-ing into them is not possible.

The worst problem is that a non-functional node is shown as "ready" in "kubectl get nodes" overview.

**Comment by mvmalderen** [comment]
We're experiencing similar behavior as described above on a 4-node AKS cluster. Before we scaled up from 3 to 4 nodes the issue was there too. After running a Spark workload on our cluster we're seeing all sorts of odd things happen ranging from nodes getting in NotReady but still having running pods, to pods stuck in Unknown or Terminating states. Rebooting the underlying VM of the Azure scale set seems to temporarily resolve this situation until we run our workloads again. This is very annoying and in a production environment the workaround of rebooting nodes is not a very desirable fix if 2 hours (or less) later the same situation occurs.

`$ kubectl get nodes
NAME                       STATUS     ROLES     AGE       VERSION
aks-agentpool-27796459-0   Ready      agent     3d        v1.10.5
aks-agentpool-27796459-1   NotReady   agent     3d        v1.10.5
aks-agentpool-27796459-3   Ready      agent     3d        v1.10.5
aks-agentpool-27796459-4   Ready      agent     4h        v1.10.5`

`$ kubectl get pods -n elk
NAME                                 READY     STATUS    RESTARTS   AGE
elasticsearch-data-0                 1/1       Running   0          7h
elasticsearch-data-1                 1/1       Running   0          7h
elasticsearch-data-2                 1/1       Unknown   0          7h
elasticsearch-head-b4fb898cd-89rlf   1/1       Running   0          1h
elasticsearch-head-b4fb898cd-pn2zh   1/1       Unknown   1          2d
elasticsearch-master-0               1/1       Running   0          7h
elasticsearch-master-1               1/1       Running   0          7h
elasticsearch-master-2               1/1       Unknown   0          7h
kibana-c74bdc999-k9qjh               1/1       Unknown   1          2d
kibana-c74bdc999-m6nm6               1/1       Running   0          1h
kibana-c74bdc999-nn595               1/1       Running   1          2d`

`$ kubectl get pods -n spark-cluster
NAME                              READY     STATUS    RESTARTS   AGE
jupyter-698b87d6d4-tqm86          1/1       Running   1          22h
spark-livy-5fdcd494f7-gvqjd       1/1       Unknown   1          2d
spark-livy-5fdcd494f7-ls94l       1/1       Running   0          1h
spark-master-b6cb67bb4-8t4ns      1/1       Running   1          1d
spark-ui-proxy-56b5d64799-fcthz   1/1       Unknown   1          2d
spark-ui-proxy-56b5d64799-gw26z   1/1       Running   0          1h
spark-worker-ff758b68f-ntb2s      1/1       Running   0          4h
spark-worker-ff758b68f-qzdwm      1/1       Running   0          4h`

**Comment by seanknox** [comment]
Closing due inactivity. Feel free to re-open if still an issue.

**Comment by damienwebdev** [comment]
@seanknox I think a basic response regarding the nature of "self-healing" nodes in an ACS availability set or an AKS cluster would help. Do note that I'm not referring to the nature of self-healing AKS containers, as they're managed by replication controllers in k8s. 

What I, and I think the majority of people on this issue, are wondering is IF I were to kill a node (either manually or by murdering it with overload), would the availability set for the cluster bring a new node back up to keep the number of nodes consistent with what was requested?
