### ISSUE TITLE
Node time off-sync

### ISSUE THREAD

**Issue by henrylilei** [Azure/AKS#1336]
**What happened**:
Node time is off-sync.

**What you expected to happen**:
Node time in-sync with each other.

**How to reproduce it (as minimally and precisely as possible)**:
One of my clusters in Mooncake has this issue.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.8

**Logs**:
● systemd-timesyncd.service - Network Time Synchronization
   Loaded: loaded (/lib/systemd/system/systemd-timesyncd.service; enabled; vendor preset: enabled)
  Drop-In: /lib/systemd/system/systemd-timesyncd.service.d
           └─disable-with-time-daemon.conf
   Active: active (running) since Tue 2019-11-26 03:38:51 UTC; 1 day 3h ago
     Docs: man:systemd-timesyncd.service(8)
 Main PID: 955 (systemd-timesyn)
   Status: "Synchronized to time server 91.189.89.198:123 (ntp.ubuntu.com)."
    Tasks: 2
   Memory: 1.8M
      CPU: 95ms
   CGroup: /system.slice/systemd-timesyncd.service
           └─955 /lib/systemd/systemd-timesyncd

-- Logs begin at Tue 2019-11-26 03:36:25 UTC, end at Wed 2019-11-27 07:02:53 UTC. --
Nov 26 03:35:42 localhost.localdomain systemd[1]: Starting Network Time Synchronization...
Nov 26 03:35:42 localhost.localdomain systemd[1]: Started Network Time Synchronization.
Nov 26 03:36:12 aks-scalable-28732146-3 systemd-timesyncd[853]: Synchronized to time server 91.189.91.157:123 (ntp.ubuntu.com).
Nov 26 03:38:24 aks-scalable-28732146-3 systemd[1]: Stopping Network Time Synchronization...
Nov 26 03:38:24 aks-scalable-28732146-3 systemd[1]: Stopped Network Time Synchronization.
-- Reboot --
Nov 26 03:38:51 aks-scalable-28732146-3 systemd[1]: Starting Network Time Synchronization...
Nov 26 03:38:51 aks-scalable-28732146-3 systemd[1]: Started Network Time Synchronization.
Nov 26 03:39:22 aks-scalable-28732146-3 systemd-timesyncd[955]: Synchronized to time server 91.189.89.198:123 (ntp.ubuntu.com).

From timedatectl:
      Local time: Wed 2019-11-27 07:03:49 UTC
  Universal time: Wed 2019-11-27 07:03:49 UTC
        RTC time: Wed 2019-11-27 07:03:49
       Time zone: Etc/UTC (UTC, +0000)
 Network time on: yes
NTP synchronized: yes
 RTC in local TZ: no

Thanks!

**Comment by xenalite** [comment]
Does your AKS Subnet have an NSG applied? We found that we were blocking UDP Port 123 to time servers, so the nodes drifted out of sync.

**Comment by henrylilei** [comment]
The NSG is a default one and Outbound was allowed on Any Port Any Protocol.

**Comment by d4rkd0s** [comment]
@henrylilei If you check here: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/time-sync

Microsoft states that the nodes (running marketplace Ubuntu) will sync to ntp.ubuntu.com, the output you sent appears to be correct.

`Network time on: yes` ✅
`NTP synchronized: yes` ✅
`Synchronized to time server 91.189.91.157:123 (ntp.ubuntu.com)` ✅

Also appears it's been running and the service is active:
`Active: active (running) since Tue 2019-11-26 03:38:51 UTC; 1 day 3h ago`

You might want to try this from (https://docs.microsoft.com/en-us/azure/virtual-machines/linux/time-sync)
```
To confirm NTP is synchronizing correctly, run the ntpq -p command.
```

**Comment by keshavprasadms** [comment]
Yes same issues here. This is a big blocker since our google sso loging fails when there is a drift. And when we have auto scaling enabled, we dont want to go to every node manually and install ntpd.

Previously on AKS node pool
deployer@aks-nodepool1-33649709-1:~$ sudo timedatectl status
      Local time: Mon 2020-02-24 13:16:44 UTC
  Universal time: Mon 2020-02-24 13:16:44 UTC
        RTC time: Mon 2020-02-24 13:14:55
       Time zone: Etc/UTC (UTC, +0000)
 Network time on: yes
NTP synchronized: no
 RTC in local TZ: no

As a workaround we have installed ntpd and added this in the configuration file
/etc/systemd/timesyncd.conf
[Time]
Servers=0.debian.pool.ntp.org 1.debian.pool.ntp.org 2.debian.pool.ntp.org 3.debian.pool.ntp.org

deployer@aks-nodepool1-33649709-1:~$ sudo timedatectl status
      Local time: Mon 2020-02-24 13:20:21 UTC
  Universal time: Mon 2020-02-24 13:20:21 UTC
        RTC time: Mon 2020-02-24 13:20:21
       Time zone: Etc/UTC (UTC, +0000)
 Network time on: yes
NTP synchronized: yes
 RTC in local TZ: no

**Comment by previ** [comment]
We had the same issue but it turned out to be a firewall problem (still investigating).
ntp is not installed but not needed by timedatectl/timesyncd ( see https://help.ubuntu.com/lts/serverguide/NTP.html ).
