### ISSUE TITLE
Public IP not released when deleting cluster via Terraform

### ISSUE THREAD

**Issue by giggio** [Azure/AKS#1405]
I am bringing this over from https://github.com/terraform-providers/terraform-provider-azurerm/issues/4911

**What happened**:
It is not possible to delete an AKS resource if a public ip is attached to a k8s service of type LoadBalancer.

**What you expected to happen**:
When deleting the AKS resource, the IP is released and the resource is deleted.

**How to reproduce it (as minimally and precisely as possible)**:
Create a service of type LoadBalancer with a public IP.

**Anything else we need to know?**:
This was tested in AKS with Terraform. See the related item on the beginning of the issue.

**Workaround**:
First delete the service, then delete AKS.
This works but AKS should be able to clean up after itself.

**Environment**:
- Kubernetes version (use `kubectl version`): Occurs in all versions
- Size of cluster (how many worker nodes are in the cluster?): Does not matter
- General description of workloads in the cluster: does not matter

**Comment by syedhassaanahmed** [comment]
+1 We're currently facing this issue.

**Comment by mmcarguero** [comment]
+1 We're currently facing this issue.

**Comment by giggio** [comment]
Please don't add comments with +1, add your 👍.

**Comment by palma21** [comment]
This is not something we see on normal deployments, 

For example, a simple 

```
az aks create -n aks -g aks 

kubectl apply -f azure-vote.yaml (with a service type LB)

az aks delete -n aks -g aks 
```
just works, same happens if I use ARM, python or go SDKs.

So it seems that the scenario under which this happens is restricted to what TF is doing.  When AKS is deleted all those resources are cleaned up as expected, but you need to send the call to delete it first. Could it be that TF is not following the same order ARM does when deleting an RG and start by the highest level objects and is trying to delete the IP before deleting the cluster?

Did you try to delete aks for example via CLI after deploying via TF to confirm?

**Comment by jluk** [comment]
cc @tombuildsstuff in the event he knows if TF has some additional logic for resource deletion

**Comment by tombuildsstuff** [comment]
@jluk apologies for the delay replying - been afk.

Terraform uses the same graph for creation and deletion - so if a resource is created after another resource (for example a Pod is created after the AKS Cluster is created, which is created after the Resource Group) then they'll be deleted in the reverse order (e.g. the Pod gets deleted before the AKS Cluster before the Resource Group).

That said, in retrospect it appears this is an issue with Terraform Core's dependency ordering rather than AKS directly - and I believe this has been fixed in a newer version of Terraform Core, so I'd suggest confirming if this issue still exists on those.

**Comment by ams0** [comment]
Tested with k8s 1.18.4, TF 0.12.26, created an `azurerm_kubernetes_cluster` resource, create a deployment+service of type `LoadBalancer` (using `kubectl`), then `terraform destroy`. Cluster and RG went away without a hitch.

**Comment by jluk** [comment]
It looks like this is resolved on the latest version of TF core, at least that's how I read these comments. As a result I'm going to close this issue as resolved externally via TF since it doesn't look like an AKS issue.

Thanks for the info @tombuildsstuff / @ams0 lmk if I misunderstood anything in here.
