### ISSUE TITLE
kubectl get fails with error Unable to connect to the server: dial tcp: look up ....no such host

### ISSUE THREAD

**Issue by grohan2002** [Azure/AKS#141]
Issue 
AZCLI used - 2.0.25
Created an AKS setup used the Jenkins Microsoft Template workstation .
Commands used 
==> az group create --name simplimedaks-new-rg --location eastus
==> az aks create --resource-group simplimedaks-new-rg --name simplimedaks-new --node-count 2 --generate-ssh-keys   --kubernetes-version 1.8.1
==> sudo az aks install-cli
==> az aks get-credentials --resource-group=simplimedaks-new-rg --name=simplimedaks-new
==> kubectl get node -o wide

error 
Unable to connect to the server: dial tcp: lookup simplimeda-simplimedaks-new-4ad96d-c2b29752.hcp.eastus.azmk8s.io on 168.63.129.16:53: no such host

**Comment by lopolipop** [comment]
me too

**Comment by mdaguete** [comment]
Same with westeurope, 

    Unable to connect to the server: net/http: TLS handshake timeout

**Comment by seneccamiller** [comment]
Have you tried creating the cluster with version 1.8.6?

**Comment by rohangupt** [comment]
@seneccamiller  Tried with 1.8.6 ,

was able to connect using kubectl but still we are facing intermittent connection issues 

vagrant@node2:~$ kubectl get nodes -o wide
The connection to the server simplimeda-simplimedaks-new-4ad96d-693e3b50.hcp.eastus.azmk8s.io:443 was refused - did you specify the right host or port?
vagrant@node2:~$ kubectl get nodes -o wide
The connection to the server simplimeda-simplimedaks-new-4ad96d-693e3b50.hcp.eastus.azmk8s.io:443 was refused - did you specify the right host or port?
vagrant@node2:~$ kubectl get nodes -o wide
The connection to the server simplimeda-simplimedaks-new-4ad96d-693e3b50.hcp.eastus.azmk8s.io:443 was refused - did you specify the right host or port?
vagrant@node2:~$ kubectl get nodes -o wide
NAME                       STATUS     ROLES     AGE       VERSION   EXTERNAL-IP   OS-IMAGE                      KERNEL-VERSION      CONTAINER-RUNTIME
aks-nodepool1-33828484-0   NotReady   agent     14m       v1.8.6    <none>        Debian GNU/Linux 8 (jessie)   4.11.0-1016-azure   docker://1.12.6
aks-nodepool1-33828484-1   Ready      agent     13m       v1.8.6    <none>        Debian GNU/Linux 8 (jessie)   4.11.0-1016-azure   docker://1.12.6
vagrant@node2:~$ kubectl get nodes -o wide
NAME                       STATUS     ROLES     AGE       VERSION   EXTERNAL-IP   OS-IMAGE                      KERNEL-VERSION      CONTAINER-RUNTIME
aks-nodepool1-33828484-0   NotReady   agent     15m       v1.8.6    <none>        Debian GNU/Linux 8 (jessie)   4.11.0-1016-azure   docker://1.12.6
aks-nodepool1-33828484-1   Ready      agent     14m       v1.8.6    <none>        Debian GNU/Linux 8 (jessie)   4.11.0-1016-azure   docker://1.12.6

Moreover , one of the nodes in the setup gives the same error as mentioned in the issue ;-

 Warning  KubeletSetupFailed       13m   kubelet, aks-nodepool1-33828484-0  Kubelet failed to get node info: failed to get external ID from cloud provider: Get http://169.254.169.254/metadata/instance/compute/name?api-version=2017-04-02&format=text: dial tcp 169.254.169.254:80: getsockopt: no route to host

**Comment by lpozo16** [comment]
Hi there! I'm new in Azure. I've installa a Kubernetes Cluster v1.9.6 in Azure and followed the steps in order to operate kubernetes from console.

When I try to get any resource, for example the pods, by executing `**kubectl get pods**`, I'm getting back next error:
`**Unable to connect to the server: proxyconnect tcp: dial tcp: lookup http: no such host**`

Equally, if I try to execute any other command by using AKS, for example next one `**az aks browse --resource-group my_POC_kubernetes --name PocKubernetes**`, y get back next error: `**Unable to connect to the server: proxyconnect tcp: dial tcp: lookup http: no such host**`.

My region is WestEurope.

Thanks a lot! :-)

**Comment by seanknox** [comment]
Closing due inactivity. Feel free to re-open if still an issue.

**Comment by andrei-dascalu** [comment]
this happens constantly to me on newly created AKS cluster

**Comment by bhvishal9** [comment]
This is happening on AWS as well with kops created clusters.

**Comment by ylhyh** [comment]
same issue here, I have just deployed a new cluster in US West 2, but can't connect to apiserver due to the DNS resolve issue:
`ylhyh@Azure:~$ az aks get-credentials --resource-group q1win --name q1win
The behavior of this command has been altered by the following extension: aks-preview
Merged "q1win" as current context in /home/ylhyh/.kube/config
ylhyh@Azure:~$ kubectl get nodes
Unable to connect to the server: dial tcp: lookup q1win-dns-27def107.c61914bc-dfd4-4cb1-9582-947bd9976708.privatelink.westus2.azmk8s.io on 168.63.129.16:53: no such host`

**Comment by ylhyh** [comment]
I have a workaround to bypass this issue: disable "Private cluster" feature when creating kubernetes cluster

**Comment by PhelixPhoenix** [comment]
I'm also having this issue. Followed these steps https://docs.microsoft.com/en-us/azure/aks/azure-ad-integration exactly and can't connect.

**Comment by gminnella23** [comment]
Hi
was getting this today. I have the aks-preview extension as part of my az CLI. It was out of date. I upgraded it and everything is working again.

**Comment by raouf-massy** [comment]
hello
you forgot this command
az aks get-credentials --resource-group myResourceGroup --name myAKSCluster

**Comment by eman32387** [comment]
> hello
> you forgot this command
> az aks get-credentials --resource-group myResourceGroup --name myAKSCluster

Yes. This solves the issue. Make sure also that you set the subscription if you have multiple.
