### ISSUE TITLE
Multiple auto-created identities cause auth issues

### ISSUE THREAD

**Issue by wasker** [Azure/AKS#1410]
**What happened**:
aks-preview 0.4.27 started to auto-create and assign omsagentIdentity to node pools. This causes code that doesn't expect multiple identities present to fail (i.e. calls to metadata identity endpoint fails due to missing client_id/object_id).

**What you expected to happen**:
Limit the amount of auto-created managed identities to 1. If users need more than one identity on the pool, this should be an explicit decision - otherwise it's a surprise that requires updates in infra that is not enlightened about multiple identities (e.g., acs-keyvault-agent).

**How to reproduce it (as minimally and precisely as possible)**:
1. Use aks-preview 0.4.27+ to create AKS cluster with `--enable-managed-identity` option.
1. Start debian pod in cluster with kubectl.
1. Execute `curl -H "Metadata:true" "http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https://vault.azure.net/"` from the pod.
1. Observe that the call fails, until one of the identities' ID is passed in client_id/object_id parameter. If you remove one of the identities and reimage VMSS, the call succeeds.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.17
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by wasker** [comment]
What's interesting is that azure.json on the node has `userAssignedIdentityId` matching the kubelet identity that I see in the output of `az aks show`. However queries to the metadata identity endpoint are failing if both kubelet and omsagent identities are configured on the VMSS.

**Comment by jluk** [comment]
@sauryadas could you take a look at this MI issue?

**Comment by sauryadas** [comment]
@norshtein will take a look at this when he is back from holidays next week.

**Comment by norshtein** [comment]
This is expected behavior. All identities created by AKS are infra identities and are not expected to be used by end user. To use an identity in your application pod, you should use [aad-pod-identity](https://github.com/Azure/aad-pod-identity). If you do want to use AKS created identity in your pod, you should provide the identity client id to your pod and let your application pod send request with client id.

**Comment by sauryadas** [comment]
thanks @norshtein .. @wasker This is a deviation from the experience we had with SPN's (and by design) where anyone with access to the cluster could simply refer it. The whole migration to using Managed Identities and having individual identities for the cloud provider and each add on is to provide a separation of duties with each identity

**Comment by wasker** [comment]
It looks like aad-pod-identity [is not supported by Windows containers though](https://github.com/Azure/aad-pod-identity/issues/242).
