### ISSUE TITLE
GPU & AZ: 'The requested size for resource '<REDACTED>' is currently not available in location 'eastus' zones '1,2,3' for subscription '<REDACTED>'.

### ISSUE THREAD

**Issue by jayush** [Azure/AKS#1444]
**What happened**:
Create AKS cluster with GPU nodepool with AvailabilityZones. Tried few combinations of GPU instance types and regions with same result. Nodepool creation fails even when a single availability zone is specified. Creating GPU nodepool in the same region without AvailabilityZones works. 

**What you expected to happen**:
GPU nodepool creation should work with AvailabilityZones. If GPU nodepools with AvailabilityZones is not supported, this should be documented as a limitation in https://docs.microsoft.com/en-us/azure/aks/availability-zones. 

**How to reproduce it (as minimally and precisely as possible)**:
Create "gpuzones" nodepool with availability zones. Observe that the GPU nodepool with availability zones creation fails with the error you are getting
```
az aks nodepool add --resource-group <REDACTED> --cluster-name <REDACTED> --name gpuzones --node-count 2 --node-vm-size Standard_NC6s_v2 --node-zones {1,2,3}
Operation failed with status: 'Bad Request'. Details: Provisioning of resource(s) for Agent Pool gpuzones failed. Error: {
  "code": "InvalidTemplateDeployment",
  "message": "The template deployment failed with error: 'The resource with id: '<REDACTED>' failed validation with message: 'The requested size for resource '<REDACTED>' is currently not available in location 'eastus' zones '1,2,3' for subscription '<REDACTED>'. Please try another size or deploy to a different location or zones. See https://aka.ms/azureskunotavailable for details.'.'."
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by jluk** [comment]
Thanks for reporting @jayush the error implies the VM creation could not occur due to allocation. I don't believe there is any blocker on using GPUs with Zones.

The error doc returned shows the msg is given if Azure quota can't meet the request. https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/error-sku-not-available#symptom

To help diagnose, can you try this deployment in another region with the SKU and 3 zones available? It may also be the case that particular SKU wasn't available at request time in one of those zones.

**Comment by palma21** [comment]
Closing after answer was provided. Please do open another ticket if necessary
