### ISSUE TITLE
Get CanNotTaintAllAgentPools with a soft taint on 1.17 (preview)

### ISSUE THREAD

**Issue by Bessonov** [Azure/AKS#1484]
**What happened**:

I'm not sure, that this is intended, but I would ask, because it was working some weeks ago. We have following definition for the default Pool:

```hcl
	default_node_pool {
		name               = "default"
		node_count         = 1
		# define bare minimum VM for the default node pool
		vm_size            = "Standard_D1_v2" # 1/3.5
		# this setting forces the AKS Master to be HA
		availability_zones = ["1", "2", "3"]
		# Required for advanced networking
		vnet_subnet_id     = azurerm_subnet.aks.id
		node_taints = [
			"instance-type=low:PreferNoSchedule"
		]
	}
```

The reason for this Taint is that the default pool is very unflexible and therefore we don't want to schedule any of our workloads on this pool. Instead we've added a **soft** taint and defined desired `azurerm_kubernetes_cluster_node_pool` without taints.

This worked some weeks ago, but now we get following error for new clusters:

> Error creating Managed Kubernetes Cluster "XXX" (Resource Group "XXX"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="CanNotTaintAllAgentPools" Message="Operation failed due to insufficient nodes for system pod scheduling. Placing custom taints on all node pools is not supported. Retry the operation and leave at least one node pool untainted.

**What you expected to happen**:

That the creation of cluster is possible or alternatively no workloads are scheduled. A more satisfying solution can be to relax requirement of default node pool if at least one `azurerm_kubernetes_cluster_node_pool` is defined.

**How to reproduce it (as minimally and precisely as possible)**:

See above.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2020-01-27T21:11:27Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

- Size of cluster (how many worker nodes are in the cluster?): 1 default + 3x node pool with 1 node
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by Bessonov** [comment]
further activity occurs

**Comment by palma21** [comment]
We currently block if you add taints to all pools, if you created more than one pool this should work. We can consider adding an exception for soft taints.

**Comment by c4m4** [comment]
We need to be able to add taints to the default node pools, this is affinity of tunnelfront pod:

 ```
 ¦ ¦ affinity:
  ¦ ¦ ¦ nodeAffinity:
  ¦ ¦ ¦ ¦ preferredDuringSchedulingIgnoredDuringExecution:
  ¦ ¦ ¦ ¦ - preference:
  ¦ ¦ ¦ ¦ ¦ ¦ matchExpressions:
  ¦ ¦ ¦ ¦ ¦ ¦ - key: kubernetes.azure.com/mode
  ¦ ¦ ¦ ¦ ¦ ¦ ¦ operator: In
  ¦ ¦ ¦ ¦ ¦ ¦ ¦ values:
  ¦ ¦ ¦ ¦ ¦ ¦ ¦ - system
  ¦ ¦ ¦ ¦ ¦ weight: 100
```
When we bootstrap the cluster, the default pool will be the first to come up and the system pods will be schedule there, we will end up with pods running in the default agent pool and create a pool with mode = System is useless

**Comment by holgercn** [comment]
we follow [this](https://docs.microsoft.com/en-us/azure/aks/use-system-pools) document, do not schedule application pods to the system node pool. so we add the suggested taint (CriticalAddonsOnly=true:NoSchedule). facing exact the same issue with terraform and azurerm v2.24.0

**Comment by c4m4** [comment]
In few words, we are node able to mark the default pool as system pool using mode = "System" attribute and we are not able to taint the default pool

**Comment by tshaiman** [comment]
following @holgercn there is an issue when you have 2 node pools and needs 1 to be system node pool with taint "CriticalAddonsOnly=true:NoSchedule"
and another worload-pool with the taint
"UserWorkload=true:NoSchedule"

this is not supported at the moment.

**Comment by holgercn** [comment]
@tshaiman thanks for the reply, but we follow this official azure aks document https://docs.microsoft.com/en-us/azure/aks/use-system-pools, so in my opinion, this is a bug.

**Comment by c4m4** [comment]
But Why no use static pods for critical pods?

**Comment by c4m4** [comment]
The first pool to be available is default pool, but We are not able to taint this pool and create it as system pool :(

**Comment by holgercn** [comment]
and there is no way add taint to node pool afterward, portal and az both do not support.

**Comment by tshaiman** [comment]
@holgercn my point exactly. I think it's a bug as well.

**Comment by lxfontes** [comment]
same situation here. trying to create 2 node pools ( system & users ) and not being able to

```
resource "azurerm_kubernetes_cluster" "runtime" {
    name                = "poc-azure"

    network_profile {
      load_balancer_sku = "Standard"
      network_plugin = "azure"
      network_policy = "calico"
      outbound_type = "loadBalancer"
    }

    default_node_pool {
        name            = "controlplane"
        ...
        node_labels = {
          "node.kubernetes.io/role" = "controlplane"
        }
        node_taints = [
          "CriticalAddonsOnly=true:NoSchedule"
        ]
      }
}

resource "azurerm_kubernetes_cluster_node_pool" "runtime" {
  name                  = "runtime"
  kubernetes_cluster_id = azurerm_kubernetes_cluster.runtime.id
  ...
  node_labels = {
    "node.kubernetes.io/role" = "runtime"
  }
}
```

**Comment by palma21** [comment]
> When we bootstrap the cluster, the default pool will be the first to come up and the system pods will be schedule there, we will end up with pods running in the default agent pool and create another pool with mode = System is useless

Correct, is it an issue for you to treat/configure the first node pool as your system nodepool?

**Comment by palma21** [comment]
> In few words, we are node able to mark the default pool as system pool using mode = "System" attribute and we are not able to taint the default pool

You don't have to. There's no concept of default node pool per se, the defaul node pool is a system nodepool by default

**Comment by lxfontes** [comment]
@palma21 IMO the issue is that terraform node pools are not evaluated within the context of the cluster resource, but as individual resources. so once resource manager evaluates the cluster creation it only sees 1 node pool ( the default ) and that cannot have taints.

```
Error: creating Managed Kubernetes Cluster "cluster-az123" (Resource Group "resources-az123"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="CanNotTaintAllAgentPools" Message="Operation failed due to insufficient nodes for system pod scheduling. Placing custom taints on all node pools is not supported. Retry the operation and leave at least one node pool untainted."
```

**Comment by palma21** [comment]
For the rest of the comments, I think that's fair that we address it. 
We want to keep blocking total taint of all node pools since that caused many issues to users who by mistake did that and caused issues on their cluster, but we should allow the the CriticalAddonsOnly taint. 

I'm opening a separate request for that to keep this one for soft taints.

**Comment by c4m4** [comment]
> 
> 
> > When we bootstrap the cluster, the default pool will be the first to come up and the system pods will be schedule there, we will end up with pods running in the default agent pool and create another pool with mode = System is useless
> 
> Correct, is it an issue for you to treat/configure the first node pool as your system nodepool?

you can't use mode = System in the default pool, I want the default pool be a system pool and when I bootstrap the cluster all critical pods get scheduled there :)

**Comment by c4m4** [comment]
> 
> 
> > In few words, we are node able to mark the default pool as system pool using mode = "System" attribute and we are not able to taint the default pool
> 
> You don't have to. There's no concept of default node pool per se, the defaul node pool is a system nodepool by default

Double check the terraform attribute default_node_pool this is the default pool and try to use kubectl describe node on one node of this pool, you will see that is not a system pool.

**Comment by cconkrig** [comment]
We are now blocked by this bug as well. Any update on it? The default node pool should support the Taint "CriticalAddonsOnly=true:NoSchedule" and it does not. I am escalating this issue to our Microsoft rep as well.

**Comment by MaxCrank** [comment]
We're using the default pool with a single node as a system "backup" pool one because of this issue, which is not very convenient. It is achieved having _CriticalAddonsOnly_ taint on the main system pool, _ServicesOnly_ taint on the service (user type) pool and also _ServicesOnly_ toleration on services. Additionally, we put specific label on the service pool and use corresponding node selector in service deployment definitions (Helm charts of third parties allow to set up both quite easily in most cases). This approach leads to a consequence that services and non-critical 3rd parties are deployed to the service pool only.

Still, it would be great to resolve the problem of having redundant node pool.

**Comment by palma21** [comment]
I can't speak for what terraform is doing, on the azure CLI, portal and ARM, the "default" node pool is system. That is the case when you deploy just a cluster with just one nodepool (you always have to have a system pool at all times)
There really isn't a default nodepool concept outside of terraform.

```output
$ az aks nodepool list --cluster-name test1 -g aks -o table
Name       OsType    KubernetesVersion    VmSize           Count    MaxPods    ProvisioningState    Mode
---------  --------  -------------------  ---------------  -------  ---------  -------------------  ------
nodepool1  Linux     1.17.9               Standard_DS2_v2  3        110        Succeeded            System
```
This issue is for soft taints support if you're interested in critical addons taint being accepted in system pools please see/comment the dedicated issue created for that. #1833

**Comment by palma21** [comment]
My point is there is nothing nor ever was on the AKS API that refers to "default node pool".
Before the concept of system pool documentation might have used that term to indicate the initial pool, but that was all it was, the initial pool, no API property refers to it as default. Hope this clarifies what I'm saying.

**Comment by matthewi** [comment]
I actually ran into this issue and am peripherally involved with the azure terraform provider. My understanding is that the method used by the provider requires the creation of a nodepool (the default node pool). This node pool is always a system pool by default. However, despite suggestions in the provider documentation you can not add taints to it since you are not allowed to taint all node pools and, effectively, it is the only node pool at the time the provider renders the cluster resource. Using ARM templates none of this is an issue I am told.

While its true that terraform provider wraps the Azure API its not just a wrapper -- there is validation and lifecycle logic encapsulated as well. This generally should align with the documented API behavior, but may occasionally diverge if that behavior is problematic. For instance, at one point the API default was to create all blobs as public, however the portal defaulted to private. The behavior in the provider was then adjusted to deviate from the API default to the more secure and well-known defaults from the portal.

**Comment by matthewi** [comment]
My workaround is to provision a single node "default" pool with a small VM to minimize cost. I have a later step in the provisioning process that cordons and drains this node once my subsequent node pools are up. Switching this to User and scaling to 0 is futile in terraform as it reverts to System and 1 node on subsequent runs and seems to ignore the lifecycle rules to ignore changes (probably because the change is triggered by validation and not configuration).
