### ISSUE TITLE
aks create failing if executed by servicePrincipal

### ISSUE THREAD

**Issue by depohmel** [Azure/AKS#149]
I have a servicePrincipal with Contributor role. 

```
az aks create --resource-group testSP --name sp-aks-test --node-count 1 --generate-ssh-keys
```
fails with 
```
Directory permission is needed for the current user to register the application. For how to configure, please refer 'https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-service-principal-portal'. Original error: Insufficient privileges to complete the operation.
```

the same create cmd executed as a regular user with Contributor role, works without error.

Even if SP got promoted to Owner, I'm getting the same error.

**Comment by noelbundick** [comment]
Looks like your SP doesn't have permissions in your AAD tenant to create new application registrations (and by extension, another service principal)

What happens if you specify the `--service-principal` and `--client-secret` options when running `az aks create`? 

Those flags should skip the app registration step & use SP info you've already created instead of trying to dynamically create a new one

**Comment by depohmel** [comment]
Yeah, I was able to find what was wrong. this one can be closed.

**Comment by willthames** [comment]
@depohmel what exactly was wrong? This issue doesn't help people with exactly the same problem.

**Comment by hsurfer** [comment]
@depohmel what wa wrong?

**Comment by joostvz** [comment]
@willthames @hsurfer I had the same issue, but don't know the root cause. I tried to create a resource group from the Azure Cloud Shell, with a user that has the Owner role, and got the same error. As a workaround, I created an [app in Azure](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-service-principal-portal), and provided its credentials via the `--service-principal` and `--client-secret` parameters (as proposed by @noelbundick).

**Comment by depohmel** [comment]
Sorry guys for not posting what was wrong.
So apparently in Azure it's enough for service-principle to be the only owner. 
you also have to add additional permissions to it for modifying active directory. a link will look something like this: Microsoft_AAD_IAM/ManagedAppMenuBlade/Permissions/

also once you add permission don't forget to save it. (ui isn't intuitive :( )

**Comment by tabareh** [comment]
The explanation didn't help me as I'm runing 
```
az aks create -g $group -n aks-cluster -l $region \
--node-count 3 --node-vm-size Standard_DS2_v2 \
--kubernetes-version 1.11.3 --verbose --generate-ssh-keys
```
and receiving
```
Use existing SSH public key file: /home/myusername/.ssh/id_rsa.pub
Creating service principal
Directory permission is needed for the current user to register the application. For how to configure, please refer 'https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-service-principal-portal'. Original error: Insufficient privileges to complete the operation.
```

**Comment by DBarthe** [comment]
@tabareh first, from an admin account, create a service principal for the aks cluster to log into : 
```
az ad sp create-for-rbac --skip-assignment -n my-aks-sp
...
# write down the "appId" and "password" 
```
then from a limited account (that cannot grant permissions to others), create the aks cluster with `--service-principal` and `--client-secret` :
```
az aks create -g $group -n aks-cluster -l $region \
--node-count 3 --node-vm-size Standard_DS2_v2 \
--kubernetes-version 1.11.3 --verbose --generate-ssh-keys \
--service-principal <appId> \
--client-secret <password>
```

**Comment by tabareh** [comment]
@DBarthe Thanks for the reply. But I don't have access to the admin account as it's managed by corporation.
