### ISSUE TITLE
Feature Request: User initiated restart of control plane

### ISSUE THREAD

**Issue by gsxmax** [Azure/AKS#1506]
The priority always to be bringing the cluster back alive, and user has to create a case for restarting apiserver is a blocker timewise to do, could we support something that user can use(simple restarts) in time?

**Comment by foobarnum** [comment]
We continually have situations where a short term failure in lower level Azure infrastructure (CPU, RAM DISK, NETWORK) puts parts of the AKS control plane in a bad state that will not recover. An example would be the controller or scheduler unable to manage the nodes due to Azure network or DNS issue.  Azure does not detect this class of issue reliably. We repeatedly end up with cluster in a bad, unrecoverable state when we attempt an operation that requires the control plane to function. Ex: kubectl logs -or- helm deploy. Our runbook for these failures is 2 steps. Contact Azure support, Priority 1, then tell them to restart the control plane. For all of our sanity it would be better if we could simply do that ourselves. This goes into the calculus when we choose how much or effort to allocate to Azure generally.

**Comment by esunder** [comment]
I'd like to see this feature as well. I resolved two issues yesterday in two different clusters by simply having Azure support restart the Kubernetes API. If I could just have a button/api call to do this myself, it would save everyone some time.

**Comment by djsly** [comment]
Subscribing... The sad part is that its not even Azure Support that issues the restart...

**Comment by miwithro** [comment]
@gsxmax @foobarnum @esunder @djsly have you upgrading to at least K8s 1.18?  We have made significant strides in the API server stability.  I would be curious if you are still seeing that post 1.18.

**Comment by djsly** [comment]
@miwithro  we have been on 1.18 for a while now, and we still get often cases where we would need to issue a rolling restart of the apiserver

**Comment by miwithro** [comment]
@juan-lee

**Comment by miwithro** [comment]
@djsly have you enabled Uptime SLA for your clusters?  This will enable a higher level of HA/DR for the API Server which will mitigate the availability issues you have seen traditionally.

**Comment by djsly** [comment]
Yes, actually the high SLA is one of the reason why we need to initiate control plane restart since having multiple API server instances causes potential discrepancies between both instances with regards to caches.

**Comment by miwithro** [comment]
Thanks @djsly that makes sense.
