### ISSUE TITLE
Clarify 2020-03-09 Change Log Entry: CIS Password Expiration

### ISSUE THREAD

**Issue by slynickel** [Azure/AKS#1507]
**What happened**: 

[2020-03-09](https://github.com/Azure/AKS/releases/tag/2020-03-09) release log states: 
> AKS enforces password expiration as part of CIS compliance but excludes the linux admin account that is using public key auth only. All accounts created using password will be subject to this enforcement. 

Can you explain what this actual means:
What action does a user need to take, for example if you have a cluster that is two years old is the password just going to unexpectedly expire? What happens if it does? What is the expiration be default? Could you provide the CIS compliance reference? Overall not sure exactly what this change means as a cluster operator.

**What you expected to happen**: N/A

**How to reproduce it (as minimally and precisely as possible)**: N/A

**Anything else we need to know?**: N/A

**Environment**:
- Kubernetes version (use `kubectl version`): N/A
- Size of cluster (how many worker nodes are in the cluster?) N/A
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) N/A
- Others: N/A

**Comment by palma21** [comment]
Hi @slynickel, no action is required for normal clusters, because AKS uses only key based auth by default. 
Did you add passwords to your nodes manually? If yes then this would be the only case where this would be important to note (albeit not being something we recommend). This change would be present in your OS configuration _after_ the next cluster upgrade.
For reference the expiration date is being enforced for over 6months now. The change above refers to the exclusion of users that are using key based auth.

Hope this clarifies, feel free to follow up otherwise.

**Comment by slynickel** [comment]
That clarifies it. We don't use add password manually or anything like that. I just didn't fully understand the scope of that change log note.

Thanks.
