### ISSUE TITLE
Could not create a role assignment for ACR. Are you an Owner on this subscription?

### ISSUE THREAD

**Issue by nigel-dewar** [Azure/AKS#1517]
I found a bug which was closed but not properly resolved, so Im logging this AGAIN as a bug, until it actually gets proper attention.

I have same issue - Waiting for AAD role to propagate[################################ ] 90.0000%Could not create a role assignment for ACR. Are you an Owner on this subscription?

Have setup a AKS cluster with Azure AD auth, RBAC etc, all works well, when I try to connect to ACR in same resource group I get this error.

How come I have permissions to do everything, except this simple and trivial thing? Seems rather strange dont you think that I need more powerful perms than those that created the entire cluster???

**Comment by mlankamp** [comment]
If I use the command with --debug parameter, I can see the following error:
`Operation failed with status: 'Bad Request'. Details: 400 Client Error: Bad Request for url: https://graph.windows.net/ad67cb34-xxxx-xxxx-xxxx-245cd582b931/getObjectsByObjectIds?api-version=1.6`

(I replace some values in the guid, but I checked it's the same guid as my tenant id)

**Comment by andyzhangx** [comment]
are you using `--attach-acr` option? it requires subs owner role to grant access to acr, contributor role won't work.

**Comment by brent-robinson** [comment]
Why is `Owner` role required on the subscription? Shouldn't `Owner` on the ACR resource be sufficient?

**Comment by lgmorand** [comment]
I do confirm, it's rare that dev teams provisioning AKS are owner of the whole subscription. What could be the minimal role they would require to create the assignement ? 
Even if doing it "manually" 

> az role assignment create --assignee $AKS_SERVICE_PRINCIPAL_APPID --scope $ACR_RESOURCE_ID --role $SERVICE_ROLE

**Comment by manpreet1994** [comment]
I have owner role still i'm getting the same error

**Comment by yene** [comment]
If you use aks-preview it caches the service principal in `.azure/aksServicePrincipal.json`, which can lead to all kinds of problems.

**Comment by manpreet1994** [comment]
For now my solution is to generate a secret and use this secret in yaml to pull images. 

For reference:- 
https://medium.com/@pjbgf/azure-kubernetes-service-aks-pulling-private-container-images-from-azure-container-registry-acr-9c3e0a0a13f2

**Comment by spewu** [comment]
I am getting this error as well, even though I am owner on the subscription. I tried with my ACR and AKS in the same resource group, and in different resource groups - but I received the error in both cases :(

**Comment by spewu** [comment]
> If you use aks-preview it caches the service principal in `.azure/aksServicePrincipal.json`, which can lead to all kinds of problems.

Ahh, this was the root of my issue - thanks for pointing that out. After deleting that file it worked as expected 👍

**Comment by rajivml** [comment]
If I own the AKS cluster and if I own the container registry , I should be able to wire them, only DevOPS folks will have the owner permissions and rest all developers usually have contributor role, so this should be relaxed

**Comment by Lutando** [comment]
I am getting this problem as well

**Comment by andrei-dascalu** [comment]
In my case, with preview enabled, I had to delete ~/.azure/aksServicePrincipal.json and then it worked. Before, with Owner, I had this exact issue.

As I manage resources for different entities, I am often switching between accounts and under each account I have access to different subscriptions, sometimes same subscriptions but with different roles depending on account.

**Comment by krowlandson** [comment]
I've recently encountered this issue too and it seems to impact a number of `az aks` operations. Sometimes this causes the operation to fail with an error, but sometimes it only generates as a warning.

In my particular case, I was running my deployment from Azure DevOps using a Service Principal to perform the deployment operations. I was also [deploying AKS with a custom Service Principal](https://docs.microsoft.com/en-us/azure/aks/kubernetes-service-principal) (although the same issue occurs with an auto-generated Service Principal), rather than [Managed Identity](https://docs.microsoft.com/en-us/azure/aks/use-managed-identity).

After assessing the verbose and debug output I was able to identify that many of the `az aks` operations rely on access to Azure Active Directory Graph (legacy). To resolve this error, you need to ensure that whichever identity you're using to run the command has permissions to use the following API:

`https://graph.windows.net/Application.ReadWrite.OwnedBy`

For a Service Principal, you can `Add a permission` here:

`Azure Active Directory > App Registrations > {{_service_principal_}} > API Permissions`

As this API requires admin consent, you need a Global Admin to grant access before it will work. This may not always be possible, so I've outlined a couple of workaround options below.

> If you're using your user account, you should check that this API is available for your user identity. This should be available by default for user accounts, but I guess access may have been restricted by a Global Admin?

**Workaround (Service Principal)**

If you're unable to grant the above permissions to your identity (not all organisations allow API access for Service Principals) and you're using a [Service Principal for your AKS Cluster](https://docs.microsoft.com/en-us/azure/aks/kubernetes-service-principal), you can use manual Role Assignments to grant access to the ACR as per the following guide:

https://docs.microsoft.com/en-us/azure/container-registry/container-registry-auth-service-principal

Note that the documented command uses the Application ID for your Service Principal. This also requires access to the Azure Active Directory Graph. As such, you will need to replace `--assignee $SERVICE_PRINCIPAL_ID` with `--assignee-object-id $SERVICE_PRINCIPAL_OBJECT_ID` where `$SERVICE_PRINCIPAL_OBJECT_ID` is the Object ID of the Service Principal, and not the Application ID which we would usually use.

For example:

```
az role assignment create --assignee-object-id $SERVICE_PRINCIPAL_OBJECT_ID --scope $ACR_REGISTRY_ID --role acrpull
```

**Workaround (Managed Identity)**

A better alternative is to use a Managed Identity for AKS, as documented here:

https://docs.microsoft.com/en-us/azure/aks/use-managed-identity

However I found this brings it's own challenges. Firstly, you cannot update an existing cluster to use Managed Identity (requires re-creation). Secondly, if you're using a custom subnet with `--vnet-subnet-id $SUBNET_ID`, you still need to provide a "dummy" value for both `--service-principal` and `--client-secret`

For example:

```
az aks create \
    --resource-group $RESOURCE_GROUP\
    --name $AKS_CLUSTER_NAME \
    --vm-set-type VirtualMachineScaleSets \
    --load-balancer-sku standard \
    --location northeurope \
    --kubernetes-version $AKS_VERSION \
    --network-plugin azure \
    --vnet-subnet-id $SUBNET_ID \
    --service-cidr 10.2.0.0/24 \
    --dns-service-ip 10.2.0.10 \
    --docker-bridge-address 172.17.0.1/16 \
    --enable-managed-identity \
    --service-principal msi \
    --client-secret null \
    --generate-ssh-keys
```

Hopefully this helps someone reading this issue, but ideally it would be great to have the `az aks` commands updated to remove reliance on the Azure Active Directory Graph.

**Comment by oising** [comment]
Thank you @krowlandson for this post -- very enlightening and well written. Definitely storing this in OneNote for future ref. It makes perfect sense that granting this scope to the service principal should fix the issue  - but I suspect the only caveat is that the same principal must be the one who created ACR and AKS for the permission to be effective. This is usually the case, but probably good to note this too.

**Comment by solmon** [comment]
Same her this seems to not work even with high subscription owner privileges...

**Comment by avishnyakov** [comment]
We've been having similar challenges. Did anyone find a working solution or comments on path forward from Microsoft?
cc @Azure/aks-pm

**Comment by avishnyakov** [comment]
Similar problem in https://github.com/Azure/azure-cli/issues/10191

**Comment by saifrahmed** [comment]
FYI - I encountered this issue while running the Azure Tutorial "Tutorial: Deploy an Azure Kubernetes Service (AKS) cluster"
here: https://docs.microsoft.com/en-us/azure/aks/tutorial-kubernetes-deploy-cluster

On a fresh account, I could not get past step 3 due to this error.

**Comment by TomGeske** [comment]
Thanks for resurfacing this one. We are currently looking into it.

**Comment by qevers** [comment]
I ran into the same issue today and tried to do the same using the Azure Portal. The portal notified me that I could only attach an ACR when using a managed identity.

**Comment by Mahesh-MSFT** [comment]
I am facing this issue too while attaching ACR with AKS using service principal as shown below.
`az aks update -g $RG -n $AKSNAME --attach-acr <MY-ACR-NAME>`

Workarounds suggested by @krowlandson on Graph API permission and Role assignments are not helping.
Another workaround suggested by @andrei-dascalu on deleting  `~/.azure/aksServicePrincipal.json` hasnt helped either.

Is this a bug? If yes, what is the fix?

**Comment by TomGeske** [comment]
We are still investigating this issue.  As workaround you can manually assign acrPull to your kubelet identity.

**Comment by Mahesh-MSFT** [comment]
@TomGeske  - do you mean service principal by kubelet identity?
 I have tried re-assigning (deleting and adding again) arcPull to service principal.  Issue still persists.

**Comment by TomGeske** [comment]
Yes, correct: : kubelet identity
Did you wait a bit? Token renewal may take up to 60 minutes.

**Comment by Zamaka** [comment]
Have also been facing the same issue, the account running the "az aks update -g $RG -n $AKSNAME --attach-acr <MY-ACR-NAME>" command didn't have permission to create a Service Principal in Azure AD.  Once granted, everything ran as expected.

Would it be possible to add a mention of this requirement to the documentation and/or error message, rather than it only requiring Subscription Owner?

**Comment by qevers** [comment]
Just to provide you with some more information...

I now have two subscriptions (different logins): one is working, the other is not. Reproducable.

When I look at the list of subscriptions (https://portal.azure.com/#blade/Microsoft_Azure_Billing/SubscriptionsBlade) neither of the subscriptions show that my role is "Owner", but both show I'm "Account admin".

Subscription A is *working*:
* No role assignments have been made to the Subscription assigning "Owner"
* Created the container registry in a new resource group
* App registration already exited, but no roles assigned.
* Created the AKS cluster, in a new resource group (az aks create)
* Attaching ACR (az aks update --attach-acr)
  - AAD role propagation instantaneously jumps to 100%
  - AKS attached to ACR
* Everything works.

Subscription B is *not working*: 
* Using the same scripts, except for changing one subscription ID and the Service Principal and Client Secret
* ACR already exists, at least since yesterday
* ACR has role assignment "AcrPull" for the Service Principal (also at least since yesterday)
* Subscription Blade says my role is "Account Admin"
* In Access control (IAM) on the subscription I assigned the "Owner" role to myself (also yesterday).
  - There is also another role assignment for "Owner" inherited from the management group.
* Create a new resource group
* Create the cluster (az aks create) 
* Attach ACR (az aks update --attach-acr)
  - "Waiting for AAD role to propagate", for almost 2 minutes. 0% ... 90%
  - "Could not create a role assignment for ACR. Are you an Owner on this subscription?

In both cases, the Service Principals only have User.Read on the Microsoft.Graph API (AAD -> App registrations -> API Permissions).

I hope this helps.

**Comment by Mahesh-MSFT** [comment]
This is definitely a bug.

For those who need workaround (1 more!). Below is what I tried and worked for me.

```
az aks get-credentials -g $RG -n $AKSNAME --admin

$ACR_UNAME=$(az acr credential show -n $ACR_FULL_NAME --query="username" -o tsv)
$ACR_PASSWD=$(az acr credential show -n $ACR_FULL_NAME --query="passwords[0].value" -o tsv)

# Create k8s secret
kubectl create secret docker-registry acr-secret `
  --docker-server=$ACR_FULL_NAME `
  --docker-username=$ACR_UNAME `
  --docker-password=$ACR_PASSWD

# Assign k8s secret to default service account
kubectl patch serviceaccount default -p '{\"imagePullSecrets\": [{\"name\": \"acr-secret\"}]}'

# Create all the services
kubectl apply -f .\manifests\<whatever>.yml
```

**Comment by SP-SuperPoney** [comment]
[...]
> $ACR_UNAME=$(az acr credential show -n $ACR_FULL_NAME --query="username" -o tsv)
> $ACR_PASSWD=$(az acr credential show -n $ACR_FULL_NAME --query="passwords[0].value" -o tsv)

In order to use this you must enable admin account :
`Run 'az acr update -n <ACR_NAME> --admin-enabled true' to enable admin first.`

BTW this is a bug.

In my case ACR is located in subscriptionA and I can't attach it to my subscriptionB AKS cluster...

**Comment by TomGeske** [comment]
@SP-SuperPoney: If you are running latest CLI + extension and still see the problem, please open a support ticket with us.

**Comment by SP-SuperPoney** [comment]
Thanks @TomGeske for you comment.
I'm using Azure Cloud Shell which is at the latest version (I think...).
I'll open a support ticket.

```
eric@Azure:~$` az --version
azure-cli                         2.11.1

core                              2.11.1
telemetry                          1.0.5 *

Extensions:
interactive                        0.4.4
webapp                            0.2.24
aks-preview                       0.4.62
azure-firewall                     0.6.0
ai-examples                        0.2.3

Python location '/opt/az/bin/python3'
Extensions directory '/home/eric/.azure/cliextensions'
Extensions system directory '/opt/az/lib/python3.6/site-packages/azure-cli-extensions'

Python (Linux) 3.6.10 (default, Aug 28 2020, 06:39:32)
[GCC 5.4.0 20160609]

Legal docs and information: aka.ms/AzureCliLegal


You have 1 updates available. They will be updated with the next build of Cloud Shell.
````

Best regards.

**Comment by jawa-the-hutt** [comment]
I was encountering this error just now and went back through the `az login` process and then it worked.  Not sure if that was what actually fixed it or if it just needed some time to pass before I tried again.

**Comment by TomGeske** [comment]
We experinced issues with az CLI token. Deleting .azure\accessTokens.json and loging in again solved it for us.

**Comment by osi-cmorgan** [comment]
> I was encountering this error just now and went back through the `az login` process and then it worked. Not sure if that was what actually fixed it or if it just needed some time to pass before I tried again.

This was the case with me as well.

**Comment by rvanmaanen** [comment]
Had the same issue today. Got the message "Could not create a role assignment for ACR. Are you an Owner on this subscription?" when trying to attach the ACR to AKS. Managed to resolve it by giving the Service Principal the following API Permission: "Application.ReadWrite.OwnedBy". The nasty thing here is, is that the Azure CLI doesn't use the new Microsoft Graph API but the legacy Azure Active Directory Graph API, so make sure to choose the right permissions!

![image](https://user-images.githubusercontent.com/4835258/93189282-3bb76b80-f742-11ea-84ad-2afaad31eb7a.png)

**Comment by haocornell-ms** [comment]
Same issue.  Tried  re "az login" as suggested above and it worked. Believe it is a bug.

**Comment by bvijaycom** [comment]
I am also facing the same issue

Waiting for AAD role to propagate[################################    ]  90.0000%ValidationError: Could not create a role assignment for ACR. Are you an Owner on this subscription?


https://docs.microsoft.com/en-us/azure/aks/tutorial-kubernetes-deploy-cluster

az aks create \
    --resource-group myResourceGroup \
    --name myAKSCluster \
    --node-count 2 \
    --generate-ssh-keys \
    --attach-acr <acrName>

seems to be an bug.Please notify once it is resolved.

**Comment by elpablete** [comment]
Same problem too, using az aks update --attach-acr <acr-resource-id> to attach a registry on another sub (in which I'm also the owner)
