### ISSUE TITLE
[Feature] Encryption at rest with customer managed keys for OS & data disk on AKS 

### ISSUE THREAD

**Issue by jluk** [Azure/AKS#1553]
https://docs.microsoft.com/en-us/azure/aks/azure-disk-customer-managed-keys

**Comment by andyzhangx** [comment]
SSE+CMK is still in preview since it depends on AKS 1.17, and AKS 1.17 is in preview stage.

**Comment by flamingboo** [comment]
Is the Data Disk encryption also only in preview??
https://docs.microsoft.com/en-us/azure/aks/azure-disk-customer-managed-keys#encrypt-your-aks-cluster-data-disk
Thought only the OS portion was:
OS Disk Encryption supported with Kubernetes version 1.17 and above

**Comment by andyzhangx** [comment]
> Is the Data Disk encryption also only in preview??
> https://docs.microsoft.com/en-us/azure/aks/azure-disk-customer-managed-keys#encrypt-your-aks-cluster-data-disk
> Thought only the OS portion was:
> OS Disk Encryption supported with Kubernetes version 1.17 and above

@flamingboo actually it's
Data Disk Encryption supported with Kubernetes version 1.17 and above, there is no version restriction for OS Disk Encryption, I will modify the doc, thanks.

**Comment by TomGeske** [comment]
Current ETA to wrap up final GA items is end of August 2020.

**Comment by akcrisp** [comment]
Read the doc on this (appreciate its in preview) but the documentation makes no mention as to what happens if they key stored in the keyvault used by the disk encryption set is deleted or the vault itself is deleted. What is the impact on a running cluster ? does it stop immediately ? Does it affect any scaleout operations ie creation of another worker node. Is any part of the encryption stored with in etcd ? In the event of the key being deleted, whats the recovery process for a cluster that was using it ? Do you have no choice but to redeploy the cluster ? How often is the key actually read ? Is it only during cluster creation ?

Secondly is there any documentation / metrics anywhere which outlines the performance impact enabling encryption has ?

**Comment by TomGeske** [comment]
Same rules as for VMs apply. I will ensure both links are added to our AKS docs.
- https://docs.microsoft.com/en-us/azure/virtual-machines/linux/disk-encryption
- https://docs.microsoft.com/en-us/azure/virtual-machines/windows/disk-encryption

During cluster creation you pass in your 
--node-osdisk-diskencryptionset-id $diskEncryptionSetId 

ETCD is not related to OS disk encryption. 
Let me know if you have further questions.

**Comment by andyzhangx** [comment]
working on azure cli support on this feature: https://github.com/Azure/azure-cli/pull/14688

**Comment by andyzhangx** [comment]
@palma21 why reopened? This feature is already supported on AKS.

**Comment by andyzhangx** [comment]
this feature is already GA: https://docs.microsoft.com/en-us/azure/aks/azure-disk-customer-managed-keys
