### ISSUE TITLE
Azure Kubernetes VM node size change not reflecting in Azure Kubernetes Service

### ISSUE THREAD

**Issue by nidiculageorge** [Azure/AKS#1556]
Hi Team,

We had scaled down the VM size (VM SCaleset) of the Node to a Lower Standard DS2_V2 from Standard DS4_V3.The node size got reduced.

But when we check in the portal for the Kubernetes the node VM size is still showing as Standard D4S_V3

image
![image](https://user-images.githubusercontent.com/43850474/79253745-59d22480-7ea1-11ea-9ff7-ae61663e3277.png)

Can someone till whether this is a bug or an issue

We have successfully resized the machine ?

**Comment by jluk** [comment]
@nidiculageorge a node pool cannot swap VM SKUs without being recreated. The azure portal should update to reflect any new node pools you've created, could you validate you have refreshed that page and the new node pool is fully operating/running?

**Comment by nidiculageorge** [comment]
@jluk We have scaled down the Node VM size to Satndard DS2_V2 from Standard DS4_V3

![image](https://user-images.githubusercontent.com/43850474/79300044-3d66d400-7f03-11ea-8bc6-34391d7e7bc5.png)

We have refreshed the page and the new Node is fully operating and we couldnt find any issues ,we havent deployed anything,but we are bale to login to the cluster and check all.No issues as such.

But the size is not reflecting in the above aks service

**Comment by jluk** [comment]
@nidiculageorge are you using only AKS API calls or are you using direct VMSS calls to deallocate and reset the VM SKU?

If the former, that's a UI bug we can track. If it's the latter swapping VMSS settings from the VMSS API is unsupported which may cause this mismatched behavior.

**Comment by nidiculageorge** [comment]
@jluk from an Infrastructure perspective we are accessing the cluster using kubectl commands and managing. There will be pods deployed in the cluster.

**Comment by jluk** [comment]
When completing this step, do you complete the below operation via a VMSS API call?
> We have scaled down the Node VM size to Satndard DS2_V2 from Standard D4S_V3

Could you clarify the repro steps you are taking for updating the VM SKU? That will help me see where things may be going wrong to loop the right team.

**Comment by nidiculageorge** [comment]
@jluk we are downsizing the nodes from the azure portal itself.

![image](https://user-images.githubusercontent.com/43850474/79581624-52508c80-80e8-11ea-92a4-9aed1c2f9e29.png)

**Comment by jluk** [comment]
Thanks for confirming, this UX issues is due to how the VMSS is managed by AKS. Since AKS is a managed service, we don't support operations done outside of the AKS API to the infrastructure resources. In this example you are using the VMSS portal to resize, which uses VMSS APIs to resize the resource and as a result has unexpected changes. More details on this is below:

https://docs.microsoft.com/en-us/azure/aks/support-policies

AKS nodepools don't support resize in place, so the supported way to do this is to create a new nodepool with a new target and delete the previous one. This needs to be done through the AKS portal UX. This maintains the goal state of the AKS node pool, as at the moment the portal is showing the VMSize AKS knows you have because that is what was originally requested.

We will take a pass at the documentation to call this out better.  Thanks for sharing this feedback, I am going to close this as a result of the above information but if you have suggestions on how to make this clearer we can continue that conversation.

cc @mlearned @jenetlan for fyi.

**Comment by nidiculageorge** [comment]
@jluk @mlearned @jenetlan i have already resized the node size without adding any additional nodes.Will it damage thecluster,as we can see no issues so far

**Comment by jluk** [comment]
On the next CRUD operation from AKS API it may cause issues. To resolve this you should add a nodepool of the VM SKU you want and delete this existing one to ensure you are using only the AKS model and not mixing the VMSS one.
