### ISSUE TITLE
[Feature Request] Automatically shutdown agent nodes on weekends with low usage

### ISSUE THREAD

**Issue by nidiculageorge** [Azure/AKS#1577]
Hi Team,

As part of cost saving we need to enable auto shutdown of nodes for the aks cluster.The nodes are virtual machine scale sets ,is it possible to shutdown the nodes through autoshutdown feature ,we need the nodes to be shutdown during the weekends

Regards,

Nithin

**Comment by nidiculageorge** [comment]
Hi Any update

**Comment by lgmorand** [comment]
You should use cluster manual scaling (with automation), you just scale down to 0 during WE which should met your requirement

**Comment by nidiculageorge** [comment]
@lgmorand ,we want the nodes to be shutdown, the virtual machine scale set during the weekend,its not about autoscale.Can we shutdown the nodes .Is thera any automation way to do so

![image](https://user-images.githubusercontent.com/43850474/80312827-27131f00-8805-11ea-83fb-7919c37d2895.png)

**Comment by lgmorand** [comment]
I may be wrong but you want have no cost during WE, aren't you ?
If yes, why scaling to 0 (and optionally scale up on Monday) is not a valid solution for you ? Are you sure it will not deallocate/remove instances within the VMSS ?

Even what you are trying to do on the VMSS with your "shutdown" needs to be scripted (for instance with az vmss deallocate, there is no "auto shutdown" because Azure does not know when is "your" WE start)

**Comment by nidiculageorge** [comment]
@lgmorand yes,the Costing for AKS is based on the Nodes that are running.

The pods that are running does not incur any charges.It depends on the pods

**Comment by lgmorand** [comment]
I'm talking about **node scaling** ;-)

**Comment by nidiculageorge** [comment]
Thanks for the link,we are panning to shutdown the nodes,is that a feasible option ,but scaling down the is not an option as the Min node count is 0 for us

**Comment by lgmorand** [comment]
you mean that you have a node pool with 0 nodes and you still have costs ? The feature is meant for that

not sure that touching the VMSS directly seems to be a good idea : https://github.com/Azure/AKS/issues/1050#issuecomment-511819808

**Comment by nidiculageorge** [comment]
No .We have a min node count set to 1 ,We need to shutdown that node during weekend. so that it wont incur any cost,

From the portal its possible. Can we do that ,is there a way to automate that shutdown, and start the nodes on Monday

**Comment by lgmorand** [comment]
They just ([**few days ago**](https://github.com/Azure/AKS/releases/tag/2020-04-13)) released the possibility to scale down to 0. now we need to wait the portal and/or the CLI to be updated. You need to be patient a little bit but it's coming

To do what you want, you can use any schedulable scripts (devops pipeline, a bat/cron on your computer, whatever you want) and the commandline that you'll have to call is documented here: https://docs.microsoft.com/en-us/cli/azure/ext/aks-preview/aks/nodepool?view=azure-cli-latest#ext-aks-preview-az-aks-nodepool-scale

**Comment by nidiculageorge** [comment]
@lgmorand is there any script to shutdown these nodes  during weekends.

![image](https://user-images.githubusercontent.com/43850474/80703357-3db8bf00-8b00-11ea-8016-ef3b249ca8c7.png)


Deallocating these nodes will save some money,thats an option we are looking into.

**Comment by lgmorand** [comment]
so I told you, you have to **write** a script that turn them off and schedule that script on WE, that's all

you can now define some nodepool as "user" mode, and scale them to zero, which means the script will be only one line of code. you can do it ;-)

**Comment by lgmorand** [comment]
@nidiculageorge  

1- you want to reduce costs
2- it can be achieved by TWO ways: 
   - scale **nodepool** to 0 which the official way to do it
   - shutdown which is **NOT** supported as explain here: https://github.com/Azure/AKS/issues/1050#issuecomment-528617142


if you really want to do something which may **break** your cluster (confirmed by the link I gave you), prevent you from having any support and really want to shutdown a VMSS, you can use the CLI 

> az vmss deallocate

would you accept to explain why node scaling is not acceptable since it'll reduce the cost to zero ?

**Comment by nidiculageorge** [comment]
@lgmorand I was just going through the link,where is it mentioned it will break the clsuter

**Comment by flamingboo** [comment]
what is meant here, is that the cluster support would no longer be supported!
" but taking the VMSS path sends the cluster out of support since it's an out of band operation outside of AKS. As you witnessed (or as I read your repro) you will always need nodes in your default cluster as that is where critical system pods end up"

**Comment by nidiculageorge** [comment]
@lgmorand So lets conclude in this way shutting down the nodes in aks is not good idea.

Pnly reduce the node count to 0 thats the only option

**Comment by lgmorand** [comment]
That's what I'm telling you from the first comment but you are stubborn <:o)

be aware that (if I read the doc correctly) scaling to 0 is only available for "user" nodepool, and you need to have at least one system nodepool with at least one node in each cluster (=at least one VM in each cluster). solution can be to create a new nodepool with cheap VM, then change node pool mode to user before the WE, scale to 0, and do the opposite on Monday morning

**Comment by jluk** [comment]
Thanks everyone for the discussion, the advice provided by @lgmorand and @flamingboo are correct. Today, your best path to reduce cost is to manually scale your user pools down to 0, but maintain the system pool node count. Actions taken to deallocate through VMSS are unsupported actions and that is described here:

https://docs.microsoft.com/en-us/azure/aks/support-policies#managed-features-in-aks

Closing as a result, but we are actively working on more cost management improvements so this will get even better over time.

**Comment by bhicks329** [comment]
What's the issue with CA scale to zero? Is there an estimated time to fix this?

**Comment by jluk** [comment]
@bhicks329 check #1565 for CA scale to zero tracking, we're investigating it now and should come in CYQ2.
