### ISSUE TITLE
Enable aks-custom-headers in ARM templates

### ISSUE THREAD

**Issue by ohorvath** [Azure/AKS#1638]
It seems many upcoming critical changes (containerd, ubuntu 18.04 etc.) can only be enabled from Azure CLI and not from ARM templates. Our product has been built around ARM templates (provisioning and configuring AKS on the fly then deploying charts) and it's critical for us to test out the new features before those becoming the defaults.

**Comment by palma21** [comment]
Thanks for the feedback @ohorvath. One of the driving functions of not exposing it in ARM is the fact that we don't want to expose those knobs on the API because they will become GA/default and we'd have to deprecate them after which generates a lot of influx for new/deprecated properties and burden for many of the clients.

We do understand the ask/problem. In your case do you have any room for testing these on existing clusters by adding a new nodepool to the existing cluster (via CLI) and doing A/B testing?

Otherwise all the specific examples above (containerd and AKS Ubuntu 18.04) will have a specific cut-line to allow you to test in GA.

Eg. 18.04 will GA and become default from kubernetes v1.18 onwards. That means that existing clusters prior to that version will still use 16.04 and new clusters (or nodepools) created with 1.18 onwards will use 18.04 and can be used to test. (which would allow you to use ARM to create new clusters/nodepools to test)


Does this behavior meet your needs?

**Comment by ohorvath** [comment]
Thanks for the explanation. 

Manual testing is not really an option for us, we'd like to test our product the same way as it works in production with automation. The AKS cluster creation is a major part of our offering so proper testing is essential. 

I understand the concern around enabling API for specific preview features but as far as I understand the aks-custom-headers is just an array of strings so you can leave it empty or you can specify like anything. So I don't see how this field relates to anything that has to be deprecated later on. :) 

The behaviour seems ok for us, if only 1.18+ will change we have time to play with it before migrating from older versions. 

Semi related question, currently we can't activate any 1.18 version AKS cluster with ARM, having a weird error message about VMSS is not supported for 1.18. Did I miss something? :)

**Comment by palma21** [comment]
Could you paste the error you're seeing and which 1.18 version your trying to use? Or a snipped of the ARM template?

**Comment by ohorvath** [comment]
@palma21 

AKS 1.18.4, but the same error message for 1.18.2. 

**_The AvailabilityProfile type of agentpool ‘agentpoolss’ is set to VirtualMachineScaleSets, but the Kubernetes version is 1.18.4(preview) which doesn’t support VMSS._**

> “properties”: {
                “kubernetesVersion”: “1.18.4(preview)“,
                “dnsPrefix”: “[concat(parameters(‘managedClusterName’), ‘-dns’)]“,
                “agentPoolProfiles”: [
                    {
                        “name”: “agentpoolss”,
                        “count”: 3,
                        “enableNodePublicIP”: false,
                        “enableAutoScaling”: “[if(equals(parameters(‘azureAutoScalerType’),‘AKS’),bool(‘true’),bool(‘false’))]“,
                        “maxCount”: “[if(equals(parameters(‘azureAutoScalerType’),‘AKS’),int(‘99’),json(‘null’))]“,
                        “minCount”: “[if(equals(parameters(‘azureAutoScalerType’),‘AKS’),int(‘3’),json(‘null’))]“,
                        “vmSize”: “[parameters(‘sharedServicesVMSize’)]“,
                        “availabilityZones”: “[if(parameters(‘azEnabled’),variables(‘AvailabilityZones’),json(‘null’))]“,
                        “osDiskSizeGB”: 100,
                        “vnetSubnetID”: “[resourceId(parameters(‘existingVirtualNetworkResourceGroup’),‘Microsoft.Network/virtualNetworks/subnets’,parameters(‘VirtualNetworkName’),parameters(‘existingSubnetName’))]“,
                        “maxPods”: 30,
                        “type”: “VirtualMachineScaleSets”,
                        “orchestratorVersion”: “1.18.4(preview)“,
                        “osType”: “Linux”,
                        “mode”: “System”
                    },

**Comment by ohorvath** [comment]
My bad, I copy-pasted the version number from the get-versions command and forget to remove the "preview" string. However the error message is misleading when you specify random strings for "orchestratorVersion".

**Comment by palma21** [comment]
You're right, let us take a look at that.

**Comment by ohorvath** [comment]
Thanks. Meanwhile I tried something else. It seems if you enter a random value in kubernetesversion, you get the VMSS error. If the kubernetesversion is valid and put any random string in agentpool orchestratorversion, it will create the agentpool with the same version as the master without any error message. I'm not sure that's by design. :)

**Comment by palma21** [comment]
Yup, we found the issue and we're fixing it, thanks for reporting!

**Comment by Slaiyer** [comment]
I'm unable to [use the AKS specialized GPU image](https://docs.microsoft.com/en-us/azure/aks/gpu-cluster#use-the-aks-specialized-gpu-image-preview) due to this (using [Pulumi azure-native](https://www.pulumi.com/docs/intro/cloud-providers/azure/) for IaC, which generates resources from ARM Open API specifications). Is there any other way of using this besides the aks-preview CLI extension?
