### ISSUE TITLE
after AKS upgrade some pods are missing

### ISSUE THREAD

**Issue by NMark02** [Azure/AKS#1670]
Hi
**What happened**:
We upgraded our AKS from version 1.15.10. to version  1.15.11, then to  1.16.8, and lastly to 1.16.9
Later, we discovered that some pods were missing. In addition, one the deployments is incompletely gone,

**Environment**:
We are running a cluster with 2 worker nodes.
Is there any way to know why some pods did not make it to the new nodes?
where I can find logs explaining the why?

Why this behavior? Why pods are missing?
Thanks!

**Comment by jluk** [comment]
Pods will routinely be displaced and rescheduled after a cluster upgrade because all nodes get replaced. If your pods are never returning, please open a support request so we can take a look at your cluster - it will be much faster for us to deliver help instead of ad-hoc via github.

You can view all control plane logs from AKS, including actions from the scheduler.
https://docs.microsoft.com/en-us/azure/aks/view-master-logs
