### ISSUE TITLE
[Feature Request] owner role in MC group

### ISSUE THREAD

**Issue by gsxmax** [Azure/AKS#1671]
**What happened**:
In prod environment, we only assign owner role to specific resource group. However, AKS will create a MC resource group with contributor role automictically. Thus, for example with that account, we are unable to assign the role "Reader" to the identity. https://github.com/Azure/aad-pod-identity#2-create-an-identity-on-azure

**What you expected to happen**:
We could use the account which creates the AKS to do role assignment in MC group( with owner role). 

**How to reproduce it (as minimally and precisely as possible)**:
-create an account with owner role of one resource group
-follow https://github.com/Azure/aad-pod-identity#2-create-an-identity-on-azure

**Comment by ForBravo** [comment]
@gsxmax To clarity a little bit, [AAD Pod Identity](https://github.com/Azure/aad-pod-identity/blob/master/docs/readmes/README.role-assignment.md#performing-role-assignments) requires us to assign role `Managed Identity Operator` and `Virtual Machine Contributor` of the `ClusterResourceGroup` to the identity of AKS. It's not `Reader` role.

**Comment by gsxmax** [comment]
@ForBravo Thanks for helping me to clarify this

**Comment by ForBravo** [comment]
@gsxmax One more thing to clarify. After provisioning the AKS, the account we used to provision the AKS **doesn't have any role** to the MC resource group, the identity of AKS has `Contributor` role to the MC resource group.
Our expectation is: since the account we used to provision the AKS has `Owner` role to the AKS resource, it should also has `Owner` role to the MC resource group.

**Comment by TomGeske** [comment]
@ForBravo: AKS manages resources in your node resource group. Can you share your scenario why you want to have owner permissions to node resource group?
