### ISSUE TITLE
Increase OS disk size of VMSS from Terraform azurerm module

### ISSUE THREAD

**Issue by LoofahBu** [Azure/AKS#1675]
**What happened**:
I created a cluster through **terraform** but its OS disk is too small (Only 50GB). The [aks](https://registry.terraform.io/modules/Azure/aks/azurerm/4.0.0?tab=inputs) module create machine by **vmss** and all docker images are stored on OS disk. After few days, the alerting system will send notification to tell us `OS disk is full`. 

**What you expected to happen**:
We can increase OS disk from 50G to 200G.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): `1.15.10`
- Size of cluster (how many worker nodes are in the cluster?): `Standard_B2ms * 2`

**Comment by ToruMakabe** [comment]
@LoofahBu AKS's default value is 128GB and you can change it.
It seems that the Terraform module specify it fix as 50G.
https://github.com/Azure/terraform-azurerm-aks/blob/master/main.tf#L29

PR for the issue was posted but still open, I think the status of the module is not active...
https://github.com/Azure/terraform-azurerm-aks/pull/25

If you would like to use Terraform flexibly, I do not recommend the module. I hope the followings would be some of help.
https://docs.microsoft.com/en-us/azure/developer/terraform/create-k8s-cluster-with-tf-and-aks
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster

**Comment by jluk** [comment]
@torumakabe is correct, AKS enables you to set this value when deploying and has a higher default. I also highly recommend you use Terraform Azure provider directly instead of via that module project.

https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster.html#os_disk_size_gb
