### ISSUE TITLE
az aks upgrade will remove extension.

### ISSUE THREAD

**Issue by qinmaye** [Azure/AKS#1707]
**What happened**: When I use az aks upgrade, I found that it will delete the extensions. How can I solve it?

![image](https://user-images.githubusercontent.com/33417731/86427017-ba903100-bd1b-11ea-8385-7c8b4706f9b8.png)

**Comment by jluk** [comment]
This is by design, custom VM extensions cannot be installed on AKS nodes due to the reconciliation management taken by the AKS service. Please visit this document to view work arounds for node customization such as using daemon sets.

https://docs.microsoft.com/en-us/azure/aks/support-policies#user-customization-of-worker-nodes

**Comment by wumingcp** [comment]
@jluk Thanks for your reply, but I still have one question, how to install Azure Security Pack on each nodes? because currently we can use VMSS extension to install Azure Security Pack on worker nodes which run Windows OS.
