### ISSUE TITLE
Support different options for the docker root location

### ISSUE THREAD

**Issue by palma21** [Azure/AKS#1753]
Due to IO constraint issues on many disk/VM SKUs some system components can suffer from IO throttling issues, requiring using more expensive and performant disks/VMs to go around it.

We understand this option is not ideal and adds a large cost burden. As such we've been piloting https://github.com/juan-lee/knode to customize the docker root into the locally attached and much more performant temp drive. 

We will provide this as a possible configuration on SKUs that support this type of locally attached temp drive and have enough size to hold the docker root.

Have in mind your logging solutions need to point to where the docker root is to collect container logs.

**Comment by 4c74356b41** [comment]
wouldn't this make no sense with ephemeral disks? which are due in a weeks time?

**Comment by alexeldeib** [comment]
There are many SKUs which do not support ephemeral OS, but there's no reason to have a large OS disk to keep workload performance high in that scenario. The goal would be to keep a smaller system disk, and let workloads use e.g. temp disk (if one is available) or a faster separate data disk. OS disks are also somewhat constrained by size at the high end compared to data disks (topping out at 2TB). 

Additionally, we've heard asks for using local nvme instead of ephemeral os/temp disk, which is significantly faster yet.

**Comment by 4c74356b41** [comment]
sorry, I dont follow, none of these are possible currently, because you cant customize underlying vmss

**Comment by alexeldeib** [comment]
I'm the developer working on that kind of functionality.

**Comment by 4c74356b41** [comment]
as a side note, why not just let people use overrides that will get passed to the vmss object?

**Comment by palma21** [comment]
this feature in specific doesn't particularly leverage the VMSS API. 

For context on the cases that do use the VMSS API, the AKS API is made to abstract the VMSS API not extend it. This is both to avoid exposing all IaaS knobs as the service is walking towards the PaaS direction, not IaaS, but also because AKS might not always be on top of VMSS.

**Comment by 4c74356b41** [comment]
yeah, sorry, I was referring to the feature @alexeldeib is working on. So it would be possible to use ultra disks as an OS disk for the underlying VMSS (or for the docker directory). Any ETA for this feature? Also any ETA for customizing the docker root? I dont see any eta on the roadmap, only see its in progress. 

other points - fair enough. although they would greatly simplify life for folks wanting to do something custom with the vmss (like aks engine supports many of the features that are not yet supported in aks)

**Comment by 4c74356b41** [comment]
please, no custom headers on this one for the love of god.

**Comment by alexeldeib** [comment]
Sorry I missed these comments, just circling back. We focused on ephemeral os first because we cache many images on the VHD to reduce provisioning latency. Temp disk loses that benefit (can't prebake content there). I'm circling back to this (no header), unfortunately was a little late for the November API but probably will ship in the one following that (either December or January). If you have a critical need for this on all your nodes sooner please open a support ticket and share the ticket number (we have a workaround but it's a bit heavy handed, see also https://github.com/juan-lee/knode).

>So it would be possible to use ultra disks as an OS disk for the underlying VMSS
Ultra disks are available as data disks only AFAIK, this is a compute limitation not AKS.

**Comment by haizafrog** [comment]
HI @alexeldeib 
In our use-case, we want to create a node pool using Standard_L16s_v2, mount the Nvme local disk, and set the docker root to it. I understand it not supported yet, How we can achieve this? 
Thanks!!!

**Comment by alexeldeib** [comment]
You can set the field "data-root" in the docker config file (/etc/docker/daemon.json) to change the default.

If you do this, you may want to clean up the docker images on the OS disk. 

https://github.com/juan-lee/knode/blob/fa780d2ab1563838a7bc1e78e214a5a204c660f1/main.go#L258 shows one way to do it.

Daemonset can also help you format/mount the disk.

**Comment by ams0** [comment]
This article might help you with NVMe preparation https://medium.com/cooking-with-azure/using-nvm-e-instances-in-azure-kubernetes-service-40c587dbd67b

**Comment by alexeldeib** [comment]
^that will work well for workload volumes, but less so for docker root. The initial setup will be exactly what the local provisioner does out of the box, detecting and mounting the drives.
