### ISSUE TITLE
kubectl get pods: Unable to connect to the server: net/http: TLS handshake timeout 

### ISSUE THREAD

**Issue by kadircanercetin** [Azure/AKS#177]
Today we start to get connection error from our cluster.  (version 1.8.1)

kubectl cluster-info
Kubernetes master is running at https://elexon-poc-aks-e15aceb3.hcp.westeurope.azmk8s.io:443

Any help will be great.
Thanks.

**Comment by matkam** [comment]
Seeing the same issue https://github.com/Azure/AKS/issues/164

**Comment by Zenlil** [comment]
Been running an AKS-cluster (1.8.1) for some time.
On friday last week (feb 9th) we suddenly could not contact the k8 api.
Got "TLS handshake timeout" on all our development machines.

We have a Makefile to deploy a new cluster but that dont work => see #182 

Since it's a "preview" and we're on PAYG we can't send a support-ticket... Is anything happening at all on this, or are your recommending we go back to ACS instead?
