### ISSUE TITLE
control-plane label on admission webhooks definitions

### ISSUE THREAD

**Issue by dprotaso** [Azure/AKS#1771]
Turns out Knative doesn't run on AKS 1.17 because there's some Azure component that's mutating our webhooks which we did not expect.

See https://github.com/knative/pkg/issues/1590 for details.

I read https://docs.microsoft.com/en-us/azure/aks/faq#can-i-use-admission-controller-webhooks-on-aks and I'm curious why the selector like

```yaml
namespaceSelector:
    matchExpressions:
    - key: control-plane
      operator: DoesNotExist
```

is necessary when the question states https://docs.microsoft.com/en-us/azure/aks/faq#can-admission-controller-webhooks-impact-kube-system-and-internal-aks-namespaces

> To protect the stability of the system and prevent custom admission controllers from impacting internal services in the kube-system, namespace AKS has an Admissions Enforcer, which automatically excludes kube-system and AKS internal namespaces. This service ensures the custom admission controllers don't affect the services running in kube-system.

Since there's an Admissions Enforcer preventing these kube-system and AKS namespaces modifications is it necessary to mutate our webhook definitions?

This behaviour could break other projects & products who don't expect these external mutations - ie. [Tekton CD](https://github.com/tektoncd/pipeline) is broken as well

**Comment by mattmoor** [comment]
cc @ImJasonH

**Comment by palma21** [comment]
The selector is not necessary to be added be added manually as it will be added automatically, but I believe from the issue in knative the issue was the two reconciliations conflicting. 

Seems it has been solved there, is there something we can do to help further?

@samkreter

**Comment by dprotaso** [comment]
> Seems it has been solved there, is there something we can do to help further?

Pushing the resolution of this on each project doesn't scale in my opinion. What we've done in Knative is a workaround.

> is there something we can do to help further?

I'd recommend stop mutating the webhook spec

**Comment by tomwganem** [comment]
Hi there,

Our corporate security policy that is necessary for our SOC2 compliance requires us to scan all images that we currently run, including images we don't control the life-cycle for. This includes all the images in the kube-system namespace for aks. We tried to implement a solution with https://github.com/jainishshah17/tugger that utilizes a webhook to automatically change the registry of any pod in a namespace to a private one, and then we built some automation to mirror images. But because of this issue, we are unable to implement this for the kube-system namespace. 

That is to say, I understand why it's implemented like this, but I would like the option to turn it off. Will this be addressed in the future?

**Comment by tomwganem** [comment]
Hi there,

Our corporate security policy requires us to scan all images that we currently run, including images we don't control the life-cycle for. This includes all the images in the kube-system namespace for aks. We tried to implement a solution that utilizes a webhook to automatically change the registry of any pod in a namespace to a private one, and then we built some automation to mirror images. But because of this issue, we are unable to implement this for the kube-system namespace.

That is to say, I understand why it's implemented like this, but I would like the option to turn it off. Will this be addressed in the future?

**Comment by slenky** [comment]
Reopen please? It's still an issue.

**Comment by dprotaso** [comment]
@Azure/aks-leads can you re-open this issue?

**Comment by gambtho** [comment]
Based on this PR, https://github.com/knative/pkg/pull/1949, it appears this is no longer an issue with knative/tekton

Issues like kubeflow, https://github.com/kubeflow/pipelines/issues/5244,  (use of the control-plane label by other projects) we will remove in a upcoming update by relying on "managedby: aks" as our label for protecting namespaces from webhook changes.   

For the issue mentioned by @tomwganem  -- you can use the label/annotation [admissions.enforcer/disabled: true](https://learn.microsoft.com/en-us/azure/aks/faq#can-admission-controller-webhooks-impact-kube-system-and-internal-aks-namespaces)  to allow your webhook to operate on kube-system and other AKS managed namespaces, but this is not recommended



Any other scenarios that remain a problem?
