### ISSUE TITLE
AKS cluster w different zones per pool

### ISSUE THREAD

**Issue by rajivml** [Azure/AKS#1853]
Hi, 

We are POC'ing to move some of our kubernetes workloads from GKE to AKS and we have observed that the availability of GPU nodes under AKS availabilty zones are very limited and we also got to know that any new node type that is introduced will be non zonal first and it will be available under availability zones after some timeframe .

So, I have been exploring this scenario where I want to setup an AKS cluster where primary node pool will be zonal and secondary node pool that is GPU node pool will be non zonal.

And we have kubernetes jobs which has to be run on GPU nodes and these jobs does require a PVC,  in this scenario what should we set the type of storage class , I have tried setting storage class to default but it didn't work due to affinity errors and I tried setting storage class to an custom class with volumebindingmode set to waitforfirstconsimer but this also didn't worked and the job failed with anti affinity error again

So does AkS support this kind of setup where primary nodepool is backed by availabilty zones and on secondary nodepools availability zone support is not enabled ?

**Comment by jluk** [comment]
Yes, we do support clusters with mixed pools that have different zone specifications.

For the volume issues, can you share the spec? cc @andyzhangx if he can lend eyes

**Comment by andyzhangx** [comment]
For azure disk, there is limitation that disk in zone#1 could not be attached to vm in zone#2 or vm in non-zone. Set volumebindingmode to waitforfirstconsimer in storage class is the correct way, so pod would be scheduled to the node first and then create PVC according to zone info. And pod in zone#1 vm could not be moved to zone#2 vm due to limitation of disk. You may use https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/ to restrict pod in zone nodes, otherwise it may break after pod moving to other zone vm.
