### ISSUE TITLE
Help | Local Storage | Lsv2-series

### ISSUE THREAD

**Issue by MateusAmin** [Azure/AKS#1879]
How do I access the SSDs on Lsv2-series nodes in AKS? Needed for a distributed database deployment.

https://github.com/Azure/AKS/issues/105

https://webcache.googleusercontent.com/search?q=cache:yK4hQRXIJ0YJ:https://feedback.azure.com/forums/914020-azure-kubernetes-service-aks/suggestions/36433282-make-lsv2-series-available-on-aks+&cd=4&hl=en&ct=clnk&gl=us

https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/local-ssd

**Comment by andyzhangx** [comment]
try this open source solution: https://github.com/Azure/kubernetes-volume-drivers/tree/master/local

**Comment by olsenme** [comment]
We are currently exploring support for https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner and was wondering if we might setup some time with you to learn more about your use case?

**Comment by olsenme** [comment]
@MateusAmin  would you be willing to chat with the PG team?

**Comment by olsenme** [comment]
@MateusAmin would you be willing to chat with the PG team?

**Comment by Bessonov** [comment]
The local storage of Lsv2-series provide a very fast and comparatively cheap storage, but without redundancy. There many software components which maintain own redundancy and because of that, some teams can decide to make a trade-off between storage-based redundancy and performance per $. Some components examples:
- CockroachDB
- YugaByteDB
- Kafka/ZooKeeper
- Galera Cluster
- Cassandra
- ... many others ...

But also Follower-Leader Databases like Postgres with automatic Failover. Or even own storage deployment on top like Longhorn, rook, OpenEBS etc.

All of them will benefit from the high io/transfer rates of persistent local storage.

**Comment by andyzhangx** [comment]
answer provided by https://github.com/Azure/AKS/issues/1879#issuecomment-700772256
