### ISSUE TITLE
Cluster Autoscaler taking too long to scale

### ISSUE THREAD

**Issue by MohitBaj** [Azure/AKS#1898]
For adding the 1st new node in a nodepool, cluster autoscaler took 15 minutes to add the node, but for the 2nd node addition, it took around 5 minutes. Could you please tell me the reason for this? 
Also for scheduling a pod on already present node, time take was in second(5-10 seconds), but to schedule the pod on a new node, it is taking around 5 minutes(after the node was ready, node also took other 5 minutes to convert from not-ready to ready state). Is there a reason for taking this long on a new node?

**Comment by marwanad** [comment]
@MohitBaj the bottleneck for adding a node could be due to various factors. SKU, capacity in the region, etc all come into play. Can you file a support ticket so we can look into the issue?

You should also be able to monitor the newly added VM on portal until it gets to "Succeeded" provisioningState on portal which should give you some indicator.

**Comment by MohitBaj** [comment]
I have raised the support ticket. Though would these factors affect node addition timing?(When nodes are of same type and configurations in same nodepool)
