### ISSUE TITLE
where example.hosts located? how to edit it in AKS?

### ISSUE THREAD

**Issue by kshke** [Azure/AKS#1929]
where example.hosts located? how to edit it in AKS?
I want to add many A record for coredns, according to the document, I can use host plugin, I have add a recored in custom-dns configmap and it works. 

but what is this means "example.hosts must be a file" ?  where can I add or edit example.hosts? is it in coredns pod? base on my understanding, we can't edit coredns pod.  can I manage A record via file？

https://docs.microsoft.com/en-us/azure/aks/coredns-custom#hosts-plugin

apiVersion: v1
kind: ConfigMap
metadata:
name: coredns-custom # this is the name of the configmap you can overwrite with your changes
namespace: kube-system
data:

test.override: | # you may select any name here, but it must end with the .override file extension

      hosts example.hosts example.org **{ # example.hosts must be a file**

          10.0.0.1 example.org

          fallthrough

      }

**Comment by robbiezhang** [comment]
`example.hosts` is just a dummy file. There is no such file in the coredns pod.
we add it in the example, because the FILE is required if you want to restrict the plugin to ZONE.
https://coredns.io/plugins/hosts/#syntax

If you want to specify multiple A records, you can define them in the INLINE section.
