### ISSUE TITLE
Custom Images in AKS.

### ISSUE THREAD

**Issue by chowmean** [Azure/AKS#1942]
Is there a way to use a custom image in AKS? If not shouldn't this be an option?

**Comment by yangl900** [comment]
It's not an option. Curious any reason you want to bring your own image? the AKS managed image ensures everything is patched and tuned for container workload.

**Comment by chowmean** [comment]
We want to use Cilium and its ebpf capabilities like kube-proxy replacement can only work with the latest kernels. So we wanted to see if we can build our own image and use it like we can do in AWS EKS.

**Comment by yangl900** [comment]
I see. Thanks for the context!

**Comment by palma21** [comment]
The AKS image kernel should already support those capabilities and we have have some ebpf tooling installed already: 
https://github.com/Azure/AKS/blob/master/vhd-notes/aks-ubuntu/AKSUbuntu-1804/2020.10.21.txt 
Is there any key thing you're missing/not working?

ebpf still has some scalability, reliability and future unknowns but we are tracking it closely and considering it. In these scenarios for the inclusion on AKS it would have to be in a fully managed/supported way.

Do you have as well specific scenarios you can only achieve by replacing kube-proxy? This is something we're avidly collecting as well!

**Comment by chowmean** [comment]
We want to optimize it further for fast data path ,DSR etc. You can find more on cilium documentation. I am curious why this restriction of not allowing other to use custom image

**Comment by palma21** [comment]
AKS nodes and LB should already do DSR, are you having issues there?

Custom nodes is not something currently coalesces with a fully managed service model AKS has, which will tend to be increasingly abstracted rather than the other way around. We couldn't guarantee any SLO on the nodes if they are allowed to have any type of configuration possible. Similarly we wouldn't be able to support them as we do.

For custom Images we recommend using [aks-engine](https://github.com/Azure/aks-engine)

That's why generally we like to focus on the use cases themselves and are happy to explore the components and offer them as part of the service if possible.
Hope this makes sense.
