### ISSUE TITLE
Containerd Fails to Pull from Private Registry with ImagePullSecret Creds

### ISSUE THREAD

**Issue by kevingbb** [Azure/AKS#1951]
**What happened**: Get ImagePullBackOff when trying to pull container images from a Private Registry (Aquasec in this case) that is protected with credentials and AKS is using containerd as runtime. The ImagePullSecret is setup correctly and works as expected from a nodepool using docker(moby) as runtime.

**What you expected to happen**: Container images to be successfully pulled down to the node.

**How to reproduce it (as minimally and precisely as possible)**: 
1. Create AKS Cluster with Containerd
2. Install Aquasec using aquactl tool (this sets up all the secrets/credentials and image pull secret)
3. Check pod status and they all have ImagePullBackoff
4. Add nodepool to cluster that uses docker and the aquasec DS starts up as expected

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.8
- Size of cluster (how many worker nodes are in the cluster?): 5
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): 
![runningcontainers_snapshot](https://user-images.githubusercontent.com/19918338/98523624-6cb1a980-2276-11eb-83ab-0dbdc4ab1955.png)
[describeoutput.zip](https://github.com/Azure/AKS/files/5509431/describeoutput.zip)

- Others:

**Comment by eriksywu** [comment]
Hey Kevin

Do you specify the imagepullsecret on the aqua pod specs explicitly or via a serviceaccount? Do you see any errors relating to auth from kubelet or containerd logs? (i.e journalctl -u containerd)

I'm not familiar with aquactl works but I'm wondering if this could be related
https://github.com/aquasecurity/deployments/blob/e5bb2e1f762efc39e7832e3511ea7aaaa8f0a373/automation/aquactl/default/aks/aquasec.cfg#L22
What happens if you change the sock path to /var/run/containerd.sock (docker.sock isn't used by k8s in containerd clusters and will soon be deprecated)

**Comment by kevingbb** [comment]
Hi @eriksywu , the imagepullsecret is set via an aqua serviceaccount. I did not see any errors relating to auth when I checked in the journalctl kubelet or containerd logs. It feels authentication related, but the message just stated that the container image was not found. We know it is there as I was able to pull the image locally to my machine and the pull from the docker machine worked as expected.

Aquactl is used to generate all of the manifest files based on configuration parameters and then apply them to the cluster. Great find on the sock path. I will double-check that, and if not set to containerd.sock I will give it a try and report back.
