### ISSUE TITLE
AKS Autoscaler does not work with an empty nodepool

### ISSUE THREAD

**Issue by tillepille** [Azure/AKS#1957]
**What happened**:
I created an AKS Cluster with 1 node and an additional nodepool via Terraform with 0-10 instances and starting with 0 nodes in it.
Then I scheduled pods to run on instances of this pool (with node labels).
The AS did not create any new nodes in that group, as the status ConfigMap states, the status of the last scrape remained on `0001-01-01:00`.

**What you expected to happen**:
When creating pods the autoscaler adds nodes to that group even when the node group has no nodes yet.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create additional nodepool with 
```hcl
  enable_auto_scaling   = true
  min_count             = 0
  max_count             = 10
  node_count            = 0
```
2. create pods that need nodes from this nodepool.

**Anything else we need to know?**:
When initializing with 1 node in the pool, let let the AS scale down to 0 nodes, and create pods afterwards, the AS works as expected.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.17.3 (didn't choose one, the recommended version from azure)
- Size of cluster (how many worker nodes are in the cluster?): 1 in default group, for controller, 0-10 in the additional nodepool
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): gitlab runners
- Others:

**Comment by yangl900** [comment]
@marwanad any idea?

**Comment by JasonWhall** [comment]
+1 Also seeing this behaviour. It looks like when the pool is initially created it must have >= 1 node initially to allow scaling from 0. Otherwise it is unable to see any of the nodeSelector labels to trigger a scaleup.

<img src="https://user-images.githubusercontent.com/42138928/99083333-50d33e00-25bd-11eb-93e2-0a13cfae9007.png"  width="200"/>

**Comment by JasonWhall** [comment]
After a bit of investigating it looks like this is due to this ["feature" in the Kubernetes Cluster Autoscaler]( https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/azure/README.md#scaling-a-vmss-node-group-to-and-from-0)

It advises that Node Labels that are used by the nodeSelector must be applied as a tag on the VMSS. So to give some steps to a working example:

1. Create a nodepool that uses the template label tag.
```bash
az aks nodepool add --cluster-name myCluster \
  --resource-group myResourceGroup \
  --name mypool \
  --enable-cluster-autoscaler \
  --max-count 10 \
  --min-count 0 \
  --node-count 0 \
  --tags "k8s.io_cluster-autoscaler_node-template_label_agentpool"="mypool"
```
Note: the `  --tags "k8s.io_cluster-autoscaler_node-template_label_agentpool"="mypool"` is adding a tag which says the `agentpool` label on the node would be `mypool`

2. Deploy a kubernetes pod/deployment that uses this label in the `nodeSelector` field. Example below:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myDeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myPod
  template:
    metadata:
      labels:
        app: myPod
    spec:
      containers:
      - name: myPod
        image: mcr.microsoft.com/azure-cli
      nodeSelector:
        agentpool: mypool # Refers to pool name created earlier
```
The pod should then trigger a scaleup event when describing the pod `kubectl describe pod mypod`

```
  Normal   TriggeredScaleUp   16s                   cluster-autoscaler  pod triggered scale-up: [{aks-mypool-12814015-vmss 0->1 (max: 10)}]
```

It sounds like these VMSS tags should be something are auto-applied upon agent pool creation, however I know tags are finite and if a node has lots of user assigned labels, this could consume this limit without being made clear to the user.

**Comment by marwanad** [comment]
@JasonWhall @tillepille thanks for reporting. I've identified a regression with a recent release and will be preparing a fix for that. You shouldn't need to apply those labels as tags manually - they'll be populated by default.

**Comment by marwanad** [comment]
Fix should be rolled out. 

Please feel free to re-open/comment on the issue if you're still facing the issue.
