### ISSUE TITLE
Missing Resources in MC_* when listing via az resource list -g <MC_* resource group name>

### ISSUE THREAD

**Issue by aido123** [Azure/AKS#1964]
**What happened**:

As part of automation, trying to list all resources in the MC_* resource group but it's showing as empty. I can see all the resources successfully via the UI. I can also list resources successfully in other Resource Groups that are not the MC_* one.

**What you expected to happen**:

I would have expected to see all the resources in the MC_* resource group like I see in the UI.

**How to reproduce it (as minimally and precisely as possible)**:

- Create an AKS Cluster
- List the resources in the MC_* resource group e.g. 
az resource list -g MC_adrian-group_cluster_westeurope
[]

**Anything else we need to know?**:

Resources start to appear slowly after a lengthy period i.e. + 18 minutes after cluster created. Reproduced on both EastUS2 and WestEurope

**Environment**:
azure-cli:      2.14.1
AKS Version:   1.17.13
Cluster Size:  1 Node
No workloads deployed yet

**Comment by yangl900** [comment]
@aido123 CLI and portal actually hit the same API at the backend (but may hit different region). The /resources API is served from a regional cache from Azure Resource Manager, which is eventual consistent, and not real time.

To get real time /resources result, you would want to hit the endpoint where the resource group locate. I developed a tool called [armclient](https://github.com/yangl900/armclient-go), which allows you to make a request like:

```
armclient get https://westeurope.management.azure.com/subscriptions/{id}/resourcegroups/{group}/resources?api-version=2015-01-01
```

Note you can use `westeurope.management.azure.com` instead of `management.azure.com`. however, I don't think the regional endpoint is officially supported (because you won't get the automatic failover when needed). So consider do failover to the original endpoint from client side.

The other option is to list resources by type, which is always realtime. e.g. `az vmss list`, `az vnet list` etc.

**Comment by aido123** [comment]
Thanks for the info @yangl900, this is very useful.

I'll checkout both your tool and see if az vmss list will do the trick.

Best Regards,
Adrian

**Comment by aido123** [comment]
FYI, az vmss list --resource-group <resource group> is NOT realtime

**Comment by yangl900** [comment]
@aido123 you are right, but under a condition. I missed that earlier.

If the region had no other VMSS at all, meaning it is the first time deploying VMSS in a region, it is not realtime. But if the region already had some VMSS, the `az vms list` is realtime. Let me know if you see otherwise.
