### ISSUE TITLE
Cluster creation reports failure but goes on to succeed - confuses automation tooling

### ISSUE THREAD

**Issue by dimbleby** [Azure/AKS#1972]
**What happened**:

We create AKS clusters using terraform.  Reasonably often we see that failing with an error like this:
```
waiting for creation of Managed Kubernetes Cluster "simpl-cluster-integration-2-aks-k8s" (Resource Group "simpl-cluster-integration-2-aks"): Code="InternalOperationError" Message="AKS encountered an internal error while attempting the requested Creating operation. AKS will continuously retry the requested operation until successful or a retry timeout is hit. Check back to see if the operation requires resubmission. Correlation ID: d0f19ff8-d361-8447-7250-139174c4389d, Operation ID: 0c29feeb-a9d0-418f-b429-8b1e520e120a, Timestamp: 2020-11-16T14:23:54Z, Error: addonIdentityReconciler retry failed: autorest/azure: Service returned an error. Status=403 Code=\"AuthorizationFailed\" Message=\"The client '329189cb-bb7e-47b0-852d-9535eee6569f' with object id '329189cb-bb7e-47b0-852d-9535eee6569f' does not have authorization to perform action 'Microsoft.ManagedIdentity/userAssignedIdentities/write' over scope '/subscriptions/<redacted>/resourceGroups/MC_simpl-cluster-integration-2-aks_simpl-cluster-integration-2-aks-k8s_uksouth/providers/Microsoft.ManagedIdentity/userAssignedIdentities/omsagent-simpl-cluster-integration-2-aks-k8s' or the scope is invalid. If access was recently granted, please refresh your credentials.\"."
```

where that client ID is AzureContainerService:
```
Get-AzureADObjectByObjectId -ObjectIDs 329189cb-bb7e-47b0-852d-9535eee6569f

ObjectId                             AppId                                DisplayName
--------                             -----                                -----------
329189cb-bb7e-47b0-852d-9535eee6569f 7319c514-987d-4e9b-ac3d-d38c4f427f4c AzureContainerService
```

Failing is OK: the issue is that after reporting failure, retries happen - and the cluster goes on to be created successfully.

This is particularly confusing for terraform, which becomes awkward to use when its state file does not match reality.  When this happens it believes that the cluster does not exist, but it does, and so further attempts to manage it fail.

I'd think that other automation tools might similarly be confused: the API seems to have reported an error but then the operation succeeds anyway.

**What you expected to happen**:

Don't report an error if retries are still happening and the operation might yet succeed.

I guess a flag "dont-retry-after-reporting-errors" or somesuch that could be used by automation tooling would work.

**How to reproduce it (as minimally and precisely as possible)**:

We see this only intermittently.  Repro is simply to use the terraform `azurerm_kubernetes_cluster` resource to create a cluster.

If it becomes important to the investigation please say so and I can try to extract a suitable fragment from our larger configuration.

**Anything else we need to know?**:

I've also raised https://github.com/terraform-providers/terraform-provider-azurerm/issues/9342 asking whether the terraform provider can do better with this.  But on reflection a report here seemed worthwhile too.

**Environment**:

The cluster isn't yet created at the time we hit the issue, I don't think this section is relevant.

**Comment by yangl900** [comment]
Hi @dimbleby ,

thanks for reporting. That's actually a bug in our code. It did not wait long enough for the granted permission to take effect and failed. You saw the cluster later became Succeeded is because we have built auto-repair for all Failed clusters. That kicked in soon and since the granted permission took effect already, everything succeeded.

We realized the bug from internal monitoring and has fixed the issue already. It's pending a hotfix release to rollout.

**Comment by dimbleby** [comment]
Hi, 

Great to hear that there's a bug here that's being fixed, thank you!

However I am still interested in the wider question.  Bugs and errors will always happen; and an API that says "no" but means "maybe" is hard to handle - certainly for terraform because of its state file, but I'd think also for other tooling.

Could you comment on this too?

Thanks again.

**Comment by yangl900** [comment]
The API actually said "internal error" on the creation failure, if you check the Activity Log of the resource group, you will see the error. And if you do a GET right after the failure, you will see the cluster exits and in "Failed" state.

At client side, if you retry the original PUT operation again, you should see Succeeded result. If client did not retry, the back end will try to heal the cluster as well, and bring it to "Succeeded" state. 

I'm not very familiar with the terraform provider, are you saying it did not retry on the internal error? or it attempted but expect the resource doesn't exist?

**Comment by dimbleby** [comment]
I am not that familiar with the internals of the terraform provider either.  As I understand it, it did not retry: and then subsequent manual retries failed (because the cluster does exist, but terraform's state file says otherwise).  But I might have the wrong end of the stick.

I think you are saying that clients should consider "internal error" as being retriable.

I will update the terraform issue to point at this discussion, hopefully someone on that project will take a look.

**Comment by ashtewari** [comment]
@yangl900 Can you please share the status of this hotfix? We don't use Terraform. We are running into this issue in our automation 
 also. This also need to be addressed in the Kubernetes version upgrade path.

**Comment by JohnRusk** [comment]
I'm making some enquiries about this with my colleagues in the AKS team.

**Comment by JohnRusk** [comment]
Here are some points of background info.  @dimbleby I pretty sure you already know this background info, but I'm listing it here for completeness and for reference for anyone else who reads this thread.

There are two time periods of interest:
1. The first is during the initial operation that created (or updated) a cluster.  For long running operations such as that, you can poll for status until Azure considers the operation to be completed.  Details on the polling process are here https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/async-operations  but normally you don't need to think about it because handling of these async long running operations is automatically built into most Azure SDKs.
2. The second timeperiod is _after_ Azure considers the initial long-running operation to be completed.  There are various issues that can affect cluster health, and AKS runs a Remediator process to attempt to automatically fix them.  
   
The message you report `AKS will continuously retry the requested operation until successful or a retry timeout is hit` indicates that the issues is being addressed by the remediator.  So it falls into the time period I've labelled 2, above.  

I'll continue to seek additional info, and post my findings here.

**Comment by JohnRusk** [comment]
@ashtewari After looking into the details, I beileve your version of this issue, which you've logged directly with Microsoft, is probably different from what is discussed in this GitHub issue.  Firstly, yours is does not contain the permissions error which yangl900 said has been hotfixed, so that hotfix is not relevant to you. Secondly, indications so far are that the remediation/retry sequence of events in your case a substantially different from those outlined by dimbleby above.  So let's handle yours through Microsoft support rather than this  GitHub issue.

**Comment by JohnRusk** [comment]
@dimbleby You and yangl900 have covered things fully in your comments above. I don't have anything else to add. Can you please update us here if/when you hear back from the Terraform folks?

**Comment by techbunny** [comment]
@JohnRusk I would like to add that this issue has come up with another customer using Terraform as well, particularly with the addition of node pools. On the high level, TF takes a return status code of "failed" as the final word and failed resources do not (by design) end up in the TF state file.  Instead a future run of the same code will expect to deploy the missing resource and then update the state.  

With some aspects of AKS configuration being subject to remediation and Azure effectively retrying the creation of that resource "out of band" - TF was already informed of failure, marked that portion of the deployment as failed and has moved on.  When the same TF code is run again with the goal of building the failed item again, TF attempts to create a resource that already exists and THAT fails, which leaves the TF state file out of sync with reality and required manual intervention to correct.  I assume that the aks-remediator uses the failed provision state to help determine what to retry, however that means that a "failed" state is not the final word regarding deployment state and causes pain with 3rd party tooling. 

It would be great if there was a "soft failure" or "remediation" provisioning state that would potentially allow 3rd party tools to wait for a true end state of "succeeded" or "failed".

**Comment by JohnRusk** [comment]
Thanks for the great description @techbunny .  cc'ing @miwithro since I'm not actually working on this aspect of AKS myself.

**Comment by palma21** [comment]
We'll look into it, but in essence those are standard states from ARM that AKS adheres to, other Azure resources like VMSS can also report provisioning failures or timeouts and keep retrying to ensure the instance correctly starts (and only then bring the VMSS to succeeded).

It's likely better to discuss this with the specific client in this case, I see the thread is still open, and align with TF folks how this can have a smooth UX. 

We will to bring this up on our next meeting with them.

**Comment by dimbleby** [comment]
Am surprised to see this being closed.  @palma21 was that your intention when you added those labels?

From my point of view: we continue to hit the problem that this issue describes and - per your update - converation is active and ongoing.

**Comment by palma21** [comment]
Yup you're right, closed by mistake. Re-opening

**Comment by dimbleby** [comment]
The bot insists!  @palma21 can you remove the labels?

**Comment by palma21** [comment]
He's in the right, it's the human's fault

**Comment by seitosan** [comment]
Hello, I have the same issue. How can we solved ? 

My terraform version : 

Terraform v0.13.3
+ provider registry.terraform.io/hashicorp/azurerm v2.55.0

aiting for creation of Managed Kubernetes Cluster "XXXXXXXXXXXX" (Resource Group "XXXXXX"): Code="CreateVMSSAgentPoolFailed" Message="AKS encountered an internal error while attempting the requested Creating operation. AKS will continuously retry the requested operation until successful or a retry timeout is hit. Check back to see if the operation requires resubmission

**Comment by zak-forsyth** [comment]
I am seeing the same error as well. Azure AKS retries the node pool through the remediation process and does eventually succeed but fails the Terraform automation.

Terraform v0.13.5

provider registry.terraform.io/hashicorp/azurerm v2.53.0

Error: waiting for creation of Managed Kubernetes Cluster "XXXXXXX" (Resource Group "XXXXXX"): Code="CreateVMSSAgentPoolFailed" Message="AKS encountered an internal error while attempting the requested Creating operation. AKS will continuously retry the requested operation until successful or a retry timeout is hit. Check back to see if the operation requires resubmission.

**Comment by helshabini** [comment]
Issue is still present with Terraform's azurerm provider v2.55.0

I've tried using SystemManaged or UserManaged identities for the cluster and the result is the same.

`Error: waiting for creation of Managed Kubernetes Cluster "xxxxxxxx" (Resource Group "xxxxxxxxx"): Code="CreateVMSSAgentPoolFailed" Message="AKS encountered an internal error while attempting the requested Creating operation. AKS will continuously retry the requested operation until successful or a retry timeout is hit. Check back to see if the operation requires resubmission. Correlation ID: xxxxxxxx, Operation ID: xxxxxxxx, Timestamp: 2021-04-15T12:54:45Z."`

Eventually the cluster is created and healthy. But for Terraform, that's not going to cut it because as far as Terraform is concerned this resource is in a failed state, and Terraform will attempt to redeploy it next time.

Any suggestions?

**Comment by seitosan** [comment]
Hello 

You Can import it after azure create successfully the cluster. It s works for me but it not a production ready usé case :/

Regards

**Comment by rhollins** [comment]
I had this issue today previously I was using same code and cluster was built successfully, using terraform 0.12.25 and provider 2.56.0

Error: waiting for creation of Managed Kubernetes Cluster "..." (Resource Group "..."): Code="CreateVMSSAgentPoolFailed" Message="AKS encountered an internal error while attempting the requested Creating operation. AKS will continuously retry the requested operation until successful or a retry timeout is hit. Check back to see if the operation requires resubmission. Correlation ID: ..., Operation ID: ..., Timestamp: 2021-04-29T14:57:31Z."

**Comment by dimbleby** [comment]
That's the sort of thing I had in mind here
> I guess a flag "dont-retry-after-reporting-errors" or somesuch that could be used by automation tooling would work.

**Comment by JohnRusk** [comment]
>One would need to be able to update that setting later without needing to redeploy the cluster.... but maybe it's something to consider

@techbunny, you're suggesting that the setting is stored at cluster level?  (My mind is blank of what TF means in your message)

What if instead of being stored, it was just a parameter in every create/update call?  That way there's no state to manage, and the desired behaviour is explicit in each call.

**Comment by techbunny** [comment]
@JohnRusk (Sorry for the delayed response here - missed some email alerts.) I would assume the setting would need to be stored at cluster level, as auto-remediation would need to remain either on or off.   TF (terraform) would be written to have auto-remediation off for deployment (or forever, if that was the desire).  Then after successful deployment, the TF could be updated to turn auto-remediation on if that behavior is desired for later in the lifecycle of the cluster.   Having auto-remediation off initially would mean that TF would either succeed or fail cleanly, and if a failure occurred the code could be run again as the state would be correct.

**Comment by JohnRusk** [comment]
I spoke with @palma21 about this. He has a better solution in mind. It's better than what we discussed above @techbunny, and I like it.  I'll leave it to @palma21 to share details as and when appropriate.

**Comment by vinisoto** [comment]
@JohnRusk @palma21 we are hitting this pretty consistently in our automation. We are NOT using Terraform, just plain PowerShell scripts.

`E: ERROR: Deployment failed. Correlation ID: 80efda0d-7f45-4c04-bc76-df15d4e05b10. AKS encountered an internal error while attempting the requested Creating operation. AKS will continuously retry the requested operation until successful or a retry timeout is hit. Check back to see if the operation requires resubmission. Correlation ID: b4b3daf9-e4ee-4152-a9d3-b90f000ebde2, Operation ID: 00c24402-a3d4-4704-9996-15b89da3cf29, Timestamp: 2021-06-24T16:46:01Z.`

Is there something we can check/poll on our end to figure out:

a) what the underlying failure was
b) if AKS is still actively trying
c) what is the retry timeout here so that at least we can have our scripts wat that long

**Comment by JohnRusk** [comment]
Vinisoto, This is being actively discussed. I don't have the answers to your questions I'm sorry. Maybe palma21 will have them.

**Comment by adrianmarinica** [comment]
I am hitting the same issue, but for a different reason. While creating the cluster through Terraform, it fails with the following error:

Failed to resolve the domain name assigned to the cluster 
**Error**  No such host is known.
**Domain Name**  <cluster-name>-dns-k8s-b2ebf992.hcp.westeurope.azmk8s.io
**Summary**  Encountered a SocketException while resolving the domain name. This means that the FQDN for the cluster cannot be resolved.

The cluster eventually transitions from a Failed state to a Succeeded state, but Terraform is all confused by the outcome. Any ideas?

**Comment by paulgmiller** [comment]
@tombuildsstuff suggests we should turn a sup operation code and that he's discussed this with people on the aks team. Trying to follow up with @palma21. Do we have any examples of other azure resources doing this? I was nder the 

As I mention in terraform-providers/terraform-provider-azurerm#12719 anyting that passes the syncronous put will be retried by aks even if the subsequent async operation progress update fails. I think distinguishing based on that is probably more releiable than a subcode and wuld work across most/all azure resources but if there are sevral other azure services providing a sub code then we can consider introducing one into aks.

**Comment by tombuildsstuff** [comment]
@paulgmiller we've discussed a sub-status code with @palma21 previously since that matches other resources - we're actually meeting with @palma21 on Friday so perhaps he can forward the meeting invite?

In terms of examples of other Azure Services, IIRC both Kusto (which iirc returns more granular status about the Kusto cluster provisioning as a sub-status) and CosmosDB (which has a similar flag returned per location/replica regarding the replica status) have sub-statuses available, but I'm sure there's other examples.

One of the core behaviours of Terraform is that we only mark a resource as "ready" (e.g. finished creating) once it's fully available (for example, once a Key Vault cluster has created _and_ the DNS has replicated, so that dependent operations can succeed) - where different Azure API's have a different meaning for a `ProvisioningState` of `Failed` (which in most API's means "this will never recover", but can sometimes mean "this will never recover (and will be cleaned up automatically)" or "this may recover" depending on the API), without a sub-status we have no idea which of the three this is (and so we can't continue polling).

FWIW I agree with you that there _should_ be a behavioural consistency across resources during failure (e.g. if the initial PUT/POST works, then an Async failure should always be Terminal) - however those behaviours were defined for API's that don't interact with third-party components with discrete failure modes, so whilst perhaps the AKS API's could poll for longer to match that behaviour - I'd argue API's need to determine what that behaviour _should_ be (for example, a new `ProvisioningState` of `NeedsMaintainance|AutoRecovering` [or similar] with a sub-status with more context) so that downstream users of the API can determine how to proceed if they're interested - before it's abstracted out at the ARM level.

Per your suggestion, I think this would be easiest to discuss on a call - hopefully @palma21 can forward the invite but if not then let me know and I can set something up 👍 

Thanks!

**Comment by paulgmiller** [comment]
ProvisioningState must be failed, but thre's a good chance we can set provisioningstatus to "willretry" or "autoreconciling" looking at code. 

Also checking azure guidance to see if we can get a recommecdation so all RP's in azure can eventually follow the same practice here.

**Comment by kriesto** [comment]
Hello Everyone,

For those who are still facing this Error while using terrafom AKS module
Code="CreateVMSSAgentPoolFailed" Message="AKS encountered an internal error while attempting the requested Creating operation. AKS will continuously retry the requested operation until successful or a retry timeout is hit. Check back to see if the operation requires resubmission

try to set enable_host_encryption value to false, and try again

**Comment by JohnRusk** [comment]
@kriesto I don't see how that setting relates to this issue.  What is the relationship? Also, host encryption is a good thing in terms of security.  I wouldn't feel comfortable with changing a security setting to fix the issue in this thread (which is not security related).

**Comment by sumansla123** [comment]
Thank you @kriesto for the pointer. EncryptionAtHost feature needs to be enabled at the subscription to deploy the AKS cluster successfully with host based encryption set to true. In my case, this feature was not enabled in the subscription and code was breaking with "CreateVMSSAgentPoolFailed" error. 

az feature register --namespace "Microsoft.Compute" --name "EncryptionAtHost"
az feature list -o table --query "[?contains(name, 'Microsoft.Compute/EncryptionAtHost')].{Name:name,State:properties.state}". 

Voila my cluster deployed successfully ...

> Hello Everyone,
> 
> For those who are still facing this Error while using terrafom AKS module Code="CreateVMSSAgentPoolFailed" Message="AKS encountered an internal error while attempting the requested Creating operation. AKS will continuously retry the requested operation until successful or a retry timeout is hit. Check back to see if the operation requires resubmission
> 
> try to set enable_host_encryption value to false, and try again

**Comment by sumansla123** [comment]
Thank you @kriesto for the pointer. EncryptionAtHost feature needs to be enabled at the subscription to deploy the AKS cluster successfully with host based encryption set to true. In my case, this feature was not enabled in the subscription and code was breaking with "CreateVMSSAgentPoolFailed" error.

az feature register --namespace "Microsoft.Compute" --name "EncryptionAtHost"
az feature list -o table --query "[?contains(name, 'Microsoft.Compute/EncryptionAtHost')].{Name:name,State:properties.state}".

Voila my cluster deployed successfully ...

**Comment by tombuildsstuff** [comment]
@paulgmiller @palma21 apologies for the ping, any thoughts on the above?

**Comment by tombuildsstuff** [comment]
ping @paulgmiller @palma21

**Comment by justindavies** [comment]
Hey @tombuildsstuff - thanks everyone in this thread.  I'm going to pick this up internally so we can get to a resolution.

**Comment by asahadevops** [comment]
Hi @justindavies is there any progress on that? We have also hit the same issue using azurerm 2.89.0 and Terraform 1.0.11

**Comment by JimFran** [comment]
Getting same issue when deploying an AKS cluster with Terraform but AKS is being deployed:

```
terraform {
  # Live modules pin exact Terraform version; generic modules let consumers pin the version.
  # The latest version of Terragrunt (v0.19.0 and above) requires Terraform 0.12.0 or above.
  required_version = ">= 0.13"

# Live modules pin exact provider version; generic modules let consumers pin the version.
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 2.0"
    }
    helm = {
      source  = "hashicorp/helm"
      version = ">= 2.0"
    }
  }
```
However after sign in to the AKS cluster I get this error message:
```
E0127 15:18:58.992427   20620 round_tripper.go:61] CancelRequest not implemented by *genericclioptions.CommandHeaderRoundTripper
Is there any workaround for this issue?
```

I'm not sure if it's related to the previous error message:

```
[1m [31mError:  [0m [0m [1mwaiting for creation of Managed Kubernetes Cluster "aks-xx" (Resource Group "rg-xx"): Code="CreateVMSSAgentPoolFailed" Message="AKS encountered an internal error while attempting the requested Creating operation. AKS will continuously retry the requested operation until successful or a retry timeout is hit. Check back to see if the operation requires resubmission. Correlation ID: , Operation ID: 
```

**Comment by dimbleby** [comment]
ugh, a stalebot appears

>  I'm going to pick this up internally so we can get to a resolution.

@justindavies any news?

**Comment by Scarlettliuyc** [comment]
hi @justindavies  and @tombuildsstuff  good day.

We have customer got same issue.
Code="**CreateVMSSAgentPoolFailed**" Message="AKS encountered an internal error while attempting the requested Creating operation. AKS will continuously retry the requested operation until successful or a retry timeout is hit. Check back to see if the operation requires resubmission. Correlation ID:xxxx, Operation ID: xxx, Timestamp: xxx."
And its popup an error for terraform.exe error:
 [error]Error: The process 'C:\xxx\windows\terraform\0.14.9\x64\terraform.exe' failed with exit code 1 ##[debug]Processed: ##vso[task.issue type=error;]Error: The process 'C:\xxx\windows\terraform\0.14.9\x64\terraform.exe' failed

However the **AKS deployed** successfully, confirmed with customer and it also shows in the deployment log. Could I confirm whether you have fix this issue?
It happens intermittently. 
Thanks

**Comment by tombuildsstuff** [comment]
@Scarlettliuyc this issue is still open (see above) - so it's not fixed / is currently waiting on the AKS Team

**Comment by alvinli222** [comment]
Hi all,

We're currently working on a solution that will disable the automated reconciling of failed clusters. I'll keep this thread updated as soon as we disable it.

**Comment by tombuildsstuff** [comment]
@alvinli222 sounds good - will that include an API to trigger/wait for a reconciliation too?

**Comment by dimbleby** [comment]
stalebot is the worst

**Comment by alvinli222** [comment]
Hey folks, apologies for the delay. We've disabled this and are currently working on GAing a manual reconciliation feature.

**Comment by dimbleby** [comment]
still live

**Comment by mattwilder** [comment]
Will this new "disable automated reconciling" feature apply to AKS node pools as well as clusters? We just hit this issue turning up AKS node pools with terraform.

Terraform apply failed with
```
 Error: waiting for creation of Agent Pool (Subscription: <OMITTED>
│ Resource Group Name: <OMITTED>
│ Resource Name: <OMITTED>
│ Agent Pool Name: "v1z3u4easv5"): Code="ReconcileStandardLoadBalancerError" Message="Reconcile standard load balancer failed. Details: outboundReconciler retry failed: Category: ClientError; Code: Unspecified; SubCode: TooManyRequestsHighCostGetVMScaleSet; Message: ; InnerMessage: ; Dependency: Microsoft.Compute/VirtualMachineScaleSet; AKSTeam: Networking; OriginalError: autorest/azure: Service returned an error. Status=429 Code=\"OperationNotAllowed\" Message=\"The server rejected the request because too many requests have been received for this subscription.\" Details=[{\"code\":\"TooManyRequests\",\"message\":\"{\\\"operationGroup\\\":\\\"HighCostGetVMScaleSet3Min\\\",\\\"startTime\\\":\\\"2022-11-23T23:18:04.4762007+00:00\\\",\\\"endTime\\\":\\\"2022-11-23T23:19:30+00:00\\\",\\\"allowedRequestCount\\\":237,\\\"measuredRequestCount\\\":261}\",\"target\":\"HighCostGetVMScaleSet3Min\"}] InnerError={\"internalErrorCode\":\"TooManyRequestsReceived\"}; Retriable: false; InternalRetryAfterTimer: 2022-11-23 23:19:30.495138368 +0000 UTC m=+7704.825209571."
│
│   with azurerm_kubernetes_cluster_node_pool.node_pools["v1z3u4easv5"],
│   on main.tf line 81, in resource "azurerm_kubernetes_cluster_node_pool" "node_pools":
│   81: resource "azurerm_kubernetes_cluster_node_pool" "node_pools" {
```

However on the next apply the resources already existed.

```terraform {
  required_version = "~> 1.3.0"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.30.0"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.16.0"
    }
  }
}
```

**Comment by zerodayyy** [comment]
not stale

**Comment by matthchr** [comment]
As @Alvinli222 said, the component which performed these out of band cluster state changes was disabled around ~Sept 2022. AFAIK, there are no other ways agent pool or managed cluster can have their `ProvisioningState` changed out of band (from Failure to Success, or otherwise).

I believe this issue can _probably_ be closed once we've confirmed with Terraform that the issue is solved on their end.

**Comment by dimbleby** [comment]
> I believe this issue can probably be closed once we've confirmed with Terraform that the issue is solved on their end.

@matthchr how's that going?

**Comment by dimbleby** [comment]
> I believe this issue can probably be closed once we've confirmed with Terraform that the issue is solved on their end.

@matthchr how's that going?

**Comment by dimbleby** [comment]
I really ought to write my own counterbot.

@matthchr can you confirm that this issue should be closed?  if yes, can you close it?

**Comment by dimbleby** [comment]
You've worn me down.  

If this is fixed and should be closed I wish someone would say so and close this deliberately rather than waiting for the bot to do it.  

But I have long since moved on, and give up on continuing to ask for that.

**Comment by matthchr** [comment]
AFAIK this has been fixed since Sept 2022.

**Comment by stephybun** [comment]
@matthchr I'm following up on Terraform side here - several solutions were discussed above so just to confirm:

The change made on the AKS API side is that auto-reconciliation has been turned off i.e. if the initial provisioning of a cluster fails, then it will always remain in a failed state.

A follow up question to the above is whether this mechanism has also been switched off for node pools?

**Comment by matthchr** [comment]
> The change made on the AKS API side is that auto-reconciliation has been turned off i.e. if the initial provisioning of a cluster fails, then it will always remain in a failed state.

Yes

> A follow up question to the above is whether this mechanism has also been switched off for node pools?

Also yes
