### ISSUE TITLE
Masters node

### ISSUE THREAD

**Issue by przemolb** [Azure/AKS#198]
If I create managed kubernetes cluster on Azure (AKS) I don't have any access to the master node (do I ?). Is the master node in HA mode (multi-master) ? I cannot verify it ....

**Comment by RohanNagar** [comment]
You don't have any access to the master node, that is correct.

**Comment by przemolb** [comment]
What about HA mode ? Can you show some docs telling that they are HA-ed ? Any technical details ? One would need some kind of documentation before going for production.

**Comment by ultimateboy** [comment]
This is by design. AKS provides the Kubernetes api as a service. We do not expose the internals. We will provide more technical details as we gear up for GA, but you'll never have direct access to the master nodes.

With that said, it is not recommended to run production systems on AKS while AKS is in preview.

**Comment by pengzhisun** [comment]
@ultimateboy since the AKS is already GA, do you have any documents about how we manage the master node internals inside the AKS, my customer also want to make sure our design met their requirements, especially for following 2 questions:

1. what's the HA design and implementation
2. how we isolate the kubernetes cluster networks across tenants, are all master nodes inside AKS are belong to a shared virtual network?

**Comment by alanjcastonguay** [comment]
@jnoller Can you reopen and prioritize this documentation request?
