### ISSUE TITLE
Private Cluster - BYO DNS Zone

### ISSUE THREAD

**Issue by palma21** [Azure/AKS#2015]

**Comment by MikeForster100** [comment]
Very interested in this - we are looking to switch everything to private endpoints and looking to roll out AKS but due to our environment and admin model we have an issue with the current configuration (Automatic Private DNS Zone in the auto created RG).  Our current practice - We create the private dns zones in a central subscription which has our central custom DNS servers which then forward to Azure for private endpoint resolution (Currently for storage and sql)  Therefore we would like to create one private endpoint DNS zone (in our central subscription) for AKS and point the new AKS cluster(s) to it during creation to add its entries in it.  Even if a new cluster had to generate the private zone (due to the GUID?) we could live with that as the location (central subscription) is key.

**Comment by GinSiuCheng** [comment]
Putting this sample here for people looking to deploy this via TF with hub-spoke requirements (where dns resolver lives in hub): https://github.com/GinSiuCheng/private-aks-deployment/blob/master/modules/azure_kubernetes_service/main.tf

**Comment by phealy** [comment]
You can now [bring your own private DNS zone](https://docs.microsoft.com/en-us/azure/aks/private-clusters#configure-private-dns-zone).
