### ISSUE TITLE
[Known Issue] ContainerD + Kubenet - Pod IP SNAT/Masquerade behavior 

### ISSUE THREAD

**Issue by palma21** [Azure/AKS#2031]
There's currently a known issue / behavior change on AKS clusters using the Kubnet network plugin + ContainerD container runtime. Note: All kubernetes v1.19+ clusters use ContainerD container runtime.

The existing behavior for AKS clusters using kubenet network plugin is to only SNAT/Masquerade pod traffic to the source Node IP when leaving the PodCIDR and cluster Subnet.

Due to an issue setting up the networking configuration on the new containerd clusters, currently all traffic is SNATed/Masqueraded to the source Node IP, including pod-to-pod traffic.

This behavior will be corrected back to the existing behavior on the next Node Image Version planned for Jan 2021. When that is released any cluster upgrade or node image upgrade will ensure the behavior is to only SNAT when leaving the Pod CIDR and cluster Subnet. You'll be able to control this as today with Azure CNI by configuring the IP Masq Agent config map.

Until then if you want to ensure the behavior is the same as before please use this Daemon Set:
https://github.com/Azure/AKS/blob/master/examples/iptables/snat_exemption_ds.yaml

**Comment by nooshin-mirzadeh** [comment]
Just for information of other users, this issue causes problem for a NetworkPolicy with podSelector configs. Since the policy will be set based on the ipset of the pods in the IPtables by Calico, but the source IP of the packet is set to the node IP and even the packets that are supposed to be allowed will be dropped.

**Comment by dennis-benzinger-hybris** [comment]
@palma21, we use kubenet and Calico with network policies which use pod selectors (the case described by @nooshin-mirzadeh above). Now after creating the daemonset I see that connections start to work, then break again and work again, etc.

Is that expected? Are Calico and your daemonset fighting over the right IPtables rules?

**Comment by dennis-benzinger-hybris** [comment]
@denniszielke, maybe you can answer my question above 😉.

**Comment by dennis-benzinger-hybris** [comment]
Looks like the connections were flaky only in the beginning. Over time it stabilized 🤔.

**Comment by dennis-benzinger-hybris** [comment]
> This behavior will be corrected back to the existing behavior on the next Node Image Version planned for Jan 2021.

@palma21, is there an ETA ?

**Comment by eriksywu** [comment]
@dennis-benzinger-hybris 
The fix should reach all prod regions by weds. 

Some context for how this kubenet snat issue effected calico+kubenet clusters:

For calico+kubenet clusters, the fix is only on the node side so you can pick up the fix via a node image upgrade (or k8s image upgrade). Previous to this fix, we first bootstrap nodes with the default kubenet cni before the calico daemonset finishes setting up the calico cni plugin chains. This has the adverse effect of introducing the kubenet snat issue described in this issue to nodes that run non-hostnetwork pods (i.e coredns, metricserver, etc). Because calico cni takes over after, the kubenet snat issue can get mitigated if those original pods that triggered the kubenet snat rules get bounced/deleted or if you restart your nodes.
