### ISSUE TITLE
not supported to iniciated calls DT from AKS/Kubernetes to SQL on VM

### ISSUE THREAD

**Issue by porrascarlos802018** [Azure/AKS#2036]
Windows containers cannot initiate calls DT to external VM running SQL
This feature is not documented for AKS . Will this feature be available soon? 
https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/494 

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by immuzz** [comment]
There is work in progress on MSDTC support in Windows Containers. For more updates please open an issue under this repo where Windows team is working on. https://github.com/microsoft/Windows-Containers

Please link the issue here once you have opened the issue and close it here as this will be tracked under Windows Containers

**Comment by immuzz** [comment]
https://github.com/microsoft/Windows-Containers/issues/24 Linked the issue to Windows Containers as its being tracked there.
