### ISSUE TITLE
AKS Upgrade to 1.19 Causing my complete environment down. Containerd is failing to load my PODS which runs on side car containers.

### ISSUE THREAD

**Issue by SamaChandra** [Azure/AKS#2037]
**What happened**: Upgraded from Azure Kubernetes Version 1.18.10 to 1.19.03

**What you expected to happen**: All micro services should work as how they are working earlier.

**How to reproduce it (as minimally and precisely as possible)**: I am unable to reproduce or do any changes now. the total cluster was down due to this containerd.

**Anything else we need to know?**: My whole cluster is down which is a high priority issue.

**Environment**: Production Environment
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-19T07:38:38Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-16T20:43:08Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
- Size of cluster (how many worker nodes are in the cluster?):15
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): There are total 25 micro-services failed as "Back off restarting failed container" , We have Consul service mesh sider car proxy container and consul-connect-inject acl token container to create mTLS certificates fetch from vault. There is a connectivity from Ambassador Endpoint API gateway to consul resolveer.
![Ambassador](https://user-images.githubusercontent.com/68558191/102956895-0475fa80-44a7-11eb-9ffc-816f3370c0b4.jpeg)
![ambassador2](https://user-images.githubusercontent.com/68558191/102956897-06d85480-44a7-11eb-99e3-701a2fd6832a.jpeg)

- Others:
![image](https://user-images.githubusercontent.com/68558191/102956929-21123280-44a7-11eb-8c92-d35745f35137.png)

**Comment by palma21** [comment]
Hi @SamaChandra sorry for your issues. You mention on your message the the culprit seemed to be the change to containerd was this something you could root cause and fix with config changes on your side? From the messages I can't help a lot but we'd be happy to dig into it if you happen to have open a support ticket and share the number we can look into your cluster and help out. Are any of those components trying to access a docker folder?

From a communication perspective, while definitely breaking apps is not something we expect with the change, were aware that 1.19 came with containerd or was that a surprise?
