### ISSUE TITLE
Turn off node auto-repair

### ISSUE THREAD

**Issue by zhiweiv** [Azure/AKS#2038]
Recently we found node auto-repair is enabled by default and can only be turned off by Azure support.

Can you provide an option to not enable it at cluster creation? We don't want to enable it for some clusters.

**Comment by seguler** [comment]
Could you please elaborate on why you don't want the node auto-repair on some clusters?

**Comment by zhiweiv** [comment]
1 We have stateful background worker pods, we would like not to restart them easily, sometimes kubelet doesn't work which cause node not ready(eg https://github.com/kubernetes/kubernetes/issues/93771), but pods on that node should be able to continue to work, we want to restart the node after confirm everything is ok.

2 The auto reboot may clear the evidence of some bugs about aks/k8s, we'd like to check first when problem happen.

**Comment by palma21** [comment]
If kubelet is not working and the node is not ready the API would eventually kill the pods on that node (even if they are running) and create them on other nodes. The node auto repair waits for this time before taking any action to avoid #1. If this is not working as you expect please do let us know.

I'd love to hear more on 2 and how we can improve logging / visualization so that you have all data you need to investigate. What are the key things you need or feel you are lacking?

**Comment by zhiweiv** [comment]
For example, cni state, hcs state, network state, container runtime state will be reset after reboot.  If kubelet hang due to deadlock, you will unable to collect dump because of reboot.

Now there is a issue https://github.com/Azure/AKS/issues/2042 we found after turn off node auto-repair in testing cluster.

**Comment by zhiweiv** [comment]
Close this, I will ask azure support to turn off node auto-repair when necessary.
