### ISSUE TITLE
Is there a way to upgrade the AKS load balancer to standard from basic?

### ISSUE THREAD

**Issue by junkiebev** [Azure/AKS#2053]
We have half a dozen older AKS clusters which were created before Standard went GA for load balancers, so they are basic skus and experiencing issues with ephemeral port exhaustion and connection drops.

Is there a way to upgrade the AKS load balancer to standard from basic? Similar to the way it didn't used to be possible to rotate service principal credentials, I'm praying that there is a command to migrate with the az cli.

Hope I'm not out of luck!

**Comment by palma21** [comment]
Yes, we're working on it, but it's a bit of work from scratch since the actual BLB to SLB IaaS components don't have migration so we really can't migrate any IP or the actual configs and reuse them, so we're trying to make a way to at least automate the cluster migration so it seamless even thought the front end IPs would be different (at least until they are possible to be migrate which the LB teams are working on).

You can track it here: #1687
