### ISSUE TITLE
AutoScaler support for NCasT4_v3 nodepools

### ISSUE THREAD

**Issue by andrewsali** [Azure/AKS#2088]
**What happened**:

In the latest release notes it is mentioned that NCasT4_v3 SKUs are supported. However when adding a node-pool with this SKU and turning on auto scaling, the auto-scaler is completely wiped out. The cluster-autoscaler-status configmap disappears.

Removing the auto-scaling for this nodepool makes the cluster autoscaler functional again.

**What you expected to happen**:

Cluster autoscaler should support this SKU and should provision / deprovision new nodes. Operations of the cluster-autoscaler should not suspend when scaling is enabled in such a nodepool.

**How to reproduce it (as minimally and precisely as possible)**:

Add a nodepool with this SKU and enable autoscaling on this nodepool.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.10
- Size of cluster (how many worker nodes are in the cluster?): 3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): Microservices
- Others:

**Comment by marwanad** [comment]
@andrewsali That release is still on-going and hasn't concluded yet as mentioned on the release notes. Which region are you hitting this in?

Are you creating that nodepool with zero nodes? The only dependency on the SKU types is when scaling from zero and there are no existing nodes (it uses the SKU information to predict the capacity) to build a template of.

**Comment by andrewsali** [comment]
@marwanad hitting this in West Europe region

Yes, the nodepool is created with 0 nodes. However the autoscaler shuts down even before receiving a scaling request, just having a nodepool with this SKU with autoscaling turned on triggers the crash.

Manual scaling works OK.

**Comment by marwanad** [comment]
@andrewsali The change haven't hit westeurope yet. 

Yes, it builds the node template on initialization, and if you retrieve the CA logs you'll see the log line that indicates so. This behaviour is [by design](https://github.com/kubernetes/autoscaler/blob/8c315390007fac118d438c907ca3db0f49739476/cluster-autoscaler/core/utils/utils.go#L170-L173) upstream.

It will work for a pool with that SKU if you're not scaling to/from zero. You might be able to get it working if you create it with at least one and have a min-count set to 0, it will use the live node to build the template and cache it. However, you'll be at the sake of the cache TTL there. I recommend using it with `-c 1 --min-count 1` until the change to support the SKU is out.

**Comment by andrewsali** [comment]
Great, thx for the feedback!

I will close this for now and reopen if still seeing the issue in a few days when the rollout should have completed.

I am still wondering though if the behaviour of the autoscaler to completely halt when there is an unsupported SKU is appropriate, especially that this is done silently.
