### ISSUE TITLE
Disable the virtual node add-on should drain and delete the virtual node

### ISSUE THREAD

**Issue by chunliu** [Azure/AKS#2091]
**What happened**:
When using `az aks disable-addons -a virtual-node` to disable the virtual node add-on, the add-on is disabled but the virtual node is still there and in the NotReady state. 

![image](https://user-images.githubusercontent.com/2128551/106755925-a9b8ec80-6669-11eb-8793-f946b9c3fd77.png)

If there is a pod running on it, the pod will be stuck in the Terminating state. If the pod is deployed as part of Deployment, a new pod would be scheduled and stuck in Pending state. 

![image](https://user-images.githubusercontent.com/2128551/106756199-fd2b3a80-6669-11eb-826a-a6011267d648.png)

Users have to manually clean it up. 

**What you expected to happen**:
When the add-on is disabled, the virtual node should be drained and deleted as well. Or if there are pods running on the virtual node, show a warning and stop processing. 

All other resources that are created by the add-on, such as the network profile etc., should also be removed when the add-on is disabled. 

**How to reproduce it (as minimally and precisely as possible)**:
1. Enabled the virtual node add-on. 
2. Deploy some pods to the virtual node. 
3. Disable the add-on. 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.19.6
- Size of cluster (how many worker nodes are in the cluster?) 2
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) Testing
- Others:

**Comment by gossion** [comment]
there is only 1 virtual node, draining that node would make those pods have nowhere to run and lead to unexpected result.
instead of draining that node directly, it would be better to check the pods running on virtual node first before disabling the add-on:
1. if there is no pod running on virtual node, it is safe to disable the addon
2. if there are pods running on virtual node, raise an error and tell user to delete all pods on virtual node first.
