### ISSUE TITLE
Run custom script extension when provisioning new agent nodes

### ISSUE THREAD

**Issue by northtyphoon** [Azure/AKS#212]
When I create an AKS cluster, how can I configure running the custom script extension on agent node (eg, 
 install AzSecPack on each new agent nodes)?

**Comment by amanohar** [comment]
@northtyphoon at this time AKS don't support configuration of CSE via it's API.

**Comment by stroon2** [comment]
+1 We need this feature too. :-)

**Comment by valorl** [comment]
This is absolutely necessary when using the SMB or any other flex volume. In the case of [`microsoft.com/smb`](https://github.com/Azure/kubernetes-volume-drivers/tree/master/flexvolume/smb), `jq` and `cifs-utils` need to be installed. 
VMs are recreated on upgrade and these dependencies are lost.

**Comment by andyzhangx** [comment]
@valorl microsoft.com/smb already supports custom extension installation, while it's not in AKS yet, see:
https://github.com/Azure/kubernetes-volume-drivers/blob/master/flexvolume/smb/README.md#option1-use-azure-custom-script-extension-to-install-smb-driver-on-every-agent-vm
And I have already made a PR to install [blobfuse driver](https://github.com/Azure/kubernetes-volume-drivers/blob/master/flexvolume/blobfuse) in acs-engine first, and AKS will adopt this code change when it's merged.
Since there is already azure file built-in plugin, can I ask why you want `microsoft.com/smb` into AKS? Have you set up SMB server by yourself?

**Comment by valorl** [comment]
@andyzhangx Thanks, I must have missed that in the README. I assume I'll still have to run this after every upgrade? 

As for my use-case, yes, we have some on-premise shares we need to be able to access (we're also using Site-2-Site VPN).

**Comment by andyzhangx** [comment]
@valorl currently you need to run that custom extension script for new node, I will add this smb driver(and also cifs-utils) into acs-engine first, and after a few weeks, AKS will have smb driver. Thanks for providing the info, that's helpful to move things forward.

**Comment by valorl** [comment]
@andyzhangx Thanks, much appreciated.

**Comment by andyzhangx** [comment]
FYI @valorl https://github.com/Azure/acs-engine/pull/3455 has both blobfuse & smb flexvolume drivers installed in acs-engine

**Comment by logicfox** [comment]
Do we know if this has been adopted by AKS yet? We would love to switch to blobfuse from the current azure-files storage we're using.

**Comment by andyzhangx** [comment]
@logicfox Not yet, blobfuse will be as an addon in both acs-engine and AKS, related PR(https://github.com/Azure/acs-engine/pull/3575) has been merged into acs-engine.
also cc @jackfrancis

**Comment by t1agob** [comment]
Do we have any news about the timeframes to have this implemented in AKS?

**Comment by andyzhangx** [comment]
@t1agob as I know the solution is use daemonset + hostpath volume to do this.

**Comment by t1agob** [comment]
@andyzhangx I see. So this is not an actual custom script extension in the Azure ARM Template when deploying. You need to have a manual step after the initial cluster deployment. right?

**Comment by andyzhangx** [comment]
@t1agob It's [daemonset](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/) , user needs to run a daemonset which could run a container on every node and install packages inside the container, and finally the packages is installed on the node by [hostpath](https://kubernetes.io/docs/concepts/storage/volumes/#hostpath) volume

**Comment by t1agob** [comment]
@andyzhangx clear. Thanks!

**Comment by seanmck** [comment]
We have no plans to enable arbitrary custom script extensions on agent nodes. If possible, you should enable what you need via Kubernetes daemonsets.

**Comment by t1agob** [comment]
Not the answer I was expecting but at least we now have a clear answer. Thanks @seanmck

**Comment by dominik-lekse** [comment]
We also use DaemonSet to apply modifications to the cluster nodes. In particular, we add CA certificates to the nodes trust store to be able to access a Docker repository signed with a private CA.

A problem of this approach is that the Docker daemon needs to be restarted once the trusted certificates have been modified.

Any idea how this problem could be solved using the daemonset approach?

**Comment by cezarsa** [comment]
@dominik-lekse I had the exact same problem of requiring a new CA on AKS created nodes due to a private registry.

The solution I found was creating a DaemonSet that uses `nsenter` to "escape" the container namespaces and update the host CA bundle and restart the docker daemon. This requires a privileged container with `hostPID` set to true. It's not pretty, but it works quite well.

I created a repository and a docker image with this logic and there's a nice example on how to run this daemonset in https://github.com/tsuru/hostcert#using-a-daemonset.

**Comment by anshul4694** [comment]
We also need this feature to come in. The requirement is to install certain components on the nodes at the time of provisioning them.

**Comment by joetechbob** [comment]
I have Windows nodes and need to install dependencies. As priveleged containers aren't possible on Windows, using a DaemonSet doesn't seem to be an option there.

Does anyone have a workable solution for Windows nodes? One idea was to use VMSS and custom script extensions...But it feels like we would fall more inline with what aks-engine was setting up if there was simply an option to run additional setup scripts as a part of the pile of scripts that are being run anyway...

**Comment by qinmaye** [comment]
DSC's Script resource to run custom script is a good way.

**Comment by qinmaye** [comment]
You can see this [article](https://review.docs.microsoft.com/en-us/engineering/projects/ops/build-service/run-custom-script-on-vmss-by-dsc) to see more details. But it perhaps needs some Authority.
