### ISSUE TITLE
Cluster autoscaler should delete oldest vms first on scale in

### ISSUE THREAD

**Issue by denniszielke** [Azure/AKS#2164]
**What happened**:
Currently the cluster autoscaler deletes the newest vm when it scale down the VMSS instances again.
This causes issues that the older VM of the VMSS stay there forever while the autoscaler always adds new vms and removes them when scaling in.

**What you expected to happen**:
The VMSS scaler has a scale in policy that can be configured to always delete the oldest vm on scale down. We would like to have a similar scale in policy on the AKS cluster autoscaler as a configurable option.

**Comment by marwanad** [comment]
CA doesn't delete the newest VMs - it deletes the "unused" VMs with resource utilization below a configured threshold `--scale-down-utilization-threshold` so it's up to how the pods were assigned. Naturally, most of the time that will be the newest created VMs that were created to accommodate the workload.

Keep in mind, it doesn't scale down by setting the VMSS capacity and deletes particular VMs instead. This is because it needs to consider some scheduling constraints when draining the nodes (Taints, etc).

Can you elaborate on the use-case for that scale-in policy?

**Comment by denniszielke** [comment]
Ok that makes sense. I guess then the question is if we can influence the HPA to delete certain pods on scale in?

**Comment by marwanad** [comment]
There's an upstream KEP for that :) https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/2255-pod-cost. 

It's on the application owner though to implement a controller that would mutate those annotations.

**Comment by denniszielke** [comment]
Interesting alpha feature pod deletion cost coming up in 1.21 https://github.com/kubernetes/kubernetes/pull/99163
