### ISSUE TITLE
I want to run startup shell script when the new node is provisioned in AKS

### ISSUE THREAD

**Issue by 14sudharsan** [Azure/AKS#2247]
```
I want to run startup shell script when the new node is provisioned in AKS. Can you pls let me know how to do that
```

**Comment by palmerabollo** [comment]
@14sudharsan you can use a [Kubernetes daemonset](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/) to run your shell script in all nodes. Would that work for you?

AFAIK, AKS doesn't support using a cloud-init script yet. Since [aks-engine](https://github.com/Azure/aks-engine) supports it, I guess it would be technically possible to expose it in AKS as well. It would be a nice feature.

**Comment by miwithro** [comment]
Correct running shell scripts on the AKS nodes directly is not supported.  What exactly are you trying to configure?

**Comment by 14sudharsan** [comment]
Actually I tried to attach blob storage file share in all the nodes . If in
case scale up nodes we should attach blob storage in new node as well

**Comment by justindavies** [comment]
@14sudharsan, are you trying to mount a blob container on all nodes?  The best way to achieve what you are looking to do for your workloads to access shared storage is to either integrate with blob storage through the API, or use Azure files or Azure NetApp as a volume for those workloads to access: https://docs.microsoft.com/en-us/azure/aks/azure-files-volume
