### ISSUE TITLE
Microsoft Defender for Containers Runtime Security- Pod Inventory and Process detection.

### ISSUE THREAD

**Issue by miwithro** [Azure/AKS#2268]
Azure Defender is adding runtime security of applications running in AKS.   The initial implementation will be have the Azure Defender as a AKS managed addon deployed through a daemonset.  The initial capability will be to automate pod inventory of what is running in an application.

**Comment by PixelRobots** [comment]
I noticed the add-on is already available as a preview. Is this part of that add-on already? Would love to test this.

**Comment by miwithro** [comment]
The current addon is through an agent, we are reworking it to run as a daemonset and adding in profiling capabilities to be followed by process detection.

**Comment by PixelRobots** [comment]
Oh nice!  Sounds really cool. Will it also do windows containers? Any time frame?

**Comment by roberthstrand** [comment]
> The current addon is through an agent, we are reworking it to run as a daemonset and adding in profiling capabilities to be followed by process detection.

Just following this up, as it's been a while since the last update.

Does this mean that we are waiting for the daemonset so that Defender is actually useful for anything other than Arc enabled clusters that are manually set up? I'm referring to this point in the FAQ: https://docs.microsoft.com/en-us/azure/security-center/defender-for-kubernetes-introduction#does-azure-defender-for-kubernetes-support-aks-with-vmss-nodes

**Comment by miwithro** [comment]
@roberthstrand that is correct.

**Comment by roberthstrand** [comment]
> @roberthstrand that is correct.

Alright, do we have some sort of estimate for this?

**Comment by miwithro** [comment]
@roberthstrand Microsoft Defender for Containers will be in Public Preview 12/13/2021

**Comment by miwithro** [comment]
GA'ed.  Dup of #2526 and #2527. Closing.
