### ISSUE TITLE
AKS v1.20+ messes up tags on entities it doesn't own

### ISSUE THREAD

**Issue by wasker** [Azure/AKS#2290]
**What happened**:

AKS v1.20+ copies tags from the AKS resource to public IP address resource, which was created separately from AKS.

**What you expected to happen**:

AKS should not rewrite tags on entities it doesn't own.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create new AKS resource, assign tag "entity: A"
2. Create new Public IP resource in a different resource group, assign tag "entity: B"
3. Configure newly created public IP resource as an outbound IP address for AKS' load balancer via `aks update --name myaks --resource-group myrg --load-balancer-outbound-ips /id/of/a/public/ip/resource`
4. Deploy ingress-nginx chart that makes use of this public IP address (need to provide both IP address and the name of the RG where the address is, since address is outside of the MC_xxx resource group).
5. Remove ingress-nginx chart with helm delete.
6. Re-deploy ingress-nginx chart with the same parameters as step (4).

Observe that after few minutes the tags on the Public IP address have changed with new tags annotating something relevant for AKS, and existing "entity: B" tag is overwritten with the "entity: A" tag from the cluster itself.

I understand that AKS needs to annotate resources for something, but it should not alter tags it doesn't recognize.

From my observations so far, it looks like "helm install" -> "helm delete" -> "helm install" for ingress-nginx triggers bad behavior. If you inspect events for nginx namespace after "helm delete", you'll see that AKS attempts to delete the public IP address, but fails due to IP address still being present in relevant LB configurations (this is expected). My hunch is that this puts the machinery that reconciliates ingress and LB settings into a bad state, which results in subsequent "helm install" triggering an update which overwrites tags with values from cluster tags.

**Comment by miwithro** [comment]
@brkifle please address.

**Comment by feiskyer** [comment]
The issue should be caused by the cloud provider codes [here](https://github.com/kubernetes/legacy-cloud-providers/blob/638db08374e0bddefb7a251545378a1f0d14629f/azure/azure_loadbalancer.go#L2230-L2241) and [here](https://github.com/kubernetes/legacy-cloud-providers/blob/638db08374e0bddefb7a251545378a1f0d14629f/azure/azure_loadbalancer.go#L2593-L2610), which is: when a PIP has service tags or its IP address is same as service.spec.LoadBalancerIP, then PIP would be applied with tags configured in cloud provider config file. The fix for #2301 would partially fix the first service tags condition, but won’t for the second service.spec.LoadBalancerIP condition. Another fix from cloud provider would be required to fix this issue.

/assign @nilo19

**Comment by nilo19** [comment]
https://github.com/kubernetes/kubernetes/pull/101752 to fix this one
