### ISSUE TITLE
Issue: Accessing the Kubernetes API from within the pod leads to connection-reset 

### ISSUE THREAD

**Issue by Pradyumnakashyap** [Azure/AKS#2304]
**What happened**: My application experiences a connection reset trying to access the Kubernetes API using the official Kubernetes JAVA client. 

**What you expected to happen**: Application inside the pod should be allowed authorized access of Kubernetes API without any interruptions in connection.

**How to reproduce it (as minimally and precisely as possible)**: Use an Official JAVA client to access the Kubernetes API from within the pod and the server seems to reset the connection without reason

**Anything else we need to know?**: After debugging the issue, I noticed that all pod creations and communications to the Kubernetes API takes place on a custom Kubernetes -API end point generated by AKS, that is visible on the Azure Kubernetes Service overview page.  But the Official Kubernetes clients written in different languages expect to reach the Kubernetes API at kubernetes.default.svc (hence my application is not able to access the Kubernetes API) 

Solution: Both Kubernetes.default.svc and the custom endpoint should resolve to the Kubernetes API server for authorized clients running inside pods, this way the Official Kubernetes clients can be used without mishaps.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.9 
- Size of cluster (how many worker nodes are in the cluster?) - 3 Node
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) Java app
- Others:

**Comment by jabbera** [comment]
- I'm having a similar problem on 1.20.2 and was trying to figure out how to reproduce it. In my case I'm using the python client and it seems, anecdotally, that if my application is not accessing the service endpoint for a long period of time I get a connection reset. Subsequent attempts work. I was assuming it had something to do with a state tracking device (load balancer, ip tables) dropping the connection because keep alives weren't being sent but this is all just an uneducated guess.

Do you notice your reset is related to load (or lack there of?).

**Comment by Pradyumnakashyap** [comment]
Yes, a quick hack was to change the code to persistently keep trying (retries with a long time-out helped) and the connection would be successful eventually.  But also note if you manually change your application to reach the end point to the one visible on the Azure Kubernetes cluster overview UI ( called API server address ), then it works fine ! But for that you will have to write your own client and the Official clients will not do as they are assume they could reach the API server on Kubernetes.default.svc.
