### ISSUE TITLE
Creating AKS via az cli doesn't associate the subnet to the NSG

### ISSUE THREAD

**Issue by rajdhandus** [Azure/AKS#2309]
**What happened**:

The Load Balancer IPs created in AKS were not reachable from Internet. 

**What you expected to happen**:

The Load Balancer IPs should have been reachable from the Internet

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a RG
2. Create a VNet 
3. Create a subnet
4. Create AKS with Azure CNI and associate subnet
5. Create a Load Balancer and try to reach from Internet. If reproduced successfully - the connectivity should not be there.
6. Check the NSG that is created in MC* - it shouldnt have association to any subnet. 
![image](https://user-images.githubusercontent.com/6888014/116953420-0b293100-ac42-11eb-8b27-442f39a43398.png)
7. Try to associate manually to the subnet created in #3. Although the UI warns its already associated - its not!
8. Now check connectivity - and it should work.
![image](https://user-images.githubusercontent.com/6888014/116953515-50e5f980-ac42-11eb-9b0a-60c0a9b719c0.png)

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.4
- Size of cluster (how many worker nodes are in the cluster?) 3 VMs
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) .net core
- Others: Can help reproduce if needed. Have clusters in AME.

**Comment by joaguas** [comment]
Hi @rajdhandus ,

AKS's NSG (aks-poolname-xxxxxxxx-nsg) is associated with worker nodes NICs. This is the NSG that gets populated with the required rules whenever you expose a service.

That ...NRMS is a specific subscription enforced NSG that gets attached to your subnets minutes after creation. Ingress traffic doesn't work right away because AKS does not populate that NSG specific to you and traffic is checked against both NSGs (the AKS(nics) one and the Subnet one) - Once you associate the subnet with the AKS one (as you did) it works.
