### ISSUE TITLE
Request for a private AKS API endpoint with a support for a customer provided publicly resolvable DNS name

### ISSUE THREAD

**Issue by mapdegree** [Azure/AKS#2376]
**What happened**:
Users in a network topology need to resolve the AKS API endpoint within different parts of the organisation inside a private network topology. Instead of bringing private DNS resolvers everywhere possible in an enterprise organisation, we would need to rely on a publicly resolvable DNS entry for that purpose. Current AzureRM APIs do not allow to mix a public DNS entry with a private network topology.

**What you expected to happen**:
Users inside a private network topology should be able t resolve a publicly resolvable DNS entry of the AKS API endpoint, but can still connect (Layer 4) to the private AKS API endpoint.  

**How to reproduce it (as minimally and precisely as possible)**:
We used terraform provider (azurerm) or via Azure Portal or AZ CLI. Same result - it is not possible to configure a custom publicly resolvable DNS name with a private network topology AKS API endpoint.

**Anything else we need to know?**:
We are using version 1.20.5.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.20.5
- Size of cluster (how many worker nodes are in the cluster?) 6 (one of them), we have 7 AKS clusters and will expand
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): various - all mentioned above
- Others:

**Comment by sdktr** [comment]
There actually is a public resolvable DNS that points to the controle plane IP of a private cluster. It is the record used for in-portal navigation to AKS resources. I've seen that record as output in AKS deployment details as well as in F12 browser debug:

`https://{{guid-ish?}}-priv.portal.hcp.westeurope.azmk8s.io/apis/apps/v1/deployments?limit=200`

Tagging allong on this issue because the private DNS integration is in dire need for a simpeler approach in my opinion as well.

**Comment by SatyKrish** [comment]
Private AKS cluster with Public FQDN is now in preview. 

https://docs.microsoft.com/en-us/azure/aks/private-clusters#create-a-private-aks-cluster-with-a-public-dns-address-1

**Comment by feiskyer** [comment]
Public DNS feature has been in preview and BYO public DNS is not supported.
