### ISSUE TITLE
Cluster-autoscaler support for HBv3 series

### ISSUE THREAD

**Issue by andrewsali** [Azure/AKS#2393]
**What happened**:

Adding a HBv3 nodepool disables the cluster autoscaler

**What you expected to happen**:

Cluster autoscaler should support HBv3 (it support HBv2), as it is GA in certain regions for more than 3 months (https://azure.microsoft.com/en-us/updates/hbv3series-vms-now-generally-available-in-east-us-south-central-us-and-west-europe)

**How to reproduce it (as minimally and precisely as possible)**:

Create a nodepool with HBv3, watch the cluster-autoscaler-status configmap disapper.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.19
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by marwanad** [comment]
@andrewsali sorry for the delayed response - it will be rolling with next week's release so expect to see it in the release notes.

Also for completeness: The only thing that is "blocked/unsupported" is scaling from zero since that requires updating the SKU list with the new SKU capacities for CA to predict the resources on the nodes. We are also working on utilizing the SKU API so this static list will no longer be needed in the future :)
