### ISSUE TITLE
API Server keeps bleeding Error budget while trying to connect to port 19100 on the node IPs

### ISSUE THREAD

**Issue by EraYaN** [Azure/AKS#2397]
**What happened**:

The logs gets one of these lines for every node every couple of minutes:
```
E0621 08:26:29.036308       1 status.go:71] apiserver received an error that is not an metav1.Status: &amp;fmt.wrapError{msg:"error trying to reach service: dial tcp 10.8.0.66:19100: connect: connection refused", err:(*net.OpError)(0xc0240dd950)}

```

**What you expected to happen**:
There should be no error and no depletion of the error budget. Those requests should not be happening on that port at all. When SSH'ed in to the nodes there is nothing listing on these ports.

```
kubectl get all --all-namespaces -o yaml
```
That does not even contain the port number.

**How to reproduce it (as minimally and precisely as possible)**:
I'm absolutely not sure, this cluster was deployed some 250 days ago using Terraform.
And the only thing non default about that is that it's using a `SystemAssigned` identity, all addons are disabled and finally that the network_addon and network_policy are `azure`.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
  ```
  Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"6b3f9b283463c1d5a2455df301182805e65c7145", GitTreeState:"clean", BuildDate:"2021-05-19T22:28:47Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
  ```
- Size of cluster (how many worker nodes are in the cluster?): 3 in system node pool 3 in linux worker pool and 1 in windows pool. (All nodes are either D2asv4 or D8asv4)
  ![image](https://user-images.githubusercontent.com/1627021/122746827-b2ae0180-d28a-11eb-9436-4670811a6267.png)

- General description of workloads in the cluster: HTTP/gRPC microservices
- Others: Running Azure CNI

It seems to have started around half way in April.

**Comment by jemag** [comment]
We have had the same issue on our side too. Looking at the kube-audit logs it seems to be linked to prometheus
since it shows
`
userAgent | Prometheus/2.19.0
`
trying to call
`
requestURI | /api/v1/nodes/aks-main-42554519-vmss000038:19100/proxy/metrics
`

At first I thought it might be related to the Prometheus Operator running on our clusters, however I saw that the clusterrole referenced is ""system:prometheus" and user is "hcpService".

This clusterrole is created by AKS at cluster creation. So I am not sure why it is trying to make those requests and essentially spamming API server errors. Sometimes it also tries to make requests to port 10257: 
`
/api/v1/nodes/aks-main-42554519-vmss00003f:10257/proxy/v1/metrics
`

Regarding your depletion of error budget @EraYaN I am curious which kubernetes version you are running? In our case, the budget depletion started happening as soon as we upgraded any of our clusters from version 1.19.x to 1.20.X. as you can see from : 
![image](https://user-images.githubusercontent.com/7985687/122839452-0db11a00-d2c6-11eb-8ac8-5f1953c20cd0.png)


Our production cluster hasn't been upgraded yet and shows no such sign of steady errors:
![image](https://user-images.githubusercontent.com/7985687/122839517-2d484280-d2c6-11eb-8722-81f542ea393e.png)

**Comment by EraYaN** [comment]
It seems like we also upgraded to v1.20.2 from v1.19.3 and then the problem started:

![image](https://user-images.githubusercontent.com/1627021/123076135-2251f700-d419-11eb-9e44-375fd41bc4a8.png)

That date the 19th was exactly the same date the variable changed in our terraform specification.

We are at v1.20.7 now but that didn't fix anything.

**Comment by jpweber** [comment]
Having the same issue here. Doing some digging on AKS and "hcpService" Brought me here (https://docs.microsoft.com/en-us/security/benchmark/azure/baselines/aks-security-baseline#22-configure-central-security-log-management) 
In particular this part
> Guidance: Enable audit logs from Azure Kubernetes Services (AKS) master components, kube-apiserver and kube-controller-manager, which are provided as a managed service.
kube-auditaksService: The display name in audit log for the control plane operation (from the hcpService)
masterclient: The display name in audit log for MasterClientCertificate, the certificate you get from az aks get-credentials
nodeclient: The display name for ClientCertificate, which is used by agent nodes

Which looks to me like the errors are being caused from a client on the azure side scraping the api and generating the errors.

**Comment by luddskunk** [comment]
I am experiencing the very same errors. v1.19.7 is working fine, both 1.20.7 and 1.21.1 is causing the Error Budget to bleed. I enabled diagnostics for the cluster and see similar logs. 

Did anyone open a support ticket or have any more updates to share?

**Comment by jemag** [comment]
I have had a ticket open for about 2 weeks now, and the only suggestion I received so far was to enable the Uptime SLA, which should obviously not be related since everything worked fine for any version prior to 1.20.X. Nonetheless tried it and behavior is the same with or without Uptime SLA.

Perhaps someone here will have better luck with their own ticket.

**Comment by luddskunk** [comment]
Thanks for letting us know @jemag. I opened a ticket too, providing screenshots and log dumps. Let's see where it heads to. For now, I will freeze the upgrade of my other clusters.

**Comment by luddskunk** [comment]
Update on AKS Ticket from Azure Support:

"Please let me know if you’re seeing errors like this in your Prometheus monitoring.
[Prometheus]: [FIRING:1] KubeAPIErrorsHigh warning (monitoring/k8s nodes proxy CONNECT)   
If you’re error is like this, then this is a known issue at our end. Hotfix for hasn’t been pushed to all the regions yet and expected to be pushed within 1-2 weeks. "

Hopefully this will resolve the issue, even though I don't see the specific Prometheus log mentioned.

**Comment by jemag** [comment]
Thanks for the update @luddskunk. Are these errors supposed to happen on Prometheus instances running in the cluster or the Azure Monitor Prometheus integration thing?

On our side we're using Prometheus Operator and I believe the alert "KubeAPIErrorsHigh" is not used anymore, but rather "KubeAPIErrorBudgetBurn", which we are indeed getting. I think "KubeAPIErrorsHigh" might still be used with OpenShift though, not sure.

I have an update with our ticket as well, mentioning the following : 

> This issue might be related to a similar issue where we can see Multiple 503 errors in API server causing "KubeAPIErrorsHigh" alert 
>  
> Root cause Analysis :- A scrape job was added to the prometheus-server instance running in the customer control plane for scraping a node-exporter systemd service which will be installed on customer VMs (and exposed at port 19100 so as not to conflict with 9100 which is typically used by customer node-exporter daemonsets) soon but has only been released in internal subscriptions so far. This will allow us to expose better AKS node metrics to customers. The errors show up because the prometheus server on the customer control plane is attempting to scrape the node-exporter metrics endpoint at port 19100 regardless of whether the AKS node VM extension is installed, resulting in an increase in 503s from the kube-apiserver. The scrape job was added prematurely so we could monitor the VM extension rollout, but this will be removed to avoid the misleading error increase in customer monitoring and we will pursue a different solution for monitoring the rollout. 

Which should fix the spam of errors from the scrape job, however I do not have any ETA on that so far.

One thing that I realized though, is that our production cluster that is still on 1.19.X still has those port 19100 errors in the API Server logs, <ins>**however**</ins> there is no increase in API Server Read errors or Write durations detected by Prometheus. I am curious if any of you also have 1.19.X clusters that show those errors in the logs, but don't exhibit any problem in the Prometheus monitoring?

**Comment by luddskunk** [comment]
Hey @jemag! Thanks for sharing your correspondence.

> One thing that I realized though, is that our production cluster that is still on 1.19.X still has those port 19100 errors in the API Server logs, however there is no increase in API Server Read errors or Write durations detected by Prometheus. I am curious if any of you also have 1.19.X clusters that show those errors in the logs, but don't exhibit any problem in the Prometheus monitoring?

I also noticed exactly the same actually. I can see these type of error logs in one of my clusters which is running 1.19.7. Further on I noticed that 1.20.7 generates 500, but 1.21.1 generates 500/503's (Yes, I kept upgrading one cluster in order to see if the bleed issue was resolved)

I can also add that I this morning received a response from my ticket regarding the ETA:

> I have checked with our engineering team and it seems that your issue might be related to a known issue at our end.
Hotfix for the issue is already in release process for different regions and should be pushed to **westeurope before end of next week.**

**Comment by pietervincken** [comment]
We're running into exactly the same issue (including the KubeAPIErrorBudgetBurn alert).

**Comment by MattJeanes** [comment]
We're also seeing this on all 4 clusters we have (3 West Europe, 1 East US) - what is the timeline for this fix rollout, this is causing our alerting systems to fire off frequently with false alarms

**Comment by EraYaN** [comment]
Our support contact said that the fix has not yet been rolled out due to technical issues. Waiting for an ETA update now.

**Comment by Aaron-ML** [comment]
Ah, Our support ticket engineer told us to upgrade to 1.20 to resolve these API errors, glad this was acknowledged by Microsoft with a hotfix due as we've been seeing these alerts page us for a few weeks now across all clusters.

**Comment by shanalily** [comment]
The fix for the RCA referenced by @jemag has been rolled out to all public cloud regions and errors from scraping port 19100 should not contribute to error budget depletion anymore.

ETA for port 10257 error fix rolling out to all of public cloud is end of this week or early next week. It only affects cluster with Linux node VHD versions older than 2021.06.01.

**Comment by MattJeanes** [comment]
Thank you for the update @shanalily - I can confirm that the 19100 port error is resolved in all my clusters across all regions. It is also worth mentioning that you can manually fix the 10257 error by upgrading the image on the node pools like so, as recommended to me by Azure support:

```bash
az aks nodepool upgrade \
    --resource-group myResourceGroup \
    --cluster-name myAKSCluster \
    --name mynodepool \
    --node-image-only
```

Or alternatively by upgrading the entire Kubernetes cluster which will also roll out new image versions, which is the route I opted for as I wanted to upgrade them anyway.
