### ISSUE TITLE
Test everything on 1.19.07 but it's EOS, should I test again on 1.19.11?

### ISSUE THREAD

**Issue by AlanPPP** [Azure/AKS#2404]
We the whole team spend 1 month to test everything on AKS 1.19.07 but it's EOS now. Should I test everything again for 1.19.11? Can 1.19.11 perfectly replace 1.19.07 without any new bugs or performance issue?  
Is there any possibility to create 1.19.07 again, I don't want the new patch.

**Comment by justindavies** [comment]
Hi @AlanPPP with minor releases there should not be breaking changes in Kubernetes that would affect your existing tests.  I would recommend taking a look at the Kubernetes Changelog here: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md#changelog-since-v11910 so see if any of those changes would affect you.
