### ISSUE TITLE
Network Polciy for webhook configuration

### ISSUE THREAD

**Issue by phillebaba** [Azure/AKS#2440]
**What happened**:
When setting up new network policies for Ingress Nginx I realized that I needed to allow traffic to the ValidatingWebhookConfiguration. This should have been simple but was made complicated by the way tunnelfront works. Allowing ingress from tunnelfront did not seem to be enough as it does not NAT the traffic. Running TCP dump on tunnelfront showed that traffic from 192.0.2.100 was being sent to the validating webhook service. Understandable as that would be the IP for the AKS API server making the requests.

A simple solution would be to allow requests from 192.0.2.100/32 to the webhook service. The question is if this is a static IP that will always be used or can this IP be changed in the future?

**Anything else we need to know?**:
N/A

**Environment**:
- Kubernetes version (use `kubectl version`): 1.20.7 with Calico

**Comment by danimal521** [comment]
tunnel-front is being deprecated in place of konnectivity. This will allow you to standardize you network policy.

**Comment by jveski** [comment]
@phillebaba Allowing packets from 192.0.2.100/32 is all you need for the current tunnel implementation.

As @danimal521 mentioned, we are in the process of rolling out [apiserver-network-proxy](https://github.com/kubernetes-sigs/apiserver-network-proxy) (aka Konnectivity), which will effectively NAT the traffic such that allowing ingress from pods labeled `app=konnectivity-agent` will be sufficient. I'd recommend adding those rules now since the update might hit your clusters soon.

I'm going to close this out for now - feel free to reactivate and mention me if you have any more questions.
