### ISSUE TITLE
--max-surge parameter of az aks nodepool upgrade doesn't take effect

### ISSUE THREAD

**Issue by chi-qin** [Azure/AKS#2469]
## What happened:

When I use `az aks nodepool upgrade --resource-group $resourceGroup --cluster-name $clusterName --name $pool.name --node-image-only --max-surge 20%`  to upgrade vmss nodes os version, it seems that --max-surge doesn't take effect, it upgrades each node one by one.

## What you expected to happen:

I hope that each time, there are 20% of all the nodes upgrading.

## Environment:
- 2 node pools
- Kubernetes versions:1.19.7
- Node sizes: Standard_D4s_v3, Standard_D16s_v3

**Comment by rishabhsaha** [comment]
How many nodes are there in the nodepool? 20% of how many nodes?

**Comment by chi-qin** [comment]
> How many nodes are there in the nodepool? 20% of how many nodes?

About 106, 106 too.

**Comment by rishabhsaha** [comment]
Hi @chi-qin - can you create a support ticket following the steps above to help the support team help debug? To clarify your issue - you have 106 nodes in each nodepool and the expectation is during the node image upgrade it should upgrade 21 nodes at a time. But in your case it's still upgrading one node at a time instead of 21 nodes. Is that the correct assessment?
@palma21 - FYI.
