### ISSUE TITLE
 CVE-2017-1002101 & CVE-2017-1002102 patch eta?

### ISSUE THREAD

**Issue by dfcarpenter** [Azure/AKS#248]
https://cve.mitre.org/cgi-bin/cvename.cgi?name=2017-1002101
https://cve.mitre.org/cgi-bin/cvename.cgi?name=2017-1002102

An announcement/ETA for patches to these would be great.

**Comment by andyzhangx** [comment]
So the question here would be when following k8s versions will be availabe on AKS:
Fixed versions:
Fixed in v1.7.14 by #61047
Fixed in v1.8.9 by #61046
Fixed in v1.9.4 by #61045
Fixed in master by #61044 (included in v1.10.0-beta.3, will be in v1.10.0)

more details:
https://github.com/kubernetes/kubernetes/issues/60813
https://github.com/kubernetes/kubernetes/issues/60814

**Comment by slack** [comment]
AKS rollout for this week includes support for 1.7.15, 1.8.10 and 1.9.6.

Should be in all AKS regions by Friday.

**Comment by sauryadas** [comment]
Closing this as this has been fixed
