### ISSUE TITLE
Adding external plugins support for CoreDns

### ISSUE THREAD

**Issue by TahaSnoussi** [Azure/AKS#2483]
**What happened**:
I set up a first AKS cluster for applications that exposes services to onprem infrastructure.
I used CoreDns ConfigMap to support a private dns zone and exposed the coredns as an internal load balancer service with static private IP 147.1.1.100.
On prem DNS servers were configured to redirect enterprise.cloud zone to 147.1.1.100.
Then, I added a second AKS cluster where I configured the coredns service with 147.1.1.101.
I tried to use alternate coredns plugin to forward requests to second AKS cluster in case requested service is not resolved by the first cluster (alternate NXDOMAIN . 147.1.1.101).

**What you expected to happen**:
The coredns pods restarts with new configuration

**How to reproduce it (as minimally and precisely as possible)**:
The ConfigMap for CoreDns
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  cloud.server: |
    dev.enterprise.cloud:53 {
      kubernetes enterprise.cloud
      k8s_external enterprise.cloud {
        ttl 1200
      }
      alternate NXDOMAIN . 147.1.1.101 {
        policy sequential
      }
    }
Then delete coredns workers
kubectl delete pod --namespace kube-system -l k8s-app=kube-dns

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.21.1
- Size of cluster (how many worker nodes are in the cluster?): 10 nodes / pool. 10 pools.
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) processing units
- Others: .

**Comment by EPinci** [comment]
Hey @TahaSnoussi, can you help out clarifying the ask here?

If the issue is in CoreDNS picking up the changes, please note that just changing the configmap will not trigger a pod restart (kubernetes behavior, see also [here](https://github.com/kubernetes/kubernetes/issues/22368)). In order to pickup changes to the custom configuration configmap you need to restart the coredns pods with `kubectl delete pod --namespace kube-system -l k8s-app=kube-dns`.

About the "alternate" plugin, the [official documentation](https://docs.microsoft.com/en-us/azure/aks/coredns-custom#what-is-supportedunsupported) states that non built-in plugins are not supported and alternate is not in the [coredns built-in plugins](https://coredns.io/plugins).
Are you expecting to have alternate built in the system deployment of CoreDNS of AKS?
Have you considered deploying a custom CoreDNS pod(s) to your cluster that has the plugins and the configuration you need?

Thank you.

**Comment by TahaSnoussi** [comment]
Hi @EPinci 
Thanks for the hint about the custom configuration. I use this already since it's clearly documented here https://docs.microsoft.com/en-us/azure/aks/coredns-custom.

For the alternate external plugin, I managed to build a CoreDNS with it. Then I tried to replace the AKS built-in Pods.
Do you think it's possible to add a new CoreDNS deployment side by side?
Can you help me with kubernetes templates for doing that?

**Comment by EPinci** [comment]
@TahaSnoussi, 
you cannot replace the builtin CoreDNS of AKS: it is deployed as an addon an will revert changes you do it.
You can certainly add a new deployment of CoreDNS as a standard workload and eventually "wire it" to the built-in and the ones you need for your scenario.
You can get started on the deplyment by looking at [CoreDNS deployment resources](https://github.com/coredns/deployment).

Thank you.
