### ISSUE TITLE
Long delay to all web request (Waitiing TTFB is large value)

### ISSUE THREAD

**Issue by mostaqur** [Azure/AKS#2511]
Hi,
I am using AKS to deploy my Tomcat based Java web application. 
My cluster is using Kubernetes 1.19.11.
I install Ingress according to https://docs.microsoft.com/en-us/azure/aks/ingress-internal-ip guide.

I am using ClusterIP as service which is exposed through ingress. Infront of ingress I am using Application Gateway for public access.

I noticed every web request suffering from long delay as Waiting TTFB.

I tried with turning on --set controller.service.externalTrafficPolicy=Local in Ingress  level. 

I also tried with change service to NodePort and use externalTrafficPolicy=Local.

I also tried with disabling monitoring the cluster.

Still no luck.

Anyone can help me?

**Comment by mostaqur** [comment]
Hi,
Still waiting for the response. Anyone can help?

**Comment by vijaypatnana** [comment]
Hi,

@mostaqur we are in the same boat.

We recently upgraded our AKS clusters to 1.19.11 version in lower environments, since then we are seeing high TTFB for graphql app. 

I am hitting an API call using curl command with **--write-out** option from AKS worker node, here is the output -

**time_namelookup=0.000028
time_appconnect=0.000000
time_connect=0.000213
time_redirect=0.000000
time_pretransfer=0.000279
time_starttransfer=10.692330 --> (TTFB is too high)
time_total=10.692389**

TTFB(time_starttransfer) is too high on AKS 1.19.11 version. 

we have another cluster with **1.17.13** version running same application. Output from curl command on AKS 1.17.13v -

**time_namelookup=0.000
time_appconnect=0.000
time_connect=0.000
time_redirect=0.000
time_pretransfer=0.000
time_starttransfer=1.210
time_total=1.210**

We see high TTFB on 1.19.11 version. Can you please take this as priority, This issue is blocking us on many aspects. will be waiting for your response. Thanks!

**Comment by mostaqur** [comment]
Hi,

This becomes a bit urgent. Anyone can help me, please?

**Comment by mostaqur** [comment]
I am repeating myself. Can anyone advise me at least from where I can get some help?
