### ISSUE TITLE
Support for cross-region loadbalancer

### ISSUE THREAD

**Issue by jemag** [Azure/AKS#2535]
Cross-region load balancer currently mentions the following limitation (https://docs.microsoft.com/en-us/azure/load-balancer/cross-region-overview#limitations):

> Integration with Azure Kubernetes Service (AKS) is currently unavailable. Loss of connectivity will occur when deploying a cross-region load balancer with the Standard load balancer with AKS cluster deployed in the backend.

- Are there any plans for making AKS integration possible with cross-region load balancer?
- Would it also be possible to have more details on why these loss of connectivity currently occurs?

Intended setup would be something like:
![image](https://user-images.githubusercontent.com/7985687/132040125-21752592-2add-41c6-a589-7d6c90c7af4e.png)
but with cross-region load balancer instead of Traffic Manager.

**Comment by tomkerkhove** [comment]
+1

**Comment by phealy** [comment]
Cross-region load balancer works with AKS since they added floating IP support last year. When configuring the cross-region load balancer entry, you will need to add the [`service.beta.kubernetes.io/azure-additional-public-ips`](https://cloud-provider-azure.sigs.k8s.io/topics/loadbalancer/#:~:text=service.beta.kubernetes.io/azure%2Dadditional%2Dpublic%2Dips) annotation with the value set to the global VIP on all services behind the cross-region LB to tell kube-proxy to accept traffic on the additional IP.
