### ISSUE TITLE
AKS Fails to build due to disabled feature: Microsoft.ContainerService/AutoUpgradePreview

### ISSUE THREAD

**Issue by sossickd** [Azure/AKS#2584]
Since the release of the latest azurerm terraform provider 2.79.x the following error appears when building a new AKS cluster.

```
Plan: 1 to add, 0 to change, 0 to destroy.
azurerm_kubernetes_cluster.main: Creating...

Error: creating Managed Kubernetes Cluster "Example-AKS" (Resource Group "kubernetes-prod"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="BadRequest" Message="Feature Microsoft.ContainerService/AutoUpgradePreview is not enabled. Please see https://aka.ms/aks/previews for how to enable features."
```

Downgrading the azurerm provider to 2.78.0 fixes the issue.

The following [MR](https://github.com/hashicorp/terraform-provider-azurerm/pull/13493) caused the issue on the azurerm terraform provider.

@tombuildsstuff mentioned in the [related issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/11396) on the azurerm terraform provider github project.

"Whilst this is a change in Terraform, unfortunately this is an AKS bug - since submitting the default value to the API shouldn't require this preview feature to be enabled (as it's marked as the default value in the API, too). We've raised this with the AKS Team on Friday, but I'd suggest opening an issue on the AKS Repository too where someone from that team should be able to take a look."

**Comment by tombuildsstuff** [comment]
@palma21 FWIW we raised this issue with the AKS Team on Friday since this API behaviour differs from some other Azure API's where it's possible to set this a field to the default value (e.g. `none`) without being opted into the feature.

A `null` value and `none` aren't treated the same on the AKS side. The value when this is set to `null` isn't returned in the API response unless it's explicitly configured, however, there is a default behaviour for this field. Notably we've had reports that the default value isn't set to `none` in some cases either, [for example here it's set to the value `"undefined"` in the API response](https://github.com/hashicorp/terraform-provider-azurerm/issues/13447#issue-1003666036) which isn't defined in the Swagger spec. Within Terraform we need a means of reconciling these to a single default value.

Unfortunately whilst this _is_ a bug on our side (and it's unfortunate that we didn't spot setting this to `none` required the Preview feature, which is something we've got a plan to fix longer-term) - since there are multiple possible default values for this field (null, `none` and `undefined`), removing this default value would reintroduce a separate bug into the plan (that this field is shown as having no value when there's multiple defaults available in the API) - so to be honest I don't think that's necessarily the right fix here.

Were there a single default value here then we could reliably not send this value in the request, however, since there's multiple possible default values and the AKS API isn't returning the value for this field from the API if it's unset, but is defaulting this fields behaviour (and there's multiple possible default values) - in practice we need to do so to coalesce this on our side. One of the core tenants of Terraform is that the plan says what it'll do (and folks use tools like Sentinel & OpenPolicyAgent to validate the Terraform Configurations match what they expect) - so from our side it's imperative that we can determine the default value for these fields.

This is causing issues for users today, [this issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/13447#issue-1003666036) shows a user provisioning the same cluster using the same settings at different points in time and getting different results from the AKS API - which is ultimately why we've had to set this to `none` here to disable this preview functionality.

If it's not possible to determine the single default value for a given Preview feature, and that can't be explicitly disabled without being opted into the Preview - given the requirements here we may have to consider omitting support for new Preview functionality until that's fixed (and that's not something we want to do / in the best interest of users) - so ultimately I think that both of these bugs need to be fixed in the API here.

Happy to chat further about this, but this is an issue affecting all preview functionality within AKS,  this is exacerbated by having multiple default values, which we've no means of reconciling down to a single value in the Provider with the information returned from the API unfortunately.
