### ISSUE TITLE
Logs from Pods not always collected  

### ISSUE THREAD

**Issue by trhumphries** [Azure/AKS#2603]
**What happened**: We have Azure Monitor with Container Insights hooked up to our AKS clusters. In some cases the log for individual pods are not being collected and forwarded to Azure monitor. In some cases no log entries for a pod are collected in other cases only part of the log entries get collected. We use Console logging for all of our logs. Note that in all cases I can dump the logs from the pod and the entries do exist. The Log entries are going to stderr

**What you expected to happen**: I expect all entries written to stderr and stdout to be reflected in the ContainerLogs table in Azure Monitor

**How to reproduce it (as minimally and precisely as possible)**: Setup a cluster using Azure Monitor

**Anything else we need to know?**: This only started happening with in the last 10 days. I only noticed today because I was trying to diagnose an issue

**Environment**: AKS
- Kubernetes version (use `kubectl version`): 1.20.9
- Size of cluster (how many worker nodes are in the cluster?) 10
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) Http Micro services and cron jobs 
- Others:

**Comment by phealy** [comment]
In the future, for something specifically related to your cluster like this, please open a service request. This kind of transient problem is usually specific to a single cluster or region and needs to be investigated by support. If you're still experiencing the issue now, please open a support request. Otherwise, please open one if it reoccurs
