### ISSUE TITLE
AKS support of an external Azure NAT Gateway / external loadbalancer as outboundType option

### ISSUE THREAD

**Issue by MasterKolka** [Azure/AKS#2624]
Feature request.

If I have multiple small AKS clusters it would be good to have an option to configure one egress gateway for all of them to reduce costs.

Similar feature request - https://github.com/Azure/AKS/issues/1122

**Comment by phealy** [comment]
This is already possible using a single VNet and the bring-your-own VNet configuration (doc links: [kubenet](https://docs.microsoft.com/en-us/azure/aks/configure-kubenet) / [Azure CNI](https://docs.microsoft.com/en-us/azure/aks/configure-azure-cni)). If you're using managed networking (where AKS creates the networks in the MC resource group and uses a separate VNet for each cluster), this isn't possible because [a single NAT gateway can't span multiple VNets](https://docs.microsoft.com/en-us/azure/virtual-network/nat-gateway/nat-overview#:~:text=NAT%20can%27t%20span%20multiple%20virtual%20networks.).

To do this:
1. Build a virtual network with one or more subnets for each cluster.
2. Provision a single NAT gateway for those subnets.
3. Use [`outboundType userAssignedNATGateway`](https://docs.microsoft.com/en-us/azure/templates/microsoft.containerservice/managedclusters?tabs=bicep#:~:text=userAssignedNATGateway) via the ARM object or `[--outbound-type](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#:~:text=Ubuntu%20or%20CBLMariner.-,--outbound-type,-How%20outbound%20traffic)` parameter to `az aks create` when you provision your cluster (note that because the feature is in preview, this requires the aks-preview extension and the options won't show in the regular docs I just linked yet).

**Comment by MasterKolka** [comment]
@phealy Thanks! Haven't seen that feature. Could somebody add a page to the "Egress" section here - https://docs.microsoft.com/en-us/azure/aks/nat-gateway ? Thanks.

**Comment by phealy** [comment]
I've already got the doc PR written, actually! Just waiting on provisioning clusters in my test sub to validate syntax before I submit it.

**Comment by phealy** [comment]
@MasterKolka Doc PR merged, should be published in about an hour.
