### ISSUE TITLE
Default cluster CNI configuration results in overlapping VNet address ranges

### ISSUE THREAD

**Issue by aelij** [Azure/AKS#2727]
**What happened**:
When creating an Azure CNI AKS cluster with default configuration, the diagnostic tool in the portal complains about overlapping addresses:

> Kubernetes service address range is overlapping a vNet address range
> Kubernetes service address range: 10.0.0.0/16 is overlapping virtual network address ranges: 10.0.0.0/8.

**What you expected to happen**:
No errors

**How to reproduce it (as minimally and precisely as possible)**:
1. `az aks create -g testcluster -n testcluster -x --network-plugin azure`
2. Go to the AKS Portal blade > Diagnose > Connectivity Issues

**Environment**:
- Kubernetes version (use `kubectl version`): 1.21.7
- Size of cluster (how many worker nodes are in the cluster?) 3

**Comment by miwithro** [comment]
@phealy

**Comment by miwithro** [comment]
@phealy

**Comment by higordearaujo-bsy** [comment]
Does anybody have at least a workaround we can use? On my end I also get HTTP 400 with the same error message as the one in the OP when trying to do aks operations through az cli.

**Comment by gwynforthewyn** [comment]
This would be incredible to have fixed. Presently, in the Azure Portal AKS cluster setup, the "Basic" network option always creates clusters with overlapping CIDRs in the virtual networks that Azure automatically sets up for the cluster. This means that peering two of the virtual networks, letting two clusters communicate with each other over the Azure backbone, doesn't work correctly by default.

**Comment by gwynforthewyn** [comment]
This issue’s still important to me and I think addressing it would be valuable. 

Maybe if the api backend could accept a flag like —non-overlapping-cidrs-please (with a better name) that would throw an error if the currently requested cidr would overlap another AKS cidr in the searched subscription?

**Comment by gwynforthewyn** [comment]
This is still an issue that's important to me. what do you think, @chasewilson ?

**Comment by gwynforthewyn** [comment]
I’m sure I don’t get points for longevity, but it really would be slick if this were addressed. It’s a crappy usability problem that gives me pause for thought when recommending azure to colleagues for kubernetes hosting @chasewilson @allyford

**Comment by chasewilson** [comment]
Hey @gwynforthewyn you definitely get points for longevity. At least in my book. Let me take a look at this and see what we can do.

**Comment by chasewilson** [comment]
Ok, I can't repro this issue any more. Using same command, same plugin, etc..., I don't get a warning or error for overlapping CIDRs and my VNet network is in a different space than my Service CIDR. @gwynforthewyn  do you have the same issue still or more detail I can follow up on?

**Comment by gwynforthewyn** [comment]
I’ll see what I can do this evening after work!

**Comment by chasewilson** [comment]
Much Appreciated! I'll keep an eye out for your response and hopefully we can get this closed one way or another!

**Comment by gwynforthewyn** [comment]
Okay; I've been tinkering, and I've remembered why I had chimed in on this issue. Unfortunately, the issue I was talking about is different to the issue the original reporter was reporting.

For me, the issue was that I had several AKS clusters. I wanted gather their logs into a dedicated cluster that hosted Elasticsearch (a dedicated cluster because elasticsearch is very RAM intensive). I knew I would have to create the Elasticsearch cluster, then peer each of the vnets together so that logs could flow over the azure backbone.

However, then I realised that each AKS cluster is created with the kubernetes default 10.0.0.0/16 service cidr address range. Therefore, when I tried to peer each of the several vnets together, there was overlapping IP addresses and I got inconsistent results trying to send logs to my centralised logging cluster. 

What I had intended to request was like...whether during the validation period when I'm creating a new cluster if there could be a validation step in the case that one service CIDR overlaps another that reads something like, "Hey, you have another cluster that is already using this service cidr; if you ever need to peer these two clusters together you will have undefined behaviour".

Now that I read this over and familiarise myself with the details again, I can acknowledge that's not the same as the original reporter's issue. I can file a separate github issue requesting additional validation, if that seems like something your team would be willing to evaluate on the roadmap?

Thanks @chasewilson !
