### ISSUE TITLE
What instance types are supported by the cluster auto scaler?

### ISSUE THREAD

**Issue by BartVB** [Azure/AKS#2736]
We are getting error messages like:

`Unable to build proper template node for aks-appv4-41339789-vmss: instance type "Standard_D2as_v5" not supported `

in the cluster autoscaler logs. Alas I'm unable to find a list of supported VM sizes in the documentation, Azure support also doesn't seem to know. The documentation does mention:

https://docs.microsoft.com/en-us/azure/aks/quotas-skus-regions#supported-vm-sizes
> The list of supported VM sizes in AKS is evolving with the release of new VM SKUs in Azure. Please follow the AKS release notes to stay informed of new supported SKUs.

But there are 12 pages of release notes. The release notes are also a bit vague:
> Added support for more SKUs for scaling from zero (including Standard_E2s_v5, Standard_D8s_v5 and Standard_D4s_v5).

Which implies that besides the mentioned SKUs other SKUs have also been added?

A list or, even better, an indication in the portal and CLI tool on nodepool/cluster creation would be great.

**Comment by marwanad** [comment]
We are switching to retrieving a dynamic list of SKUs so any SKU supported by your AKS cluster in that region and subscription, will be supported by cluster autoscaler from scaling to zero.

Note that any SKU is already supported by autoscaler. The matrix is smaller for scaling from zero because the SKU information (vCPU, memory, etc) needs to be obtained somewhere.


A good place to see what's supported currently is the SKU list [here](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/azure/azure_instance_types.go). Note that the last commit is still rolling in all regions as of the AKS release notes.

**Comment by BartVB** [comment]
Thank you for the quick response! We'll wait for the new release then, Das_v5 seems to be supported there. 
Is there any place where we can see the deployed AKS version? Can't find that in the docs.

**Comment by marwanad** [comment]
The estimated times in the release notes would be your best bet there: https://github.com/Azure/AKS/releases/tag/2022-01-06

Which region are your clusters in?

**Comment by phealy** [comment]
I believe the new release is out in all public regions - can you please confirm that this is resolved?
