### ISSUE TITLE
Public cluster egress traffic

### ISSUE THREAD

**Issue by srinman** [Azure/AKS#2775]
**What happened**:
AKS public cluster deployment

Currently, there is a support to use AzureKubernetesService FQDN tag that can be used in Azure Firewall to restrict outbound traffic from the AKS cluster.  However, this will not be used when customers add an additional network rule to allow TCP communication to port 443 of API server's IP.  This is required for any app or solution (under namespaces other than kube-system or gatekeeper-system) that need to talk to API server.  

**What you expected to happen**:

Can you add support for AKS public cluster IP addr/prefixes tag that can be used by customers for egress traffic? This will help to eliminate IP specific network rules. 

**How to reproduce it (as minimally and precisely as possible)**:

Deploy public cluster with egress controls as documented here
https://docs.microsoft.com/en-us/azure/aks/limit-egress-traffic#required-outbound-network-rules-and-fqdns-for-aks-clusters

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by olsenme** [comment]
@palma21

**Comment by Dilergore** [comment]
@phealy - Just to give some more context:

We are aware that on Layer 7 (Application Rules) in the AZFW there is an option to use the 'AzureKubernetesService' service tag. Which somewhat works and would be a solution to solve this issue, however for some traffic (for example nginx ingress controller) the firewall denies the traffic with 'SNI TLS extension was missing' error. This issue seems to happen if the pod is trying to communicate with the API but do not have the proper value set for the 'KUBERNETES_SERVICE_HOST' environment variable. We had an open MS case for this (2111230050001269) where the support was recommending a [3rd party solution](https://github.com/redhat-cop/podpreset-webhook) to overcome this issue which we were not happy with. We have many teams internally using AKS, AKS is our main compute platform. We would expect the solution to work out of the box without added complexity like adding 3rd party products to our clusters. If you have any solution which you could recommend to look into I would appreciate.

Thanks!

**Comment by phealy** [comment]
@Dilergore I apologize - I got this confused with another request. I was thinking of an NSG service tag (IP based), rather than the Azure Firewall FQDN Tag - which was implemented and should already contain an entry for the API server hostname.

Azure Firewall can only apply an application rule (which is the only kind of rule that works off FQDNs) if there's a hostname in the TLS SNI field. In this case, because the workloads are connecting by IP address, there's no hostname and so no application rule will match; traffic falls back to the network rule. We can't create a group to automatically add the IP address to the network rules.

The issue here goes back to how the kubernetes default in-cluster configuration works. The kubernetes.default service is a standard service with an endpoint object, [programmed by the basic kubernetes services](https://github.com/kubernetes/kubernetes/blob/908a830c8a56423252497d5d7e25d83f0c22f981/pkg/controlplane/reconcilers/instancecount.go#L50-L143). Because it's using an endpoint, it *must* use the IP address; there's no way to program a DNS hostname here. This is what's causing requests using the standard in-cluster configuration to not utilize the appropriate DNS name for matching the rules.

We're limited on what we can do to fix this because we have to follow upstream K8s expectations. Overriding the behavior of the default service discovery variables would be a big change and cause lots of confusion. You can work around this on your end by overriding the KUBERNETES_SERVICE_HOST environment variable in the pod - either setting it manually via the pod manifest, or adding an admission controller to set it automatically on your workloads, but understanding that this violates the regular contract for that in-cluster configuration.

**Comment by Ledermayer** [comment]
@phealy To give you some more context:

We have tried to use only the FQDN tag, no layer4 port 443 open outbound to AzureCloud service tag, but it's not really worked out for us.  Seems, that the Layer7 application firewall will be drop all https packes which have the IP in the packet header instead of FQDN, and since there is no layer4 rule to fall back (the whole excercise that we do not want to allow egress to that houndreds of thousands of adresses the AzureCloud tag covers) we are in the swamp.

This is a problem even with the [tool](https://github.com/redhat-cop/podpreset-webhook) for mutating admission webhhok MSFT offfered us and @Dilergore mentioned, as that deployment failing too when trying to create a secret (or fetching it), so you cant even deploy it out of the box. 

We ended up using https://github.com/hmcts/k8s-env-injector, in a terraform module, as thats better working out for us.

However, globally these are not really great options, and what we are asking that from a certain API version you choose, start using IPs from a more strict ranges and give its own ServiceTag what we can use as the truth for our layer4 443 outbound rules destination, so we know that AKS deployed after a certain date will fall in the new tag ranges. We do not really want to use layer7, but we are forced to as any other filtering option are so loose, that it's not passing any reasonable security expectations.

Hope this makes sense, and we feel this is for the good for the whole AKS community going forward.

Regards,
@Ledermayer

**Comment by phealy** [comment]
@Ledermayer hitting your points:

As much as I really would like to, there's no feasible way for us to create a more user-specific service tag. Service tags are by definition the same for everyone, and we're not set up to allocate cluster API server IPs from a block that would be includable in a service tag at this time.

AKS already has a webhook that we use to modify our `kube-system` pods to force them to use the cluster FQDN/L7. I implemented a small change to that webhook so that it will also modify any pod with the annotation `kubernetes.azure.com/set-kube-service-host-fqdn` applied to it (with any value; even an `""` empty string is good enough). This should provide you with a built-in solution that will work well. I expect that change to be in the `2022-07-17` release. Take a look at the [release notes page](https://github.com/Azure/AKS/releases) for more details once those notes are announced.

As far as the regular contract goes - what I mean is that it would be modifying the upstream behavior that you'd otherwise get. If you deploy K8s anywhere with open source code, you get KUBERNETES_SERVICE_HOST as the IP of the in-cluster `kubernetes.default.service` endpoint. Changing that without a deliberate customer action is a change we'd prefer not to do.

**Comment by Dilergore** [comment]
> AKS already has a webhook that we use to modify our `kube-system` pods to force them to use the cluster FQDN/L7. I implemented a small change to that webhook so that it will also modify any pod with the annotation `kubernetes.azure.com/set-kube-service-host-fqdn` applied to it (with any value; even an `""` empty string is good enough). This should provide you with a built-in solution that will work well. I expect that change to be in the `2022-07-17` release. Take a look at the [release notes page](https://github.com/Azure/AKS/releases) for more details once those notes are announced.

@phealy - The above sounds amazing, this is exactly what we need.
