### ISSUE TITLE
BuiltIn Azure Policy K8sAzureHostFilesystem ignores "excludedContainers" parameter

### ISSUE THREAD

**Issue by Bananenbieger1234** [Azure/AKS#2807]
**What happened**:

I defined some k8s containers to exclude with the parameter "excludedContainers" within the Azure Policy 098fc59e-46c7-4d99-9b16-64990e543d75 with display_name "Kubernetes cluster pod hostPath volumes should only use allowed host paths".

The specified containers are not excluded during evaluation.

The parameter exists:
![image](https://user-images.githubusercontent.com/48549289/155545986-3f30fe2d-48ee-4485-bab1-d20d1d5aa89b.png)

There is also some logic concerning excluded container handling, but this doesn't seem to work.
![image](https://user-images.githubusercontent.com/48549289/155546267-7321ceec-14a5-4c0c-9faa-65401f01e283.png)

**What you expected to happen**:

Specified excludeContainers should be excluded!

**How to reproduce it (as minimally and precisely as possible)**:
1. Setup AKS
2. Enable Azure Policy Addon
3. Deploy a pod/container which is non-compliant to the mentioned azure policy.
4. Create Azure Policy for the mentioned azure policy and set the parameter "excludedContainers" with one existing container to be excluded.
5. Policy is marked as non-complient, because container is not excluded

**Anything else we need to know?**:

I can prepare a PR if you tell me were the source code is located.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.22.4
- Size of cluster (how many worker nodes are in the cluster?): 4
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): HTTP microservices
- Others:

**Comment by miwithro** [comment]
@Fseldow

**Comment by fseldow** [comment]
Hi @Bananenbieger1234 
Sorry for confusing you, the exclude container in policy K8sAzureHostFilesystem is the only one special case that it will only exclude read only for containers because hostPath volume is not a container-level spec which is under pod level. It is considered to deprecate this parameter in the future.
Below it the description:
`The list of InitContainers and Containers to exclude from readonly evaluation. It will not exclude the disallowed host path. The identify is the name of container. Use an empty list to apply this policy to all containers in all namespaces.`
https://github.com/Azure/azure-policy/issues/884

**Comment by Bananenbieger1234** [comment]
@fseldow ok thanks for your explanation. I now understand the difference between container level and pod level policies. Maybe I need to exlude based on namespaces ...
I will close this issue.

**Comment by Bananenbieger1234** [comment]
@fseldow are you planning to implement other kinds of exclusions like pod-level exclusions?
