### ISSUE TITLE
CVE-2022-0492: flaw in Linux Kernel cgroups feature allows container escape

### ISSUE THREAD

**Issue by miwithro** [Azure/AKS#2834]
It has been discovered that under certain circumstances, the Linux kernel’s cgroups v1 release_agent feature can be used to escalate privilege and bypass namespace isolation unexpectedly.

https://ubuntu.com/security/CVE-2022-0492

# AKS Information:

Update your node image to [2022.03.29](https://github.com/Azure/AgentBaker/blob/master/vhdbuilder/release-notes/AKSUbuntu/gen1/1804/2022.03.29.txt) to remediate this vulnerability.

**Comment by saffiali** [comment]
@miwithro Any ETA on this please?

**Comment by miwithro** [comment]
@saffiali it will be in all Azure regions by 3/25

**Comment by justbert** [comment]
Hello!

It appears that the fix for CVE-2022-0492 missed it's original release in 5.4.0-1072 was was released in 1073.76: https://launchpad.net/ubuntu/+source/linux-azure-5.4/+changelog

It is also pointing to 1073.76 in the CVE database (though, it was originally 1072): https://ubuntu.com/security/CVE-2022-0492

**Comment by miwithro** [comment]
@justbert you are right.  I updated our guidance.
