### ISSUE TITLE
lost connection to pod

### ISSUE THREAD

**Issue by LoungeFlyZ** [Azure/AKS#285]
When using:

`az aks browse --resource-group k8clustergroup --name myAKSCluster`

We regularly get the following after a couple of mins:

`0403 11:33:13.011244    5897 portforward.go:178] lost connection to pod`

Is there anything we can do to keep the connection to the pod open?

**Comment by LoungeFlyZ** [comment]
@Zimmergren this seems to solve it!  the connection dropping must have something to do with it being idle?

**Comment by wouterhund** [comment]
I'm getting the same for any kind of `kubectl port-forward` where the TCP socket is idle for few minutes.

**Comment by baracoder** [comment]
Experiencing the same with `kubectl logs -f`, if the pod does not log anything for a couple of minutes, the connection freezes up.

**Comment by DamonStamper** [comment]
This is probably caused by the Azure load balancer. See [Microsoft Documentation on how to update your load balancer's timeout](https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-tcp-idle-timeout).

You can also update the timeout via a GUI through portal.azure.com. Go to the "MC_$CLUSTERNAME" resource group > the 'Load balancer' resource type > 'Frontend IP configuration' > Select one of the rows (I only have one and it looks generated) > Select one of the 'Used by' links  > Increase the 'Idle timeout (minutes)' slider > Click the "Save" button.

If this is what it is than a permanent fix would be having 'az aks browse' have a tcp keep-alive per the MS documentation I mentioned.

**Comment by baracoder** [comment]
The maximum timeout I can set through the portal is 30 minutes. On GKE I can leave a port-forward or `logs -f` open over the weekend and it will be still responsive when I come back.
