### ISSUE TITLE
Cannot create AKS with Windows VMSS that does not support accelerated networking.

### ISSUE THREAD

**Issue by mikeolasz** [Azure/AKS#2858]
**What happened**:

Created an AKS resource through terraform (azurerm version 2.99.0) with an additional Windows 2019 node pool with the VM size set to Standard_B2s and the windows VMSS was created with accelerated networking enabled. This prevents the nodes to be scaled because the Standard_B2s VM is not supporting AN. I've been using this configuration for a long time now and never had this issue. 

[This issue](https://github.com/Azure/AKS/issues/1404) is very similar, although it's mentioned that AN is turned on when the SKU supports it.

I also tried to create this configuration through the Azure Portal but it failed during deployment due to the same error VMSizeIsNotPermittedToEnableAcceleratedNetworkingForVmss.

**What you expected to happen**:

Have a Windows VMSS that is not using AN if the SKU does not support it.

**How to reproduce it (as minimally and precisely as possible)**:

Create an AKS resource through the Azure Portal with an additional Windows node pool and the VM size set to Standard_B2s.

**Comment by mikeolasz** [comment]
Looks like the AKS team resolved the issue. Now the VMSS is created without AN enabled if the SKU does not support it. Closing this as the problem mentioned above is gone.

**Comment by t-l-k** [comment]
Windows accelerated networking on AKS is not possible right - as per https://github.com/Azure/AKS/issues/2620 ? Can't find any explicit guidance as such, all documented evidence indicates that it _should_ work if the underlying SKUs/sizes/os image support it. 

Though the presence of https://github.com/Azure/AKS/issues/2620 suggests otherwise.

In my experience over the past couple of days playing with it, it definitely doesn't. I had also hit that https://github.com/Azure/AKS/issues/1404 issue in past couple of days. 

Very limited information. I've my eye on this '[upstream](https://docs.microsoft.com/en-us/azure/aks/windows-faq#what-if-i-need-a-feature-thats-not-supported)' resource: [list of AKS compatible skus](https://github.com/Azure/aks-engine/blob/e01249356fb6ed7752ba4d1946edd12914a128b1/pkg/helpers/azure_skus_const.go).
