### ISSUE TITLE
adding nodepools with unique subnet will validade the state of other existing nodepools

### ISSUE THREAD

**Issue by mracfa** [Azure/AKS#2865]
**What happened**:

Adding a new nodepool on a different subnet will validade the consistency/status of the existing nodepools. If for some reason other nodepool has an issue (with node count invalid for the subnet) it will fail

**What you expected to happen**:

Expect if i add a new nodepool on a different subnet, it should be independent in terms of node count and number of available IP's. This way we could quickly replace a nodepool, and we dont need to fix the other.

**How to reproduce it (as minimally and precisely as possible)**:

It's not possible to do a repro now, but the below cluster add that issue (with invalid node count for the size of subnet) on 22/03, so when adding the new nodepool on a different subnet, it was always failing with the message of insuficient IP's.

On this particular case we had to lower the node count number and only afterwards add the new nodepol.

ResourceID: /subscriptions/cb9fb916-41de-4dbf-ac39-e83a1d047a65/resourceGroups/ece-prdweua-devdat5-k8s-rg/providers/Microsoft.ContainerService/managedClusters/ece-prdweua-devdat5-k8s

**Comment by alexeldeib** [comment]
@paulgmiller 

just to clarify, you hit IP exhaustion in one subnet, so you created another and tried to create a new nodepool without fixing the exhaustion on the first one? dumb question, howd you get into that state on the first nodepool? I thought the validation you mentioned should fail the request on the frontend validation, not put the AP in failed state.

**Comment by paulgmiller** [comment]
They might get  into that through manual vmss scaling or autoscaleing (or a bug in our validation).

**Comment by mracfa** [comment]
> @paulgmiller
> 
> just to clarify, you hit IP exhaustion in one subnet, so you created another and tried to create a new nodepool without fixing the exhaustion on the first one? dumb question, howd you get into that state on the first nodepool? I thought the validation you mentioned should fail the request on the frontend validation, not put the AP in failed state.

Hi Alex. Yeah, first nodepool was in a weird state:  the count and the maxCount were higher (68 nodes, maxpods 15 - requesting 1088 IP's) than the number of available IP's in the subnet (1019). I believe not all those 68 nodes had all ip's assigned though (i believe some of the nodes had 12, 13).

Nevertheless, when adding the second nodepool on a different subnet, it shouldn't validate the the first nodepool and fail, right? That defeats the purpose of multiple nodepools on different subnets, i guess.

I can give you more insights on this if you want.

**Comment by MageshSrinivasulu** [comment]
I am too facing a similar issue. There is an unnecessary validation happening over a different subnet.

Let's take two subnets for example. 

- aks ( having enough ip) 
- aks_dmz ( not having enough ip)

If I try to create a new node pool using the **aks** subnet. There is unnecessary validation is being performed over **aks_dms** subnet and the cluster creation is failing. This is becoming a pain while doing cluster maintenance. **aks_dmz** can run out of ip because of cluster auto-scaling but why is it being considered during cluster creation with a **aks** subnet?

**Comment by paulgmiller** [comment]
@mracfa rafca @MageshSrinivasulu I can confirm that we do validate all nodepools on an agentpool operation mostly because historically they were shared so we have to check them but you're right we need not necessarily fail. 
I am really curious how you got into such a failed state though. @mracfa  indicated some machines did not have all their secondary ips. Were they in a failed state?  If you willing to give more cluster details to pmiller@microsoft.com I can maybe hunt this down and we'll look at if we can free individual nodepools from being blocked by others.

**Comment by MageshSrinivasulu** [comment]
@paulgmiller Hey paul, I have dropped you a detailed mail with the support ticket as well. Please do let me know if you need more details on this.
