### ISSUE TITLE
Nodepool taint update is not working

### ISSUE THREAD

**Issue by Krupakarreddin** [Azure/AKS#2870]
Node taints are not getting updated on existing node pool. Tried thru ARM template. Its reflecting in portal but if we do `kubectl describe node <nodename >`
taints are not available.
**Scope**:- updating taints on  existing node pool
Taints gets relflected only during the creation of node pool

**Comment by Xinyue-Wang** [comment]
Hi @[Krupakarreddin](https://github.com/Krupakarreddin), thanks for bringing up this issue. 
We temporarily disabled node pool taint update feature due to a livesite incident. But now we have started to re-enable this feature now, it has already been in eastus2euap, centraluseuap, westcentral us regions.
And if you need it urgent, you can try to update the taints and reimage your nodes. Then taints on nodes will be updated.
Sorry for any inconvenience.

**Comment by nzarhin** [comment]
Hi, @Xinyue-Wang , can you pls kindly share the re-enable timeline.. We are on open ticket with MS support waiting to implement in WestUS2.

**Comment by Xinyue-Wang** [comment]
@nzarhin we have enabled editing taints in westus2 now.

**Comment by Krupakarreddin** [comment]
@Xinyue-Wang Can you enable it on West Europe pleaase

**Comment by JRolfe-Gen** [comment]
Why does this take so long to resolve?

**Comment by Xinyue-Wang** [comment]
@JRolfe-Gen  Hi, the nodepool taint update has been enabled. I will resolve this issue
