### ISSUE TITLE
CVE-2018-25032 

### ISSUE THREAD

**Issue by westrope** [Azure/AKS#2900]
Our Ubuntu AKS Clusters are being flagged for CVE-2018-25032:
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-25032

Which can be fixed by upgrading the zlib package:
https://lists.debian.org/debian-security-announce/2022/msg00079.html

Can this be fixed by the AKS team?

**Comment by CocoWang-wql** [comment]
The patch was released in (1:1.2.11.dfsg-0ubuntu2.1). 
![image](https://user-images.githubusercontent.com/45681473/163705824-f587c219-44d3-43f2-a1e4-dd46b63cb099.png)

Since 2022.04.05 AgentBaker, we are using (1:1.2.11.dfsg-0ubuntu2.1). 
![image](https://user-images.githubusercontent.com/45681473/163705958-45e5f573-98dc-429b-9ae9-9ef6d5f08036.png)
[2022.04.05.txt](https://github.com/Azure/AgentBaker/blob/master/vhdbuilder/release-notes/AKSUbuntu/gen1/1804/2022.04.05.txt)

The 2022.04.05 AgentBaker should be released soon as planned. Please check https://github.com/Azure/AKS/releases to follow the image update.
