### ISSUE TITLE
ARM/Bicep deployment does not remove Azure Policy add-on

### ISSUE THREAD

**Issue by fschmied** [Azure/AKS#2904]
**What happened**: We have an existing AKS cluster. We added and enabled the Azure Policy add-on via the _Defender for Containers provisioning Azure Policy Addon for Kubernetes_ Azure Policy Assignment. We later removed that Policy Assignment, but the Azure Policy add-on of course remained present and enabled.

We then redeployed the AKS cluster using the original Bicep file, which did not list the `azurepolicy` add-on under `addonProfiles`:

```
    addonProfiles: {
      omsagent: {
        enabled: true
        config: {
          logAnalyticsWorkspaceResourceID: logAnalyticsWorkspaceId
        }
      }
    }
```

Yet, the Azure Policy add-on still remained present and enabled on the cluster.

**What you expected to happen**: I expected the AKS cluster to be adapted to match the Bicep resource definition. I.e., I expected the `azurepolicy` addonProfile to be removed because it was not listed in the Bicep file.

**How to reproduce it (as minimally and precisely as possible)**:
* Create an AKS cluster without the `azurepolicy` add-on.
* Enable the add-on via the Portal (under "Policies").
* Wait and note that the Azure Policy add-on is configured and enabled on the cluster.
* Export an ARM file for the cluster. Note that it contains the `azurepolicy` under `addonProfiles`.
* Remove the `azurepolicy` add-on entry from `addonProfiles` in the ARM file.
* Redeploy the ARM file.
* Note that the `azurepolicy` add-on remains present and enabled, it was not removed in the previous step.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.22.6

**Comment by matthchr** [comment]
This is a limitation of the current AKS API implementation, where PUT has merge semantics. This means you can't just remove something from the API (as then the merge semantics kick in). The workaround is to explicitly set the addon `enabled: false`, rather than just removing it. That should correctly disable the addon.

We're talking about ways to update this behavior in the future to be more intuitive (and work better with policy), but those conversations are ongoing.

**Comment by fschmied** [comment]
Okay, thanks for the information!
