### ISSUE TITLE
Upgrade only AKS control plane via ARM

### ISSUE THREAD

**Issue by jabbera** [Azure/AKS#2905]
**What happened**:

Triggering an upgrade via arm by setting managedClusters.properties.kubernetesVersion causes all node pools to upgrade. I'd prefer my nodepools to stay on their current version assuming they are no more then 2 minor versions behind the control plane. This is possible via az cli.

Note: This question was asked here as well with no good answer: https://docs.microsoft.com/en-us/answers/questions/759713/aks-upgrade-with-arm-template.html

**Comment by miwithro** [comment]
@kaarthis

**Comment by asos-philc** [comment]
The behaviour I'm currently seeing is nodepools *not* being upgraded when an upgrade is triggered by managedClusters.properties.kubernetesVersion in the ARM template.

This appears to be a change in behaviour and is causing issues across the cluster estate I help to manage because this method was being relied on to upgrade node pools.

Some clarity around this area would be greatly appreciated...

**Comment by palma21** [comment]
I think you're referring to this?
https://github.com/Azure/AKS/blob/master/CHANGELOG.md#release-2022-03-27

**Comment by jabbera** [comment]
> I think you're referring to this?
> 
> https://github.com/Azure/AKS/blob/master/CHANGELOG.md#release-2022-03-27

Looks like you were ahead of me! Thanks.
