### ISSUE TITLE
Add support for AKS Public API ServiceTag 

### ISSUE THREAD

**Issue by Borrelworst** [Azure/AKS#2931]
### Feature Request

**What happened**:
When having an AKS cluster behind a firewall and have an egress rule 0.0.0.0/0 to the firewall, API connectivity is not working if you only have application rules in Azure Firewall. Even when you already have an application outbound rule *:443, you still need a network rule for the API to become reachable.

To make it work you have to add the IP or FQDN to the firewall as a net rule. However, in case you are regularly deploying new clusters in the environment, you have to add the IP/FQDN every time a new cluster is deployed. In case you have a shared environment (as we have) and are not responsible for the firewall (as this is the responsibility of another team), this not an ideal situation. What would be really convenient is when the AKS public IPs can be mentioned as a ServiceTag instead of specifying it separately for every cluster. 

A net rule with *:443 would also work, but then you loose all SNI header information in the firewall logging (hence you are not seeing actual addresses anymore).

**How to workaround the issue**:
With all the testing so far I did found a workaround for the issue, however this is not really recommended as you will need to deploy a public loadbalancer. We do not need a public loadbalancer and therefore this is not a solution for us, but if you are allowed to use a public loadbalancer, and you are behind an Azure Firewall, you can solve it like so:

1. Deploy an AKS cluster with UDR and 0.0.0.0/0 to the Azure Firewall
2. Deploy a service in the cluster with type LoadBalancer
3. When the LoadBalancer is created in Azure, create an outbound rule on the loadbalancer to route node traffic to the loadbalancer
4. On the UDR, add an additional rule with:
  a. Source IP = Master API IP address
  b. Next Hop = Internet

Now your nodes are reaching the API via de Public Loadbalancer created in the cluster. However, you are bypassing the API traffic from the Firewall. 

In our case, we are now solving it by running a script once a day to add the newly created AKS clusters to the firewall. If there is a ServiceTag for the AKS API Public IP, it would be easy to implement in Azure Firewall as you would only need 1 rule in the Firewall to make it work for all clusters and it would also directly work once a new AKS cluster is created.

**Comment by phealy** [comment]
Unfortunately, due to architectural requirements we're under at this time, we can't currently add customer API server addresses to a service tag. However, there may be an alternate solution that works just as well for what you need.

A question here: are you having trouble reaching the API server from applications in your cluster, using the in-cluster configuration? If so, you're running into the same issue as #2775: the API server endpoint variable KUBERNETES_SERVICE_HOST is by default set to the IP address of the API server endpoint instead of the hostname, and so it doesn't match the application rules because there's no hostname to match.

The easy fix for this is to use the API server hostname, which will then match the application rules already part of the AzureKubernetesService FQDN tag. I've copied part of my comment below - as of about a month ago, we have a webhook that can modify your pod environment variables to include the API server hostname instead. You need to add an annotation to your pods (in the template pod spec of your deployment) to indicate you want this done, but it should resolve the rule matching problem for you.

> AKS already has a webhook that we use to modify our `kube-system` pods to force them to use the cluster FQDN/L7. I implemented a small change to that webhook so that it will also modify any pod with the annotation `kubernetes.azure.com/set-kube-service-host-fqdn` applied to it (with any value; even an `""` empty string is good enough). This should provide you with a built-in solution that will work well. I expect that change to be in the `2022-07-17` release. Take a look at the [release notes page](https://github.com/Azure/AKS/releases) for more details once those notes are announced.

Does this resolve the issue for you?
