### ISSUE TITLE
[Question] Postpone upgrades until the next maintenance window when the best-effort maintenance is skipped

### ISSUE THREAD

**Issue by marcindulak** [Azure/AKS#2962]
The goal of this issue is to motivate a clarification of the behavior of planned maintenances, their current limitations, and how they interact with [automatic upgrades](https://docs.microsoft.com/en-us/azure/aks/upgrade-cluster#set-auto-upgrade-channel). Please feel free to open a more appropriate roadmap issue to track the features of a planned maintenance, which follow from this issue.

I believe a common expectation from a planned maintenance is that it happens at the specified time, not some other time, unless explicitly allowed, and includes the operations that were scheduled for the maintenance. The tentative list of scheduled operations is also typically expected to be known in advance. 

The current planned maintenance [limitations](https://docs.microsoft.com/en-us/azure/aks/planned-maintenance#limitations) include the following points

```
1. AKS reserves the right to break these windows for unplanned/reactive
maintenance operations that are urgent or critical.

2. Currently, performing maintenance operations are considered best-effort only and
are not guaranteed to occur within a specified window.

3. Updates cannot be blocked for more than seven days.
```

Question 1: 
Would an "unplanned/reactive" operation from the first point be also applied if no planned maintenance is configured by the customer? What are examples of such operations?

Question 2:
In https://github.com/Azure/AKS/issues/2014#issuecomment-1066770477 the following case is described 

```
... The configured maintenance window (Thursday 2-3 am UTC) seems to not have any effect as
the cluster just updates nodes during daytime like today ...
```

Is this an example of the 2nd point above? If yes, would it be possible to have the upgrades scheduled for the given day explicitly dropped, since the best-effort maintenance was skipped? The upgrades would be postponed until the next scheduled planned maintenance.

Question 3:
What happens to the upgrades (updates?) blocked for seven days? Are they abandoned and new upgrades are scheduled for the next maintenance window, are the upgrades force-applied in the last 24 hours of the seventh day?

Additionally, it may be already the case, but please keep the wording "updates" vs "upgrades" consistent, and provide references to operations which are considered upgrades or updates.

**Comment by marcindulak** [comment]
:eyes:

**Comment by marcindulak** [comment]
:eyes:

**Comment by kaarthis** [comment]
Question 1:
Would an "unplanned/reactive" operation from the first point be also applied if no planned maintenance is configured by the customer? What are examples of such operations?


These are essentially super corner cases which should typically not happen (I have not seen this happen over the last year) . These maybe Infra issues (undetermined). 

Question 2:
In https://github.com/Azure/AKS/issues/2014#issuecomment-1066770477 the following case is described

... The configured maintenance window (Thursday 2-3 am UTC) seems to not have any effect as
the cluster just updates nodes during daytime like today ...
Is this an example of the 2nd point above? If yes, would it be possible to have the upgrades scheduled for the given day explicitly dropped, since the best-effort maintenance was skipped? The upgrades would be postponed until the next scheduled planned maintenance.

For auto upgrades (Upgrader) based on internal testing,  can take upto a day (Ideally few hours) from the window start to effect . This will be documented as a limitation / things to note in the public docs soon.  We shall work to improve the timelines here in future. 

Question 3:
What happens to the upgrades (updates?) blocked for seven days? Are they abandoned and new upgrades are scheduled for the next maintenance window, are the upgrades force-applied in the last 24 hours of the seventh day? Typically the updates happen by region so if after 7 days a new version becomes available that will be applied. https://releases.aks.azure.com/webpage/index.html
