### ISSUE TITLE
Cloud configuration for container log rotation - K8S cluster

### ISSUE THREAD

**Issue by darkprisco** [Azure/AKS#299]
Hi, 
 I would like to know if it is possible to configure in such way the information I can find in:
/etc/docker/

![1](https://user-images.githubusercontent.com/22886636/38628690-86f6bc8e-3da1-11e8-991a-cbe88526f785.png)

Honestly I didn't get if this is something configurable or not.
Microsoft support said me that this is a feature currently not present  and they have suggested me to raise an issue here.

I didn't get also why on another resource group I have found a different configuration.
I think this is not good, because on another resource group I found this:

![2](https://user-images.githubusercontent.com/22886636/38628950-3172e0de-3da2-11e8-9a50-a28f7e74a895.png)

And you can imagine that with this kind of configuration (not set by me) multiple containers potentially can fill the whole disk in few time. (5GB * container)

Tks
Prisco

**Comment by slack** [comment]
We are working on shipping control plane logs to Azure Monitor, which should be available late June.

If you would like logs/metrics from your applications, you can use any existing monitoring tool: Sysdig, Datadog, ELK, TICK, etc. Or Log Analytics from Microsoft: https://docs.microsoft.com/en-us/azure/aks/tutorial-kubernetes-monitor

**Comment by slack** [comment]
To the point about configuring or controlling per-container docker logs, we don't have anything in the backlog at this time.

**Comment by branstraub** [comment]
Hi @DaveAurionix, did you found a way to reduce a limit to other than 5gb? I'm facing a similar issue with an AKS deployment. Thanks :)

**Comment by DaveAurionix** [comment]
@branstraub Sorry, no, mostly due to time pressure.  I was also reluctant to dig too deep and stray from the beaten path by tuning Docker configuration that is managed by AKS.  I was hoping Microsoft would tune the AKS defaults or expose a high-level configuration value in the ARM template JSON for the AKS cluster.

In the end we increased the size of the disks used by our VMs so we're less concerned for now, but are paying a little more as a result.

We are also performing automated controlled drains+reboots of the nodes twice per week which means that pods are shut down and moved around at least every 4 days, so we're (hopefully) not likely to accumulate huge sets of logs (they are deleted when the pod is I believe).

I'd rather that this was an easily-configurable setting across the cluster though.  It doesn't need to be per-container, per-pod or even pod-node.

**Comment by jnoller** [comment]
Closing as stale/solved
