### ISSUE TITLE
Enabling AGIC addon via Azure Portal doesn't add required permissions for AppGw managed identity over vnet scope 

### ISSUE THREAD

**Issue by kamilzzz** [Azure/AKS#3031]
**What happened**: 

Enabling AGIC addon via Azure Portal resulted in warning message stating that Application Gateway has not been created yet and it may take up to 15 minutes.
After 30+ minutes the warning remained the same and the Application Gateway wasn't created.
Looking at the appgw-ingress pod inside cluster I found out it doesn't have required permissions over vnet:

> client.go:352] Error while getting virtual network 'vnet-lab001-XXX': network.VirtualNetworksClient#Get: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client 'cdd02f05-6f92-4d68-97a2-794154487838' with object id 'cdd02f05-6f92-4d68-97a2-794154487838' does not have authorization to perform action 'Microsoft.Network/virtualNetworks/read' over scope '/subscriptions/XXX/resourceGroups/aks/providers/Microsoft.Network/virtualNetworks/vnet-lab001-XXX' or the scope is invalid. If access was recently granted, please refresh your credentials."

After granting contributor access to Application Gateway managed identity manually, the Application Gateway has been createed successfully.

**What you expected to happen**:
AGIC addon to be enabled successfully.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create AKS cluster with user assigned identity, using kubenet network plugin and bring your own subnet & route table.
2. Enable AGIC addon via Azure Portal
3. Application gateway won't be created until you assign roles to newly create managed identity manually.

**Anything else we need to know?**:
1. AKS cluster is using kubenet network plugin with bring your own subnet & bring your own route table has been created via Bicep template.
2. AKS cluster is using user assigned managed identity with Contributor role granted over vnet and route table.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.22.6
- Size of cluster (how many worker nodes are in the cluster?) 2 nodes
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) 
- Others:

**Comment by raghulmsft** [comment]
@kamilzzz : We are investigating this right now and we need a couple more information from you to help with the process. 

Can you provide us with:

- The subscription ID used when you ran into the issue
- A rough timeline on when you tried this actions so we can query our logs for that period
- The cluster Id of the cluster you had this issue with

Thanks!

**Comment by Shark** [comment]
@raghulmsft I currently experience the same issue. How can I share the information you requested privately?
Thanks for your help!

**Comment by raghulmsft** [comment]
@Shark : You can email me at rethiraj@microsoft.com!

**Comment by JS-GERVAIS** [comment]
Having the same issue in a fresh cluster, 1.24.6 with one node pool  (dev cluster).  Using CNI instead of kubenet. 

 ingress-appgw-deployment pod in kube-system is restarting hundred times a day, and spams this log

E1005 20:19:16.104600       1 client.go:352] Error while getting virtual network 'XXXXXXXXXXdev-vnet': network.VirtualNetworksClient#Get: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '1eb856f5-b1b8-4708-a57c-eb5c36a0eb1c' with object id '1eb856f5-b1b8-4708-a57c-eb5c36a0eb1c' does not have authorization to perform action 'Microsoft.Network/virtualNetworks/read' over scope '/subscriptions/4864705f-11a3-457b-ad12-b1544ad65f06/resourceGroups/XXXXXXXXXX_dev/providers/Microsoft.Network/virtualNetworks/XXXXXXXXXXdev-vnet' or the scope is invalid. If access was recently granted, please refresh your credentials."

The managed identity has the read access scope on the vnet

**Comment by nanunna** [comment]
@JS-GERVAIS  Could you pls answer the below questions to help us troubleshoot this issue further ?

- Did you also use your own vent & route table for the cluster ? 
- Are you using managed identities or user-managed identities (Service principal) ?
- What role does the cluster identity has ? Contributor role or Read role over vnet & route table
- did you initially use the app-gw in a different vnet for ingress controller ?

Thanks

**Comment by chandraneel** [comment]
Closing the bug due to lack of response.  Please feel free to activate this later point in time
