### ISSUE TITLE
Built-in default Pod Topology Spread constraints for AKS

### ISSUE THREAD

**Issue by iqsarv** [Azure/AKS#3036]
**Scenario**
We are trying to make sure that the pods are spread evenly across the zones without any skew towards selected zones.

**Question**
According to https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/#internal-default-constraints, the built in defaults allow for maxSkew: 5. Is it different for AKS? How can we check the default constraints?

Also, what does it mean to allow a skew of 5? Please help with an example

**Comment by DazRomance** [comment]
Hi, 

With the upcoming end of support for AKS 1.22 I have several clusters to upgrade from 1.22 to 1.23 but ideally and would like to go up to 1.24.
However since 1.24 introduces a fix to the skew calculations (https://github.com/kubernetes/kubernetes/pull/107009) I need to know if the default constraints  on AKS are the same as in the docs linked by @iqsarv or if they are different somehow.

Is there a way to see the current applied constraints ? Or can someone from MS disclose the information ?

**Comment by varora24** [comment]
Hi,
Yes, AKS does follow the Kubernetes defaults as outlined in the [docs](https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/#internal-default-constraints). Currently, this is managed by AKS and cannot be customised at a cluster level. You can however, override the cluster level default by specifying spread at a pod level incase you require a different skew.
We have a workstream in progress to investigate changing these values and making them customizable in the future. 
Hope this helps!

**Comment by varora24** [comment]
Closing as the ask is same as Feature Request #3056
