### ISSUE TITLE
Logging level to be disabled by default. 

### ISSUE THREAD

**Issue by upasedharmaraj** [Azure/AKS#3134]
**What happened**:
Currently, AKS logging level is set to std out enabled for all namespaces, this causes lot of log ingestions and icreases total bill. 

**What you expected to happen**:
AKS logging should be kept to error only by default and configured on demand using custom config map. 
https://docs.microsoft.com/en-us/azure/azure-monitor/containers/container-insights-agent-config

**How to reproduce it (as minimally and precisely as possible)**:
3 TB logging ingestion for 90 days happens when: 
- there are more than 10 nodes available in your cluster. 
- there is load on system

**Environment**:
- Kubernetes version : AKS 1.23.5
- Size of cluster : 5-10

**Comment by MarkTopping** [comment]
Hey @upasedharmaraj 

I figured I'd just share with you my experience here.... when I configured the OMS Agent to only export stderr logs I still found the ingestion levels to be quite high (less of course, but still far higher than I expected). When I dug a little deeper I found that many K8s components were logging 'info' level logs to stderr instead of stdout. I think (IIRC) this was due to the use of some library being used in many K8s components which simply funnelled all logs to stderr. Pretty rubbish really when you're trying to capture errors while reducing noise and cost :(

**Comment by vdiec** [comment]
Hi @upasedharmaraj, this is an issue we are aware of and will be fixing. I will reply back here when the fix is rolled out. Thanks!

**Comment by vdiec** [comment]
Hi @upasedharmaraj, please see instructions [here](https://learn.microsoft.com/en-us/azure/azure-monitor/containers/container-insights-agent-config) on how to edit the ConfigMap file settings to only collect logs from stdout.

**Comment by vdiec** [comment]
Hi @upasedharmaraj , please see instructions [here](https://learn.microsoft.com/en-us/azure/azure-monitor/containers/container-insights-agent-config) on how to edit the ConfigMap file settings to collect stdout logs from specific namespaces.  We will not be changing the default behavior since many customers are using it.
