### ISSUE TITLE
[BUG] DHCP Issues leading to DNS resolving problems

### ISSUE THREAD

**Issue by slynickel** [Azure/AKS#3162]
**Describe the bug**

We are experiencing this in two AKS clusters, in different Azure regions in our fleet of more than 100. Made a MSFT ticket as well but creating something here to see if we are alone.

We are finding a few AKS node VMs don't end up with DHCP leases. The most impactful result of this is that `/etc/resolv.conf` looks like this. 

```
user@aks-nodepool-######-vmss000001:~$ cat /etc/resolv.conf
# This file is managed by man:systemd-resolved(8). Do not edit.
#
# This is a dynamic resolv.conf file for connecting local clients directly to
# all known uplink DNS servers. This file lists all configured search domains.
#
# Third party programs must not access this file directly, but only through the
# symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a different way,
# replace this symlink by a static file or a different symlink.
#
# See man:systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

# No DNS servers known.
```

More specifically if you run ` netplan ip  leases eth0` you will find there is no lease and as result no DNS resolver info for the VMSS agent VM.

Downstream impacts are:
1. DNS resolution on the VM doesn't work since there are no name servers.
2. If coredns ends up a node that doesn't have lease or DNS configuration it will crashloop since the forward plugin doesn't work.
3. If you need to pull external images from something that isn't cached on the node the image pull will fail since DNS resolution will fail.

Notable, as long as coredns starts somewhere most pods will be fine since coredns running on other nodes will respond to pod level DNS queries.

**To Reproduce**

Unclear how to get into this state. 

**Expected behavior**

DNS resolution to work.

**Screenshots**

See above.

**Environment (please complete the following information):**
- Kubernetes version: 1.23.5
- Node image version: AKSUbuntu-1804gen2containerd-2022.07.04
- Kernel version: 5.4.0-1089-azure

**Additional context**

Made a MSFT ticket about this already. DHCP is pretty low level stuff and making changes to it to try and fix it would likely break our AKS support policy stuff.

**Comment by holophil** [comment]
@slynickel Have you seen the note about the "emerging issue under Investigation" on the portals [service health dashboard](https://portal.azure.com/#view/Microsoft_Azure_Health/AzureHealthBrowseBlade/~/serviceIssues)? 

it states:

`Azure customers running Canonical Ubuntu 18.04 experiencing DNS errors - Investigating
Starting at approximately 06:00 UTC on 30 Aug 2022, a number of customers running Ubuntu 18.04 (bionic) VMs recently upgraded to systemd version 237-3ubuntu10.54 reported experiencing DNS errors when trying to access their resources. Reports of this issue are confined to this single Ubuntu version. This bug and a potential fix have been highlighted on the Canonical / Ubuntu site, which we encourage impacted customers to read: https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1988119 An additional potential workaround customers can consider is to reboot impacted VM instances so that they receive a fresh DHCP lease and new DNS resolver(s). If you are running a VM with Ubuntu 18.04 image, and you are experiencing connectivity issues, we recommend you evaluate the above mitigation options. If you are not experiencing impact on your Ubuntu 18.04 images, but you have unattended security updates enabled, we recommend you review this setting until the Ubuntu issue is mitigated. The next update will be provided in 6 hours, or as events warrant.`

For us draining nodes and restarting them helped to mitigate the issue.

**Comment by slynickel** [comment]
Ah, good call. We have all sort of alerting setup for service health alerts but not "emerging issues". Given what we see in DHCP we expected this to be the way to mitigate. 

I'm going to close this since the eventual service health alert will probably be the thing folks should track.
