### ISSUE TITLE
Failed to upgrade kubernetes service

### ISSUE THREAD

**Issue by smartaquarius10** [Azure/AKS#3221]
Team,

We have VMAS type AKS with 1 node pool having 7 working nodes and 1 spare which helps us at the time of upgrade. Networking type is Azure CNI. Currently, we are on 1.23.5 version and trying to upgrade (Control plane+all node pools.. VMAS allows only this option) to version 1.23.8 but getting this error regularly:

![image](https://user-images.githubusercontent.com/7824529/191415569-75e76e50-e365-43c0-a1ee-b4fa63a5d98c.png)

Per node, max 30 pod is set and in total we have 102 pods in our AKS environment. The VNET cidr is /20 and subnet cidr is /24.

We have just reduced the replica value to 0 in 10 deployments which brings the pod count to 92 but still the available ip's in the subnet is same as it is before reducing the replica count which is obvious because nodes keep the ip addresses:

![image](https://user-images.githubusercontent.com/7824529/191416431-e9311629-9ef9-4b29-9e3f-59b37a51d552.png)

Ideally we should have 30x8 +3= 243 ips but AKS is not allowing us to upgrade with just 92 pod count 

Kindly suggest some resolution as it is impacting our environment. 

Regards,
Tanul

**Comment by carvido1** [comment]
Hello @smartaquarius10 
Can you tell us if you are usign Kubenet or CNI? As per information given, I can guess you are using CNI, that's why you have allocated private IP addresses belonging to that subnet.

From azure, we have the following article that can be insightful, [Configure Azure CNI networking in Azure Kubernetes Service (AKS)](https://learn.microsoft.com/en-us/azure/aks/configure-azure-cni).
Here it says that the equation to calculate the subnet is the following:

```
(number of nodes + 1) + ((number of nodes + 1) * maximum pods per node that you configure)
```

On your case, this is `(7+1) + ((7+1)*30) = 248`. This number fits on your subnet design.

At the beginning of the issue explanation, you have mentioned also a spare node using during the upgrade. Is this a node you create by scaling out the cluster ? I'm asking this because when you do an AKS upgrade, the previous equation already takes into account a temporal node that gets created to help with the upgrade, therefore if you add an extra node before the upgrade the equation will be `(8+1) + ((8+1)*30) = 279` which exceeds the subnet allocation.

Hope this helps you to understand the upgrade process.

BR

**Comment by smartaquarius10** [comment]
@carvido1, Yes we have Azure CNI. 

So basically when we have designed everything around 4 years back our azure architect created the AKS with manual scaling of 8 nodes. 

So what we thought is use 7 nodes for our work and keep 1 count aside and never use it so that whenever we initiate the upgrade, AKS will scaled that count and use the extra node as a temporary node. 

As shown in the node pool image below currently the value is 7. We never change it to 8 but keep that as buffer for AKS. Basically that was our understanding regarding AKS upgrading. 

![image](https://user-images.githubusercontent.com/7824529/191442751-87aba10c-c87d-44e2-ab91-5d10e63f4af9.png)

We never scale up anything or touch this value before upgrades. still error is coming 

The main problem is that we have upgraded to 5 different versions last month only and never faced this situation. We were on 1.19.3 and jumped one by one to 1.23.5. I don't know why this is coming now. Subnet cidr is same VNet cidr, node count is same. In short, everything is same. But never faced this situation in upgradation till last month.

**Comment by smartaquarius10** [comment]
@carvido1, We have tried downscaling the nodes to 6 but still the same error and with different numbers..  Now 186 count is coming rather than 248. Neither its allowing us to scale down or scale up.

![image](https://user-images.githubusercontent.com/7824529/191456074-1be14fc9-d621-4c08-9017-b94152a7538c.png)

**Comment by carvido1** [comment]
Hello @smartaquarius10 .

We have a cluster working with nodepools instead of the VMSS. I have checked the`Max surge definition` for the nodepool and it can not be changed. We don't use CNI for this cluster.

Can you double check the max Pods per node property for the nodepool ?
Also, can you check if any other deployment is present on the cluster ?
Can you check the number of pods running in your cluster ? You can use this command which will output them sorted by the node they are scheduled:

```bash
kubectl get pods -A -o wide --sort-by=.spec.nodeName
```

It is possible that after an AKS upgrade newer pods were introduced by Azure, for instance the pods for the CSI. You can check this using:

```bash
kubectl get daemonset -n kube-system | grep csi
```

If you don't use the CSI drivers[ you can disable them](https://learn.microsoft.com/en-gb/azure/aks/csi-storage-drivers#disable-csi-storage-drivers-on-a-new-cluster), as a [feature to do so was released this month](https://github.com/Azure/AKS/releases/tag/2022-09-11).

If this does not help, maybe the unique approach is to scale down everything to the minimum (deployments, remove daemonsets ...) scale the cluster to 1 and try the upgrade and scale out again... Your case is quite strange and we never faced something similar.

Hope this gives some light to your problem.
BR

**Comment by smartaquarius10** [comment]
@carvido1, 
1. Max pods per node is 30
2. Deployments(including Microsoft and my company workload):- 8 belonging to AKS and 33 our application
3. Daemonsets(including Microsoft and my company workload):- 11 related to AKS and 1 is of prisma cloud
4. Number of pods :- 102
     - Node 1:- 15
     - Node 2:- 12
     - Node 3:- 15
     - Node 4:- 15
     - Node 5:- 14
     - Node 6:- 15
     - Node 7:- 16

But the strange thing I have just observed is on 18th of June we have upgraded are cluster to 1.22.6 from 1.19.13. And if you see these screenshots, these dameon sets and storage classes are exactly 96 days old.. We have never created them and we don't know anything about them at all. Do you want me to delete all of them. If yes then how should I delete them?

![image](https://user-images.githubusercontent.com/7824529/191495725-13ad2830-dfd8-4f41-aa86-6e67e12ab744.png)

![image](https://user-images.githubusercontent.com/7824529/191495737-78110081-fe69-42da-adb2-6f3766373a04.png)

**Comment by carvido1** [comment]
Hello @smartaquarius10 

CSI driver was [announced in April](https://github.com/Azure/AKS/releases/tag/2021-04-22) that it will be default storage driver. In July this year, they released it to all Kubernetes clusters with versinon >= 1.21. 

As you can see on the `default (default)` and `default-retain` storage classes, the provisioner is still the `kubernetes.io/azure-disk`. I would give a try to disable the CSI driver and try the upgrade then.

If the scale option is not working properly and disabling the CSI driver does not help, perhaps is a moment to open a ticket in Microsoft Azure Support.

Best regards.

**Comment by smartaquarius10** [comment]
@carvido1, Sure.. I will try disabling the CSI driver as they are on no use to me. A ticket with microsoft is already open. The problem is that even if scale down approach works in lower environment still it seems to be a super risky approach in production.

**Comment by smartaquarius10** [comment]
@carvido1 , Do we have to pass all these options for disabling CSI

`--disable-disk-driver --disable-file-driver --disable-snapshot-controller `

My prisma cloud is using default-retain and tagged with the persistent volume. Disabling all these options will not impact the old and existing volume right?

**Comment by carvido1** [comment]
Hello @smartaquarius10 
If you want to disable the CSI driver you have to disable the three features.
You can enable them after upgrading the cluster, if it works...

Let me know how if this approach works for you.

**Comment by smartaquarius10** [comment]
@carvido1, Sure.. But, I got a response from Microsoft support team that this is the backend issue coming for multiple subscriptions in VMAS clusters. Microsoft is working on its resolution but they haven't share any timeline yet. Support team is following up with the product teams.

**Comment by carvido1** [comment]
Hello @smartaquarius10 
Do you have any news from the MS support team ?

**Comment by smartaquarius10** [comment]
@carvido1, Asked yesterday, they are still working on it.

**Comment by smartaquarius10** [comment]
@carvido1 , Its resolved now.
