### ISSUE TITLE
Deployment issue with Flux [BUG] 

### ISSUE THREAD

**Issue by gertkjerslev** [Azure/AKS#3233]
When deploying AKS cluster with the flux extention the flux part of the deployment fails.

**To Reproduce**
flux.bicep

```
param clusterName string

resource aks 'Microsoft.ContainerService/managedClusters@2021-10-01' existing = {
  name: clusterName
}

resource flux 'Microsoft.KubernetesConfiguration/extensions@2022-03-01' = {
  name: 'flux'
  scope: aks
  properties: {
    extensionType: 'microsoft.flux'
    scope: {
      cluster: {
        releaseNamespace: 'flux-system'
      }
    }
    autoUpgradeMinorVersion: true
    releaseTrain: 'Stable'
  }
}
```

Error after [7m58s]
```
{"code":"DeploymentFailed","message":"At least one resource deployment operation 
failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage 
details.","details":[{"code":"ExtensionOperationFailed","message":"The extension operation failed with the
 following error:  Error: {failed to install chart from path [] for release [flux]: err [release flux failed, 
 and has been uninstalled due to atomic being set: 
 Get \"https://name.hcp.westeurope.azmk8s.io:443/apis/apiextensions.k8s.io/v1/customresourcedefinitions/fluxconfigs.clusterconfig.azure.com\": 
 dial tcp ip-here:443: connect: connection refused]} 
occurred while doing the operation : {Installing the extension} on the config."}]}
```

**Environment (please complete the following information):**
 -  Bicep CLI version 0.9.1
 - Kubernetes version 1.24.0

**Additional context**
Seems to work with kubernetes version 1.23.8, but the could be a coincidence..?

**Comment by gertkjerslev** [comment]
The issue persists with version 1.23.8, but more random.

**Comment by ReneRebsdorf** [comment]
ip-here:443 doesn't look right :)

**Comment by MariusStorhaug** [comment]
Any update on this?

**Comment by prabhumathiyalagan** [comment]
I'm facing the same issue with AKS version 1.23.12
`az k8s-extension update --configuration-settings multiTenancy.enforce=false -g test-rg -c test-ask -n flux -t managedClusters --yes

(ExtensionOperationFailed) The extension operation failed with the following error:  Error: {Helm installation from path [] for release [flux] failed with the following error: err [release flux failed, and has been uninstalled due to atomic being set: timed out waiting for the condition]} occurred while doing the operation : {Installing the extension} on the config.
Code: ExtensionOperationFailed
Message: The extension operation failed with the following error:  Error: {Helm installation from path [] for release [flux] failed with the following error: err [release flux failed, and has been uninstalled due to atomic being set: timed out waiting for the condition]} occurred while doing the operation : {Installing the extension} on the config.`

It is not creating cluster config without this update

**Comment by ReneRebsdorf** [comment]
Coming closer to the 1 year birthday on this ticket and zero response despite the many tags of the bot :-(

**Comment by gertkjerslev** [comment]
I have done some deployment in the last weeks and it seems that the issue is the system pool "VM" SKU needs to be at least "Standard_D2" The B-series will not allow for FluxCD to be installed in time.

**Comment by gertkjerslev** [comment]
I think we can close this now :-)
