### ISSUE TITLE
[Question] Why does the Azure Kubernetes Service RBAC Reader role not allow viewing node resources?

### ISSUE THREAD

**Issue by fschmied** [Azure/AKS#3336]
Users assigned the "Azure Kubernetes Service RBAC Reader" currently cannot view node resources (e.g., via kubectl, or in the Azure Portal). See the [role definition](https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#azure-kubernetes-service-rbac-reader), which does not contain a _dataAction_ related to nodes.

Why is that? And if I wanted to define my own role instead, what _dataActions_ would I need to grant?

**Comment by sabbour** [comment]
Can you try:

```
"dataActions": [

     "Microsoft.ContainerService/managedClusters/nodes/read"

]
```

**Comment by fschmied** [comment]
We ended up with manually adding the data actions `Microsoft.ContainerService/managedClusters/nodes/read` and also `Microsoft.ContainerService/managedClusters/metrics.k8s.io/nodes/read`.

I'm still wondering why this isn't included with the `Azure Kubernetes Service RBAC Reader` role by default?

**Comment by CocoWang-wql** [comment]
This [reader role](https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#azure-kubernetes-service-rbac-reader) is designed for the components running on aks cluster instead of the azure resources. That's why there is no node reader in data action. If the [Azure built-in roles](https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles) don't meet the specific needs of your organization, you can create your own custom roles.

**Comment by fschmied** [comment]
Okay, thanks for the answer.
