### ISSUE TITLE
[BUG] AKS Node Image Version is null

### ISSUE THREAD

**Issue by alextadams88** [Azure/AKS#3342]
**Describe the bug**
[The documentation](https://learn.microsoft.com/en-us/azure/aks/node-image-upgrade#check-if-your-node-pool-is-on-the-latest-node-image) states that in order to view the current image version of your AKS node, you should execute the command `az aks nodepool show --resource-group myResourceGroup --cluster-name myAKSCluster --name mynodepool --query nodeImageVersion`. Executing this command shows no output.

Dropping the `--query nodeImageVersion` from the command reveals a JSON payload with many fields. One of the fields is `nodeImageVersion`, but the value is `null`. How can the value of the node image be null? Surely my node is running some image, and that image must have some version. 

Additionally, the UI just shows a blank field where the Node image version is meant to be displayed. 

I understand that I am running k8s version 1.22.11, which is soon to be retired. I plan to upgrade this, but I need to know if I need to upgrade my node images as well, and I can't do that if I have no way to know what the current version is. 

How can the current node image version be viewed?

**To Reproduce**
Execute the command `az aks nodepool show --resource-group myResourceGroup --cluster-name myAKSCluster --name mynodepool --query nodeImageVersion` on an affected cluster or attempt to view the node version in the UI.

**Expected behavior**
Current node version should be displayed. 

**Screenshots and logs**
The UI just shows a blank field where the Node image version is meant to be displayed. 
![image](https://user-images.githubusercontent.com/28212242/202325282-01c9b30b-655d-4c77-9a83-4237fad9d806.png)

My full output of executing those commands is viewable here: https://paste.microsoft.com/b1a82317-5f7c-4cc2-b3ce-06e23ed5a6bb

**Environment (please complete the following information):**
 - azure-cli version 2.42.0
 - Kubernetes version 1.22.11
 - Browser Chrome

**Additional context**

**Comment by carvido1** [comment]
Hello @alextadams88

This problem is related to the way the cluster was created. Your cluster `alex1337-westus2-p01-aks` was deployed with the old nodepool way with VMs instead of the nodepools with Virtual Machine Scale Sets which allows you to create nodepools on demand after the cluster creation.

See the difference here:
<img width="711" alt="image" src="https://user-images.githubusercontent.com/30261431/202779376-9ad3b6eb-1fc2-4da1-b847-eed6c413b2a5.png">
This is a cluster created with VMs nodepools.

<img width="900" alt="image" src="https://user-images.githubusercontent.com/30261431/202779483-46ec0ca6-b4d4-4904-9933-915437186543.png">

This is a cluster created with VMSS nodepools.

It is true that this information is not displayed on the Azure portal, despite to that you can get the information by checking one of the VMs that form the cluster

```bash
az vm show  -g mc_$AKS_RG_$AKS_CLUSTER_NAME_westus2 -n $VM_NAME --query storageProfile.imageReference.id -o tsv
```
Hope this helps you.

BR
