### ISSUE TITLE
[Question] GRPCContainerProbe feature gate not enabled on 1.24 cluster?

### ISSUE THREAD

**Issue by tspearconquest** [Azure/AKS#3349]
**Describe scenario**
Hello, we are working to implement a gRPC health endpoint in our application and had converted our `startupProbe` in the Kubernetes deployment manifest to enable the Kubelet to try to connect but we received a failure during the pod restart:

`New error   Warning  Unhealthy  17m (x39 over 42m)     kubelet            Startup probe failed: error: this server does not implement the grpc health protocol (grpc.health.v1.Health): unknown service grpc.health.v1.Health`

We understand this feature to be behind the `GRPCContainerProbe` feature gate in upstream Kubernetes v1.24, which is our current cluster version.

**Question**
According to the documented AKS support policies [here](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-grpc-liveness-probe) it says that beta features are supported, so I wanted to check if it's possible somehow to enable this feature gate in our cluster?

**Comment by joaguas** [comment]
hi @tspearconquest , 

The `GRPCContainerProbe` feature gate is enabled in AKS clusters running 1.24+ k8s (in 1.23 for example it won't work since the feature gate was alpha and therefor not enabled by default.

I can see successful probes on 1.24:

```
Name:             test-grpc
Namespace:        default
Priority:         0
Service Account:  default
Node:             aks-nodepool1-42135208-vmss00000g/10.224.0.33
Start Time:       Thu, 24 Nov 2022 12:53:27 +0000
Labels:           <none>
Annotations:      <none>
Status:           Running
IP:               10.224.0.43
IPs:
  IP:  10.224.0.43
Containers:
  agnhost:
    Container ID:  containerd://b015433dcf0803934e2fc7878802fd0139849cef256e100f321df2d59746f302
    Image:         k8s.gcr.io/e2e-test-images/agnhost:2.35
    Image ID:      k8s.gcr.io/e2e-test-images/agnhost@sha256:fde7ba8937b36702c2f840001d37ac15cc0cc401d0adcf5cc909f963f36b6f44
    Ports:         5000/TCP, 8080/TCP
    Host Ports:    0/TCP, 0/TCP
    Command:
      /agnhost
      grpc-health-checking
    State:          Running
      Started:      Thu, 24 Nov 2022 12:53:28 +0000
    Ready:          True
    Restart Count:  0
    **Readiness:      grpc <pod>:5000  delay=0s timeout=1s period=10s #success=1 #failure=3
    Startup:        grpc <pod>:5000  delay=0s timeout=1s period=10s #success=1 #failure=3**
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-65h4p (ro)
Conditions:
  Type              Status
  Initialized       True
  **Ready             True**
  ContainersReady   True
  PodScheduled      True
Volumes:
  kube-api-access-65h4p:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age    From               Message
  ----    ------     ----   ----               -------
  Normal  Scheduled  3m22s  default-scheduler  Successfully assigned default/test-grpc to aks-nodepool1-42135208-vmss00000g
  Normal  Pulled     3m22s  kubelet            Container image "k8s.gcr.io/e2e-test-images/agnhost:2.35" already present on machine
  Normal  Created    3m22s  kubelet            Created container agnhost
  Normal  Started    3m22s  kubelet            Started container agnhost
```

The same pod running on 1.23.x is unable to use grpc as expected (with a "missing probe handler" for grpc):

`  Warning  Unhealthy  2m11s (x61 over 12m)  kubelet            Startup probe errored: missing probe handler for test-grpc_default(112df0ef-ff1f-4f6c-88b1-7e4bb514c8af):agnhost`


Notice how this is different from the error you have:
`New error   Warning  Unhealthy  17m (x39 over 42m)     kubelet            Startup probe failed: error: this server does not implement the grpc health protocol (grpc.health.v1.Health): unknown service grpc.health.v1.Health`

This actually looks like the actual response from the grpc call made by the probe (meaning you're running 1.24+) but it's your actual app that hasn't implemented the health checking protocol - the fact that is mentions `grpc.health.v1.Health` hints at a missing service (Health) or not exported on the protobuf.


To clear any doubts you could try the example from the k8s docs to test out simple grpc probing: https://kubernetes.io/blog/2022/05/13/grpc-probes-now-in-beta/#trying-the-feature-out

**Comment by tspearconquest** [comment]
Thanks @joaguas I've forwarded this info back to the developer reporting the issue and will update once I have more info.
