### ISSUE TITLE
kubernetes hybrid support

### ISSUE THREAD

**Issue by neutrongenious** [Azure/AKS#335]
Allow support for Hybrid cluster. 
allowing admins to create one aks with both windows and Linux machines. 
This feature will allow us best of both worlds.

existing apps running on windowservercore or nanoserver while still providing leverage to use rest of images for linux and so.

similar to:
https://github.com/Azure/acs-engine/blob/master/examples/windows/kubernetes-windows-version.json

**Comment by neutrongenious** [comment]
@slack feedback appreciated.

**Comment by neutrongenious** [comment]
Any plans for this?

**Comment by joakimhellum-in** [comment]
We have been testing hybrid clusters in AKS for some months now, and with recent changes to the service and upgrade to Windows Server 1803, it seem to be working quite well for our use case. However it's not supported yet and don't work well with the CLI tools etc. It would be really great to see Windows support soon :)

**Comment by NareshBanala** [comment]
Will windows container support .Net framework 4.6.2 images?

**Comment by davidwmartines** [comment]
Hi @seanmck.  I'm glad to know this is on the roadmap.  So far AKS seems awesome.  Any idea of the timeline on when this hybrid capability will become available?    My company is depending on this being a reality for our deployment strategy due to having legacy .NET framework containers in the mix.  As it is, all of our attempts to create hybrid clusters via swarm mode have failed due to HNS issues in windows server.  I imagine that is what may be plaguing AKS as well.

**Comment by seanmck** [comment]
Sorry, no concrete timelines to share yet. You can upvote this request and follow it here:

https://feedback.azure.com/forums/914020-azure-kubernetes-service-aks/suggestions/34973563-add-support-for-windows-nodes

Closing this issue as we're trying to keep this repo scoped to issues with the shipped functionality.
