### ISSUE TITLE
AKS Auto-Upgrade Channel issue with latest version of AKS

### ISSUE THREAD

**Issue by James-Rush** [Azure/AKS#3363]
**Describe the bug**
AKS Cluster auto-upgrade command no longer works with the latest version of AKS-Preview or CLI.

**To Reproduce**
1. Upgrade to the Latest AKS Version
2. Run the command: az aks update --resource-group (AKSRG) --name (AKS) --auto-upgrade-channel rapid
3. Receive the following error: (BadRequest) Auto Upgrade Channel Invalid is invalid. For more information, please check https://aka.ms/aks-auto-upgrade
Code: BadRequest
Message: Auto Upgrade Channel Invalid is invalid. For more information, please check https://aka.ms/aks-auto-upgrade 

**Expected behavior**
AKS Upgrades the selected cluster to utilize the rapid or stable choice.

**Screenshots**
<img width="612" alt="AKS Issue" src="https://user-images.githubusercontent.com/105318023/204588642-20abc887-846c-4f05-a715-beb1a55273bd.PNG">

**Environment (please complete the following information):**
 -  CLI Version: 2.42.0
 - Kubernetes version: 1.24.6
 - CLI Extension version: 2.42.0

**Additional context**

**Comment by iamsoorya** [comment]
I have th same exact issue. Not getting any resolution.
az aks update --resource-group xxx --name xxxx  --enable-pod-identity

Is failing with same error. Please help asap. It is holdingup entire deployment

**Comment by AndreiBarbu95** [comment]
Hello!

As per our test, we found that this is may be an issue with aks-preview new CLI version. You may remove aks-preview or downgrade the version.
 
We tested and the downgrade of the aks-preview extension to 0.5.115 seems to fix this. See below.

$ az extension remove --name aks-preview
$ az extension add -n aks-preview --version 0.5.115
The installed extension 'aks-preview' is in preview.
$ az aks update -g akstest -n akstest
The behavior of this command has been altered by the following extension: aks-preview
no argument specified to update would you like to reconcile to current settings? (y/N): y
/ Running ..

We recommend you trying the same while the issue is getting addressed.

**Comment by arfallas** [comment]
Do we have an ETA for the fix?

**Comment by justindavies** [comment]
This issue should be resolved - can you confirm you are no longer seeing this?
