### ISSUE TITLE
How to confirm whether the ip address is created using command line or by exposing a loadbalancer service?

### ISSUE THREAD

**Issue by smartaquarius10** [Azure/AKS#3393]
Hello,

We have 2 ingress controllers in our Azure kubernetes exposing their own Load balancer type service. Due to this, Azure kubernetes basic(sku) loadbalancer forntend ip configuration is showing 2 ip addresses with their own rule counts.

Now, we are unable to figure out whether these ip addresses are created on the fly while hosting Kong and Nginx load balancer services or they are created manually via this command

`az network public-ip create --resource-group myResourceGroup --name myAKSPublicIP --sku basic --allocation-method static`

I tried running this query inside graph explorer but unable to figure out as there is no separate flag is given in the output:

```
resources
| where properties.ipAddress in ("xx.xx.xx.xx","yy.yy.yy.yy")
```

I'm asking this because we have to remove 1 ingress controller but we can't release its linked public ip address because it is mapped to multiple url's in our organization's firewall. 

If the ip is created on the fly then the moment I remove the ingress controller it will also release the linked ip address which is extremely risky as transferring all the urls to other ip in the firewall is a very time-consuming process.  If somehow, I can capture this ip address then I will just create one more loadbalancer type service for the required ingress controller using that ip address which is very easy.

Please suggest any procedure to confirm whether these static ip's are created on the fly or manually via command by some user.

Kind Regards,
Tanul

**Comment by carvido1** [comment]
Hello @smartaquarius10 .

Have you checked if you have any k8s service in your AKS cluster that has a public IP address assigned to it ? You can verify this using the following command:

```bash
kubectl get service -A
```

If you have more than 1 LoadBalancer service, probably someone created the new public IP address with basic SKU.

In addition to this check, you can always see if the public IP address is in the resource group that gets created with the AKS cluster that has the name `MC_$RESOURCEGROUP_$CLUSTERNAME_$REGION`. The IP addresses created by a loadbalancer service should reside here unless the annotation `service.beta.kubernetes.io/azure-load-balancer-resource-group` was given.

Furthermore, if a public IP address gets created manually to be used later on as public IP address for a K8s service, the AKS cluster's ServicePrincipal or the AKS cluster's managed identity [requires network contributor for that IP address resource](https://learn.microsoft.com/en-us/azure/aks/kubernetes-service-principal?tabs=azure-cli#networking). So this has to be done by someone, otherwise you will see a pending status on the loadbalancer service.

To finish, Azure/Microsoft discourages the use of basic SKU public IP addresses and basic SKU LoadBalancers. To change this it is required to recreate the cluster.

Hope this helps you a little bit.
KR.

**Comment by smartaquarius10** [comment]
@carvido1 , yeah I have already checked all these. Currently we have 2 ip addresses 

- one for kong ingress controller loadbalancer service
- Other for ingress nginx loadbalancer service

None of them is showing under `MC_$RESOURCEGROUP_$CLUSTERNAME_$REGION` in All resources section. Checked it twice. 

Tried running this query as well in graph explorer but no result

```
Resources
| where properties.ipAddress in ("xx.xx.xx.xx”)
```

Checked the kong and nginx services yaml but none of them has this annotation

`service.beta.kubernetes.io/azure-load-balancer-resource-group`


I’m totally out of option now. Not at all able to confirm if these are manually created ip’s or the one created on the fly.

**Comment by carvido1** [comment]
Hi @smartaquarius10 

Regarding where the IP goes, you can try to create a LB service and then search with the azure portal which resource group has that IP address. This can tell you if it goes to the same RG as the ingress-nginx and kong public IP addresses.

---

I've been investigating what triggers the public IP address to get deleted when a LB service is removed. It seems the [finalizer](https://kubernetes.io/docs/concepts/overview/working-with-objects/finalizers/) annotation was introduced in K8s 1.17. This apparently tells the loadbalancer to clean the public IP addresses not used.

I have tried to remove this metadata in a LB service I have created for testing purposes

```yaml
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
``` 

and then try to delete the service and create a new one to get the same IP but it has not worked.

Probably you need to consider opening a ticket in Azure support to see which are the possibilities...

BR

**Comment by smartaquarius10** [comment]
Its resolved
