### ISSUE TITLE
[BUG] Please do not upgrade to k8s 1.25 if you are using calico

### ISSUE THREAD

**Issue by qpetraroia** [Azure/AKS#3403]
AKS has acknowledged a bug with K8s 1.25 and the calico networking stack. If you are using calico in production, please do not upgrade to k8s 1.25 or create new 1.25 clusters with calico enabled. Once fixed, this bug will be updated and marked closed.

Thank you

**Comment by vimorra** [comment]
could you share more detail about the bug?

**Comment by siegenthalerroger** [comment]
@vimorra AKS is deploying a calico version that appears to be compatible with 1.25+ with an operator version that is _not_ compatible. Concretely they just need to use a Tigera Operator version of 1.28+ (https://github.com/tigera/operator/releases/tag/v1.28.0) so that the patch (https://github.com/tigera/operator/pull/2035) is actually included. This would also result in a new enough calico version so the API version conflicts aren't happening.

**Comment by n0daft** [comment]
Any news on this? Our Development cluster is basically useless until resolved since calico stack is not working anymore.

**Comment by robbiezhang** [comment]
reopen per #3394
