### ISSUE TITLE
Is it suggested to use Ephemeral OS in AKS?

### ISSUE THREAD

**Issue by smartaquarius10** [Azure/AKS#3409]
Team,

We have node pool of type VMAS with B2s size sku of 8 nodes. Is it suggested to use [Ephemeral OS](https://learn.microsoft.com/en-us/azure/aks/cluster-configuration#ephemeral-os) in AKS to improve performance. 

Please suggest. Thank you. Happy new year. 

Kind Regards,
Tanul

**Comment by andyzhangx** [comment]
ephemeral OS disks are stored only on the host machine, just like a temporary disk. This configuration provides lower read/write latency, along with faster node scaling and cluster upgrades.

When you don't explicitly request managed disks for the OS, AKS will default to ephemeral OS if possible for a given node pool configuration.

ephemeral OS disk is already the default os disk type in aks cluster creation, so that's suggested type.

**Comment by smartaquarius10** [comment]
@andyzhangx, We have the managed disk type. Could you please share the difference between ephemeral and managed type. Would be grateful if you can share with the example/use case. 

I am unable to understand the details shown on microsoft website.

**Comment by circy9** [comment]
Does this answer your question? https://learn.microsoft.com/en-us/answers/questions/474914/what-is-the-relationship-and-difference-between-ma

**Comment by smartaquarius10** [comment]
@circy9 , yup I have gon through this one before. But unable to relate it with any real time scenario.

**Comment by qpetraroia** [comment]
Hi @smartaquarius10,

Does this help? https://learn.microsoft.com/samples/azure-samples/aks-ephemeral-os-disk/aks-ephemeral-os-disk/

**Comment by olsenme** [comment]
We also have this article https://techcommunity.microsoft.com/t5/fasttrack-for-azure/everything-you-want-to-know-about-ephemeral-os-disks-and-azure/ba-p/3565605
