### ISSUE TITLE
[BUG/Question] AMA stops reporting metrics, Node experiences CPU pressure

### ISSUE THREAD

**Issue by dkarnutsch** [Azure/AKS#3469]
**Describe the bug**
Repeated CPU pressure on node of worker node pool (03/02/2023 11:35 - 12:20, 17/01/2023 09:30 - 11:00, 31/12/2022 23:30 - 13:15, 21/12/2022 00:30 - 10:00).

Steps to mitigate:
- Last occurrence: Deleted two pods from the node (deployment was recreating them)
- Previously restarted node using `az vmss restart`

I know this looks like to be customer initiated, but the following things let me think differently:
- The node is becoming completely unresponsive (connecting via SSH using `kubectl debug node/aks... -it --image=mcr.microsoft.com/dotnet/runtime-deps:6.0` not possible)
- The AMA pod is experiencing high CPU and it stops reporting metrics
- All other pods are also experiencing high CPU, which is odd, because it is not traffic related (pods are from different projects)
- I’ve recovered the kubelet logs from the node, which show an unusual amount of “Finished parsing log file” messages during the time of the CPU pressure from the pod which was deleted to mitigate 
- ama-logs pod on node contains error messages

**To Reproduce**
Sorry, I can't deliver that right now.

**Expected behavior**
AMA should continue to deliver metrics/logs. Node should stay responsive. Resource requests should be fulfilled.

**Screenshots**
CPU pressure on node
<img width="1105" alt="vmss_0002LH-cpu-pressure" src="https://user-images.githubusercontent.com/10632685/217780982-e8a9be1e-b6ff-47ea-a038-21912d304454.png">

CPU pressure on pod level; AMA stops reporting metrics
<img width="1509" alt="pods-cpu-pressure_censored" src="https://user-images.githubusercontent.com/10632685/217781645-fcdb1cac-1f49-4870-9c6e-97c18717706e.png">

Logs from ama-logs on node with CPU pressure
<img width="1137" alt="ama-logs" src="https://user-images.githubusercontent.com/10632685/217782168-3e500378-8b94-490d-8379-d69ec101d756.png">

Kubelet logs
<img width="1601" alt="kubelet-logs_censored" src="https://user-images.githubusercontent.com/10632685/217787292-2907df2c-190f-4e01-bb07-c3e31a746ae5.png">

**Environment:**
 - Kubernetes version: 1.23.12
 - Node-Pool: Linux, Standard_D4d_v5, Autoscaler enabled

Any help is greatly appreciated.

**Comment by saaror** [comment]
ACK adding @ganga1980

**Comment by ganga1980** [comment]
Hi, @dkarnutsch - I am investigating and will update on this soon.

**Comment by ganga1980** [comment]
Hi, @dkarnutsch , looks like there was network issue during the time window - 03/02/2023 11:35 - 12:20 and i see few errors mentioned below related timedout. The screenshot of the ama-logs indicate the same too.

Since there was network issue, we cant get all the logs related to ama-logs agent.

can you please share the full logs as well through this command

**kubectl cp  -c ama-logs kube-system/ama-logs-fdbfk:/var/opt/microsoft/linuxmonagent/log/mdsd.err mdsd.err**


 2023-02-03T10:29:35.5381150Z: Failed to upload to ODS: **Operation timed out after 60000 milliseconds with 0 bytes received**, Datatype: INSIGHTS_METRICS_BLOB, RequestId: 673f7c9c-02c6-44cc-abb4-d3ffd93a80e1, RetryCount: 9, NextRetry: 60s
2023-02-03T10:29:35.5381770Z: Failed to upload to ODS terminally, Datatype: INSIGHTS_METRICS_BLOB, RequestId: 673f7c9c-02c6-44cc-abb4-d3ffd93a80e1
2023-02-03T10:29:36.0343280Z: Failed to upload to ODS: Operation timed out after 59999 milliseconds with 0 bytes received, Datatype: CONTAINER_LOG_BLOB, RequestId: 53076be4-f71e-47ec-be22-ebf8435ca0ba, RetryCount: 9, NextRetry: 60s
2023-02-03T10:29:36.0343660Z: Failed to upload to ODS terminally, Datatype: CONTAINER_LOG_BLOB, RequestId: 53076be4-f71e-47ec-be22-ebf8435ca0ba,

@saaror , @aritraghosh , I think this needs to be investigated by AKS side with regards to network issue during the time window and unresponsive of the node.

**Comment by dkarnutsch** [comment]
HI @ganga1980 – thanks for investigating.

We had an auto-patch applied on Monday (1.23.12 -> 1.23.15), so all nodes restarted and thus the pod is gone. So I suppose there is no way for me to recover the logs, right? If this happens again, I will try to copy the logs.

**Comment by dkarnutsch** [comment]
I've tried to look into the occurrence of 17/01/2023 09:30 - 11:00 as well.

<img width="1103" alt="Screenshot 2023-02-15 at 09 49 08" src="https://user-images.githubusercontent.com/10632685/218980495-d5166532-25e0-427b-b739-b926b5b5b0e1.png">

Also high CPU on ama-logs as well as applications pods. Ama-logs stopped reporting metrics.
<img width="1403" alt="Screenshot 2023-02-15 at 09 50 15" src="https://user-images.githubusercontent.com/10632685/218980789-fa234951-129d-46fa-8c95-e9e80b5c62f9.png">

I have no access to the logs as the monitoring agent does not store logs from stdout of pods running in kube-system with the default config. Resolved by rebooting the node. Were there also networking problems during this time?

**Comment by ganga1980** [comment]
> I've tried to look into the occurrence of 17/01/2023 09:30 - 11:00 as well.
> 
> <img alt="Screenshot 2023-02-15 at 09 49 08" width="1103" src="https://user-images.githubusercontent.com/10632685/218980495-d5166532-25e0-427b-b739-b926b5b5b0e1.png">
> 
> Also high CPU on ama-logs as well as applications pods. Ama-logs stopped reporting metrics. <img alt="Screenshot 2023-02-15 at 09 50 15" width="1403" src="https://user-images.githubusercontent.com/10632685/218980789-fa234951-129d-46fa-8c95-e9e80b5c62f9.png">
> 
> I have no access to the logs as the monitoring agent does not store logs from stdout of pods running in kube-system with the default config. Resolved by rebooting the node. Were there also networking problems during this time?

Yes, i see the same network timeout errors to ingest the data during this time window as well. as you can see in below screenshot 
![image](https://user-images.githubusercontent.com/20712167/219171804-81e09761-4a17-4dab-9b3f-fda3335c5f9f.png)

**Comment by aritraghosh** [comment]
Please let us know if you are able to reproduce it. We believe the primary cause of the issue was node saturation from the app workloads.

**Comment by dkarnutsch** [comment]
Since the latest Kubernetes update (1.24.10) we are not experiencing it anymore. I hope it stays this way.
