### ISSUE TITLE
[Feedback] Inconsistent Display of Patch Version in kubernetesVersion Field after Auto-upgrade in AKS API

### ISSUE THREAD

**Issue by zioproto** [Azure/AKS#3573]
# Scenario

Related to https://github.com/Azure/terraform-azurerm-aks/issues/335

Create a cluster with auto-upgrade-channel `patch`:

```
az aks create \
 --location eastus \
 --name testcluster \
  -g testcluster \
 --network-plugin azure  \
 --kubernetes-version 1.25  \
 --node-vm-size Standard_DC4s_v2 \
 --node-count 2 \
 --auto-upgrade-channel patch 
```

When creating the cluster the AKS API returns this values:

```
 az aks show --name testcluster -g testcluster -o json | jq ".kubernetesVersion, .currentKubernetesVersion"
"1.25"
"1.25.5"
```

After an automatic upgrade ( `automatic_channel_upgrade=patch` ) the AKS API will return something like:

```
 az aks show --name testcluster -gtestcluster -o json | jq ".kubernetesVersion, .currentKubernetesVersion"
"1.25.6"
"1.25.6"
```

There is no consistency if the field `kubernetesVersion` should contain the patch version information or not. This behaviour leads to corner case bugs in the Terraform AzureRM provider.

# Feedback
It would be great of the API could return a map for kubernetesVersion with `major` `minor` and `patch` similar to what you get with `kubectl version`. This way external tools could use the API without ambiguities.

**Comment by palma21** [comment]
it is expected on the scenario you described there, might be helpful to understand what the problem is?

on your first example you placed 1.25 (so what you PUT is what you GET) on the k8sVersion, if you PUT 1.25.5 you GET 1.25.5

the currentVersion param is a readonly param that always represents the full version

the difference on autoupgrade is just because auto-upgrades makes the exact PUT as I mentioned above and doesn't use the aliasing.

(fwiw if you put 1.25 again after autoupgrade, that is fine and it shouldn't take any effect because that's an alias to the latest patch)

**Comment by zioproto** [comment]
The problem is not with the `PUT` but with the `GET`.
How can we `GET` the alias minor version `1.25` after an autoupgrade event ?

The problem is that Terraform saves in the state that the cluster is at `1.25` and should ignore the patch upgrades done by the `auto-upgrade-channel: patch`.

Because `kubernetesVersion` returns first `1.25` and after the upgrade `1.25.6` this causes state drift.

I guess the solution then is to implement in the Terraform provider the logic to ignore the patch version from the string returned by the AKS API.

I wanted to make sure I did not miss the AKS API call to always `GET` the alias minor version.

**Comment by palma21** [comment]
But it is related is what I was trying to explain, auto-upgrade does a 1.25.6 PUT, whereas the original create did a 1.25 PUT. We need to return exactly what was PUT in that field.

How would you want the auto-upgrade to PUT I guess is the question here. 

We could have autoupgrade PUT with 1.25 but that could cause other issues, and we still need a place to display the patch. So unless I'm missing a root issue here, the even deeper problem is how you have an automatic process change the state (like auto-upgrade) and that not conflict with TF state. You _could_ ignore the patch for this specific case, but I'm not sure that's generic enough for other things.

**Comment by alex8bitw** [comment]
This is an issue because it shows drift when there is none.

For example, here's a json chunk from Azure Aks:

`    "type": "Microsoft.ContainerService/ManagedClusters",
    "properties": {
        "provisioningState": "Succeeded",
        "powerState": {
            "code": "Running"
        },
        "kubernetesVersion": "1.25",
        "currentKubernetesVersion": "1.25.6",
`

The portal shows 1.25.6, which is the version AKS is currently on.  If we now update our terraform to reflect 1.25.6, we get drift.

Digging through the plan output data, we see:

./tfstate:          "kubernetes_version": "1.25",
./tfstate-prev:          "kubernetes_version": "1.25.6",

Even when we are ignoring kubernetes_version in lifecycle.
      ~ kubernetes_version                  = "1.25.6" -> "1.25"

**Comment by stevehipwell** [comment]
Could we get this reopened?

**Comment by zioproto** [comment]
@stevehipwell you could please ask @palma21 to re-open the issue.

But what are you asking for exactly ?

In the issue description I had this initial API change proposal:

> It would be great of the API could return a map for kubernetesVersion with major minor and patch similar to what you get with kubectl version. This way external tools could use the API without ambiguities.

It this what you are asking for or you have in mind a better solution ?

Thanks

**Comment by stevehipwell** [comment]
@zioproto if the auto upgrade is modifying the `kubernetesVersion` field it's a defect AFAIK. We saw this with Terraform and raised it with the AKS team. In the TF case we also observed a cluster upgrade operation when the drift was corrected.

Related to Terraform, and your suggestion, is the fact that the AKS resource only carries a single version while the data source has two like the CLI/API.

CC @phealy
