### ISSUE TITLE
[Question] AKS Azure integration legacy

### ISSUE THREAD

**Issue by vojtechvelkjop** [Azure/AKS#3663]
**Describe scenario**
We had noticed about "Update your clusters from Azure AD Integration (legacy) to managed Azure AD"  until 1.6 2023
**Question**
What happened after this time? The cluster will break ?
Thank  for information

**Comment by JRobertEdwards** [comment]
Would like to know the answer to this as well as we have two clusters using the legacy method. Documentation mentions deprecation but the email mentions retiring the feature which isn't very clear.

**Comment by dwv1627** [comment]
We are looking for this answer as well.  The email in March of this year said it would be retired 29 February 2024.  The email the other day says it is retired 1 June 2023.  Quite a big difference, we need clarification on this.

**Comment by adasseville** [comment]
Please note the official Azure notification mail points to this repo for support. The Azure support team itself doesn't know anything. They tell you to migrate to the newer version of the integration but cannot predict if anything will break, only offering to help when its already broken.

**Comment by vojtechvelkjop** [comment]
Hello I have asked MS technician and they told me that cluster will stop working. 
Answer:
"Yes, if you don't migrate from Azure AD Integration (legacy) to Managed Azure AD even after the deadline, the Azure AD Integration (legacy) feature will be retired and you will no longer be able to use it. This means that you will not be able to create new clusters with Azure AD Integration (legacy) and existing clusters with Azure AD Integration (legacy) will stop working. Therefore, it is recommended that you migrate to the new AKS-managed Azure AD integration feature before the deadline to avoid any disruption to your AKS clusters."

**Comment by CocoWang-wql** [comment]
Hello all, thanks for the feedback. 

AAD legacy will be deprecated and not supported since 1st June. And no new clusters with AAD legacy enabled can be created anymore. 
Starting from 1st August, 2023, we will upgrade all existing AAD legacy clusters to Managed AAD automatically. It might cause some apiserver downtime during the upgrade. If you want to manage the upgrade downtime during non-business hours, it's recommended to do the migration manually before 1st August.

The notification email with this plan should be sent out before next week. Pls feel free to let me know any more questions.
