### ISSUE TITLE
[Question] Ubuntu 18 End of life to may 31st, K8S 1.23 nodes are ubuntu 18 and don't retire until july...

### ISSUE THREAD

**Issue by ddanboyle** [Azure/AKS#3672]
**Describe scenario**
Microsoft sent around a notice saying that ubuntu 18 vms need to be upgraded by may 31st.

https://techcommunity.microsoft.com/t5/azure-compute-blog/canonical-ubuntu-18-04-lts-reaching-end-of-standard-support/ba-p/3822623

Aks version 1.24 is using ubuntu 18 nodes, and aks lifecycle specifies that version 1.24 is end of life in July

https://learn.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli#aks-kubernetes-release-calendar

Whereupon we go to kubernetes 1.25 which has ubuntu 22 nodes...

**Question**
Am I ok ignoring the kubernetes 1.25 upgrades until july, per the aks lifecycle cycle, since AKS manages those nodes and not me?

**Comment by vrdse** [comment]
I'm wondering the same. Would appreciate an answer.

**Comment by ondrejhlavacek** [comment]
This is a real pain in the ass. 

It really wouldn't hurt to align the EOL of AKS 1.24 and Ubuntu 1804 since there is no node image upgrade available for AKS 1.24 to Ubuntu 2204. 

Sending a notice 1 day in advance and announcing it publicly 1 week in advance (https://github.com/Azure/AKS/blob/master/CHANGELOG.md#release-2023-05-21) leaves me speechless. 

Also the email notice mentions Ubuntu PRO which doesn't seem to apply to AKS? Or does it? I'd happily spend the extra ~3% before we manage to upgrade to AKS 1.25.

**Comment by vrdse** [comment]
Microsoft support said that "Microsoft will provide on a weekly base, until July, any updates provided by Ubuntu on they ESM repositories." Though, I did not verify the statement by myself yet.

**Comment by sabbour** [comment]
After May 31, 2023, Ubuntu 18.04 will reach end of life. AKS will continue to update the host OS from Canonical into the Kubernetes 1.24 VHD images. Customers will not receive daily security updates from Canonical past the end of May, but will be able to consume those through a node image update only.
