### ISSUE TITLE
Azure CNI overlay IP reservation issues

### ISSUE THREAD

**Issue by ohorvath** [Azure/AKS#3686]
**Describe your scenario**
We are trying to move away from kubenet and start using Azure CNI overlay. 

**Feedback**
One of the advantages of Azure CNI would be to save IPv4 address space. With the current implementation it's actually worse than kubenet ever was or actually worse than standard CNI in that regard. We deploy two node pool clusters (max count 999) with autoscaler enabled and AKS tries to pre-allocate 1998 IP addresses upon creation. How on earth this will save us IP space? I'd like to see the default kubenet behaviour where no IP pre-allocation was necessary.

**Comment by kevinkrp93** [comment]
@phealy @chasewilson - please take a look at this

**Comment by tyler-lloyd** [comment]
@ohorvath - we can definitely improve the wording on this message, but it isn't actually allocating that many IPs when creating the cluster.

For Azure CNI Overlay, we validate the IP space for agent pools based on theoretical max if autoscaler is enabled. This means that even if your agentpools have a current count of 3, but your max count is 999 then in theory if autoscaler were to scale those up to 999 each you would need 1998 IPs. This prevents clusters from exhausting their subnets because of autoscaler. But importantly, it will not pre-allocate those IPs ahead of time (e.g. if there are 2 nodes in each pool then a total of 4 IPs would be used at that time and you are free to use the rest of the subnet space).
