### ISSUE TITLE
Restarting cluster changed private API Service Private Endpoint IP. Is there a way to fix this?

### ISSUE THREAD

**Issue by JarkoDubbeldam** [Azure/AKS#3691]
I am hosting a private AKS cluster using a BYO Vnet with Azure CNI networking. This means that the subnet I specified for the nodes is also used for the private endpoint where the API server can be reached. Based on this IP, I have configured some firewall rules to ensure access to the API server is limited to those who need it.

However, when I shut down and restart the cluster, the node IPs and the private endpoint for the API server are de- and reallocated. This causes the IP for the API server to change, breaking my firewall rules. I don't want to allow the entire subnet in the firewall, since that includes the IPs to reach the pods directly.

**Question**
Is there a way to pin the IP of the API server or at very least make the allocation deterministic?

**Comment by abarqawi** [comment]
@JarkoDubbeldam its expected behavior once we stop/start AKS cluster 
mentioned here
https://learn.microsoft.com/en-us/azure/aks/start-stop-cluster?tabs=azure-cli#about-the-cluster-stopstart-feature
-When you start your cluster back up, the following behavior is expected:
The IP address of your API server may change.
-If you provisioned PrivateEndpoints linked to private clusters, they need to be deleted and recreated again when starting a stopped AKS cluster.

**Comment by JarkoDubbeldam** [comment]
@abarqawi 

Thanks for the information. I'll have to look if I can put the private endpoint in a different subnet then, so that it hopefully is recreated on the same IP address instead of racing with the node ips.
