### ISSUE TITLE
[BUG] AKS Node_pool upgrade mount Filesystem /run/credentials/systemd-sysusers.service mounted read-only on node pool

### ISSUE THREAD

**Issue by Mehmoodhassan** [Azure/AKS#3745]
I am not sure about this behavior whether this is a bug or I missed configuration while deploying AKS cluster.
I have deployed a AKS cluster with 3 node pools via Terraform and node pool mounted Filesystem /run/credentials/systemd-sysusers.service  as read only then manually changed it to read/write.
So, when I upgraded my AKS cluster and node pools it mounted back as read only. 

How can I make it permanent as read/write?
Am I missing any configuration? 

Thanks in Advance

**Comment by sabbour** [comment]
Directly manipulating nodes in a node pool is not a supported operation. Any custom changes that are not performed from the AKS API won't persist through an upgrade, scale, update or reboot. Also, any change to the nodes' extensions like the CustomScriptExtension can lead to unexpected behavior and should be prohibited.

For workload-specific configurations or packages, AKS recommends using [Kubernetes daemon sets](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/). While this path is recommended if you need to customize the nodes, AKS engineering and support cannot help troubleshoot or diagnose modifications that render the node unavailable due to a custom deployed daemon set.

See [Support policies for Azure Kubernetes Service](https://learn.microsoft.com/en-us/azure/aks/support-policies#user-customization-of-agent-nodes) for more details.
