### ISSUE TITLE
[BUG] AKS agentpool properties are showing blank

### ISSUE THREAD

**Issue by saikumar0412** [Azure/AKS#3759]
**Issue**
AKS agentpool properties are showing blank(properties like Image reference, publisher, sku, offer)

**To Reproduce**
1. Run command 'az vmss show -n mc_rg -n vmss-name '
you can see  Image reference, publisher, sku, offer values null

**Expected behavior**
Values should be showed for  publisher, sku, offer of Vm image, I would like to use Azure Linux container Host but not sure of  its publisher, sku, offer even its showing same for ubuntu

**Screenshots**
![image](https://github.com/Azure/AKS/assets/32194003/d514ac8b-7510-46c9-8219-32afb940a761)

**Environment (please complete the following information):**
 -  CLI Version [2.49.0]
 - Kubernetes version [e.g. 1.25.6]

**Additional context**
Need details of publisher, sku, offer of Azure linux container host(AKSCBLMariner Image - 
**AKSCBLMariner-V2gen2-202306.19.0**)

**Comment by PixelRobots** [comment]
Hello,

As far as I know the view in the VMSS is expected behaviour as you should not be dealing with the VMSS at all, everything should go via the AKS API's.

AzureLinux is currently only for AKS not standalone VMs. This might change.

To create a node pool with AzureLinux you can follow this guide. https://learn.microsoft.com/en-us/azure/azure-linux/tutorial-azure-linux-add-nodepool

Hope that helps

Thanks

Richard
