### ISSUE TITLE
[Question] Log analytics LogEntry column formatting

### ISSUE THREAD

**Issue by catmanjan** [Azure/AKS#3766]
**Describe scenario**
We are drilling into our logs using the default log analytics platform, so we select our Workloads tab, select a Deployment and click Live logs and then click View in Log Analytics.

**Question**
Is there a way for the LogEntry to be formatted in a nicer way? Perhaps even have it automatically detect the columns?

The log entry itself is well formatted, e.g. 

2023-07-06 01:07:33 warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3] Failed to determine the https port for redirect.

But we can't easily sort and filter on timestamp and log level...

**Comment by ganga1980** [comment]
Hi, @catmanjan ,  best option here is to write the log message in JSON string so that LogEntry will be JSON which can convereted dynamic using  https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/parsejsonfunction you can extract the fields from JSON and do filtering/sort extracted fields. If not, you will have to do string split on the LogEntry column and extend the fields, then you can do sorting/filtering etc.

**Comment by catmanjan** [comment]
@ganga1980 thanks we are just beginning our AKS journey, is there a way to make log analytics remember string splits, so that next time a technician clicks on "Live logs" -> "View in logs analytics" they will see the split fields? At the moment it seems to revert back to the container style logs

![image](https://github.com/Azure/AKS/assets/137350/2ccf5f28-57f5-40c7-82ed-99565694d54e)
