### ISSUE TITLE
[BUG] network observability addon address already in use

### ISSUE THREAD

**Issue by mikec-greene** [Azure/AKS#3768]
**Describe the bug**
We have decided to test the network observability add-on following the setup guide for existing clusters here: https://learn.microsoft.com/en-us/azure/aks/network-observability-managed-cli?tabs=non-cilium#existing-cluster
We are using Azure managed prometheus and grafana.

After running the az aks update command all the daemonset pods crashloop with the error below

**To Reproduce**
1. Run command 'az aks update \
    --resource-group <clusterrg> \
    --name <clustername> \
    --enable-network-observability'
2. get logs for kappie-agent pods to see error `error listening on :8080: listen tcp :8080: bind: address already in use` screenshot below

**Expected behavior**
pods to be running and sending metrics to azure managed prometheus

**Screenshots**
![image](https://github.com/Azure/AKS/assets/95421630/9249298b-bfb0-457a-84e7-565bdae12bf2)

**Environment (please complete the following information):**
 -  CLI Version 2.46.0
 - Kubernetes version 1.26.3
 - CLI Extension version `aks-preview 0.5.145`

**Comment by mainred** [comment]
Hey @mikec-greene, the error happens because the network observability add-on picks `:8080` as the default listening address for metrics. The workaround is we figure out which process is taking 8080 from the host-network, and configure the pod with the other possible ports instead.
The long-term fix is from the AKS side, we will use a well-known port and add this to AKS official doc.

**Comment by mikec-greene** [comment]
It looks like there must've been an update on the Azure side since this started sending metrics about 15-15:30 UTC yesterday. Thanks for responding @mainred 👍
