### ISSUE TITLE
[BUG] Persistent volume claims seem to not be cleaned up

### ISSUE THREAD

**Issue by catmanjan** [Azure/AKS#3968]
**Describe the bug**
We have a Kubernetes application which creates jobs which create persistent volume claims, through normal operation we have found that we have ended up with a lot of PVC disks in All Resources.

**To Reproduce**
Not quite sure on these, but....
1. Run a cronjob which uses a PVC
2. Delete the job/cronjob and associated persistent volume claims or persistent volumes in different orders
3. Notice a growing number of PVC disks in All Resources

**Expected behavior**
PVC disks are cleaned up or otherwise

**Screenshots**
![image](https://github.com/Azure/AKS/assets/137350/5b60c586-d348-495f-9b9c-07fbcfa2fc24)

**Comment by andyzhangx** [comment]
And we have enabled [HonorPVReclaimPolicy](https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/2644-honor-pv-reclaim-policy) for Azure Disk CSI driver on 1.28, so if you are on earlier version:

It is recommended to delete the corresponding PersistentVolumeClaim object instead of the PersistentVolume object when deleting a CSI volume. The external provisioner in the CSI driver will react to the deletion of the PersistentVolumeClaim and based on its reclamation policy, it issues the DeleteVolume call against the CSI volume driver commands to delete the volume. The PersistentVolume object is then deleted.

https://learn.microsoft.com/en-us/azure/aks/csi-storage-drivers
