### ISSUE TITLE
[Feature] AKS Cost Analysis

### ISSUE THREAD

**Issue by kaysieyu** [Azure/AKS#3981]
Customers often look to third-party applications to get granular AKS cost allocation reporting. Third party solutions, however, require effort to deploy, fine-tune, and maintain for each AKS cluster. Some are also paid solutions which increase total cost of ownership.

AKS Cost Analysis add-on is an Azure native cost management solution that enables granular breakdown cluster infrastructure costs by Kubernetes specific constructs like cluster and namespace as well as Azure resource categories like compute, storage, network. This add-on is built on top of the OpenCost project, with cost allocation data reported directly in the Azure Portal UI.

Read about AKS Cost Analysis in recent [blog post](https://aka.ms/aks/cost-analysis). 
GA on March 19, 2024 at KubeCon EU. Azure Update [announcement](https://azure.microsoft.com/updates/generally-available-cost-analysis-addon-for-aks/).

For more information, refer to [docs](https://aka.ms/aks/docs/cost-analysis).

**Comment by denniszielke** [comment]
@kaysieyu the link to the techcommunity arcticle does not work. It should be https://aka.ms/aks/cost-analysis

**Comment by kaysieyu** [comment]
@denniszielke thanks for the catch. Fixed.

**Comment by andriktr** [comment]
Hey,
I successfully deployed this add-on and can see some cost data in Azure portal cost analysis area. However I'm bit worried about several errors in cost-analysis deployment. Here are some of them:

```
cost-analysis-agent-7d6fb79497-n87hw:cost-analysis-opencost 2024-01-24T08:54:24.932611233Z WRN Unable to download Azure pricing data
```

---

```
cost-analysis-agent-7d6fb79497-n87hw:cost-analysis-opencost 2024-01-24T08:54:24.908145557Z WRN Error in pricing download query from API
cost-analysis-agent-7d6fb79497-n87hw:cost-analysis-opencost 2024-01-24T08:54:24.908186518Z INF Failed to download pricing data: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions//providers/Microsoft.Commerce/RateCard?%!f(MISSING)ilter=OfferDurableId+eq+%!M(MISSING)S-AZR-0003p%!+(MISSING)and+Currency+eq+%!U(MISSING)SD%!+(MISSING)and+Locale+eq+%!e(MISSING)n-US%!+(MISSING)and+RegionInfo+eq+%!U(MISSING)S%!&(MISSING)api-version=2015-06-01-preview: StatusCode=403 -- Original Error: adal: Refresh request failed. Status Code = '403'. Response body: failed to get service principal token, error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Multiple user assigned identities exist, please specify the clientId / resourceId of the identity in the token request"} Endpoint http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%!A(MISSING)%!F(MISSING)%!F(MISSING)management.azure.com%!F(MISSING)
```

---

```
cost-analysis-agent-7d6fb79497-n87hw:cost-analysis-opencost 2024-01-24T08:54:24.93186134Z WRN ComputeCostData: continuing despite error parsing normalization values from max(count_over_time(kube_pod_container_resource_requests{resource="memory", unit="byte", }[2m] )): No data error: getNormalization
```

All errors comes from cost-analysis-opencost container. 

Any thoughts, suggestions?

Thank you.

**Comment by dewolfs** [comment]
I just enabled cost-analysis as described [HERE](https://learn.microsoft.com/en-us/azure/aks/cost-analysis)

The cluster was created with the following parameters: 
`az aks create -g rg-aks-test -n my-aks-test --node-count 2 --enable-cost-analysis --generate-ssh-keys --tier standard --node-vm-size=Standard_A2_v2 --enable-oidc-issuer --enable-workload-identity --kubernetes-version 1.27.3 --enable-managed-identity`

The container with name `cost-analysis-opencost` is showing the following error:

> WRN Error in pricing download query from API

> 2024-02-08T08:40:26.201035697Z INF Failed to download pricing data: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions//providers/Microsoft.Commerce/RateCard?%!f(MISSING)ilter=OfferDurableId+eq+%!M(MISSING)S-AZR-0003p%!+(MISSING)and+Currency+eq+%!U(MISSING)SD%!+(MISSING)and+Locale+eq+%!e(MISSING)n-US%!+(MISSING)and+RegionInfo+eq+%!U(MISSING)S%!&(MISSING)api-version=2015-06-01-preview: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Multiple user assigned identities exist, please specify the clientId / resourceId of the identity in the token request"} Endpoint http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%!A(MISSING)%!F(MISSING)%!F(MISSING)management.azure.com%!F(MISSING)

I could find back a similar open issue at openCost: https://github.com/opencost/opencost/issues/1610

@kaysieyu do you have more info on this?  

How long does it takes before data is visible in the Azure portal? An indication (1h/1day) should be added to the documentation.

**Comment by Frettarix** [comment]
**Additional request on Feature**

**Description:**
I am part of a team that runs hybrid cloud solutions in an Enterprise environment on both EKS and AKS. We are running similar out-of-the-box tools to ensure the user experience is very similar for our users. This means they can move cross-cloud with very little effort and a similar user experience. Part of this solution we are also looking to make a cost overview per namespace available for both EKS and AKS. To ensure the cost can be retrieved on a per namespace base; we would like to consume the API from OpenCost. Currently we are not able to do so with Azure.

**Use Case:**
To facilitate a hybrid cloud environment we adopt similar technologies across EKS and AKS. We would like to have the OpenCost API available on AKS in a secure way so that we can query and show the user's consumption and what the cost is for their Kubernetes namespace(s). We will have a similar approach for EKS.

**Problem:**
When enabling AKS Cost Analysis there is a pod within the kube-system namespace that handles the API's. This API is not exposed and is not reachable out of the box. When trying to find more information we notice that more users are struggling with this problem (read above).

**Wanted Solution:**
We would like to have the API available in a secure way either internally in the cluster, or within our intranet. Whether this is through the Azure portal or not is not a problem as long as we are also able to retrieve raw KubeCost data which we would also receive from our EKS API.

We are also quite curious what the future vision is for Cost Analysis. In 2024 we often see an API first approach, but if I read previous posts it seems that the API is blocked. To ensure our strategy and choice of product is correct it would be good to ensure that we understand the strategy of Microsoft.

**Comment by mloskot** [comment]
I'm seeing similar issue to @dewolfs' in https://github.com/Azure/AKS/issues/3981#issuecomment-1933664834  but, interestingly, it is tagged as `INF` and not error or warning:

```
INF Failed to download pricing data: azure.BearerAuthorizer#WithAuthorization: 
Failed to refresh the Token for request to https://management.azure.com/subscriptions//providers/Microsoft.Commerce/RateCard?%!f(MISSING)ilter=OfferDurableId+eq+%!M(MISSING)S-AZR-0003p%!+(MISSING)and+Currency+eq+%!U(MISSING)SD%!+(MISSING)and+Locale+eq+%!e(MISSING)n-US%!+(MISSING)and+RegionInfo+eq+%!U(MISSING)S%!&(MISSING)api-version=2015-06-01-preview:
StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'.
Response body: {"error":"invalid_request","error_description":
"Multiple user assigned identities exist, please specify the clientId / resourceId of the identity in the token request"}
Endpoint http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%!A(MISSING)%!F(MISSING)%!F(MISSING)management.azure.com%!F(MISSING)
```
