### ISSUE TITLE
[Feature] [Istio Add-on] Output Istio Gateway IP address

### ISSUE THREAD

**Issue by yuft** [Azure/AKS#3987]
**Is your feature request related to a problem? Please describe.**

After enabling public gateway using `az aks mesh enable-ingress-gateway` or ARM template, there is no way to retrieve the public IP address or DNS label.

A valid scenario is to configure a DNS record.

**Describe the solution you'd like**
Put IP address as an output.

**Describe alternatives you've considered**
Bring my own IP also solves the issue. Related to https://github.com/Azure/AKS/issues/3757

**Additional context**

**Comment by nshankar13** [comment]
@yuft did you mean for an existing / pre-configured Azure public IP address, or just the external IP of the ingress gateway created by AKS by default? The latter should be accessible by getting the service in the `aks-istio-ingress` namespace: `kubectl get svc aks-istio-ingressgateway-external -n aks-istio-ingress`. 

We can't output the IP address of the ingress gateway via CLI upon enablement because it is not part of the ARM profile of the add-on - it's only part of the service spec for the k8s LoadBalancer.

**Comment by yuft** [comment]
@shashankbarsin correct. An alternative is to output the IP if I cannot customer the IP so I can configure DNS with it.

Happy to close this one and track in another issue.

**Comment by nshankar13** [comment]
@yuft the following annotations can now be added to the Istio ingress K8s service:

- `service.beta.kubernetes.io/azure-load-balancer-internal-subnet`: to bind an internal ingress gateway to a specific subnet.
- `service.beta.kubernetes.io/azure-shared-securityrule`: for exposing the ingress gateway through an augmented security rule.
- `service.beta.kubernetes.io/azure-allowed-service-tags`: for specifying which service tags the ingress gateway can receive requests from.
- `service.beta.kubernetes.io/azure-load-balancer-ipv4`: for configuring a static IPv4 address.
- `service.beta.kubernetes.io/azure-load-balancer-resource-group`: for specifying the resource group of a public IP in a different resource group from the cluster.
- `service.beta.kubernetes.io/azure-pip-name`: for specifying the name of a public IP address.
