### ISSUE TITLE
[Question] Does Aks perform cordon/drain when deleting a node pool?

### ISSUE THREAD

**Issue by Taha-cmd** [Azure/AKS#3996]
**Describe scenario**
I want the ability to programmatically resize my node pools. I want to know if I have to take care of cordoning/draining the nodes myself.

**Question**
The [documentation](https://learn.microsoft.com/en-us/azure/aks/resize-node-pool?source=recommendations&tabs=azure-cli#remove-the-existing-node-pool) clearly says that Aks does NOT perform cordon/drain when deleting a node pool. I deleted a node pool in portal to see what happens and it appears that my node pool is being cordoned/drained. So what is happening? Is the documentation not up to date?

**Comment by whaakman** [comment]
When deleting a nodepool, each node is drained and a taint to prevent scheduling is applied due to the node being deleted. The documentation can use rewording as it is important that workloads that do not support this kind of behavior are impacted. A good practice is to cordon and drain the node programmatically through the automation you use to deploy new node pools and make sure all workloads have been rescheduled before deleting the old node pool.

I will create a PR for the Docs team with some rewording.

**Comment by fschmied** [comment]
> A good practice is to cordon and drain the node programmatically through the automation you use to deploy new node pools and make sure all workloads have been rescheduled before deleting the old node pool.

@whaakman Could you expand on that a bit, please? What's the advantage of cordoning and draining the node(s) programmatically when AKS will practically do the same automatically? And will the nodepool deletion abort if draining the nodes fails?

I'm working on the same team as @Taha-cmd and we're using Terraform to manage our node pools. If we can rely on AKS draining nodes gracefully, we can simply use Terraform's _create-before-destroy_ behavior to ensure the new nodepool is created before the old one is deleted - the rest will be handled by AKS. If not, we need to use a "provisioner" to run an extra script that manually drains (and cordons) the nodes in-between. That's much more complex and also introduces more potential error cases, so we'd rather avoid it if it's unnecessary anyway.
