### ISSUE TITLE
Managed disk encryption at REST support for AKS + default disk option (std or premium)

### ISSUE THREAD

**Issue by gkaleta** [Azure/AKS#41]
Top customer ask - AKS support for Managed Disk's Encryption at REST + default option for Standard or Premium disk.

**Comment by khenidak** [comment]
Hi @gkaleta The encrypted disk support are added to Kubernetes upstream backlog. And it should be there (not in next minor version because code freeze is 11/22).

As for Standard or Premium disks support: 
Azure Premium VMs support both premium and standard disks
Azure standard VMs support only standard disks
Aks uses managed disks by default. 

If you want to create aks cluster with premium VMs use ``` ---node-vm-size``` argument in your ```az create ``` command details are here https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az_aks_create

**Comment by slack** [comment]
Closing this issue, let us know if you have any further questions.
