### ISSUE TITLE
AKS nodes are not scaling up 

### ISSUE THREAD

**Issue by haarvester** [Azure/AKS#4109]
**Describe the bug**
After upgrading AKS from 1.26.10 to 1.27.7 on one of the clusters, I deleted a node in the node pool, which included 2 nodes. Afterward, I was unable to scale to 2 nodes. I tried to scale using the CLI:

I tried to scale by CLI: 
az aks scale --resource-group my-cluster --name my-cluster --node-count 2 --nodepool-name default
Output: 
  "agentPoolProfiles": [
    {
      "availabilityZones": null,
      "count": 2,
      "creationData": null,
      "currentOrchestratorVersion": "1.27.7",

However, only one node was actually added. I observed this in the UI and with kubectl get nodes.

**To Reproduce**
The issue occurred on 3 out of 2 AKS clusters that were upgraded with no issues.

**Expected behavior**
Able to scale to target count which described in node pool

**Screenshots**
![image](https://github.com/Azure/AKS/assets/78104086/2932a9dc-b4d7-4800-a5a9-4d30f062ebf6)

**Environment (please complete the following information):**
 -  az cli 2.50.0
 - AKS 1.27.7
 - OS version: AKSUbuntu-2204gen2containerd-202401.17.1

**Additional context**
Also after upgrading I unable to pull nginx-ingress image. Unknown desc = failed to pull and unpack image "registry.k8s.io/ingress-nginx

**Comment by philwelz** [comment]
Can you please provided more insights with kubelet or scheduler logs ? Otherwise its hard to help.

But until that you could also try to add a new system node pool and delete to old system node pool. Details can be found [here](https://learn.microsoft.com/en-us/azure/aks/use-system-pools?tabs=azure-cli)

PS. Its not recommended to have only a system node pool in the cluster. Better add an user mode node pool and run your workload there.
