### ISSUE TITLE
[BUG] Cluster Autoscaler ignores skip-nodes-with-local-storage setting

### ISSUE THREAD

**Issue by frederikspang** [Azure/AKS#4126]
**Describe the bug**
When setting `skip-nodes-with-local-storage` with `--cluster-autoscaler-profile`, it seems to be ignored, according to the Cluster Autoscaler Logs:

```
node aks-mypoolname-vmss000000 cannot be removed: pod with local storage present: notification-controller-66bdd585c4-f9l22
```

**To Reproduce**
Set config as: 
```
az aks update -g clustername -n <n> --cluster-autoscaler-profile skip-nodes-with-local-storage=false skip-nodes-with-system-pods=false scale-down-unneeded-time=3m scale-down-utilization-threshold=0.7 ignore-daemonsets-utilization=true
```

See in response:
```
  "autoScalerProfile": {
    "balanceSimilarNodeGroups": "false",
    "daemonsetEvictionForEmptyNodes": false,
    "daemonsetEvictionForOccupiedNodes": true,
    "expander": "random",
    "ignoreDaemonsetsUtilization": true,
    "maxEmptyBulkDelete": "10",
    "maxGracefulTerminationSec": "600",
    "maxNodeProvisionTime": "15m",
    "maxTotalUnreadyPercentage": "45",
    "newPodScaleUpDelay": "0s",
    "okTotalUnreadyCount": "3",
    "scaleDownDelayAfterAdd": "10m",
    "scaleDownDelayAfterDelete": "10s",
    "scaleDownDelayAfterFailure": "3m",
    "scaleDownUnneededTime": "3m",
    "scaleDownUnreadyTime": "20m",
    "scaleDownUtilizationThreshold": "0.7",
    "scanInterval": "10s",
    "skipNodesWithLocalStorage": "false",
    "skipNodesWithSystemPods": "false"
  },
```

**Expected behavior**
Node is scaled down.

**Environment (please complete the following information):**
 - CLI Version [2.57.0]
 - Kubernetes version [1.28.5]
 - CLI Extension version [aks-preview 1.0.0b6]

**Comment by vanny96** [comment]
Same over here with version 1.28.3, apparently this issue was already discovered and fixed as described by [this issue](https://github.com/Azure/AKS/issues/3704) 

This is quite important as we're incurring into increased costs because of this, anyone from the AKS team that could take a look at this? @kevinkrp93 maybe you already know how to address this?

**Comment by stonkie** [comment]
Same here in 1.28.5. We worked around it using the `cluster-autoscaler.kubernetes.io/safe-to-evict-local-volumes` annotation on most of our pods.

**Comment by frederikspang** [comment]
> EDIT: To add extra info that might be useful to debug the issue, we started experiencing this problem on the `23/02/2024`, ~2 weeks after our upgrade of AKS. @frederikspang could you check when you started experiencing this issue as well?

It's been "a few days" - Could be since our last maintenance windows, but I am unsure. _Around_ 23/02/2024 is not unrealistic

**Comment by bondido** [comment]
> Same over here with version 1.28.3, apparently this issue was already discovered and fixed as described by [this issue](https://github.com/Azure/AKS/issues/3704)
> 
> This is quite important as we're incurring into increased costs because of this, anyone from the AKS team that could take a look at this? @kevinkrp93 maybe you already know how to address this?
> 
> EDIT: To add extra info that might be useful to debug the issue, we started experiencing this problem on the `23/02/2024`, ~2 weeks after our upgrade of AKS. @frederikspang could you check when you started experiencing this issue as well?

We've experienced the issue #3704 when we were trying to upgrade to 1.25.6. It was fixed then, so I'm not sure if this issue is the same.

Besides of that, we are also experiencing the issue now (also since 22-23.02.2024 depending on cluster region).

In fact, problem is doubled :-/

Firstly - in case of scale-up, the pool is first expanding up way above necessity - to the maximum limit set (even if small resources for one tiny pod are needed). After some time the pool size stabilize, but after the load drop it's not able to return to small enough size because of "pod with local storage present" issue. It usually stays at 3 or 4 nodes when it shuld go to 2 or even 1.

Both problems are causing increased costs.

We've tried with kubernetes 1.28.3 and 1.28.5 - both have both issues.

But **1.27.9** which we've just also **tested** - autoscales **OK**.

We have a support request opened for that, but no conclusions yet.

Probably we'll go back to 1.27.9 at least temporarily until the issue is fixed. So you may try it if possible in your case.

Hope the fix is available really soon.

**Comment by kevinkrp93** [comment]
Fix is being rolled out.
