### ISSUE TITLE
[BUG] Automatic upgrade changes `kubernetesVersion` & `orchestratorVersion`

### ISSUE THREAD

**Issue by stevehipwell** [Azure/AKS#4127]
**Describe the bug**
When an AKS cluster is using an alias version and an automatic upgrade is applied the AKS orchestrator modifies the cluster `kubernetesVersion` and node pools `orchestratorVersion` which causes churn in our automation. This can be confirmed via the `az aks show` & `az aks nodepool show` CLI commands.

**To Reproduce**
1. Have an AKS cluster using a version alias on not the latest version (create with old patch version and then update to use an alias version)
2. Run `az aks show` and capture the `kubernetesVersion` & `currentKubernetesVersion` fields
3. Run `az aks nodepool show` and capture the `orchestratorVersion` & `currentOrchestratorVersion` fields
4. Run an automatic upgrade with the cluster set to `NodeImage`
5. Re run the commands from steps 2 & 3 and compare.

**Expected behavior**
I'd expect only the `currentKubernetesVersion` & `currentOrchestratorVersion` fields to hav e been modified by the upgrade.

**Screenshots**
n/a

**Environment (please complete the following information):**
 -  CLI Version: n/a
 - Kubernetes version: 1.28
 - CLI Extension version: n/a
 - Browser: Chrome

**Additional context**

**Comment by kaarthis** [comment]
This is due to a recent bug we had on upgrade validation and resource field updates. This affects users on older API versions, and the fix is already out starting March 2024.
However, the users who have performed upgrades before the fix is released, may see this **_kubernetesVersion_** field not currently updated (as desired).  

To mitigate - you can do a put operation again setting the kubernetesVersion field to the value of currentKubernetesVersion. You can also use portal/cli to issue an upgrade to the currentKubernetesVersion. Those operations will not roll the nodes again to upgrade, and will fix the wrong version on resource field.

**Comment by stevehipwell** [comment]
@kaarthis this issue is explicitly about the `kubernetesVersion` field being updated when it shouldn't be; an automatic upgrade shouldn't modify the `kubernetesVersion` field if it's an alias. I don't think your resolution is actually a resolution for the issue.

CC @phealy
