### ISSUE TITLE
[Question] How to use SecretProviderClass to create tls secret for ingress controller?

### ISSUE THREAD

**Issue by AdamMachera** [Azure/AKS#4150]
**Describe scenario**
I'm following scenario for ingress SSL offloading:
https://learn.microsoft.com/en-us/azure/application-gateway/for-containers/how-to-ssl-offloading-ingress-api?tabs=alb-managed
I'm having problem with comprehend how to get listener-tls-secret from keyvault.

I don't want to manually download first pfx and then prepare tls secret like this:
openssl pkcs12 -in sslcert.pfx -nocerts -out sslcert.key
openssl rsa -in sslcert.key -out sslcert-decrypted.key
openssl pkcs12 -in sslcert.pfx -nokeys -out sslcert.crt 
kubectl create secret tls listener-tls-secret --cert sslcert.crt --key sslcert-decrypted.key -n test-infra

There is a nice walkthrough for nginx how to use SecretProviderClass:
https://learn.microsoft.com/en-us/azure/aks/csi-secrets-store-nginx-tls

**Question**
How can I use SecretProviderClass to create a listener-tls-secret for ingress if I have pfx cert uploaded into keyvault?

**Comment by kamilzzz** [comment]
You basically need to mount CSI secret store volume as the sample you linked shows. It will sync KV certificate into k8s secret.

If you would like to use wildcard cert as default TLS certificate for nginx ingress controller (`--default-ssl-certificate`) this should be quite straightforward as you just define `extraVolume` for nginx ingress controller deployment and set your secret name as default-ssl-certificate controller arg.

If you want to use separate certificate per Ingress definition (certificate A for Ingress A, certificate B for Ingress B) you just need to mount more volumes which will sync more secrets. This depending on your setup might get more tricky as by design it is assumed secret needs to live in the same namespace where Ingress is defined. As you obviously cannot mount volumes on the Ingress level, you need to find a better place for that - most likely your application Deployment exposed via that specific Ingress.
