### ISSUE TITLE
[Question] Disabling manage service affect SLA?

### ISSUE THREAD

**Issue by Bj3MaS** [Azure/AKS#4237]
**Describe scenario**
We have a production cluster we want to remove the calico network policy. We want to use this [feature](https://github.com/Azure/AKS/issues/3845)  but is GA before June. 

**Question**
Can we implement a resource quota on the Calico namespace in the meantime, and would this impact the SLA provided by Microsoft?

**Comment by PixelRobots** [comment]
I personally would not do that. You may find as it is a managed resource the changes will get replaced by a reconciliation. I am not 100% sure if it will, but I do know newer services will do this.

It would be best to open a support case to confirm if this is a supported scenario.

**Comment by JoeyC-Dev** [comment]
I don't suggest so. 
When this feature is just being rolled out as Public Preview, I tried it on my test cluster with disabling and enabling it multiple time (purposely), and my cluster failed when trying to get back to Calico again because "xxx is already existing" (I forget the name). In the end, I just have to make the test cluster stay in "None".
I remember there is a fix for this being rolled out later. But this experience told me that never deploy the preview feature on the production environment unless I monitor it on the staging one for months.

**Comment by Bj3MaS** [comment]
Got answer from Microsoft, best way was temporary modify calico using Felix configuration
