### ISSUE TITLE
[Question] ETA on Flux v2.3.0 extension availability

### ISSUE THREAD

**Issue by rbnis** [Azure/AKS#4315]
**Describe scenario**

Flux has released v2.3.0 2 weeks ago. 
In this release many APIs have been moved to GA.

AKS extension for Flux is still on v2.1.2.

**Question**

Is there any ETA on the availability of Flux v2.3.0 in the flux extension for AKS?

**Comment by bene-tleilax-werdna** [comment]
Bumping this question - it would be nice to know when Microsoft plans to release Flux v2.3.0 on AKS. 

Not having that functionality right now means having to use an older version of the Flux CLI to see Flux-managed resources since the current iteration of the Flux CLI only returns resources that use the GA APIs.

**Comment by k7o** [comment]
It looks like these changes are coming in a July release as noted here, https://learn.microsoft.com/en-us/azure/azure-arc/kubernetes/extensions-release#flux-gitops
