### ISSUE TITLE
[BUG] Logging in to a managed identity from a pod using az cli 

### ISSUE THREAD

**Issue by yuvallb** [Azure/AKS#4439]
**Describe the bug**
Cannot login using az cli from pod running with a service account that is federated to a managed identity.

**To Reproduce**
1. Create a managed identity
2. Create a service account
3. Create a federated-credential identity, linking the identity to the service account

From the pod: 
5. verify the application is able to authenticate as the managed identity using DefaultAzureCredentialBuilder
6.  install Azure CLI
7.  run "az login --identity"
8. Error: No access was configured for the VM,
9. run "az login --identity --allow-no-subscriptions"
10. Get a response, but when trying to access protected resources: Forbidden

**Expected behavior**
az cli should be able to login and use the pod managed identity to access protected resources

**Screenshots**

**Environment (please complete the following information):**
 - Kubernetes version 1.28.10
 - Azure CLI version 2.62.0

**Comment by JoeyC-Dev** [comment]
Not sure why you are mentioning that you using "pod managed identity", as it will be deprecated in Sept 2024 (in ~2 months) and it is already not being maintained since Sept 2023. And I don't see Pod managed identity need to use "federated-credential identity" either, because Pod managed identity need to communicate with IMDS, while federated credential identity does not (also "az login --identity" is not the correct way to login by using federated-credential identity).

If you are using workload identity, in your repro steps, there is no step mentioning that you are adding workload-identity related labels to the Pods. The context you are giving is confusing. 

If you are actually using Pod managed identity, you should give up that approach right now, as it is no longer supported. If you are using [Workload identity](https://learn.microsoft.com/en-us/azure/aks/workload-identity-deploy-cluster), the repro steps you are giving does not look like right.

To login as workload identity:
```bash
az login --federated-token "$(cat $AZURE_FEDERATED_TOKEN_FILE)" --service-principal -u $AZURE_CLIENT_ID -t $AZURE_TENANT_ID
```
(Note: you still need to grant at least a Reader role to managed identity on the scope of any Azure resources, or it will return an error.)
Workload identity (or federated-credential identity) does not require IMDS connection at all. So the `--identity` way is wrong.

**Comment by yuvallb** [comment]
Thanks!!
I am doing workload identity.
You command works perfectly.
For some reason Azure support were not able to point me to this direction.
