### ISSUE TITLE
Azure Linux nodes will default to using cgroupsv2 starting AKS 1.29

### ISSUE THREAD

**Issue by flora-taagen** [Azure/AKS#4495]
Please note that Azure Linux nodes on kubernetes version [1.28](https://learn.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli#aks-kubernetes-release-calendar) will be end of life in November 2024. When upgrading to kubernetes version [1.29](https://learn.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli#aks-kubernetes-release-calendar) or above, Azure Linux will default to [cgroupsv2](https://kubernetes.io/docs/concepts/architecture/cgroups/) which may impact your workloads.

**Comment by hterik** [comment]
I'm a bit confused. This has been described as the default in AKS since 1.25, for example 
here https://github.com/Azure/AKS/releases/tag/2023-07-16
here: https://learn.microsoft.com/en-us/troubleshoot/azure/azure-kubernetes/create-upgrade-delete/aks-increased-memory-usage-cgroup-v2#cause 
and here https://doc.kaas.thalesdigital.io/docs/Breakingchanges/aks125

Which version of cgroups is really used and how can one verify this? :slightly_smiling_face:

**Comment by flora-taagen** [comment]
@hterik 

Ubuntu has defaulted to cgrouspv2 since **AKS 1.25.**
Azure Linux has defaulted to cgroupsv2 since **AKS 1.29**

To check the cgroups version on your nodes you can run the following command:
`grep cgroup /proc/filesystems`

If your system supports cgroupv2, you would see:
`nodev   cgroup`
`nodev   cgroup2`

On a system with only cgroupv1, you would only see:
`nodev   cgroup`

**Comment by eeowaa** [comment]
For those running Node.js workloads on Azure Linux AKS nodes, ensure that you are using Node.js 20.3 or greater, otherwise you will run into memory issues. See also: https://github.com/Azure/AKS/issues/3443#issuecomment-1703354926
