### ISSUE TITLE
New VNET isn't cleaned up if the deployment fails

### ISSUE THREAD

**Issue by emrekenci** [Azure/AKS#457]
When you choose to create a new VNET while deploying a new cluster and the deployment fails, the created VNET remains in the subscription.

The code causing this behavior can be the same with what's causing [this issue](https://github.com/Azure/AKS/issues/181)

**Comment by mboersma** [comment]
@emrekenci I assume you created a new VNet and AKS cluster in the Azure Portal (since the CLI doesn't support that in one action). It's not related to issue #181.

While it is part of the overall "create Kubernetes cluster" workflow, creating a VNet is a separate action within that flow, just as creating a new Resource Group is. So I'm not sure deleting it automatically would be the expected behavior.

**Comment by emrekenci** [comment]
I see your point, but it should be, imo. Also, I think it belongs inside the MC_ resource group, not the AKS resource group. Otherwise, you need to manually give the SP permissions **manually** to be able to get public IPs for kubernetes services. Not something a new user can figure out on their own. But that's another issue.

**Comment by jnoller** [comment]
Closing this issue as old/stale/resolved.

Note: 
If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
