### ISSUE TITLE
[Known issue] Custom CA (preview) error in 2024.09.23.0 and 2024.09.30.0 node image versions

### ISSUE THREAD

**Issue by allyford** [Azure/AKS#4586]
In 2024.09.23.0 and 202409.30.0 node image versions, pods deployed by the daemonset created by Custom Certificate Authority feature will encounter following error: “error: ErrImageNeverPull and Container image "mcr.microsoft.com/aks/aks-node-ca-watcher:static" is not present with pull policy of Never”, caused by a missing tag for node-ca-watcher image. This error can stop your custom certificates from being properly added to the node’s trust store.

**Required action**
There are two ways to mitigate this error:
1.	Once available in your region, upgrade your affected nodes to 202410.09.0 node image version, which contains correctly tagged image.

2.	If the new node image is not yet available, you can manually mitigate the issue. On affected nodes, mcr.microsoft.com/aks/aks-node-ca-watcher container image needs to be retagged to use the tag that is expected by daemonset deployed by custom-ca feature, using the following command:

ctr --namespace k8s.io image tag mcr.microsoft.com/aks/aks-node-ca-watcher:master.240820.1 mcr.microsoft.com/aks/aks-node-ca-watcher:static

This has to be executed on every affected node.

**Comment by davetheninja** [comment]
Is there an ETA for releasing the permanent fix here?  I have a new release that is blocked as a result.

For the two work arounds above, 1) doesn't seem available in East Japan region yet 2) either manually, or using a daemonset (mentioned in other thread) will not work due to heavily restricted policies in place on my Azure instance (out of my control).

I did try updating the setting for the custom-ca-trust but it subsequently gets overridden (updated) to latest - any way to prevent these auto updates?

**Comment by UtheMan** [comment]
@davetheninja the fix should be available within 5-6 business days in Japan East region. The manual mitigation steps we suggested are the only way for users to fix the issue themselves. If waiting/manual mitigation is not an option, please create a support request.
