### ISSUE TITLE
Egress public IP (per service)

### ISSUE THREAD

**Issue by jalberto** [Azure/AKS#487]
By the docs, firts public IP created in the cluster is the one used for every egress traffic. This is not ideal as some services requires a control on the IP so access can be whitelisted.

Is there any way to choose which public IP each service will use? if not, what is the official approach to solve this uses cases?

I have 3 services, each one connect to azure PG DB service, I need to know which IP each service will use to whitelist the access, at same time, I will not like all of them to use same IP (because security and isolation)

**Comment by jalberto** [comment]
So as per documentation PODs will use first IP in the load balancer as output one, this makes very tricky to control which IP will be used, even more, Load Balancer IPs list seems can change in any moment, thi sjust happened to me, now I need to whitelist a new IP because it changed

**Comment by bergerx** [comment]
As far as I see in https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-outbound-connections#multife if you have multiple VIPs on a load balancer you can't know which one will be used for egress (outbound) traffic, this seems to be implemented as an optimization for possible SNAT port exhaustion.

And, any Kubernetes Service with "Type: LoadBalancer" will trigger a new VIP to be assigned to the load balancer. Any time in the cluster lifecycle any user can create a Service with "Type: LoadBalancer" and this simply makes defining rules ahead of cluster creation impossible, since the IP list will be increasing as we use more Service with "Type: LoadBalancer".

This exact issue also makes https://docs.microsoft.com/en-us/azure/aks/egress obsolete since that doc seems to be ignoring the fact that any Service with "Type: LoadBalancer" will trigger another VIP creation and that IP will be part of outgoing IP pool.

Same issue was already discussed in https://github.com/Azure/AKS/issues/189#issuecomment-365985940 previously.

**Comment by ritazh** [comment]
To ensure you can whitelist egress traffic from your services, one option is to create a nginx ingress controller with a static IP first. 

```
helm install stable/nginx-ingress --set controller.service.loadBalancerIP=<YOUR STATIC PUBLIC IP>
```
Then subsequently create each service and an ingress route for each service. Then you can whitelist the static IP used for the ingress controller since it will be the first IP on your loadbalancer. You can refer to this blog post for more details: https://ritazh.com/whitelist-egress-traffic-from-kubernetes-8a3adefd94b2

**Comment by jalberto** [comment]
@ritazh it doesn't works, check #497 

So only solution is to create one ingress per pub-IP, then assign each service to the ingress with the desired IP, but as soon you have multiple IPs in azure LB, you will never be sure which IP will be used

**Comment by bergerx** [comment]
@ritazh, this sentece doesn't seem to be complete as is:
> To ensure you can whitelist egress traffic from your services, one option is to create a nginx ingress controller with a static IP first.

It should be:
> To ensure you can whitelist egress traffic from your services, one option is to create a nginx ingress controller with a static IP first, *and prevent creation of any furter Service with Type:LoadBalancer*.

In which case the second part is not actually under control since we have no strict control over all possible clusters because of 2 main scenarios we have in use:
1. what is being deployed on a shared cluster among multiple teams is hard to coordinate and control without expressive restrictions,
2. we use some existing solutions that creates Service with Type:LoadBalancer.

Being able to restrict cluster users to create Service with Type:LoadBalancer would help for scenario 1. Currently even RBAC rules can't cover preventing its possible usage, our best bet seems to be writing an admission controller. And even though you do, it won't cover scenario 2.

For scenario 2, we'll have to modify the solutions we use if possible, to explicitly use ingress and not Service with Type:LoadBalancer. But each ingress router solution has their own restrictions which won't allow some cretain cases, for such cases the underlying solutions prefer Service with Type:LoadBalancer over ingress, there used to be valid reason for doing so.

**Comment by jnoller** [comment]
Closing this issue as old/stale/resolved.

Note: 
If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.

**Comment by posix4e** [comment]
Please reopen this issue. It's still an issue for me.

**Comment by heppth** [comment]
Yes, please reopen the issue. 

Issue #1116  is very similar
