### ISSUE TITLE
Understanding AKS compared to rolling my own VMSS

### ISSUE THREAD

**Issue by Plasma** [Azure/AKS#49]
Hi team,

I'm interested in understanding more about the difference between using my own VMSS to manage k8s versus AKS.

AKS brings some great benefits and cost reduction by not paying for masters, but there are a few questions:

1. When will Windows OS be supported for agent nodes?
2. Can we have multiple node types? To allow for running different workloads on different nodes.
3. Can you remote desktop/SSH into the nodes?
4. Understanding its a preview, but when I performed an aks cluster upgrade to update the kube version, my cluster and its pods went offline. This worries me about the PaaS safety of the platform.
5. If I roll my own VMSS, I can use the Azure Reserved Instance (RIs) system for cost reduction, but what happens if I use AKS?

Thank you

**Comment by sauryadas** [comment]
Answers 
1. Second half of 2018
2. No. When multiple agent pools are supported in the second half of 2018, you can have different node types in different pools
3. Yes you can
4. There was a bug that caused this a while back. Can you try again and let us know if the problem persists?
5. RI's cannot be used with AKS primarily because of the lack of billing support

**Comment by slack** [comment]
Going to close out this issue, let us know if you have any further questions.
