### ISSUE TITLE
Nodes not ready but pods are running

### ISSUE THREAD

**Issue by jungopro** [Azure/AKS#491]
```bash
$ kubectl get nodes
NAME                       STATUS     ROLES     AGE       VERSION
aks-nodepool1-79365606-0   NotReady   agent     4d        v1.9.6
$ kubectl get pods
NAME                                                     READY     STATUS      RESTARTS   AGE
alertmanager-kube-prometheus-0                           2/2       Running     0          4d
goodly-tarsier-prometheus-operator-create-sm-job-mbd94   0/1       Completed   0          4d
kube-prometheus-exporter-kube-state-676c4b7db9-cmwnx     2/2       Running     0          4d
kube-prometheus-exporter-node-msn9n                      1/1       Running     0          4d
kube-prometheus-grafana-7bcb88ff5f-fsghm                 2/2       Running     0          4d
looping-uakari-prometheus-operator-7b4c75ff-d6hfp        1/1       Running     0          4d
prometheus-kube-prometheus-0                             3/3       Running     1          4d
```
In addition, I can't access the pods. So the error is that the pods **appear** to be in a running state, but are actually not up and running

**Comment by sauryadas** [comment]
Can you please file support tickets for these issues ?

**Comment by aaron-bozit** [comment]
Thanks, just purchased a support plan and created a ticket.

**Comment by aaron-bozit** [comment]
@saad-msft Out of interest, what classified it as a bug?

**Comment by vlele** [comment]
I am also getting "NotReady" message. Looking at the logs it appears that there was disk pressure that caused this state.  
So I went ahead and added another node (using the scale operation).  Despite sucessfully adding the second node, I get "NotReady" for *both* nodes. 

Furtermore, I cannot  SSH into the node for troubleshooting since   I cannot get "SSH helper pod" up and running. 

Cluster version is v1.11.3

**Comment by jnoller** [comment]
Closing as solved/stale
