### ISSUE TITLE
TLS handshake timeout

### ISSUE THREAD

**Issue by przemolb** [Azure/AKS#493]
I have 2 node AKS cluster running for a while in east US. It has been created as 1.9.* but a few days ago (week ?) upgraded to 1.10.3. It went fine and worked fine. Until today:
```
$ kubectl get nodes
Unable to connect to the server: net/http: TLS handshake timeout
```
I have a few different AKS clusters and `kubectl get ...` works fine with them but with this particular one - doesn't. I have rebooted both nodes but it didn't help. I have scaled it down to 1 node and then back to 2 but it didn't help either.
How to investigate what is wrong ?

**Comment by przemolb** [comment]
I raised a ticket with Azure support but no fix so far. To be honest it makes the whole Azure AKS pretty much unreliable for production environments ...

**Comment by necevil** [comment]
@przemolb some information on this issue can be found in my post over here: 
https://stackoverflow.com/questions/50726534/unable-to-connect-net-http-tls-handshake-timeout-why-cant-kubectl-connect

That being said I have seen some indication that the AKS move to GA (general availability) and an upgrade to your cluster may solve the issue.  I have experienced the problem myself since I started documenting this stuff so at the very least I would say it's generally getting better.

Azure support should be able to help solve the problem (if nothing else works) but I have started collecting solutions in the thread over on Stackoverflow that may or may not work in your situation.  For example resizing your Cluster nodes up by one and then back down to the original size (which worked in my case) from the Azure blade UI.

Most other users (you can find several other github threads still open) have had success waiting on support if one of the easy trouble-shoot-it-yourself options doesn't get the job done.  Hope that helps!

**Comment by przemolb** [comment]
@necevil it was working before I did an upgrade to 1.10.3. After the upgrade it was still working. And then after a few days I lost control of the cluster.
I found your post but it it didn't help me.
I raise a support call with Azure and after 2-3 days they fixed it. But it was 2-3 days without the cluster. I wish I could treat GA as production ready but in this case I cannot really fully trust it.

**Comment by mboersma** [comment]
It sounds like Azure support was able to fix this cluster. I hope you're working now @przemolb, but if not please re-open this issue or send a support request to aks-help@service.microsoft.com so we can investigate further.
