### ISSUE TITLE
HTTP Application Routing lacks sufficient permissions to work when in Advanced Networking

### ISSUE THREAD

**Issue by dave-hillier** [Azure/AKS#507]
I had to add permissions for the created service principal to change the DNS

I got this error in the logs:
```
level=error msg="azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/e254f09e-7285-4329-be2a-a25588a65b44/resourceGroups/MC_rezlynx-ci-aks-rg_rezlynx-ci_westeurope/providers/Microsoft.Network/dnsZones?api-version=2016-04-01: StatusCode=0 -- Original Error: adal: Failed to execute the refresh request. Error = 'Post https://login.microsoftonline.com/8ddfa7f9-ccbb-46b8-a69f-88eed53e39c0/oauth2/token?api-version=1.0: dial tcp: i/o timeout'" 

```

**Comment by weinong** [comment]
https://docs.microsoft.com/en-us/azure/aks/networking-overview

### Advanced networking prerequisites

**The service principal used for the AKS cluster must have Contributor permissions to the resource group containing the existing VNet.**

There is an improvement in Azure Portal such that it will create the proper role assignment for you when you use advanced networking

**Comment by dave-hillier** [comment]
Given that the Portal created both the VNet and the SP it seems like this could do with improvement in the portal, even if it's a note that you must do this.

**Comment by holmesb** [comment]
"There is an improvement in Azure Portal such that it will create the proper role assignment for you when you use advanced networking" - Are you sure you haven't broken cluster creation for SPs with only Contributor rights?  Changing role assignments requires more than Contributor rights. 

We can no longer create AKS clusters due to error:

**Comment by holmesb** [comment]
"Service Principal used for the AKS cluster must have Contributor permissions"..."There is an improvement in Azure Portal such that it will create the proper role assignment for you when you use advanced networking" - I think you've broken cluster creation for SPs with only Contributor rights.  Changing role assignments requires more than Contributor.

We can no longer create AKS clusters due to error:

```
"InvalidTemplateDeployment
The template deployment failed with error: 'Authorization failed for template resource '<VNet>/<Subnet>/Microsoft.Authorization/<some kind of id>' of type 'Microsoft.Network/virtualNetworks/subnets/providers/roleAssignments'. The client '<my email address>' with object id '<object id>' does not have permission to perform action 'Microsoft.Authorization/roleAssignments/write' at scope '/subscriptions/<subscription>/resourceGroups/<VNet Resource Group>/providers/Microsoft.Network/virtualNetworks/Asos-vNet-EUW-AsosDigitalCoreDevTest/subnets/<subnet>/providers/Microsoft.Authorization/roleAssignments/<some kind of id>'.
```

**Comment by weinong** [comment]
@holmesb that error message means the user who was creating AKS doesn't have that permission to perform role assignment.

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
