### ISSUE TITLE
Intermittent networking issues with job

### ISSUE THREAD

**Issue by dave-hillier** [Azure/AKS#511]
I have had intermittent networking issues but it is easiest to see with a Cron Job. I have noticed this problem on an older cluster (20 days old) and a 1 day old cluster.
 
I have a Cron Job that creates a container every 5 minutes. Occasionally, one of the containers won't be able to resolve DNS or connect to any other container simply getting a timeout. 

Even weirder, this failure caused that one to enter a restart loop, and it never succeeds despite the fact that the Cron Job subsequently schedules more containers. For example, I had a two containers container 6 hours old with ~50 restart attempts even though around 80 other jobs had run since those two. 

The job itself is an alpine container curl a number of URLs of services within the cluster.

**Comment by baracoder** [comment]
I also experience networking problems with AKS v1.10.3, which might be related.
The nginx ingress controller sometimes won't update the configuration. I tried restarting it, it immediately failed because it could not connect to the kubernetes api. Then restarting the pod again, it worked.
Also sometimes other pods can only reach some of the replicas of a service, even though accessing the pods by the endpoint IP works from the affected pod. So far I can not tell, what is wrong but restarting pods seams to "help".

**Comment by marulm** [comment]
Even we are facing similar issue on both AKS v1.10.3 (w/RBAC and w/o RBAC) and v1.9.6 (w/RBAC and w/o RBAC) where ingress endpoints are not getting updated with newly created pods. This issue is first observed on 10-Jul-2018. All these clusters are at least 2 weeks old and we never faced this issue before. 
If we restart ingress controller pod, endpoints are updated correctly.
Not sure if its related but we can see following in logs:
"reflector.go:341] k8s.io/ingress-nginx/internal/ingress/controller/store/store.go:140: watch of *v1.Endpoints ended with: too old resource version: 1125452 (1126770)"
"[crit] 325#325: *3915 SSL_do_handshake() failed (SSL: error:1417D102:SSL routines:tls_process_client_hello:unsupported protocol) while SSL handshaking, client: 66.193.205.122, server: 0.0.0.0:443"

Controller args:
        args:
          - /nginx-ingress-controller
          - --default-backend-service=$(POD_NAMESPACE)/web-default-backend
          - --ingress-class=web-ingress          
          - --configmap=$(POD_NAMESPACE)/web-nginx-configuration
          - --watch-namespace=$(POD_NAMESPACE)
          - --force-namespace-isolation=true 

image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.15.0

**Comment by dave-hillier** [comment]
@marulm that sounds like a different issue I raised: https://github.com/Azure/AKS/issues/508

**Comment by dave-hillier** [comment]
I suspect this might actually be an Alpine bug...

https://bugs.alpinelinux.org/issues/8025

I'm going to switch my containers to Ubuntu

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
