### ISSUE TITLE
Issues with ACR authorization when AKS cluster created with SP name not appId

### ISSUE THREAD

**Issue by sjdweb** [Azure/AKS#540]
I found issues with the Azure ACR/AKS Service Principal auth integration.

The cluster was created with the clientId set to the SP name (e.g. `http://appname/`) instead of the appId (e.g. `0000-000-000`).

I ran through my problem with @andyzhangx and found that the only way this worked was to create a brand new cluster with the clientId set to the SP appName.

The docs do say this should be possible [here](https://docs.microsoft.com/en-us/azure/aks/kubernetes-service-principal#additional-considerations) 

```
When specifying the service principal Client ID, use the value of the appId (as shown in this article) or the corresponding service principal name (for example,https://www.contoso.org/example).
```

So may be worth updating the docs to only say `appId`.

**Comment by andyzhangx** [comment]
@neilpeterson

**Comment by neumanndaniel** [comment]
The docs are misleading or the az cli output in general, when you are using az ad sp create-for-rbac --skip-assignment. In the output "name" has the value of the reply URL and that would never work during an assignment, referencing the SP via the reply URL. If you look at the SP via the Azure portal you will recognize that the "name" of the SP is the same as the "displayName" output of the az cli command azure-cli-2017-10-15-02-20-15.

Nevertheless the recommendation for referencing or using a SP is to use the appId, because the appId is the unique identifier of an Azure SP.

**Comment by sjdweb** [comment]
I see @neumanndaniel. I've used the `name` value as the clientId in earlier ACS clusters also without problem as the docs recommended it too.

The ACS and AKS clusters always functioned fine using the SP `name` (e.g. `http://azure-cli-2018-07-06-15-00-13`) it was only the newer ACR integration that failed.

**Comment by neumanndaniel** [comment]
Good to know. I have run into issues in the past relating to the names. Even using what we proposing in the docs. So, I switched to the appId. :)

**Comment by weinong** [comment]
This seems like a bug in upstream. @khenidak ?

**Comment by jnoller** [comment]
Closing this issue as old/stale.

If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.

w
