### ISSUE TITLE
AKS deployed kubelets do not evict and have no system-reserved resources

### ISSUE THREAD

**Issue by mbrancato** [Azure/AKS#545]
I've noticed that even when 'free' memory runs less than 100MB (I observed 82MB), the kubelet does not evict pods. I'm not sure if this an an upstream issue, this was with AKS and 1.9.9. By default, AKS sets `--eviction-hard=memory.available<100Mi` for memory.

That said, AKS has QoS enabled but does not set *any* `system-reserved` resources for memory or CPU on the kubelet runtime. I've had this assist in`NodeLost` scenarios with AKS clusters.

The current default kublet command line in AKS is:

```
/usr/local/bin/kubelet --enable-server --node-labels=kubernetes.io/role=agent,agentpool=nodepool1,storageprofile=managed,storagetier=Premium_LRS,kubernetes.azure.com/cluster=MC_redacted_redacted_eastus --v=2 --volume-plugin-dir=/etc/kubernetes/volumeplugins --address=0.0.0.0 --allow-privileged=true --anonymous-auth=false --authorization-mode=Webhook --azure-container-registry-config=/etc/kubernetes/azure.json --cadvisor-port=0 --cgroups-per-qos=true --client-ca-file=/etc/kubernetes/certs/ca.crt --cloud-config=/etc/kubernetes/azure.json --cloud-provider=azure --cluster-dns=10.0.0.10 --cluster-domain=cluster.local --enforce-node-allocatable=pods --event-qps=0 --eviction-hard=memory.available<100Mi,nodefs.available<10%,nodefs.inodesFree<5% --feature-gates= --image-gc-high-threshold=85 --image-gc-low-threshold=80 --image-pull-progress-deadline=30m --keep-terminated-pod-volumes=false --kubeconfig=/var/lib/kubelet/kubeconfig --max-pods=30 --network-plugin=cni --node-status-update-frequency=10s --non-masquerade-cidr=10.2.1.0/24 --pod-infra-container-image=k8s-gcrio.azureedge.net/pause-amd64:3.1 --pod-manifest-path=/etc/kubernetes/manifests
```

**Comment by weinong** [comment]
We have plan to enable `--kube-reserved` on kubelet. This will probably go live in two weeks.

**Comment by woodsaj** [comment]
so we just had our services taken down because Azure decided to go and apply --kube-reserved to all of our nodes reducing our capacity by 20%.  

We had a 3 node database cluster running in AKS, with each database POD on a dedicated k8s node and configured with 85% of the allocated memory.  So as soon as this new --kube-reserved setting was applied all 3 of our database PODs where evicted from their node and left unable to be scheduled due to there suddenly being no nodes in the cluster with enough capacity.

It just seems insane that Azure would apply a change like this with no notice to customers.  
@weinong  Is this the level of service we are to expect from Azure or is this just an isolated oversight?

**Comment by andremelim** [comment]
@woodsaj Can you share details on which region / version of AKS you are using?
 I'd like to have the reservations on our new clusters as we have experienced outages due to over use of memory/cpu.

**Comment by jnoller** [comment]
Closing this issue as old/stale/resolved.

Note: 
If this issue still comes up, please confirm you are running the latest AKS release. If you are on the latest release and the issue can be re-created outside of your specific cluster please open a new github issue.

If you are only seeing this behavior on clusters with a unique configuration (such as custom DNS/VNet/etc) please open an Azure technical support ticket.
