### ISSUE TITLE
AKS Nodes default installed Docker version support

### ISSUE THREAD

**Issue by rfum** [Azure/AKS#549]
I've just realized that AKS nodes are using an old version of docker engine. Does any update plans exists? Or do we have to update the engine our own? Because it's blocking our pipeline we cannot build multistaged dockerfiles.

Here is the output of `docker version` : 
```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by weinong** [comment]
We are investigating to update the docker version.

**Comment by yaron-idan** [comment]
We are also interested in a way to upgrade docker version on the AKS clusters. Specifically because we aim at migrating from acs-engine since our nodes met this issue - https://github.com/moby/moby/issues/31768, and moving to AKS with the same docker version seems to increase the odds of meeting this issue again.

**Comment by MarkTopping** [comment]
@rfum I've previously raised this as an issue since I needed to achieve the same thing.

These issues might be of interest to you; but it isn't good news (or wasn't):
https://github.com/Azure/acs-engine/issues/2589#issuecomment-397424928
andd
https://github.com/Azure/acs-engine/issues/3213#issuecomment-402318304

**Comment by seanmck** [comment]
You can upvote this request and follow status here:

https://feedback.azure.com/forums/914020-azure-kubernetes-service-aks/suggestions/34917076-increase-kubernetes-node-docker-version-to-17-05-x

**Comment by adrienjt** [comment]
@seanmck the link is broken.

**Comment by jibinjohnbabu** [comment]
This issue is frustrating as we are blocked from implementing multistaged docker files. HELP
