### ISSUE TITLE
Default storage class consistently resets back to `default`

### ISSUE THREAD

**Issue by AaronFriel** [Azure/AKS#550]
**What happened**:

I ran the following command against my kubernetes cluster:

```
kubectl patch storageclass default \
  -p '{"metadata": {"annotations":{"storageclass.beta.kubernetes.io/is-default-class":"false"}}}'
```

**What you expected to happen**:

I would expect the `default` class to have the annotation: `"storageclass.beta.kubernetes.io/is-default-class":"false"` and for the change to persist.

It does not.

**How to reproduce it (as minimally and precisely as possible)**:

Apply the patch in the description.

**Anything else we need to know?**:

This occurs on the latest AKS version as of 2018-07-23, 1.10.5, with RBAC enabled.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10.5
- Size of cluster (how many worker nodes are in the cluster?): 1 node
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): n/a
- Others:

**Comment by AaronFriel** [comment]
Please make it not the default?

**Comment by weinong** [comment]
Can you post the feature request at https://feedback.azure.com/forums/914020-azure-kubernetes-service-aks

**Comment by adelwin** [comment]
I think this shouldn't be a feature request.

As an initial setup of AKS, yes it makes sense to set a default storage class, but we improve our pattern over time.

I have an AzureFile setup in my cluster, and due to the nature of it, I consciously want to set AzureFiles as the default storage-class, it's available as RWX.

I think the kube-controller-manager should only set back the default storage-class when there's no other storage-class in the cluster that is marked as default.
This makes sense to prevent issue with storage provisioning when there's no storage-class specified in the manifest.
But for us who knowingly added additional storage-class and knowingly update the annotation to set others as default shouldn't be penalized by resetting back the default storage provider.

We know what we're doing and we intentionally do it as such, and resetting the storage class means there's no way to update the default storage class.

Please reconsider.
