### ISSUE TITLE
Confusing versioning and no changelog

### ISSUE THREAD

**Issue by gugu91** [Azure/AKS#604]
Currently it's quite hard, in my opinion, to figure out which issues are tied with which version.
Mainly this stems from:

- Versions appear to be tied to kubernetes versions. That's quite confusing if bugs are vendor specific
- There is hardly any indication of which release solved issues that get closed
- I can't find any AKS specific changelog anywhere
- I can't find a public roadmap/backlog

**Comment by jnoller** [comment]
Hi Guglielmo / community:

First apologies for a lack of response to this - we're actively working to clean up the AKS github presence and put in place a scalable process so that issues like this, and others do not get missed.

To your questions:

1. We have a work item planned for 1H2019 (First half, 2019) to separate the versions of Kubernetes from AKS versions. The intent is to be able to show that in AKS version X, the components includes are version 1,2,3. This means it will be easier to see what versions of what are in the service.
2. This is in progress - you're perfectly right we have not done a great job on communication of changes from version to version. We're looking at this now and plan to have a public changelog soon.
3. See 2
4. This is a hard one - but without going into why, I can say we are working on cleaning up this repo and all bugs to better label known issues with the service (or k8s version, etc),  and we intend to have a clearly marked series of github issues representing what we are committed to delivering within the next 6 months.

However, I can not commit to a public AKS backlog - obviously reported issues here will be marked, tracked and closed when resolved. However we have an internal backlog as well due to the nature of AKS so tracking all backlog items on Github is not currently feasible for the team.

**Comment by jnoller** [comment]
Closing this issue as we now have:

https://github.com/Azure/AKS/releases
https://github.com/Azure/AKS/blob/master/CHANGELOG.md

The roadmap is coming, the improved AKS versioning work is also still in scope for 2019

**Comment by jluk** [comment]
Closing as Jesse mentioned in previous comment.
