### ISSUE TITLE
AKS Ingress - 404 

### ISSUE THREAD

**Issue by mariojacobo** [Azure/AKS#635]
**What happened**:

Kubernetes Ingress not working. All requests are directed to the default 404 backend. This has been working for many months. I would have filed a ticket with support, but for some reason that is malfunctioning as well (hangs on loading the support plan in the ticket creation blade): 

$ kubectl -n kube-system logs addon-http-application-routing-nginx-ingress-controller-86s48zw 
E0904 15:01:30.087167       7 backend_ssl.go:145] unexpected error generating SSL certificate with full intermediate chain CA certs: Invalid certificate.
E0904 15:02:30.087461       7 backend_ssl.go:145] unexpected error generating SSL certificate with full intermediate chain CA certs: Invalid certificate.
E0904 15:03:30.087774       7 backend_ssl.go:145] unexpected error generating SSL certificate with full intermediate chain CA certs: Invalid certificate.
E0904 15:04:30.088109       7 backend_ssl.go:145] unexpected error generating SSL certificate with full intermediate chain CA certs: Invalid certificate.
E0904 15:05:30.088399       7 backend_ssl.go:145] unexpected error generating SSL certificate with full intermediate chain CA certs: Invalid certificate.
E0904 15:05:42.846478       7 streamwatcher.go:109] Unable to decode an event from the watch stream: stream error: stream ID 619; INTERNAL_ERROR
I0904 15:05:42.921214       7 store.go:295] ignoring delete for ingress nginx based on annotation kubernetes.io/ingress.class
I0904 15:05:42.921325       7 controller.go:170] backend reload required
I0904 15:05:42.921393       7 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"default", Name:"nginx", UID:"cdd8d4ce-b053-11e8-b520-faf11cb159b1", APIVersion:"extensions", ResourceVersion:"158473", FieldPath:""}): type:'Normal' reason: 'CREATE' Ingress default/nginx
I0904 15:05:42.988271       7 controller.go:179] ingress backend successfully reloaded...
2018/09/04 15:05:42 [alert] 30#30: sendmsg() failed (88: Socket operation on non-socket)
2018/09/04 15:05:42 [alert] 30#30: sendmsg() failed (88: Socket operation on non-socket)
2018/09/04 15:05:42 [alert] 30#30: sendmsg() failed (88: Socket operation on non-socket)
2018/09/04 15:05:42 [alert] 30#30: sendmsg() failed (88: Socket operation on non-socket)
2018/09/04 15:05:42 [alert] 30#30: sendmsg() failed (88: Socket operation on non-socket)
2018/09/04 15:05:42 [alert] 30#30: sendmsg() failed (88: Socket operation on non-socket)
2018/09/04 15:05:42 [alert] 30#30: sendmsg() failed (88: Socket operation on non-socket)

**What you expected to happen**:
The ingress should forward traffic to the required service: 
$ kubectl describe ingress
Name:             nginx
Namespace:        default
Address:          REDACTED
Default backend:  nginx:80 (10.48.0.21:80)
Rules:
  Host  Path  Backends
  ----  ----  --------
  *     *     nginx:80 (10.48.0.21:80)
Annotations:
  kubernetes.io/ingress.class:  addon-http-application-routing
Events:
  Type    Reason  Age   From                      Message
  ----    ------  ----  ----                      -------
  Normal  CREATE  10m   nginx-ingress-controller  Ingress default/nginx
  Normal  UPDATE  9m    nginx-ingress-controller  Ingress default/nginx

**How to reproduce it (as minimally and precisely as possible)**:

Default 1.10.3 cluster with a simple ingress: 

$ kubectl run nginx --image=nginx --port=80 
$ kubectl expose deployment nginx --target-port=80 --port=80
$ kubectl create -f ingress.yaml 

$ cat ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  backend:
    serviceName: nginx
    servicePort: 80

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by mariojacobo** [comment]
@saykumar 
We managed to fix it by deleting the Ingress POD in the "kube-system" namespace. Kubernetes recreated it and it seems to have done the trick

**Comment by oscarwest** [comment]
Reopening this issue since we are also getting this error.
Tried restarting the ingress-controller pods to no avail. Everything in the cluster stills works, routing works. We just don't know why we're getting this error.

E0108 15:26:26.969843       7 backend_ssl.go:145] unexpected error generating SSL certificate with full intermediate chain CA certs: Invalid certificate.

Versions and Info:

AKS Version: 1.11.5
quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.14.0

**Comment by aswinraaj** [comment]
We are facing the same issue as well.

**Comment by jnoller** [comment]
First, thank you for reaching out to the AKS team. 

AKS Github issues must be generally re-creatable (e.g here is the YAML/settings/packages/etc installed, can recreate the issue on existing clusters as well as newly created clusters). Unfortunately, this issue is cluster-specific.

For cluster specific issues (those that will require support and on-call staff to access you Subscription and clusters) we ask that you file an Azure Technical Support ticket with the identified issue, rec-creation steps if available, and link to this github thread.

**We can not ask** for the access, logs and other sensitive information on github, or ask you to email/slack/etc this information to us. Our portal ticketing system will protect the information including Subscription ids and credentials. If we discover as part of the root cause that this is an AKS or upstream bug, we will mark this issue as a known issue and ensure it is on the Product backlog as a repair item.

This will allow us to root-cause the issue and ensure it’s not specific to the environment or other configuration level issue - such as NSGs, custom network devices, etc.

Jesse

**Comment by aswinraaj** [comment]
My issue was resolved . I had applied a wrong value to the ingressClass in my ingress rule in default namespace.
