### ISSUE TITLE
dnsPrefix with dot results in i/o timeout

### ISSUE THREAD

**Issue by wazowsk1** [Azure/AKS#717]
**What happened**:
Created a kubernetes cluster with ARM template, using a dot in the dnsPrefix.

Deployment works, but when I try to get the logs or browse the kubernetes dashboard, I get the following error

```
 dial tcp 10.240.0.4:10250: i/o timeout
```
(took me some time to finally figure out this was causing the error)

I also noticed that the tunnelfront pod keeps restarting.

**What you expected to happen**:

Not getting the above error

**How to reproduce it (as minimally and precisely as possible)**:
Deploy AKS with ARM template with a dnsPrefix that has a dot in the name

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
1.11.3
- Size of cluster (how many worker nodes are in the cluster?)
1
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
Default (empty), nothing deployed yet
- Others:

**Comment by felipeOliveira** [comment]
I have the same problem with one of my aks environments. Via command line I can list pods, nodes and services, but if I try exec a kubectl exec or try see the dashboard I getting this error

> Error: 'dial tcp 10.244.0.64:9090: i/o timeout'
Trying to reach: 'http://10.244.0.64:9090/'

I don't know if this problem is related with vm size, because this ocurs in a aks with 3 nodes of Standard_B2S

**Comment by palma21** [comment]
Fixed. Portal/CLI/ARM/SDK no longer accepts dots
