### ISSUE TITLE
CVE-2018-1002105 patch status ?

### ISSUE THREAD

**Issue by mdaguete** [Azure/AKS#740]
Hi all,

What's the patch status for CVE-2018-1002105 ?

Thanks. Regards.

**Comment by scotta01** [comment]
There is an announcement [here](https://azure.microsoft.com/en-us/updates/aks-clusters-patched-for-kubernetes-vulnerability/)

**Comment by erewok** [comment]
Is anyone else confused by the announcement? It reads:

> In preparation for this announcement, Azure Kubernetes Service has patched all affected clusters...

And closes with:

> If you want to upgrade to a Kubernetes release that contains the underlying fix, we have now made version 1.11.5 available.

I'm running 1.11.4, but it *sounds like* I must upgrade to avoid the vulnerability?

**Comment by seanmck** [comment]
Let me try to clarify: there is the vulnerability and there is who can exploit the vulnerability. The patch we applied removes the ability for an _unauthenticated_ user to exploit the vulnerability. New Kubernetes releases like 1.11.5 include the fix for the vulnerability itself.

Make sense?

**Comment by ktsdev** [comment]
> The patch we applied removes the ability for an unauthenticated user to exploit the vulnerability

**Comment by ortelli-oxalide** [comment]
> The patch we applied removes the ability for an unauthenticated user to exploit the vulnerability
Is this the case for clusters were RBAC is not enabled too (which was the default at least until few months ago)? 

Also, metrics server was not installed by default before version 1.11, so many people installed it "manually" on the cluster. Should something be done around metrics server settings?

**Comment by ortelli-oxalide** [comment]
I tried to answer the question by myself, with the help of this tool: https://github.com/gravitational/cve-2018-1002105
I have 3 clusters, all with **RBAC disabled**, one is at version 1.9, another is at version 1.10, and the last at version 1.11.5. **Only the one at version 1.11.5 is reported as not vulnerable**

Microsoft, could you please be more precise and better explain your statement here?
> The patch we applied removes the ability for an unauthenticated user to exploit the vulnerability

How can you explain that my 1.9 and 1.10 are vulnerable ? Is that because of RBAC disabled ? Wouldn't it be a good idea to apply a patch for rbac-disabled clusters too?
