### ISSUE TITLE
AKS cluster nodes sometimes stop getting updated

### ISSUE THREAD

**Issue by doug-fish** [Azure/AKS#748]
**What happened**:
One node is my AKS cluster appears to have not been updated recently and is running a different kernel level than the other nodes:

    k get nodes -o yaml | grep kernelVersion:
    kernelVersion: 4.15.0-1032-azure
    kernelVersion: 4.15.0-1035-azure
    kernelVersion: 4.15.0-1035-azure

I am running kured, so I'd expect any needed reboot to happen automatically. The file /var/run/reboot-required does not exist on the node.

**What you expected to happen**:
All of the nodes always get the latest patches.

**How to reproduce it (as minimally and precisely as possible)**:
Unsure. I just have to leave the cluster running, sometimes nodes stop getting patched.

**Anything else we need to know?**:
Sometimes the updates do happen properly - For example, all of the nodes received the patch associated with kernel version kernelVersion: 4.15.0-1032-azure without trouble.

The problem has occurred previously. I've brought nodes up to date by scaling the cluster down + back up, and by deleting problem nodes and scaling down and back up.

Some log info from Kured from the out of date node:
k logs -n   kube-system                kured-76d85 
time="2018-11-22T06:29:35Z" level=info msg="Kubernetes Reboot Daemon: master-5731b98"
time="2018-11-22T06:29:35Z" level=info msg="Node ID: aks-agentpool-10370064-1"
time="2018-11-22T06:29:35Z" level=info msg="Lock Annotation: kube-system/kured:weave.works/kured-node-lock"
time="2018-11-22T06:29:35Z" level=info msg="Reboot Sentinel: /var/run/reboot-required every 1h0m0s"
time="2018-11-22T06:29:35Z" level=info msg="Holding lock"
time="2018-11-22T06:29:35Z" level=info msg="Uncordoning node aks-agentpool-10370064-1"
time="2018-11-22T06:29:39Z" level=info msg="node \"aks-agentpool-10370064-1\" uncordoned" cmd=/usr/bin/kubectl std=out
time="2018-11-22T06:29:39Z" level=info msg="Releasing lock"
time="2018-11-22T07:17:01Z" level=info msg="Reboot not required"
time="2018-11-22T08:17:01Z" level=info msg="Reboot not required"
.. repeat for a few weeks
time="2018-12-06T20:17:01Z" level=info msg="Reboot not required"
time="2018-12-06T21:17:01Z" level=info msg="Reboot not required"

**Environment**:
- Kubernetes version (use `kubectl version`):
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.9", GitCommit:"57729ea3d9a1b75f3fc7bbbadc597ba707d47c8a", GitTreeState:"clean", BuildDate:"2018-06-29T01:07:01Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

- Size of cluster (how many worker nodes are in the cluster?)
3 nodes
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
Lightweight PoC usage of Java, Node, Mongo, and Python applications. Twistlock in use for security.

- Others:

**Comment by doug-fish** [comment]
One other potentially relevant piece of information: this cluster is undersized from a number of IP addresses available perspective - it has 3 nodes with 30 pod IP available per node. There are 84 pods running in the cluster total, including 30 on the node that didn't get updated:

k describe nodes aks-agentpool-10370064-1 | grep "Non-terminated Pods: "
Non-terminated Pods:         (30 in total)

Any chance the update process involves starting a new pod?

**Comment by jnoller** [comment]
First, thank you for reaching out to the AKS team. 

AKS Github issues must be generally re-creatable (e.g here is the YAML/settings/packages/etc installed, can recreate the issue on existing clusters as well as newly created clusters). Unfortunately, this issue is cluster-specific.

For cluster specific issues (those that will require support and on-call staff to access you Subscription and clusters) we ask that you file an Azure Technical Support ticket with the identified issue, rec-creation steps if available, and link to this github thread.

**We can not ask** for the access, logs and other sensitive information on github, or ask you to email/slack/etc this information to us. Our portal ticketing system will protect the information including Subscription ids and credentials. If we discover as part of the root cause that this is an AKS or upstream bug, we will mark this issue as a known issue and ensure it is on the Product backlog as a repair item.

This will allow us to root-cause the issue and ensure it’s not specific to the environment or other configuration level issue - such as NSGs, custom network devices, etc.

Jesse
