### ISSUE TITLE
Default Security Rules

### ISSUE THREAD

**Issue by jungopro** [Azure/AKS#752]
Hello
This is a general question....

When I deploy an AKS cluster, the default NSG allows 80 & 443 to th LB and the LB is allowed to all my subnet...
Meaning, http traffic is wide open to the univers right out of the gate

Any reason this is done this way? Is it safe to close it or is it needed to proper cluster operation?

Thanks
Omer

**Comment by yves-vogl** [comment]
I hope it's ok when I try to answer this.

I guess you mean the Load Balancer service which is created for Kubernetes Ingress and specific Services and the AllowAzureLoadBalancerInBound rule.

Instead of inverting this open policy we add further restrictions to the Kubernetes objects which configure the NSG appropriately.

```yaml
kind: Service
apiVersion: v1
metadata:
  name: example-svc
spec:
  type: "LoadBalancer"
  loadBalancerSourceRanges:
  - <cidr>
```

But note that for Ingress resources there's the ```nginx.ingress.kubernetes.io/whitelist-source-range``` annotation which does not get translated into NSG and acts solely on layer 7.

I think inverting this to a NSG which needs explicit rules to allow traffic could only be restricted concerning its ports. As far as I understand (at least with Azure CNI) the traffic is routed to each node which forwards the traffic to the corresponding pods through its service. The service has an ip address from the service CIDR and is represented as an overlay network and not attached to the Azure VNET. As you use a subnet for all of you nodes and all nodes need to accessible by the Load Balancer and you should not allocate ip addresses other than those for AKS nodes in the subnet it's more of a low risk to me.

**Comment by jungopro** [comment]
I see now that this setting doesn't happen on a new cluster deployment, so I'm closing this issue
