### ISSUE TITLE
Support for rotating cluster-admin credential

### ISSUE THREAD

**Issue by cwebbtw** [Azure/AKS#756]
**What happened**:

I was able to access the AKS cluster using `kubectl` with my client certificate after being removed from the subscription.

**What you expected to happen**:

I expect that if I am using managed Kubernetes, if I am removed from the subscription, my certificate should no longer grant access to the cluster. Perhaps possible to configure TTL on client certificate?

Using RBAC, I could minimise the effect of this, although using guest invites to the active directory is a problem, but if someone who once had access to my cluster at contributor level no longer works for me, I don't think that rebuilding the cluster is a suitable option.

**How to reproduce it (as minimally and precisely as possible)**:

To reproduce: 

`az aks get-credentials --resource-group <resource group> --name <cluster> --admin`

Then get removed from the subscription, then run:

`kubectl get nodes`

**Environment**:
- Kubernetes version (use `kubectl version`):

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-05-12T04:12:12Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Size of cluster (how many worker nodes are in the cluster?)

3

- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)

N/A

- Others:

N/A

**Comment by jnoller** [comment]
I've marked this as a known-issue. It is on the AKS roadmap for this year. Some context - currently we are aware that the admin credentials for a cluster are set at creation time and cannot be changed without a rebuild of the cluster. Resolution of this issue will meet the following criteria:

Customers are able to rotate the certificates returned in a kubeconfig for cluster-admin
Customers are able to rotate the certificates returned in a kubeconfig for cluster-user

Control must be exposed via the API and available in the cli. Azure Portal controls will come directly after the API and CLI support

**Comment by ediazrod** [comment]
Any updates about this issue?.

Regards!

**Comment by cwebbtw** [comment]
Are there any updates for this?

**Comment by Xorima** [comment]
thanks for pointing me here @jnoller

as per my previous comment could we all please get an update on this as it is a major security risk ...

**Comment by jnoller** [comment]
It is on track for 2019 delivery.

**Comment by zuehlke-dea** [comment]
It is possible to reset the credentials with a support ticket? We have the problem that people left the company having the admin credentials. Theoretically they still have access to production environments. We were not aware that the certificates are valid for such a long period.

**Comment by Aadryn** [comment]
Does this solution will support the behavior of just-in-time (JIT) access available with the component of Azure AD PIM ?

**Comment by jnoller** [comment]
@zuehlke-dea  It is not.

**Comment by zuehlke-dea** [comment]
ok. Thank you. Then we have to wait for the feature.

**Comment by jluk** [comment]
Thanks for your patience folks, this is still on the plan and we are investing in it.

**Comment by marcel-dempers** [comment]
Are clusters going to require a complete rebuild to use this feature once GA ?
Or should we hold off on moving our workloads to AKS because this is quite a big security risk for us.

**Comment by Xorima** [comment]
So to confirm it looks like it will take a year for a fairly major security issue to be resolved, is this the timescale we should expect for all authentication related issues with AKS or is this only for issues revolving around Administrator access revocation in future?

**Comment by sauryadas** [comment]
Apologies for the delay. We are planning to allow rotation of credentials in Nov. Users will need to create new clusters . Unfortunately there is no way to rotate the certificate today.

**Comment by zuehlke-dea** [comment]
I am happy to hear that this feature will come. Nevertheless as it requires a recreation of the AKS it will not bring us too much benefit anyway. As we run 5 AKS with one in production it is really a bit annoying that we need to recreate it for every new feature. (and there are more we are waiting for)

As the admin context certificates (at least ours) expire in 2021, it is required for all AKS to be recreated if the context should be still useable. Will there be an announcement or will it be a surprise? :) (sorry just kidding)

**Comment by DaveAurionix** [comment]
+1 for more new features to have the capability of deploying/upgrading/enabling in-place on existing clusters wherever possible.

Creating a second cluster, setting up new temporary dns entries, updating all software release pipelines to deploy to this second cluster, checking all software tests ran against new cluster, switching old DNS over to new cluster, tearing down old cluster and tearing down temporary DNS and temporary config, this is a LOT of effort.  Even with 100% release automation, it isn't great for us that critical new features and fixes need a complete rebuild.

Once updated, AKS is working brilliantly for us.  We really appreciate the work you all do.

**Comment by sauryadas** [comment]
We are working on removing the certificate entirely that is returned in the kube config file. The problem is that there is no way to invalidate the certificate in the config file. Instead in the new implementation we will replace the certificate with static tokens that can be rotated/invalidated once someone leaves the team or no longer requires access to a cluster. This will work with existing clusters; meaning once we release this feature you can upgrade your cluster and going forward from that point get-credentials will return a config file without certificates. The problem with existing clusters though is that someone with an older config file that has the certificate will still be able to access the cluster.

**Comment by zuehlke-dea** [comment]
Thank you for this information. It is very valuable for our decisions.

**Comment by cwebbtw** [comment]
The approach that Amazon EKS use has been very useful for managing users in AWS. The static token approach using webhook tokens seems like an appropriate solution, which is really good to hear. The diagram below highlights how the user authentication works and then how RBAC is authorised with EKS.

![image](https://user-images.githubusercontent.com/31657038/66422823-53e71c80-ea02-11e9-8585-2df0203e6049.png)

The process of authenticating is:

1. Client makes a request to the API server and passes a static token with a short lived user identifier.
2. The API server forwards the token to a service on the k8s control plane, in Amazon's case, (aws IAM authenticator - server side)
3. The server side authenticator confirms with IAM that the user's identifier is valid and is *still* valid (still valid being the key thing here, short lived tokens++). (authenticated)
4. Internal checks are performed to validate that the user has access to the cluster (authorised step 1, aks authorisation)
5. The server side authenticator then confirms with a config map that the IAM user/group has a mapping to a role inside k8s, i.e. cluster-admin. (authorised step 2, k8s authorisation)
6. An appropriate error is returned or the response to the request returned.

The downsides of this approach is almost certainly that the user had to have aws-iam-authenticator installed, although they recently added this to the cli. The kubeconfig would then look like:

![image](https://user-images.githubusercontent.com/31657038/66423593-e89e4a00-ea03-11e9-91fa-53365b33f859.png)

Making use of _exec_.

**Comment by LudoNieuw** [comment]
Hi there, 
Checking in to ask when this feature will be released. I see it was first scheduled in 2018, last mention from MS side was November this year, and this month is now practically over. 

I am asking because we will start production in a few months and have the ability to re-recreate our production environment before that and we really-really want this feature. Going live without the possibility of having old admin-kubeconfigs that operators may take with them is something we want to prevent but cannot currently.

Echo-ing some of the comments above, I am also curious to learn why it is taking so long to implement such an important security measure. 

Kind regards,
Ludo

**Comment by slynickel** [comment]
Could someone clarify what issue and planned fix this issue is tracking on the AKS team's Service Road Map (the Github project)? 

Why I'm confused:

In Dec '18 @jnoller stated:

> I've marked this as a known-issue. It is on the AKS roadmap for this year. Some context - currently we are aware that the admin credentials for a cluster are set at creation time and cannot be changed without a rebuild of the cluster. Resolution of this issue will meet the following criteria:
> 
> Customers are able to rotate the certificates returned in a kubeconfig for cluster-admin
> Customers are able to rotate the certificates returned in a kubeconfig for cluster-user
> 
> Control must be exposed via the API and available in the cli. Azure Portal controls will come directly after the API and CLI support

Currently in preview is the [ability to rotate certificates](https://docs.microsoft.com/en-us/azure/aks/certificate-rotation). This would appear to roughly meet the resolution criteria defined from @jnoller's comment. *Of note it requires up to a 30 minute downtime to complete the rotation.*

Then on October 8th 2019 @sauryadas stated:

> We are working on removing the certificate entirely that is returned in the kube config file. The problem is that there is no way to invalidate the certificate in the config file. Instead in the new implementation we will replace the certificate with static tokens that can be rotated/invalidated once someone leaves the team or no longer requires access to a cluster. This will work with existing clusters; meaning once we release this feature you can upgrade your cluster and going forward from that point get-credentials will return a config file without certificates. The problem with existing clusters though is that someone with an older config file that has the certificate will still be able to access the cluster.

If I'm reading the second comment correctly it would appear to mean this GitHub issue is tracking a more overarching update to do away with including certificates in kubeconfigs.

Which fix is this tracking, the first or the second? Are they related?

**Comment by zuehlke-dea** [comment]
I just tested the new feature. I had a client cert valid to 2021 in my kube config and then rotated the certificates. After the rotation kubectl was not working until I recreated the config. That is very good, but also different to the statement posted above that existing certs are still working. 

But what is really a problem for us is the 30 minutes downtime. We would really like to implement this feature on a regular basis to ensure security, but we are using istio. And istio depends a lot on the API server. We had some issue with a restarting API Server some time ago and during this incident we saw istio pilot restarting all the time. This had negative effects on envoy proxy sidecars as well. 

We might live with the fact that we cannot schedule new pods during the 30 minutes downtime, but when we suffer a downtime for already running services, this is not really a nice "feature" for production. We try to get a resilient platform with less downtime as possible, but having 30 minutes trouble every month (or 3-6 month) feels a bit working against that..

**Comment by sauryadas** [comment]
There are 2 different items:
1) Rotating certs used for communication between API server, kubelet, etc. There was no way to rotate until early last month when we rolled this feature.
https://docs.microsoft.com/en-us/azure/aks/certificate-rotation

2) because there was no way to rotate certs or invalidate certificates, even if a team member got kicked out of a project and had his kubeconfig, he could still connect to a cluster. This has been solved by the cert rotation feature. if a team member leaves, you rotate certs and get-credentials again

@slynickel i think both issues have been resolved with this feature.

But we are working on removing certs in kube configs completely and replacing them with static tokens .. We will make an announcement when it is ready through our release channels.
