### ISSUE TITLE
Should be able to downgrade

### ISSUE THREAD

**Issue by sasacocic** [Azure/AKS#765]
This is a feature request (and also a question).

Currently I'm using aks and on version 1.11.5. Kubernetes has released 1.11.6 when will this be available on aks for me to upgrade?

Feature request: People should be able to downgrade their clusters. Very useful in a scenario where someone upgrades their cluster and something fails. Ideally they probably would want to revert to the previous version. Currently in the upgrade tab of the Azure portal I'm able to do neither. If this already exists great!

**Comment by jnoller** [comment]
We are beginning to validate k8s 1.11.6 which was released during the holidays - in order to ensure stability for customers during the holidays we hold back on new component or service releases. We have exited this and will be releasing 1.11.6, and 1.12 in the next few weeks.

As for downgrading; we will need to carefully evaluate this - Kubernetes downgrades can be very problematic for the cluster and the workloads involved. Additionally, there's the scope of the downgrade - just the kubernetes version, or all related software (Azure CNI, etc).

**Comment by jnoller** [comment]
Closing as Kubernetes down grades are not on the roadmap currently.

**Comment by Pardhasaradhi-244266** [comment]
how to downgrade the aks cluster version in azure

**Comment by lindhe** [comment]
@jnoller I'd like to propose to reopen this. I have run into a compatibility problem, and it is pretty bothersome to create a whole new cluster just because of that.

**Comment by i-am-rashmi** [comment]
I agree even I am facing compatibility issues, It would be great to downgrade the cluster version

**Comment by i-am-rashmi** [comment]
@sasacocic can tou reopen the issue?
