### ISSUE TITLE
Support enabling RBAC on existing cluster

### ISSUE THREAD

**Issue by yhvicey** [Azure/AKS#789]
**What happened**:
Currently it is not able to enable RBAC on existing AKS cluster

**What you expected to happen**:
Support enable RBAC on existing AKS cluster

Is there any plan for supporting this?

**Comment by aswinraaj** [comment]
Need this feature asap for us to switch to a cluster with RBAC before we hit production.

**Comment by jnoller** [comment]
@aswinraaj This is on the AKS Roadmap, but not until later in 2019.

**Comment by devgibsonsp** [comment]
@jnoller Is this a thing now?

**Comment by pisxx-tests** [comment]
Any updates on that?

**Comment by TomGeske** [comment]
We are currently looking into enabling RBAC for none-RBAC enabled clusters as part of our AKS-managed AAD migrations experience. I keep you posted once we have an ETA.

**Comment by saswatac** [comment]
Is this supported now ? I created a cluster using terraform following https://docs.microsoft.com/en-us/azure/developer/terraform/create-k8s-cluster-with-tf-and-aks and i find it is not enabled.

**Comment by palma21** [comment]
That means either that terraform version is old or terraform is using very old APIs (or there's an explicit setting to put RBAC off) since all recent AKS APIs and clusters have RBAC on by default.

The ability to migrate requires a cluster rebuild since the control plane needs a complete redeployment.
