### ISSUE TITLE
`az aks get-credentials` fails with "permission denied"

### ISSUE THREAD

**Issue by tomconte** [Azure/AKS#8]
There is an open issue in the *azure-cli* repo. Seems to happen mostly on Windows.

https://github.com/Azure/azure-cli/issues/4746

You can use this to retrieve the YAML and update your `kubectl` config manually:

```
az aks get-credentials -g <resource_group> -n <name> -f -
```

**Comment by artisticcheese** [comment]
What do you do with Yaml after you export it with statement above?

**Comment by SenthuranSivananthan** [comment]
@artisticcheese save the yaml to a file (i.e. aks.config).

Then set the environment variable KUBECONFIG to the full path of aks.config.

You should then be able to interact with kubectl.

**Comment by sumitkute** [comment]
I manually copied the content from file. C:\Users\USERNAME\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\home\USERNAME\.kube  to  C:\Users\USERNAME\.kube 

Basically.. I first did the get-credential in Ubuntu Subsystem and then taken the file and copied to for windows CLI kubectl config.

**Comment by artisticcheese** [comment]
Saving as YAML file and the modifying variable did not work either. Error is below which appears wanting JSON and not YAML.

```
error: Error loading config file ".\.kube\config": couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
```

**Comment by benc-uk** [comment]
I found saving the YAML isn't a viable workaround as @artisticcheese states, kubctl is expecting JSON not YAML. Just hope https://github.com/Azure/azure-cli/issues/4746 gets fixed soon

**Comment by yaprigal** [comment]
After getting the exception on Windows 10, I managed to workaround this issue by doing the following:
Assuming that you already downloaded the kubectl using "az aks install-cli" command
1. Open CMD, and run: az aks get-credentials -g [your aks resource group] -n [your aks name] -f - > .kube\config
2. Add to your environment variable the following parameter: KUBECONFIG and set the value to where previous step save the config file. for example: C:\Users\[your user name folder]\.kube\config 
3. Try now to run the following command: "kubectl get nodes" 
4. In order to open the dashboard you need to run the following command:
kubectl port-forward kubernetes-dashboard-1672970692-375tg 9090 --namespace kube-system
you need to replace "kubernetes-dashboard-1672970692-375tg" with your pod name which run the dashboard. you can get it by running the following command: 
kubectl get pods --all-namespaces

Hope it will help.

**Comment by ormico** [comment]
looks like its fixed in https://github.com/Azure/azure-cli/issues/4746 and version number 2.0.21.
Get the new MSI at https://aka.ms/InstallAzureCliWindows
