### ISSUE TITLE
ErrImagePull: In-cluster Docker registry is not accessible via public DNS from the nodes except the node that runs registry pod.

### ISSUE THREAD

**Issue by PoslavskySV** [Azure/AKS#802]
**What happened**:

I have deployed a private docker registry inside k8s cluster that is accessible via public DNS (`https://my-registry.my-site.com`) and pushed `ubuntu:latest` from my local computer there. Then I tried to create a simple shell pod with image `my-registry.my-site.com/ubuntu:latest`:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: shell-demo
spec:
    containers:
        - name: ubuntu
          image: my-registry.my-site.com/ubuntu:latest
          command: ['/bin/bash', '-c', 'trap : TERM INT; sleep infinity & wait']
    imagePullSecrets:
        - name: my-registry-secret
...
```
Trying several times to run this pod I found that sometimes it starts just OK (rarely), but in most cases it fails to start and falls into infinite `ErrImagePull` -> `ImagePullBackOff` loop with (`kubectl describe pod shell-demo`):
```
Events:
  Type     Reason     Age                From                               Message
  ----     ------     ----               ----                               -------
  Normal   Scheduled  53s                default-scheduler                  Successfully assigned default/shell-demo to aks-agentpool-28071091-0
  Normal   BackOff    37s                kubelet, aks-agentpool-28071091-0  Back-off pulling image "my-registry.my-site.com/ubuntu:latest"
  Warning  Failed     37s                kubelet, aks-agentpool-28071091-0  Error: ImagePullBackOff
  Normal   Pulling    26s (x2 over 52s)  kubelet, aks-agentpool-28071091-0  pulling image "my-registry.my-site.com/ubuntu:latest"
  Warning  Failed     11s (x2 over 37s)  kubelet, aks-agentpool-28071091-0  Failed to pull image "my-registry.my-site.com/ubuntu:latest": rpc error: code = Unknown desc = Error response from daemon: Get https://my-registry.my-site.com/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Warning  Failed     11s (x2 over 37s)  kubelet, aks-agentpool-28071091-0  Error: ErrImagePull
```
In this bad scenario I noted that no any http requests reach the docker server (while the DNS is 100% OK and my in-cluster docker registry is perfectly accessible from around the world). 

After some monitoring I realised that the pod is successfully started _if and only if_ it is created on the node which simultaneously runs the `docker-registry` pod. When `shell-demo` pod is created on any other node in the cluster, the `ErrImagePull` occur.

```
> kubectl get pod -o=custom-columns=NODE:.spec.nodeName,NAME:.metadata.name --all-namespaces
NODE                       NAME
aks-agentpool-28071091-0   shell-demo
aks-agentpool-28071091-1   shell-demo2
aks-agentpool-28071091-1   docker-registry-59d5dcf6f7-8z4lj

> kubectl get pods
NAME                    READY     STATUS              RESTARTS   AGE
shell-demo              0/1       ImagePullBackOff   0          40m
shell-demo2             1/1       Running            0          38m
```

Looks like some weird bug.

**What you expected to happen**:

Obviously, a successful image pull from in-cluster Docker registry.

**How to reproduce it (as minimally and precisely as possible)**:

Deploy an in-cluster Docker registry (my config [is here](https://gist.github.com/PoslavskySV/b71ded84999d81d2ee540ed1b921eea2), a valid SSL certificate  is required). Setup k8s credentials for private registry ([this command](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/)). Push some image to the registry (e.g. `my-registry.my-site.com/ubuntu:latest`) from local computer. Then just try to run some pod which uses `my-registry.my-site.com/ubuntu:latest` image.

**Anything else we need to know?**:

- I found a [similar issue on Digital Ocean forum](https://www.digitalocean.com/community/questions/failed-to-pull-image-from-private-repository-on-kubernetes-cluster) (see the answer there)

- I tried to delete tunnelfront:

```
 kubectl -n kube-system delete po -l "component=tunnel"
```
but this didn't help.

- connected question (not mine) [on stackoverflow](https://stackoverflow.com/questions/53336855/problem-pulling-images-when-running-private-docker-registry-inside-of-kubernetes)

**Environment**:
-  Kubernetes version: 11.5 and 12.4 (I tried both)
- Size of cluster: 2
- General description of workloads in the cluster: playground cluster
- Others:

**Comment by jnoller** [comment]
First, thank you for reaching out to the AKS team. 

AKS Github issues must be generally re-creatable (e.g here is the YAML/settings/packages/etc installed, can recreate the issue on existing clusters as well as newly created clusters). Unfortunately, this issue is cluster-specific.

For cluster specific issues (those that will require support and on-call staff to access you Subscription and clusters) we ask that you file an Azure Technical Support ticket with the identified issue, rec-creation steps if available, and link to this github thread.

**We can not ask** for the access, logs and other sensitive information on github, or ask you to email/slack/etc this information to us. Our portal ticketing system will protect the information including Subscription ids and credentials. If we discover as part of the root cause that this is an AKS or upstream bug, we will mark this issue as a known issue and ensure it is on the Product backlog as a repair item.

This will allow us to root-cause the issue and ensure it’s not specific to the environment or other configuration level issue - such as NSGs, custom network devices, etc.

Jesse
