### ISSUE TITLE
"This container service is in a failed state"

### ISSUE THREAD

**Issue by davenewza** [Azure/AKS#821]
**What happened**:

**All of our AKS clusters** are reporting the following error in Azure Portal:

 > This container service is in a failed state. Click here to open a new support request.

![image](https://user-images.githubusercontent.com/6212830/52565178-c02b6500-2e0e-11e9-9479-d4343ede88b8.png)

**Anything else we need to know?**:

It seems we also cannot edit the cluster. When trying to scale out the nodes, I am getting the following error:

 > Failed to save container service 'test-aks'. Error: Operation is not allowed while cluster is being upgrading or failed in upgrade

When looking into the AKS properties, I see there is a provisioning state of "Failed":

![image](https://user-images.githubusercontent.com/6212830/52565219-e0f3ba80-2e0e-11e9-85d0-6cd97fae775d.png)

**Environment**:
- Kubernetes version 1.10.12
- 2 x Standard D4sv3 for two of the clusters, and 2 x Standard D2sv3 in another
- All clusters are hosted in North Europe

How do we troubleshoot this problem?  This is a big issue for us as we are required to scale out NOW due to increased throughput expected in the next 24 hours, but we cannot.

**Comment by jnoller** [comment]
Hi @davenewza - Thanks for bringing this up - as we can not debug specific customer cluster issues on github please file an Azure technical support ticket so we can get the needed SubID/etc information to diagnose.

However, to get you unstuck now - we've seen issues where this error can be errantly returned by ARM during the operation. Additionally, please check your available quota - we have bugs planned for resolution this quarter to do pre-flight validation of available quota prior to execution for upgrades/creates/scale up operations which can exceed a users / subscriptions available quota.

In order to clear the state you should:

1. Check your quota and free up resources as needed
2. Re-run the upgrade command, and let it proceed & finish
3. If, after command completion, you still get the "Error: Operation is not allowed while cluster is being upgrading or failed in upgrade" do the following:

```
Go to https://resources.azure.com
Guide to the cluster (<cluster name>)
Switch to Read/Write mode (on the step 8)
Click EDIT then PUT (DO NOT CHANGE ANY VALUE)
This will re-value the status of the cluster.
```

Note; this final step is temporary while we resolve a state update bug we discovered with failed / retired operations not clearing the resource state.

**Comment by davenewza** [comment]
@jnoller Thanks for your reply.  I went through support.  It was indeed a quota issue for this specific family of machines. I was able to scale out after increase the quote and re-running the upgrade command.
