### ISSUE TITLE
Kubernetes 1.9.11 is still using Docker 3.0.1

### ISSUE THREAD

**Issue by amandadebler** [Azure/AKS#826]
**What happened**: Cluster on version 1.9.11, which is in the list of fixed versions; kubectl get nodes -o wide shows Container Runtime = docker://3.0.1 on all nodes, even after running az aks upgrade --kubernetes-version 1.9.11 (no upgrade performed, because version is not different)

**What you expected to happen**: kubectl get nodes -o wide to show Container Runtime = docker://3.0.4 on all nodes

**How to reproduce it (as minimally and precisely as possible)**:
kubectl get nodes -o wide

**Anything else we need to know?**:

Remove 1.9.11 from the list of hotfix versions in https://github.com/Azure/AKS/blob/master/CHANGELOG.md and either make a 1.9.12 with the hotfix, or recommend customers upgrade to 1.10.12

**Environment**:
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.11", GitCommit:"1bfeeb6f212135a22dc787b73e1980e5bccef13d", GitTreeState:"clean", BuildDate:"2018-09-28T21:35:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
- Size of cluster (how many worker nodes are in the cluster?)
3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
HTTP microservices
- Others: Other clusters on 1.11.x and 1.12.x were upgraded and now have Docker 3.0.4

**Comment by jnoller** [comment]
I’ll chase this down today

**Comment by amandadebler** [comment]
westeurope - as of just now (13 February 16:35 CET), this is still the situation. When I run az aks get-upgrades on this cluster, I get versions 1.10.9 and 1.10.12 as the possibilities. Since it's a test cluster, I've remove its load-balancer-exposed service.

**Comment by jnoller** [comment]
I'm on it. Following up with the team(s) involved, I personally apologize for the issues/confusion

**Comment by jnoller** [comment]
Ok, so an update - Due to current limitations on upgrades being bound to Kubernetes revisions (at least a patch version increment) and lack of up new k8s 1.9 and 1.10 patch releases, here is the updated guidance:

At this time, all regions now have the CVE hotfix release. The simplest way to consume it is to perform a Kubernetes version upgrade, which will cordon, drain, and replace all nodes with a new base image that includes the patched version of Moby. In conjunction with this release, we have enabled new patch versions for Kubernetes 1.11 and 1.12. However, as there are no new patch versions available for Kubernetes versions 1.9 and 1.10, customers are recommended to move forward to a later minor release.

If that is not possible and you must remain on 1.9.x/1.10.x, you can perform the following steps to get the patched runtime:

Scale up your existing 1.9/1.10 cluster - add an equal number of nodes to your existing worker count.
After scale-up completes, pick a single node and using the kubectl command, cordon the old node, drain all traffic from it, and then delete it.
Repeat step 2 for each worker in your cluster, until only the new nodes remain.
Once this is complete, all nodes should reflect the new Moby runtime version.

We apologize for the confusion and are working to improve this process.

Note: All newly created 1.9, 1.10, 1.11 and 1.12 clusters will have the new Moby runtime and will not need to be upgraded to get the patch.
