### ISSUE TITLE
Load balancer external IP stops being accessible

### ISSUE THREAD

**Issue by darthchudi** [Azure/AKS#830]
**What happened**: I had a service of type LoadBalancer which I was able to access via the external IP gotten from `kubectl get services`. However after deploying an additional service of type LoadBalancer, both of the services become inaccessible from the external IP.

**What you expected to happen**: Services should be accessible from their external IP.

**How to reproduce it (as minimally and precisely as possible)**:  Create two services both of type LoadBalancer in the same namespace.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version: Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T19:44:10Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
- Size of cluster: 3
- General description of workloads in the cluster: Node.js HTTP microservices, Redis, RabbitMQ

**Comment by jnoller** [comment]
First, thank you for reaching out to the AKS team. 

AKS Github issues must be generally re-creatable (e.g here is the YAML/settings/packages/etc installed, can recreate the issue on existing clusters as well as newly created clusters). Unfortunately, this issue is cluster-specific.

For cluster specific issues (those that will require support and on-call staff to access you Subscription and clusters) we ask that you file an Azure Technical Support ticket with the identified issue, rec-creation steps if available, and link to this github thread.

**We can not ask** for the access, logs and other sensitive information on github, or ask you to email/slack/etc this information to us. Our portal ticketing system will protect the information including Subscription ids and credentials. If we discover as part of the root cause that this is an AKS or upstream bug, we will mark this issue as a known issue and ensure it is on the Product backlog as a repair item.

This will allow us to root-cause the issue and ensure it’s not specific to the environment or other configuration level issue - such as NSGs, custom network devices, etc.

Jesse
