### ISSUE TITLE
Services deployed to HTTP application routing domain enabled AKS, is reachable via URL only after 5-10 minutes

### ISSUE THREAD

**Issue by vineetmimrot** [Azure/AKS#835]
**What happened**:
I have deployed service to HTTP application routing domain enabled AKS cluster. Both the service and ingress is up but the website (service) is reachable via url only after 5-10 min. From the pod also if I do curl on the service IP, it is returning correct data, but from outside of the cluster the url is reachable only after 5-10 minutes.

Following are addon-http-application-routing-nginx-ingress-controller-8fm2hcz  pod logs:
```
I0215 06:35:40.235758       7 status.go:362] updating Ingress vnm-1441/sampleapp status to [{52.172.25.245 }]
I0215 06:35:40.243824       7 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"vnm-1441", Name:"sampleapp", UID:"e5489d04-30eb-11e9-91f2-3e3fbb7f1bd8", APIVersion:"extensions/v1beta1", ResourceVersion:"231550", FieldPath:""}): type: 'Normal' reason: 'UPDATE' Ingress vnm-1441/sampleapp
W0215 06:35:43.381610       7 controller.go:806] Service "vnm-1441/sampleapp" does not have any active Endpoint.
```

Following are addon-http-application-routing-external-dns-7897fb4cf5-mtj8v pod logs
```
time="2019-02-15T06:36:38Z" level=info msg="Updating A record named 'vnm-1441-sampleapp' to '52.172.xxx.xxx' for Azure DNS zone '56d68788387e4451aff1.southindia.aksapp.io'." 
time="2019-02-15T06:36:39Z" level=info msg="Updating TXT record named 'vnm-1441-sampleapp' to '"heritage=external-dns,external-dns/owner=default"' for Azure DNS zone '56d68788387e4451aff1.southindia.aksapp.io'." 
```

**What you expected to happen**:
After the ingress is up, the site should be reachable instantaneously.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy a service to HTTP application routing domain enabled AKS cluster and wait for service and ingress to up and access the site via url.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.5", GitCommit:"51dd616cdd25d6ee22c83a858773b607328a18ec", GitTreeState:"clean", BuildDate:"2019-01-16T18:14:49Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}
```

- Size of cluster (how many worker nodes are in the cluster?): 3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): The cluster is both HTTP application routing domain and RBAC enabled.
- Others:

**Comment by jnoller** [comment]
First, thank you for reaching out to the AKS team. 

AKS Github issues must be generally re-creatable (e.g here is the YAML/settings/packages/etc installed, can recreate the issue on existing clusters as well as newly created clusters). Unfortunately, this issue is cluster-specific.

For cluster specific issues (those that will require support and on-call staff to access you Subscription and clusters) we ask that you file an Azure Technical Support ticket with the identified issue, rec-creation steps if available, and link to this github thread.

**We can not ask** for the access, logs and other sensitive information on github, or ask you to email/slack/etc this information to us. Our portal ticketing system will protect the information including Subscription ids and credentials. If we discover as part of the root cause that this is an AKS or upstream bug, we will mark this issue as a known issue and ensure it is on the Product backlog as a repair item.

This will allow us to root-cause the issue and ensure it’s not specific to the environment or other configuration level issue - such as NSGs, custom network devices, etc.

Jesse

**Comment by vineetmimrot** [comment]
@jnoller This is a consistent issue in all the cluster. I am from Azure DevOps team and we are working on CD solution for AKS. I will send you YAML files to re-generate the issue.
