### ISSUE TITLE
env var valueFrom.secretKeyRef not expanded in other env var or args

### ISSUE THREAD

**Issue by cforce** [Azure/AKS#836]
According to the k8 spec https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/ , https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/ , https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#use-configmap-defined-environment-variables-in-pod-commands there should be feature that allows to expand env variables in other env variables  or args via the adress patrtern $(MY_ENV_VAR_NAME).
Sadly id doesn't work in AKS. If i check the deployed pods the env var and the args does get the expanded var content, but still show just the var name
`spec:
      containers:
      - name: #{deployment.name}
        image: #{image.repository}:#{image.version}
        env:
        - name: DB_URI
          valueFrom:
            secretKeyRef:
              name: #{deployment.name}.#{namespace.name}.db
              key: uri
        - name: SPRING_DATASOURCE_URL
          value: $(DB_URI)
        args: ["-Dspring.datasource.url=jdbc:$(DB_URI)","echo $(DB_URI)","echo $DB_URI"]`

![image](https://user-images.githubusercontent.com/393286/52918026-8ec10680-32f2-11e9-835c-756464d08c0a.png)

**Comment by cforce** [comment]
I am stranded here, can anyone speak up and give me a hint how to solve my issue by fix or workaround? Is this a verified bug?

**Comment by jnoller** [comment]
First, thank you for reaching out to the AKS team. 

AKS Github issues must be generally re-creatable (e.g here is the YAML/settings/packages/etc installed, can recreate the issue on existing clusters as well as newly created clusters). Unfortunately, this issue is cluster-specific.

For cluster specific issues (those that will require support and on-call staff to access you Subscription and clusters) we ask that you file an Azure Technical Support ticket with the identified issue, rec-creation steps if available, and link to this github thread.

**We can not ask** for the access, logs and other sensitive information on github, or ask you to email/slack/etc this information to us. Our portal ticketing system will protect the information including Subscription ids and credentials. If we discover as part of the root cause that this is an AKS or upstream bug, we will mark this issue as a known issue and ensure it is on the Product backlog as a repair item.

This will allow us to root-cause the issue and ensure it’s not specific to the environment or other configuration level issue - such as NSGs, custom network devices, etc.

Jesse

**Comment by cforce** [comment]
The problem is describe seem not related to my cluster setup, but to AKS or kubernetes in common.
AKS simply does not work as documented on the kubernetes doc and i can't find any documentation or hint for AKS why not, or how to deal with it.
I you just try to run deployment.yml from above, that will reproduce the issue

**Comment by jnoller** [comment]
@cforce Github issues have no SLA and are best effort only.  This is the first report of the issue, and if you need rapid resolution, please file a ticket which will get routed to on-call. Otherwise we will triage this as quickly as possible

**Comment by cforce** [comment]
I got your point regarding speed of resolving the issues in os repo and paid subscription. However  you still should not close the bug report, as it's pretty clear what documented standard feature of kubernetes seems not to work, even if i am the first one who complains that it does not. 
Please reopen, until somebody's has prooven the opposite - that it is working as documented.
