### ISSUE TITLE
CoreDNS Custom ConfigMap Should Automatically Reload 

### ISSUE THREAD

**Issue by RehanSaeed** [Azure/AKS#841]
In [AKS 2019-02-07 - Hotfix Release](https://github.com/Azure/AKS/releases/tag/2019-02-07), there are new instructions on how to modify the CoreDNS config using a ConfigMap. I use the config below to use Cloudflare as my external DNS provider because it's faster and more secure:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  azurestack.server: |
    azurestack.local:53 {
        forward . tls://1.1.1.1 tls://1.0.0.1 {
          tls_servername cloudflare-dns.com
          health_check 5s
        }
    }
```

However, the instructions also state that after creating the config map, you need to delete the CoreDNS deployment to force-load the new config.

```
kubectl -n kube-system delete po -l k8s-app=kube-dns
```

I've added the above into a Helm chart and want to use CI/CD. However, I'm guessing that killing the DNS pods would cause errors when making DNS requests? Ideally this restriction should be lifted and the DNS pods would reload the config automatically.

**Comment by jnoller** [comment]
Thanks for the enhancement request

**Comment by slynickel** [comment]
Just so others don't think they can be smart about this, currently the config map for coredns that is deployed with AKS has the `reload` plugin in it. This is from AKS v1.12.8:

```yaml
$ kubectl get configmap -n kube-system coredns -o yaml
apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          upstream
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
        import custom/*.override
    }
    import custom/*.server
kind: ConfigMap
metadata:
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
  name: coredns
  namespace: kube-system
```

The problem is stated in the [coredns reload plugin documentation](https://github.com/coredns/coredns/tree/master/plugin/reload#bugs):

> Also any `import` statement is not discovered by this plugin. This means if any of these imported files
changes the *reload* plugin is ignorant of that fact.

Since any customization have to be in `coredns-custom` they won't be reloaded by the coredns reload plugin today. I looked for a coredns issue on this but didn't see anything.

That said something that allows us to merge into the corefile I think would fix this. As mentioned in #919 you can't do this today on AKS. A merge into the corefile would be reloaded since the reload clause exists in the corefile initially.

**Comment by timja** [comment]
This bug is fixed upstream in coredns, but needs an update to coredns
```
$ git tag --contains 367d285765fef0f030be1b59e5d6bf5d5a008e45
v1.6.1
v1.6.2
v1.6.3
v1.6.4
```

@jnoller any idea when the version in aks-engine will get picked up?
https://github.com/Azure/aks-engine/blob/7a29e45c531617a1a26ee4107bebb4d6f8d068e8/pkg/api/k8s_versions.go

We currently  have the following versions on different clusters:
1.2.6 on k8s 1.13.10
1.3.1 on k8s 1.14.x

**Comment by slynickel** [comment]
As of 2/28/20 it looks like coredns is now 1.6.6 in cluster. I'm not actually seeing the reload behavior though. I did see this note on reload plugin https://coredns.io/plugins/reload/ 

> In CoreDNS v1.6.0 and earlier any import statements are not discovered by this plugin. This means if any of these imported files changes the reload plugin is ignorant of that fact. CoreDNS v1.7.0 and later does parse the Corefile and supports detecting changes in imported files.

This doesn't actually explain what happens with 1.6.x. I'm planning on just checking again once cordns is on 1.7.0 unless someone knows why this automatic reload of import statements should work on 1.6.6

**Comment by timja** [comment]
the commit to fix it is supposed to be included, but I tried a couple of days ago and it didn't seem to work for us 😢
