### ISSUE TITLE
destroying AKS cluster can hang indefinitely in "Deleting" status

### ISSUE THREAD

**Issue by swapzero** [Azure/AKS#847]
**What happened**:
- destroying the cluster with `terraform destroy` did not end in a timely manner (and I suppose it wouldn't have ended)
- portal was constantly showing "Deleting" status for AKS cluster for more than half an hour

**How to reproduce it (as minimally and precisely as possible)**:
- create a subnet with no routing table associated
- create a cluster with terraform forcing the nodes to be part of the subnet:
```
...
  agent_pool_profile {
    name            = "node"
    count           = 3
    vm_size         = "Standard_D1_v2"
    os_type         = "Linux"
    os_disk_size_gb = 30
    vnet_subnet_id  = "${azurerm_subnet.nodesubnet.id}"
  }
...
```
- AKS would create a  route table that's not associated to any subnet => inter-pod communication would not work
- login to portal and manually assign the AKS generated routetable to your subnet
- interpod communication should work now
- **use** `terraform destroy` **to destroy the cluster**

Result:
- Terraform would indefinitely run while waiting for AKS to be destroyed
- The portal would just show "Deleting" forever and the only resource that was still listed in the `MC...` resource group was...the generated routetable

Ended up stopping terraform and manually set the subnet route table to **None** in order to have the cluster finally deleted.

**What you expected to happen**:
- an error should have been thrown quite quickly mentioning that it cannot delete the resource because it was associated with another resource.
- ideally, that generated route table should have been exported in terraform to be associated later with the subnet...but I can't tell if this is a good idea

**Environment**:
- AKS 1.12.5
- terraform 0.11.11
- kubenet

**Comment by jnoller** [comment]
First, thank you for reaching out to the AKS team. 

AKS Github issues must be generally re-creatable (e.g here is the YAML/settings/packages/etc installed, can recreate the issue on existing clusters as well as newly created clusters). Unfortunately, this issue is cluster-specific.

For cluster specific issues (those that will require support and on-call staff to access you Subscription and clusters) we ask that you file an Azure Technical Support ticket with the identified issue, rec-creation steps if available, and link to this github thread.

**We can not ask** for the access, logs and other sensitive information on github, or ask you to email/slack/etc this information to us. Our portal ticketing system will protect the information including Subscription ids and credentials. If we discover as part of the root cause that this is an AKS or upstream bug, we will mark this issue as a known issue and ensure it is on the Product backlog as a repair item.

This will allow us to root-cause the issue and ensure it’s not specific to the environment or other configuration level issue - such as NSGs, custom network devices, etc.

Jesse
