### ISSUE TITLE
AKS: portal reports success for a failed scale up operation

### ISSUE THREAD

**Issue by swapzero** [Azure/AKS#849]
**What happened**:
Portal incorrectly reported `Successfully saved container service 'cluster-name'.` instead of an error.

**What you expected to happen**:
- to report an error and an error description

**How to reproduce it (as minimally and precisely as possible)**:
- create a /21 subnet
- use terraform to create a 8 nodes AKS cluster and assign Pod CIDR to the /21 subnet
- go to portal and scale it to 10 nodes
Result:
Portal: `Successfully saved container service 'cluster-name'.`
```
kubectl get nodes

NAME                  STATUS     ROLES   AGE     VERSION
aks-node-27255451-0   Ready      agent   31m     v1.12.5
aks-node-27255451-1   Ready      agent   32m     v1.12.5
aks-node-27255451-2   Ready      agent   31m     v1.12.5
aks-node-27255451-3   Ready      agent   16m     v1.12.5
aks-node-27255451-4   Ready      agent   16m     v1.12.5
aks-node-27255451-5   Ready      agent   16m     v1.12.5
aks-node-27255451-6   Ready      agent   16m     v1.12.5
aks-node-27255451-7   Ready      agent   16m     v1.12.5
aks-node-27255451-8   NotReady   agent   7m26s   v1.12.5
aks-node-27255451-9   NotReady   agent   7m44s   v1.12.5
```
Actually this was a failed operation since the extra 2 nodes cannot be assigned any more /24s.

**Environment**:
- AKS 1.12.5
- terraform 0.11.11
- kubenet

**Comment by jnoller** [comment]
First, thank you for reaching out to the AKS team. 

AKS Github issues must be generally re-creatable (e.g here is the YAML/settings/packages/etc installed, can recreate the issue on existing clusters as well as newly created clusters). Unfortunately, this issue is cluster-specific.

For cluster specific issues (those that will require support and on-call staff to access you Subscription and clusters) we ask that you file an Azure Technical Support ticket with the identified issue, rec-creation steps if available, and link to this github thread.

**We can not ask** for the access, logs and other sensitive information on github, or ask you to email/slack/etc this information to us. Our portal ticketing system will protect the information including Subscription ids and credentials. If we discover as part of the root cause that this is an AKS or upstream bug, we will mark this issue as a known issue and ensure it is on the Product backlog as a repair item.

This will allow us to root-cause the issue and ensure it’s not specific to the environment or other configuration level issue - such as NSGs, custom network devices, etc.

Jesse
