### ISSUE TITLE
Node image hardening

### ISSUE THREAD

**Issue by MXClyde** [Azure/AKS#855]
What are the possibilities & position of AKS team on hardening the VMs used in AKS. If I am correct it is currently not possible to change the base image used to setup the cluster, but it is possible to SSH in and implement measures manually. How do we find out which measures are supported on the VMs?

**Comment by jnoller** [comment]
Mutating the worker node OS is not supported. While for now, users have SSH access to the workers and they can temporarily change them those changes will not be persisted through scale up/down, upgrades, etc as these pull in updated VHD (OS) images. Our goal as a managed service is to gradually deprecate worker management so that users do not have to deal with workers - this includes hardening the base OS, reducing the overall OS footprint, etc.

However, these changes will take some time - so if you modify them now, just be clear that the changes will not persist and you will have to re-apply them.
