### ISSUE TITLE
'az aks browse' does not work - 'connection reset by peer'

### ISSUE THREAD

**Issue by sshorkey** [Azure/AKS#870]
Attempt to launch 'az aks browse' results in:

Merged "***" as current context in /tmp/tmp2yfddaz_
To view the console, please open https://gateway04.eastus.console.azure.com/n/cc-f346dd44/cc-f346dd44/proxy/8001/ in a new tab
Press CTRL+C to close the tunnel...
Forwarding from [::1]:8001 -> 9090
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/az/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 103, in wait_then_open
    urlopen(url, context=_ssl_context())
  File "/opt/az/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/az/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/opt/az/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/opt/az/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/az/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/opt/az/lib/python3.6/urllib/request.py", line 1321, in do_open
    r = h.getresponse()
  File "/opt/az/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/az/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/az/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/az/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

Browser displays 
{"code":"ECONNRESET","errno":"ECONNRESET","syscall":"read"}

I'm running AKS with Kubernetes 1.12.6, and attempting to run the command using the Azure Cloud Shell.

**Comment by sshorkey** [comment]
Issue resolved on its own after a few minutes with no action on my part.

**Comment by sshorkey** [comment]
Issue resumed.

**Comment by sshorkey** [comment]
Attempting to close the cloud shell and do it again has changed the error, now it is:

Merged "*****" as current context in /tmp/tmptkz2zhu0
To view the console, please open https://gateway04.eastus.console.azure.com/n/cc-f346dd44/cc-f346dd44/proxy/8001/ in a new tab
Press CTRL+C to close the tunnel...
Unable to listen on port 8001: Listeners failed to create with the following errors: [Unable to create listener: Error listen tcp4 127.0.0.1:8001: bind: address already in use Unable to create listener: Error listen tcp6 [::1]:8001: bind: address already in use]
error: Unable to listen on any of the requested ports: [{8001 9090}]

**Comment by jnoller** [comment]
First, thank you for reaching out to the AKS team. 

AKS Github issues must be generally re-creatable (e.g here is the YAML/settings/packages/etc installed, can recreate the issue on existing clusters as well as newly created clusters). Unfortunately, this issue is cluster-specific.

For cluster specific issues (those that will require support and on-call staff to access you Subscription and clusters) we ask that you file an Azure Technical Support ticket with the identified issue, rec-creation steps if available, and link to this github thread.

**We can not ask** for the access, logs and other sensitive information on github, or ask you to email/slack/etc this information to us. Our portal ticketing system will protect the information including Subscription ids and credentials. If we discover as part of the root cause that this is an AKS or upstream bug, we will mark this issue as a known issue and ensure it is on the Product backlog as a repair item.

This will allow us to root-cause the issue and ensure it’s not specific to the environment or other configuration level issue - such as NSGs, custom network devices, etc.

Jesse
