### ISSUE TITLE
Deployments in kube-system preventing autoscale down

### ISSUE THREAD

**Issue by Daryltp** [Azure/AKS#875]
**What happened**:
When using the cluster autoscaler, the cluster cannot scale down due to services in kube-system (kube-dns and tunnelfront observed in the logs below, but I assume it is the same for other services) not having associated PDBs.

**What you expected to happen**:
Nodes in the cluster scale down when under-utilised.

**How to reproduce it (as minimally and precisely as possible)**:
Install Cluster autoscaler
Spin up a number of pods causing cluster to scale out
Remove pods causing cluster to scale in.
Observe errors such as the below in logs.

Node <nodename> cannot be removed: non-daemonset, non-mirrored, non-pdb-assigned kube-system pod present: tunnelfront-56bc7fc9bd-ktnnl
node <nodename> cannot be removed: non-daemonset, non-mirrored, non-pdb-assigned kube-system pod present: kube-dns-v20-7dfdf65c84-7kqgh

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.7
- Size of cluster (how many worker nodes are in the cluster?) 7 (autoscaler min4 max10)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) N/A
- Others:

**Comment by palma21** [comment]
Hi, 

Are you using the Cluster autoscaler addon or a self installed?

This is the config that will be supported (once GA) for cluster autoscaler in AKS
https://docs.microsoft.com/en-us/azure/aks/cluster-autoscaler

Regarding the issues, AKS on the latest versions is leveraging coreDNS, that would not hit this, do you have any reason not to use coredns? that would take away one of the pods preventing scale in.

on the tunnelfront part, that is a critical pod so it's by design preventing that node to go away automatically, it's not common it lands on a scale in candidate, how many nodes do you have?

In any case, I'd suggest you use the recommended setup on docs if you can.

**Comment by Daryltp** [comment]
Hi,

We are using the cluster-autoscaler option that was hosted on that same page a matter of months ago. I am aware this is no longer the suggested method of autoscaling however, but it is not a priority at the moment to change to the newly suggested method.

It is somewhat irrelevant here due to the issue being incorrectly pre-configured elements in kube-system by AKS. I would like to think the same behaviour persists in the newly supported method of autoscaling using VMSS, as these are legitimate reasons not to scale nodes.

CoreDNS is on our to do list, but again not a priority at the moment.

Tunnelfront - I agree this is a critical pod, I don't understand how it can be uncommon that it lands on a scale candidate as by the looks of it it is not pinned in anyway to any particular node. Are there reasons this is a single pod and not a daemonset/replica set with associated PDB? We have 7 nodes presently, 2 of which were blocked from scaling down last night for these reasons.

**Comment by feiskyer** [comment]
The autoscaler has an option `--skip-nodes-with-system-pods` (default is true), which can be used to change this behavior. By default, pods in kube-system are considered as critial pods, hence non-daemonset pods are not drained.

**Comment by palma21** [comment]
Hi @Daryltp kube-dns will be present in all nodes with kube-dns-autoscaler and pdb assigned on the next release (the new CA only works with coredns enabled clusters which is why this wouldn't happen, sorry if I wasn't clear)

For tunnelfront, it currently can't be a Daemon set, so if you really want to kill the node where it is, I suggest you use the flag @feiskyer suggested.

For anything else, feel free to open a support ticket and we'll be glad to help you!

**Comment by mackrorysd** [comment]
Does the AKS team collect any data on how much of a problem this is? I've tested scale-down on 4 clusters, and on all 4, it took longer than the 10 minutes it was supposed to after all my workloads had been removed from the nodes in question. In 2 of those cases I was able to look at the autoscaler logs and confirmed that tunnelfront and metrics-server were delaying scale down. In one case, tunnelfront cost me an hour before down-scaling.
