### ISSUE TITLE
Azure Resource Name Policy makes AKS deploy template validation fail

### ISSUE THREAD

**Issue by cmendible** [Azure/AKS#892]
**What happened**: Created a resource group and applied the following policy definition:

``` json
{
  "if": {
    "not": {
      "field": "name",
      "like": "[parameters('namePattern')]"
    }
  },
  "then": {
    "effect": "deny"
  }
}
```
and setting the name pattern as: `my*`

Then tried to deploy an AKS cluster with the following command:

`az aks create -g policiesrg -n myaks --generate-ssh-keys --verbose`

The command fails with a `Bad Request` status cause the following resources do not comply with the policy:

1. aks-vnet-*
1. aks-agentpool-*
1. aks-nodepool1-*

Note that those resources are not created created in the `policiesrg` but in the resource group that the AKS service creates for the infra it needs.

**What you expected to happen**:

I expect the cluster to be created because the name of the service is compliant with the policy and to ignore the names of the infra resource group (MC__policiesrg__myaks__westeurope).

**How to reproduce it (as minimally and precisely as possible)**:
Explained above

**Anything else we need to know?**:
No, but not sure if this is the correct place to report this one.

**Environment**:
`azure-cli                         2.0.58 *`

**Comment by cmendible** [comment]
Thanks for your prompt reply, I'm aware that you can not customize the name or preserve tags, but the question here is why the process is validating the names of those resources against a policy that is not defined on their target resource group ("infra" resource group).

**Comment by jnoller** [comment]
Because the RGs created by AKS are not user modifiable, adding other resources into the created RG is not supported. Effectively we create (force-create) a dedicated managed RG for AKS that customers can not add resources to, mutate, edit, or remove. The MC_* group is for AKS / Azure usage only. 

Undoing/changing this and supporting mutation/management/naming and policy enforcement are all part of the same workstream on deck for 2019.

**Comment by cmendible** [comment]
Roger that! Thanks!
