### ISSUE TITLE
Service discovery returns bad request. Cannot reach some services from another namespace.

### ISSUE THREAD

**Issue by adriancislo** [Azure/AKS#896]
Hello,

I have an AKS cluster with additional virtual network in the same resource group. Virtual network has Address space: 172.16.64.0/20. I see all pods and services get an IP from this space.

For some of the services in `namespace1` there is a problem to reach them from `namespace2` by using name `service1.namespace1` I get bad request, but if I use name `service1.namespace1.svc.cluster.local` it works. It occurs only to some of the services in this namespace. Not all of them. I checked/compared deployment descriptors (YAMLs), no differences than names, same technology java+spring-boot. No matter how I name them, how I name namespace etc the problem occurs always to the same services.

Communication works ok if services are in the same namespace.

Below a sample http request from pod in other namespace
```
/ # curl -v deviceidp.namespace1
* Rebuilt URL to: deviceidp.namespace1/
*   Trying 172.16.73.213...
* TCP_NODELAY set
* Connected to deviceidp.namespace1 (172.16.73.213) port 80 (#0)
> GET / HTTP/1.1
> Host: deviceidp.namespace1
> User-Agent: curl/7.60.0
> Accept: */*
> 
< HTTP/1.1 400 
< Transfer-Encoding: chunked
< Date: Tue, 02 Apr 2019 07:38:12 GMT
< Connection: close
< 
* Closing connection 0
```
This is not an answer from the service, sth in it's way responses with bad request

And same request with suffix `.svc.cluster.local`
```
/ # curl -v deviceidp.namespace1.svc.cluster.local
* Rebuilt URL to: deviceidp.namespace1.svc.cluster.local/
*   Trying 172.16.73.213...
* TCP_NODELAY set
* Connected to deviceidp.namespace1.svc.cluster.local (172.16.73.213) port 80 (#0)
> GET / HTTP/1.1
> Host: deviceidp.namespace1.svc.cluster.local
> User-Agent: curl/7.60.0
> Accept: */*
> 
< HTTP/1.1 404 
< Content-Type: application/json;charset=UTF-8
< Transfer-Encoding: chunked
< Date: Tue, 02 Apr 2019 07:38:15 GMT
< 
* Connection #0 to host deviceidp.namespace1.svc.cluster.local left intact
{"timestamp":"2019-04-02T07:38:16.213+0000","status":404,"error":"Not Found","message":"No message available","path":"/"}
```
This is an answer from the service.

I tried to find some logs from dns, pods in `kube-system` namespace but I am not sure where to look actually.

The same system works now on another AKS cluster with additional virtual network but there the Address Space set in virtual network does not match with pods' IPs. 
`172.16.80.0/20` != pod IP `10.244.5.200` and svc IP `10.0.64.17`

I am not sure maybe it's somehow important, services that I cannot reach use actuator /health endpoint running on different port than the service itself and listen only on 127.0.0.1. This endpoint is used for liveness and readiness probes.

Also I tried to deploy it on another cluster, same issue.

It does not happen on clusters with kubernetes version 1.11.1

**Environment**:
- Kubernetes version 1.12.6
- Size of cluster 3
- Java Spring boot apps

**Edit**:
I also noticed that we use    "networkPlugin": "azure" in 1.12.6 cluster and    "networkPlugin": "kubenet" in 1.11.1

**Comment by jnoller** [comment]
First, thank you for reaching out to the AKS team. 

AKS Github issues must be generally re-creatable (e.g here is the YAML/settings/packages/etc installed, can recreate the issue on existing clusters as well as newly created clusters). Unfortunately, this issue is cluster-specific.

For cluster specific issues (those that will require support and on-call staff to access you Subscription and clusters) we ask that you file an Azure Technical Support ticket with the identified issue, rec-creation steps if available, and link to this github thread.

**We can not ask** for the access, logs and other sensitive information on github, or ask you to email/slack/etc this information to us. Our portal ticketing system will protect the information including Subscription ids and credentials. If we discover as part of the root cause that this is an AKS or upstream bug, we will mark this issue as a known issue and ensure it is on the Product backlog as a repair item.

This will allow us to root-cause the issue and ensure it’s not specific to the environment or other configuration level issue - such as NSGs, custom network devices, etc.

Jesse
