### ISSUE TITLE
AKS: Support confirmation on Delete in UI

### ISSUE THREAD

**Issue by jnoller** [Azure/AKS#897]
Cloning from stale issue #471 with additional details:

Currently in the Portal it is possible to delete AKS clusters without any confirmation, and other Azure resources ask you to type the resource name before the delete is executed. This is a request for second-level confirmation on destructive calls.

CLI confirmation on delete should also occur

**Comment by jluk** [comment]
@jnoller what resources prompt a double confirm? I know RG's do, but tried registry as well and it just goes straight to delete.

@jenetlan thoughts on this?

**Comment by jenetlan** [comment]
Interesting - for individual resources the only one I know of is storage accounts, and that's because it always stores data so we wanted to be super careful. VMs and the vast majority of other resources offer the confirmation dialogue ("are you sure you want to delete the resource 'myResource'?") but don't require the user to re-type the names or anything more serious. I haven't heard of any issues with that approach across the IaaS resources - have there been issues around this? In the referenced issue it seems like it was more of a customer worry than a customer problem - is that accurate?

**Comment by jluk** [comment]
@jenetlan I believe that is the case. 

This one seems like a portal call, but I am supportive of double asking since AKS ties the cluster to the MC RG - it effectively behaves like an RG and deleting it has cascading deletes into compute/network/storage.

**Comment by jluk** [comment]
Closing as resource deletion matches the Azure standard.
