### ISSUE TITLE
MountVolume.SetUp failed for volume “default-token-ljnkd” : mount failed

### ISSUE THREAD

**Issue by eugenestarchenko** [Azure/AKS#915]
Hi there,

We encountered such problem where we are seeing an issue with our pods

`MountVolume.SetUp failed for volume “default-token-ljnkd” : mount failed: exit status 1 Mounting command: systemd-run Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/fcfe0d82-5e64-11e9-a38f-6e4b11f5cea4/volumes/kubernetes.io~secret/default-token-ljnkd --scope -- mount -t tmpfs tmpfs /var/lib/kubelet/pods/fcfe0d82-5e64-11e9-a38f-6e4b11f5cea4/volumes/kubernetes.io~secret/default-token-ljnkd Output: Failed to start transient scope unit: Connection timed out`

"Restart" with kubectl pods and deployments doesn't help

Thew closest topic that looks related is https://github.com/scholzj/terraform-aws-kubernetes/issues/13

**Reboot of our AKS system nodes helped to solve this.** 

From AKS user experience - cluster just stuck in a bad state till reboot

**Comment by jnoller** [comment]
First, thank you for reaching out to the AKS team. 

AKS Github issues must be generally re-creatable (e.g here is the YAML/settings/packages/etc installed, can recreate the issue on existing clusters as well as newly created clusters). Unfortunately, this issue is cluster-specific.

For cluster specific issues (those that will require support and on-call staff to access you Subscription and clusters) we ask that you file an Azure Technical Support ticket with the identified issue, rec-creation steps if available, and link to this github thread.

**We can not ask** for the access, logs and other sensitive information on github, or ask you to email/slack/etc this information to us. Our portal ticketing system will protect the information including Subscription ids and credentials. If we discover as part of the root cause that this is an AKS or upstream bug, we will mark this issue as a known issue and ensure it is on the Product backlog as a repair item.

This will allow us to root-cause the issue and ensure it’s not specific to the environment or other configuration level issue - such as NSGs, custom network devices, etc.

Jesse
