### ISSUE TITLE
Can't create nginx-ingress - ips won't load

### ISSUE THREAD

**Issue by sshorkey** [Azure/AKS#918]
When attempting to follow the instructions in here - https://docs.microsoft.com/en-us/azure/aks/ingress-tls#configure-a-dns-name, it does not work. Instead of loading my service (or even the default 404 backend page), attempting to load to the external IP assigned to the cluster just results in: "Hmmm...can’t reach this page". I backtracked and did it again and confirmed that this happens before I even do anything to configure ingress--in other words, it fails from the moment helm installs it.

I've done this several times in this cluster before and it worked fine; I have 4 functional ingress controllers for other services. I don't get what changed.

**Comment by jnoller** [comment]
First, thank you for reaching out to the AKS team. 

AKS Github issues must be generally re-creatable (e.g here is the YAML/settings/packages/etc installed, can recreate the issue on existing clusters as well as newly created clusters). Unfortunately, this issue is cluster-specific.

For cluster specific issues (those that will require support and on-call staff to access you Subscription and clusters) we ask that you file an Azure Technical Support ticket with the identified issue, rec-creation steps if available, and link to this github thread.

**We can not ask** for the access, logs and other sensitive information on github, or ask you to email/slack/etc this information to us. Our portal ticketing system will protect the information including Subscription ids and credentials. If we discover as part of the root cause that this is an AKS or upstream bug, we will mark this issue as a known issue and ensure it is on the Product backlog as a repair item.

This will allow us to root-cause the issue and ensure it’s not specific to the environment or other configuration level issue - such as NSGs, custom network devices, etc.

Jesse
