### ISSUE TITLE
Connection refused - connect(2) for docker.sock count increased with moby v.3.0.4

### ISSUE THREAD

**Issue by rashmichandrashekar** [Azure/AKS#920]
**What happened**:
After the upgrade to moby v3.0.4 the number of exceptions trying to connect to docker.sock on the host which is mounted to the container have increased.

**What you expected to happen**:
Exception count to remain consistent with older versions which may be intermittent exceptions due to networking

**Environment**:
- This is from the telemetry for container monitoring addon for aks
- The docker.sock is mounted to the container and the container is making connections to the socket every minute to get information about the containers running on the node.

Is this a known networking issue?

**Comment by jnoller** [comment]
This is a known change by the Docker/Moby team in upstream. The way Docker CE handled the sockets is significantly different than Moby (current). There are no known networking issues at play. 

AKS Github issues must be generally re-creatable (e.g here is the YAML/settings/packages/etc installed, can recreate the issue on existing clusters as well as newly created clusters). Unfortunately, this issue is cluster-specific.

For cluster specific issues (those that will require support and on-call staff to access you Subscription and clusters) we ask that you file an Azure Technical Support ticket with the identified issue, rec-creation steps if available, and link to this github thread.

**We can not ask** for the access, logs and other sensitive information on github, or ask you to email/slack/etc this information to us. Our portal ticketing system will protect the information including Subscription ids and credentials. If we discover as part of the root cause that this is an AKS or upstream bug, we will mark this issue as a known issue and ensure it is on the Product backlog as a repair item.

This will allow us to root-cause the issue and ensure it’s not specific to the environment or other configuration level issue - such as NSGs, custom network devices, etc.

Jessed
