### ISSUE TITLE
Max Pods validation on cluster creation

### ISSUE THREAD

**Issue by tomasr** [Azure/AKS#931]
More of a question than a bug report, but the [latest AKS release](https://github.com/Azure/AKS/releases/tag/2019-04-15) discusses changes to how the value of the `maxPods` parameter is being calculated:

> Users have reported cluster crashes, unavailability and other issues
> when changing this setting. As AKS is a managed service, we provide
> sidecars and pods we deploy and manage as part of the cluster. However
> users could define a maxPods value lower than the value required for the
> managed pods to run (eg 30), AKS now calculates the minimum number of
> pods via: maxPods or maxPods * vm_count > managed add-on pods

This only seems to discuss validation for the lower-bound of `maxPods`. However, seems there have also been changes for the upper-bound?

I have one existing cluster created with `maxPods=250` (with Azure CNI).

Tried to create a new one today (for testing with a smaller VM size), and was unable to create the cluster until I dropped `maxPods` to 100. Before that I kept getting the `The value of parameter maxPods is invalid.` error.

**What happened**:

Cluster creation with larger `maxPods` value is failing.

**What you expected to happen**:

Should succeed.

**How to reproduce it (as minimally and precisely as possible)**:

Create new AKS on `1.12.7` with Azure CNI and `maxPods=250`

**Comment by jnoller** [comment]
Thanks, looking into this.

**Comment by jnoller** [comment]
@tomasr So, yes, when we put in place the minimum threshold, we discovered the upper boundary was not enforced (but it was documented as a limitation). We added the max value validation but it missed release note inclusion.

https://docs.microsoft.com/en-us/azure/aks/configure-azure-cni#maximum-pods-per-node

The upper boundary, per the docs is 110.

**Comment by tomasr** [comment]
110 used to be the default, but most certainly did not use to be the maximum.

When was that changed (and why?)

As I said, I've got a production cluster deployed with `maxPods=250`, so what's going to break now?

**Comment by jnoller** [comment]
@tomasr We're sync'ing internally on this now, you're right that this is a change, however it's also dependent on kubenet vs CNI, where kubenet has a maxpods cap of 110, and Azure CNI (per the docs) had a communicated limit of 110, however actual upper boundary for Azure CNI 256 pods. We're working docs and validation fixes. Any cluster you have in place will be unaffected as this setting can only be set at creation time

When I have line of sight the fix, we will post here.

**Comment by tomasr** [comment]
Thanks, that does make more sense. The actual value doesn't concern me as much, to be honest, just hoping not to have to rebuild the cluster!

**Comment by jnoller** [comment]
Yep, no sweat, we totally understand. Existing clusters are a-OK, the biggest issue is reconciling the docs and upper bound check with the actual limits :)

**Comment by aksuser01** [comment]
Hello!

1. If I have understood correctly, the lowest supported value for maxPods is now 30. Earlier we were using /27 subnets for our sandbox environment AKS clusters, but am I correct that from now on the absolute minimum subnet size for AKS is /26?

2. AKS cluster creation using the following Terraform configuration ends in error:

```
resource "azurerm_kubernetes_cluster" "aks-cluster" {
  ..
  agent_pool_profile {
    count    = 2
    max_pods = 16
    ..
  }
  ..
}
```

Error message:
_StatusCode=400 -- Original Error: Code="InsufficientMaxPods" Message="The AgentPoolProfile 'default' has invalid maxPods, the maxPods(16) should be larger than 30. Please refer to aka.ms/aks-min-max-pod for more detail."_

According the documentation 

>AKS now calculates the minimum number of pods via: maxPods or maxPods * vm_count > managed add-on pods

but it seems that currently the minimum number of pods is not being calculated correctly (16 * 2 > 30)?

**Comment by jnoller** [comment]
You missed the minimum value. 

```
Users have reported cluster crashes, unavailability and other issues
when changing this setting. As AKS is a managed service, we provide
sidecars and pods we deploy and manage as part of the cluster. However
users could define a maxPods value lower than the value required for the
managed pods to run (eg 30), AKS now calculates the minimum number of
pods via: maxPods or maxPods * vm_count > managed add-on pods
```

We have a hard requirement of a *minimum* of 30 max pods for the managed pods we deploy with every cluster. Therefore it's `(maxPods * vmcount) > managed add-on pods (30)` or in your example, 16 * 2 == 32 - therefore you do not hit the minimum 30 value, and therefore your lowest maxPods value is 32

**Comment by aksuser01** [comment]
Thank you for your quick response, but this is still a bit unclear to me.

Is the hard requirement checked for each node or for the whole cluster? If it's for each node, does it mean that AKS requires at least 30 IP addresses per node? E.g. for a two-node cluster 90 IP addresses, because upgrades require a temporary third node and that counts only the 'managed add-on pods'? Basically you need a subnet of /25 (128 addresses) just for a two-node cluster as maxPods is used for calculating the minimum subnet size.

It would be great if you could update the following documentation to include all these new minimum requirements: https://docs.microsoft.com/en-us/azure/aks/configure-azure-cni

**Comment by jnoller** [comment]
It is checked for the entire cluster as maxPods is set at create time of the cluster as a whole. The documentation updates are incoming.

**Comment by aksuser01** [comment]
Just to be clear, now maxPods is a cluster-wide value? As the "old" documentation states:

`
--max-pods -m
The maximum number of pods deployable to a node.
`

https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest

Could you fill the following values (accounting for the temporary node required for upgrades)?

node count: 1
minimum # of pods: ??
minimum subnet size: ??

node count: 2
minimum # of pods: ??
minimum subnet size: ??

node count: 3
minimum # of pods: ??
minimum subnet size: ??

**Comment by ball-hayden** [comment]
The docs still state the maximum is 250:

`Azure CLI: Specify the --max-pods argument when you deploy a cluster with the az aks create command. The maximum value is 250.`

In practice, the maximum appears to be 110 (attempting to create a cluster with 120 fails with "maxPods is invalid")

**Comment by jnoller** [comment]
Sorry @aksuser01 - meant to reply earlier. You're right, my mistake - it should be per node.

So, if you set it to 20:

20 OR 20 * NodeCount > 30 - for a 1 node cluster, that should correctly fail, for a 2 node cluster, it will fail because our lowest allowed value is 30. 3 nodes works as the value is >= 30

**Comment by Huesie** [comment]
@jnoller we've been using Kubenet with MaxPods=200+ (with adv n/w) on multiple clusters for months now - **per the Microsoft recommendation** [link1](https://docs.microsoft.com/en-us/azure/aks/configure-kubenet#choose-a-network-model-to-use), as "Most of the pod communication is within the cluster" and other reasons.  We use additional IP on another subnet to get "external to the cluster" access to a select number of pods and this control is good for us.

Azure CNI _used to be_ limited to 110 max pods per node due to the initial implementation, which presumably engineering has been done to remove this, BUT recently a Kubenet 110 max pods limit was added where no limit existed before [link2](https://docs.microsoft.com/en-us/azure/aks/configure-azure-cni#configure-maximum---new-clusters).

I'm unaware why Kubenet needs this 110 max pods limit - can you elaborate and can this apparently arbitrary limit on Kubenet max pods be aligned with the Azure CNI limit of 250, please?

This retrospective change in AKS of allowed maximum pods for Kubenet will require us to repeat months of stability testing if we must switch to Azure CNI, so we would be grateful of your clarification on why this decision was taken so that we can assess our next steps.

Thanks again to you personally for your continued work and efforts on AKS, we've been impressed with the renewed progress in recent months and look forward to some new AKS capabilities currently in preview.

link1: https://docs.microsoft.com/en-us/azure/aks/configure-kubenet#choose-a-network-model-to-use
link2: https://docs.microsoft.com/en-us/azure/aks/configure-azure-cni#configure-maximum---new-clusters

**Comment by jnoller** [comment]
@huesie Kubenet **has always been limited to 110 / 100 Maxpods per upstream guidance**, you can see: https://kubernetes.io/docs/setup/cluster-large/ (That page is Kubenet specific)

Having the upper boundary for the MaxPods value **not enforced** (as you noted, previously you could set this to whatever you wanted up to 250) and this was a bug that led to customers with obscure cluster failures and runtime errors. 

The intent was **always** enforce the maximum value. Historically Azure CNI was also limited to that same upper boundary, however that has changed to support 250. The fact we did not enforce was a bug.

**Comment by GuGu910** [comment]
Hi All,

Is there anyway that I can create AKS Cluster with less than 30 `--max-pod`?

Regards,
GuGu

**Comment by dariuszbz** [comment]
Yes. You can set 1 pod but than 30 nodes :) in general the total min number
of pods is 30.
