### ISSUE TITLE
Aks + Istio HPA don't working

### ISSUE THREAD

**Issue by levilugato** [Azure/AKS#938]
I have Metrics server 1.8 deployed on cluster and Istio 1.1.3 , when i configure HPA for my deployment it's don't appear the metrics...

error:

**Warning  FailedGetResourceMetric  2m6s (x3294 over 13h)  horizontal-pod-autoscaler  missing request for cpu**

**Comment by jnoller** [comment]
First, thank you for reaching out to the AKS team. 

AKS Github issues must be generally re-creatable (e.g here is the YAML/settings/packages/etc installed, can recreate the issue on existing clusters as well as newly created clusters). Unfortunately, this issue is cluster-specific.

For cluster specific issues (those that will require support and on-call staff to access you Subscription and clusters) we ask that you file an Azure Technical Support ticket with the identified issue, rec-creation steps if available, and link to this github thread.

**We can not ask** for the access, logs and other sensitive information on github, or ask you to email/slack/etc this information to us. Our portal ticketing system will protect the information including Subscription ids and credentials. If we discover as part of the root cause that this is an AKS or upstream bug, we will mark this issue as a known issue and ensure it is on the Product backlog as a repair item.

This will allow us to root-cause the issue and ensure it’s not specific to the environment or other configuration level issue - such as NSGs, custom network devices, etc.

Jesse
