### ISSUE TITLE
Kubernetes Version 1.14

### ISSUE THREAD

**Issue by ball-hayden** [Azure/AKS#940]
**What happened**:

The upgrade section in the cluster section of the portal does not list Kubernetes 1.14 as an available version

**What you expected to happen**:

I expect 1.14 to be listed as a version to upgrade to.

**How to reproduce it (as minimally and precisely as possible)**:

1) Create a cluster running Kubernetes 1.13.5
2) Visit the "Upgrade" section of the Azure portal.

**Anything else we need to know?**:

Kubernetes 1.14 was released on March 25th, 2019.

**Environment**:
- Kubernetes version (use `kubectl version`):
1.13.5

- Size of cluster (how many worker nodes are in the cluster?)
(for completeness) 2

- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
Irrelevant.

**Comment by jnoller** [comment]
Kubernetes 1.14 showing up as released was a bug. It is not released or GA. Apologies for the confusion.

We will be rolling 1.14.0 out as a preview/beta releases but it will not be GA and should not be used for production clusters.

**Comment by ball-hayden** [comment]
@jnoller I wasn't aware it ever was showing up.

Please could we re-open this until 1.14.0 is GA - that was what I was originally trying to track here?

**Comment by jnoller** [comment]
We do not leave issues like this open typically; it’s not a bug report (add a new kubernetes version) and we are rolling 1.14 out in preview shortly. Additionally we do not roll out all new kubernetes versions (1.14 will not be GA until we get additional patch versions in upstream). Tracking all requested versions here as issues without specific bug fixes or justification for the request (eg features & functionality).

However, we are working on a public roadmap that will expose this information (but not as bug reports)

The best place to track new versions and updates is the releases page here: 

https://github.com/Azure/AKS/releases

We lag behind upstream for all new kubernetes minor versions due to testing and validation / compatibility

**Comment by ball-hayden** [comment]
Understood. Thank you for your explanation 🙂
