### ISSUE TITLE
New node not available after being added

### ISSUE THREAD

**Issue by dgard1981** [Azure/AKS#944]
**What happened**:

I have added a second node to my cluster via the Azure Portal. A message has appeared in my notifications stating "Successfully saved container service.", and the number of 'Node count' in has changed to "2".

**What you expected to happen**:

I expected a second node to be available, but when running `kubectl get nodes`, it is not listed.

**How to reproduce it (as minimally and precisely as possible)**:

1. Log in to the Portal and find your Kubernetes cluster.
2. Select "Scale" from the 'Settings' menu.
3. Add an additional node (be sure to save).

**Anything else we need to know?**:

A new network interface, disk and virtual machine have been created in the clusters infrastructure resource group.

When running the following command to check query the agent pool profile...

`az aks show --resource-group my-resource-group --name my-cluster-name --query agentPoolProfiles`

...I see this output -

```
[
  {
    "count": 2,
    "maxPods": 30,
    "name": "agentpool",
    "osDiskSizeGb": 100,
    "osType": "Linux",
    "storageProfile": "ManagedDisks",
    "vmSize": "Standard_B2s",
    "vnetSubnetId": "/subscriptions/<my-subscription-key>/resourceGroups/<my-resource-group>/providers/Microsoft.Network/virtualNetworks/<my-vnet>/subnets/default"
  }
]
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12.6
- Size of cluster (how many worker nodes are in the cluster?): 1, but should be 2.
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): 1x HTTP microservice.

**Comment by jnoller** [comment]
First, thank you for reaching out to the AKS team. 

AKS Github issues must be generally re-creatable (e.g here is the YAML/settings/packages/etc installed, can recreate the issue on existing clusters as well as newly created clusters). Unfortunately, this issue is cluster-specific.

For cluster specific issues (those that will require support and on-call staff to access you Subscription and clusters) we ask that you file an Azure Technical Support ticket with the identified issue, rec-creation steps if available, and link to this github thread.

**We can not ask** for the access, logs and other sensitive information on github, or ask you to email/slack/etc this information to us. Our portal ticketing system will protect the information including Subscription ids and credentials. If we discover as part of the root cause that this is an AKS or upstream bug, we will mark this issue as a known issue and ensure it is on the Product backlog as a repair item.

This will allow us to root-cause the issue and ensure it’s not specific to the environment or other configuration level issue - such as NSGs, custom network devices, etc.

Jesse
