### ISSUE TITLE
Private API Servers 

### ISSUE THREAD

**Issue by jnoller** [Azure/AKS#948]
Tracking issue for Private API servers (via Private Link) support in AKS. 

This feature will enable projecting the Kubernetes API server as a private IP onto your virtual network. No public IP will be required for the communication between the node pool and the API server.

**Comment by mkosieradzki** [comment]
Hi @sauryadas , 

Is there any ETA for this feature? Can I assume this will allow to get rid of tunnel front?

Current documentation for AKS ingress is impossible to implement using Azure Firewall. Because it requires to make Application Rules for tcp (22, 9000) (based on wildcard FQDN) and obviously the only supported protocols are layer 7: http, https, mssql.

You basically need to open 22 and 9000 to entire IP ranges of Azure region. If this is going to take a long time, maybe as a temporary measure you can create a service tag for *.hcp.*.azmk8s.io?

**Comment by dsudduth** [comment]
@sauryadas, @jnoller - Any updates or timeline on this? I ask because we're currently attempting to leverage AKS with advanced networking which has been troublesome. MSFT Solution Architects are referring to this feature as the defacto solution moving forward.

**Comment by sauryadas** [comment]
private clusters should be available by early dec. What exactly are your issues with advanced networking?

**Comment by dsudduth** [comment]
Hi @sauryadas - Thank you for the quick update!

I don't think the challenges have been a result of defects per se. I'm finding that the documentation would benefit from consolidation. For example, the best document regarding AKS CNI is https://docs.microsoft.com/en-us/azure/aks/configure-azure-cni. However, it lacks requirements and considerations for firewall rules. Because of this, we had a tough time getting items like `kubectl logs`, `az aks browse`, and the K8s dashboard to work.

We finally stumbled across https://docs.microsoft.com/en-us/azure/aks/limit-egress-traffic with the help of an MSFT SA. After opening port `9000`, we were better off.

AKS CNI is extremely helpful, but it does present some challenges when attached to a real-world, hybrid network (including express routes to on-prem), which is vast and not controlled by a single team.

I think we will benefit from a more straightforward solution. For my team, a perfect scenario would be a solution that offers a private cluster IP, access to the private network, without the added overhead of dedicated subnets and firewall changes. As for the dynamic creation of internal LBs, that part has been excellent.

All that to say, I'm definitely excited by Private Link and the work you're doing.

**Comment by sauryadas** [comment]
@dsudduth thanks for the note. The private cluster work only enables a private network for the communication between the api server in our tenant and the AKS cluster in the customers tenant. Everything else remains the same.

AKS CNI is extremely helpful, but it does present some challenges when attached to a real-world, hybrid network (including express routes to on-prem), which is vast and not controlled by a single team. <- can you please expand on the exact issue with this? we have a whole lot of customers using this scenario

The dedicated subnet per AKS cluster will hopefully go away in a quarters time.

**Comment by bhicks329** [comment]
Hijacking this thread a little - please see this issue for details on some
problems with out of cluster communications.

Source IP does not persist outside of the vnet is a major issue. This
causes lots of issues when trying to apply different firewall rules to
nodes and subnets.

https://github.com/Azure/AKS/issues/1207



-Ben

From: Saurya Das <notifications@github.com> <notifications@github.com>
Reply: Azure/AKS
<reply@reply.github.com>
<reply@reply.github.com>
Date: 28 October 2019 at 03:54:35
To: Azure/AKS <aks@noreply.github.com> <aks@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
<subscribed@noreply.github.com>
Subject:  Re: [Azure/AKS] Private API Servers (#948)

@dsudduth <https://github.com/dsudduth> thanks for the note. The private

**Comment by dsudduth** [comment]
@sauryadas Thanks for the updates!

>AKS CNI is extremely helpful, but it does present some challenges when attached to a real-world, hybrid network (including express routes to on-prem), which is vast and not controlled by a single team.

Again, no bugs here. But, the barrier to entry for Azure CNI is a bit steep. To introduce a single cluster, you must:

1. Dedicate a subnet large enough to handle node count, container IPs (30 per node if staying with the default), and IPs for the internal load balancer.
2. Meet the Kubernetes Service address range requirements:
    - Must not be within the virtual network IP address range of your cluster
    - Must not overlap with any other virtual networks with which the cluster virtual network peers
    - Must not overlap with any on-premises IPs
    - Must not be within the ranges 169.254.0.0/16, 172.30.0.0/16, 172.31.0.0/16, or 192.0.2.0/24

To meet requirement two, I can only think of two options.
1. Go back to my internal IT and request a CIDR on the private network and keep it from getting routed. The documentation doesn't clearly state a size requirement here.
2. Provision a subnet in a separate VNet that I own in another subscription.

Because I'm incorporating this cluster into an on-prem network that's quite old, I have to take extra precautions to ensure that I meet the CNI requirements for AKS without stepping on other networks. Additionally, I have multiple clusters, translating to more dedicated subnets.

To summarize, I'm finding the overhead of privatizing the cluster to be high. For some, they may want to have the ability to access pods as if they were VMs. For my team, I'm merely looking to meet the requirement of private cluster access and connectivity to on-prem services. I've found that other cloud providers allow you to disable access to the public IP, whereas Azure's recommendation is to use authorized IP address ranges.

I'm happy to hear that the subnet requirements may go away. How about the Kubernetes service range? Will that remain?

If most of the CNI requirements are to remain, it would be great if the [docs](https://docs.microsoft.com/en-us/azure/aks/configure-azure-cni) expanded on the following:

1. What are the exact firewall requirements inbound/outbound for KubeCTL and AZ proxying, Dashboard access, etc.
2. For the Kubernetes Service range, what's the expected IP range (size)? Should this match cluster size? Should it be based on the number of service objects you expect? Also, what's the recommended method of configuring this range. Should it be a non-routed CIDR block? Should you subnet a different VNet? I know there are multiple ways to achieve this, but I'm looking for a best practice.

I hope this is helpful; I don't want to get too off-topic for this issue.

**Comment by swani01** [comment]
Could somebody please give me an example of a working deployment with Azure CNI? The one I'm using times out with Nodes not ready? 

Here is my current one, if I leave out the --enable-private-cluster switch it deploys:
az aks create \
    --name "${ClientRG}k8s${ClusterType}" \
    --resource-group ${ClientRG} \
    --kubernetes-version "1.14.8" \
    --node-resource-group "${ClientRG}k8s${ClusterType}" \
    --vnet-subnet-id ${SUBNET_ID} \   <--- Subnet is 10.10.16.0/20 with vNet 10.10.0.0/16
    --network-plugin azure \
    --enable-private-cluster \
    --docker-bridge-address 172.17.0.1/16 \
    --dns-service-ip 192.160.0.10 \
    --service-cidr 192.160.0.0/12 \
    --vm-set-type VirtualMachineScaleSets \
    --load-balancer-sku standard \
    --generate-ssh-keys \
    --verbose

**Comment by sauryadas** [comment]
this feature is not available yet..

**Comment by bhicks329** [comment]
Are there any updates on when this might be entering private preview?

-Ben

From: Saurya Das <notifications@github.com> <notifications@github.com>
Reply: Azure/AKS
<reply@reply.github.com>
<reply@reply.github.com>
Date: 9 December 2019 at 00:55:47
To: Azure/AKS <aks@noreply.github.com> <aks@noreply.github.com>
CC: Ben Hicks <bhicks329@gmail.com> <bhicks329@gmail.com>, Comment
<comment@noreply.github.com> <comment@noreply.github.com>
Subject:  Re: [Azure/AKS] Private API Servers (#948)

this feature is not available yet..

**Comment by sauryadas** [comment]
Feature has been made available in preview in 7 regions listed in the doc.

https://docs.microsoft.com/en-us/azure/aks/private-clusters

I am closing this issue . Please let me know if you still want to keep it open for some reason
