### ISSUE TITLE
Coredns timeout querying *.windows.net and *.visualstudio.com

### ISSUE THREAD

**Issue by mdaguete** [Azure/AKS#964]
Hi all,

Starting this morning ( GMT+2) we're seeing dns errors in our AKS Clusters ( v1.12.6 ) located in west europe. After digging in logs  we found timeout error in coredns errors:

    2019/05/13 13:30:23 [ERROR] 2 rt.services.visualstudio.com. A: unreachable backend: read udp 10.244.5.27:54409->168.63.129.16:53: i/o timeout
    2019/05/13 13:38:51 [ERROR] 2 xxxxxxxxxxxxx.redis.cache.windows.net. A: unreachable backend: read udp 10.244.5.27:49443->168.63.129.16:53: i/o timeout
    2019/05/13 13:39:44 [ERROR] 2 dc.services.visualstudio.com. A: unreachable backend: read udp 10.244.5.27:43252->168.63.129.16:53: i/o timeout

Trying to resolve another names do not thows timeout errors.

Regards.

**Comment by jnoller** [comment]
We are aware of an intermittent issue which came up regarding CoreDNS crashes due to a non-backwards compatible update that may have caused this, and as it's intermittent, there may have been an in-region issue 

Since this is not generally re-creatable as a bug, please contact Azure support for follow up.
