### ISSUE TITLE
AKS ingress controller 404 for .net core API project

### ISSUE THREAD

**Issue by praveenkadimi** [Azure/AKS#966]
I have an API service which is working as expected when I use path as "/". but when I mention path as "/test/" or "/test" which is not working site not reachable 404. can you help to resolve the issue

**Comment by praveenkadimi** [comment]
I'm using stable ingress controller installed from helm as mentioned Microsoft MSDN

**Comment by jnoller** [comment]
First, thank you for reaching out to the AKS team. 

AKS Github issues must be generally re-creatable (e.g here is the YAML/settings/packages/etc installed, can recreate the issue on existing clusters as well as newly created clusters). Unfortunately, this issue is cluster-specific.

For cluster specific issues (those that will require support and on-call staff to access you Subscription and clusters) we ask that you file an Azure Technical Support ticket with the identified issue, rec-creation steps if available, and link to this github thread.

**We can not ask** for the access, logs and other sensitive information on github, or ask you to email/slack/etc this information to us. Our portal ticketing system will protect the information including Subscription ids and credentials. If we discover as part of the root cause that this is an AKS or upstream bug, we will mark this issue as a known issue and ensure it is on the Product backlog as a repair item.

This will allow us to root-cause the issue and ensure it’s not specific to the environment or other configuration level issue - such as NSGs, custom network devices, etc.

Jesse

**Comment by praveenkadimi** [comment]
https://github.com/Azure/AKS/issues/186 
 in the above ticket it was clearly mentioned like azure MSDN was not updated, thank you

**Comment by praveenkadimi** [comment]
same issue was already discussed in this ticket  https://github.com/Azure/AKS/issues/186
