### ISSUE TITLE
Persist tags on managed resource groups specified by users to the underlying MC_* resource group

### ISSUE THREAD

**Issue by jnoller** [Azure/AKS#970]
This is a tracking issue for AKS support for tag pass-down / inheritance on RGs passed in by customers so that those tags cascade down to **only the underlying resource group object in the MC_* RG**.

**Comment by montebhoover** [comment]
I see that this has feature has moved to Public Preview in the roadmap - is there a particular argument to force this to take effect?

In a subscription with aks-preview enabled, I'm running:
```
az group create -n rg1 --tags tag1=val1
az aks create -g rg1 -n kub1 --tags tag1=val1 --node-resource-group mc_kub1
```

`mc_kub1` is created but it does not have `tag1` (nor do any of its resources).

In particular I am looking for a way to create the node resource group with specific tags in order to comply with my subscription policy (as discussed in https://github.com/Azure/azure-cli/issues/7573).  Thanks!

**Comment by jluk** [comment]
@montebhoover could you try this again? We've recently turned on this ability today, but the scope is only to persist the tags onto the MC_* resource group, not all the child resources.

**Comment by montebhoover** [comment]
Thanks @jluk!  This works for me when testing on a cluster in CanadaCentral:

```
> az aks create -g rgcan -n kubcan -l canadacentral --tags tag1=val1
> az group show -n MC_rgcan_kubcan_canadacentral -o json --query "tags"
{
  "tag1": "val1"
}
```

**Comment by jluk** [comment]
Awesome thanks for confirmation @montebhoover!

**Comment by jnoller** [comment]
Closing fixed, see https://github.com/Azure/AKS/releases/tag/2019-07-01
