### ISSUE TITLE
Integration with Azure Resource Health

### ISSUE THREAD

**Issue by jnoller** [Azure/AKS#994]
Tracking issue for the integration of AKS clusters, nodes, etc into Azure Resource Health

**Comment by jluk** [comment]
This capability is now in public preview for support of AKS in RHC (resource health check).

https://docs.microsoft.com/en-us/azure/service-health/resource-health-checks-resource-types

**Comment by tomkerkhove** [comment]
Great to hear! Unfortunately, I don't see it listed on that link; what is it checking for at the moment?

**Comment by jluk** [comment]
PRs are in-flight with those details, we will update the OP with full links and info when merged!

**Comment by amjadaljunaidi** [comment]
@jluk when I check this feature, I expect that we could show the resource health of AKS cluster since 30 days ago
https://docs.microsoft.com/en-us/azure/aks/aks-resource-health#view-historical-data

is it normal to show that info from Aug 24th only for all AKS cluster
![image](https://user-images.githubusercontent.com/49981856/92091937-1a698d80-edda-11ea-9591-62a9e043fb86.png)

**Comment by aritraghosh** [comment]
This is in GA now 
https://learn.microsoft.com/en-us/azure/service-health/resource-health-checks-resource-types
